### ISSUE TITLE
Error generating Bella block

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#1002]
Since the latest update, I'm unable to generate the front part of Bella.

When I go to generate a new pattern (Designs > Bella body block > New Bella Pattern), only the back part shows up. This happens whether I choose my own measurements or a standard size.

It also happens if I try to regenerate a legacy pattern.

Examples of warnings:
- Warning: Tried to access bustWidthBack in the store but it is not set
- Warning: points.waistDartLeft was set with a x parameter that is not a number

**Comment by joostdecock** [comment]
Thanks for reporting this @nataliabarnhart and well spotted :+1: 

I've rolled out a fix for this as v2.15.4, which is now deployed on freesewing.org :tada:
