### ISSUE TITLE
Add missing notches to Florent

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1015]
**What seems to be the problem?**

Florent does not (or no longer) have the notches shown here: https://freesewing.org/docs/patterns/florent/cutting/

**Comment by woutervdub** [comment]
Do we still have the old PHP code somewhere?

**Comment by joostdecock** [comment]
Yass: https://github.com/joostdecock/core/tree/develop/patterns/Beta/FlorentFlatCap
