### ISSUE TITLE
Parts size displayed when generating a pattern

### ISSUE THREAD

**Issue by econo202** [freesewing/freesewing#1021]
**What is it that you would like to see happen?**

A nice to have feature would be to display sizes of all the parts when generating patterns. That way it'd be much easier to estimate the amount of fabric needed to sew the design.

The size displayed should be total width and height of each part (incl. seam and hem allowance).

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

When creating a pattern (both a standard size, and one based on specific person measurements) size of the parts might be:

- printed on each part of a generated pattern that the user exports (see example mockup below)
- automatically added to the "notes" section of the pattern that the user saves on his account

---

![text467](https://user-images.githubusercontent.com/34138153/118497063-01fd9100-b725-11eb-8f8b-c4dd57577936.png)

**Comment by joostdecock** [comment]
Are you familiar with the **paperless** option?

**Comment by econo202** [comment]
I've played with it some time ago, but forgot that there are all the dimensions.

Thanks for mentioning this. Issue resolved. :)

**Comment by joostdecock** [comment]
Cool :)
