### ISSUE TITLE
Add link to full tutorial code at end of tutorial

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1023]
`starf` writes on Discord:

> I've just started going through the pattern design tutorial (kudos!) and I have one suggestion: would it be possible to have the whole code again at the end?

A link to the source is probably sufficient.

**Comment by starfetch** [comment]
Addressed in commit `7ad619c` in `freesewing/markdown`, issue closed.

**Comment by joostdecock** [comment]
Glad to see you're making good use of those contributor rights you have now :)

**Comment by starfetch** [comment]
Happy to help, and thanks for the invite :)
