### ISSUE TITLE
Website - Unit and value error on shoulder slope measurement page. 

### ISSUE THREAD

**Issue by mcchots** [freesewing/freesewing#1028]
**What seems to be the problem?**

On the measurements page for Shoulder slope, the description under the input reads "We estimate your shoulder slope to be around:1.3cm" instead of 13°

**Are you a FreeSewing patron?**

 - [X] No, I am not :thinking:

**Additional context**

![image](https://user-images.githubusercontent.com/975793/119238084-aece7880-bb40-11eb-9ff4-d99e922dc5a0.png)

**Comment by joostdecock** [comment]
Thanks of reporting this :+1:
