### ISSUE TITLE
Include cutting instructions on pattern parts

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1029]
You know it makes sense. Just support translation.

**Comment by joostdecock** [comment]
This shifts a lot of the documentation burden to the designer. So it might be better to come up with a way that this can be deduced.

**Comment by nataliabarnhart** [comment]
@joostdecock What would we need to document for this, and can I do it for all of the existing patterns? (To help relieve the burden on designers)

Maybe I can help with this issue at the same time: https://github.com/freesewing/freesewing/issues/644

**Comment by joostdecock** [comment]
It is currently not so easy to do. You can pass text to the title macro that would then be included. But you'd have to string it together from tokens that can be translated. And cutting instructions include things like "on the fold" or "good sides together" so that seems like stuff we should keep out of the code.

I was more thinking that for v3 we could try to come up with a way that this could be easily added by designers. Sort of registering what will be needed, and then we could include it on the pattern (perhaps some sort of annex), and also on the pattern page (on the website I mean)

**Comment by joostdecock** [comment]
I think this would add a lot of complexity for little added value. So I'm closing this.
