### ISSUE TITLE
Local cache is not updated on avatar update

### ISSUE THREAD

**Issue by chrisgloom** [freesewing/freesewing#1032]
**What seems to be the problem?**

people avatar doesn't upload

on the person page, I'm prompted to upload an avatar, the image I choose appears in the window for uploading but then doesn't actually get processed as I'm left with the default sewing skull when the page refreshes.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Add any other context or screenshots about the problem request here.
image makes it into the window fine,
![image](https://user-images.githubusercontent.com/15905991/119276259-7cc02380-bbdf-11eb-9be9-6fdb1426130e.png)

but isn't uploaded
![image](https://user-images.githubusercontent.com/15905991/119276276-91042080-bbdf-11eb-90d7-d82ad87d172b.png)

**Comment by chrisgloom** [comment]
update, now seems to show up. I did just log in on a different computer though. Will check the other.

**Comment by chrisgloom** [comment]
loads on windows 10 home Version	10.0.19041 Build 19041
using chrome Version 90.0.4430.212 (Official Build) (64-bit)

was having trouble loading on a macbook pro 2015 same chrome version but a log out/ log in just solved it there as well.

**Comment by chrisgloom** [comment]
also needed a log out, log in for pattern generated on other computer to show up on this one. That's probably the real thing I'm experiencing here.

**Comment by joostdecock** [comment]
Yeah, it's a problem between the locally cached version of your account, and what's on the backend.

You can force a refresh of your account on this page: https://freesewing.org/account/actions/reload/
This will pull your account from the backend and update the local cache.

That's not a fix obviously, and this is a bug. But it's a pretty solid workaround until we fix it for good :wink:
