### ISSUE TITLE
Change the 'designs' icon

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1040]
Starf writes on discord:

>  the icon for "designs" on the main page always bothered me, it took me a few days to realise that it's supposed to be a swimsuit

As it happens, it's are attempts to avoid gendered language that are why we have that icon.

We don't talk about *men* or *women* but instead refer to *with-breasts* or *without-breasts*.
When we added standard sizing, we needed an icon that represented these two scenarios and it's not so obvious to have an icon that distinguishes between bodies with or without breasts.
In the end, we went with pair of swim trunks (without breasts) and a swimsuit (with breasts).

Then, when we needed an icon for designs, we just used the swimsuit one since it was already in our icon library.

So let's create another icon for designs.

**Comment by lucibytes** [comment]
My humble suggestions:
+ for pros and - for cons

A bra icon and a tank top
+ A bra icon is the go-to easy-to-understand icon for breasts
- A tank top is not as obvious

A 'menswear' icon and a 'womenswear' icon, for example the icons used for Simon and Simone
+ It's immediately clear why breast measurements are important for patterns, as patterns are drafted differently
- May not be so clear for a beginner: "a shirt and a shirt with lines on it..?"

Side view of the outline of a person, one with a flat chest and one with breasts
+ Really clear difference
- Boring


To go a bit off-topic:
"We don't talk about men or women but instead refer to with-breasts or without-breasts."
Wouldn't it be a good idea to change the terms "menswear" to "masculine" and "womenswear" to "feminine"?

**Comment by joostdecock** [comment]
Perhaps we should start by clarifying what *an icon* is: An icon is a single color vectorial graphics file with no stroke, and only fill.

The *icons* for simon and simone are not icons, they are linedrawings. They have stroke and fill, not to mention different stroke widths and fill colors.

Another way to look at it is that an icon is an inkblob in a particular shape.

So we need an icon that says **Designs**. A bra is an option, but some users said they were disappointing that we don't have a swimsuit pattern because that's the shape of the icon. A bra icon would be the same problem.

A tank top is ok, because we have that, but it all depends on whether it's easy to recognize.|
Maybe I should just make some proposals :)

> Wouldn't it be a good idea to change the terms "menswear" to "masculine" and "womenswear" to "feminine"?

My personal favorite is: Feminine Presenting / Masculine Presenting

**Comment by joostdecock** [comment]
Howzdis? :point_down: 

![design](https://user-images.githubusercontent.com/1708494/119534104-d747b400-bd86-11eb-86de-f476f65818fb.png)

**Comment by starfetch** [comment]
Very nice! But maybe a bit more unisex-looking? I somehow immediately think "female", probably because of the curved sides and the tight armholes

**Comment by starfetch** [comment]
Maybe that could really be the distinction for with/without breasts like lucibytes suggests above, maybe with some tweaks to make it a bit more obvious?

**Comment by joostdecock** [comment]
Please vote on this comment with your preference for the new **designs** icons:

![designs](https://user-images.githubusercontent.com/1708494/119871981-43f7b580-bf23-11eb-9b40-733c24a17d37.png)
:heart: :heart: :heart: | :rocket: :rocket: :rocket: | :eyes: :eyes: :eyes:

**Comment by joostdecock** [comment]
I'm sorry, but I hate it.

![tshirt](https://user-images.githubusercontent.com/1708494/120074027-20f01180-c09b-11eb-81e1-0f62ab51fdc0.png)

**Comment by starfetch** [comment]
I think it's ok... _ducks_
Alternative: Something that says "sewing pattern" a bit more? A stylised cut-on-fold pattern part?

**Comment by joostdecock** [comment]
Problem is that it's too detailed in comparison to the other icons. It stands out like a sort thumb.
Something like a pattern part is going to require a level of detail that means that whatever we end up with has the same problem.

Icon design is tricky.

**Comment by joostdecock** [comment]
Making an executive decision, and going with this instead:

![hanger](https://user-images.githubusercontent.com/1708494/120074667-2b5fda80-c09e-11eb-9e4b-a8f8cf5c5de4.png)

**Comment by starfetch** [comment]
Very nice! I love it.
