### ISSUE TITLE
Newsletter - Summer 2021 edition

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1053]
This is an umbrella issue for everything that needs to happen for the newsletter 2021 summer edition.

- [ ] Interview of An by Eleonore
  - [x] Write
  - [x] Submit
  - [x] Put in markdown repo
  - [ ] Proofread 
- [ ] Natalia has something on the git good gurl topic
  - [x] Write
  - [x] Submit
  - [x] Put in markdown repo
  - [ ] Proofread 
- [ ] Something about the passing of PDC
  - [x] Write
  - [x] Submit
  - [x] Put in markdown repo
  - [ ] Proofread 
- [ ] An invitation for people to contribute (to the newsletter)
  - [ ] Write
  - [ ] Submit
  - [ ] Put in markdown repo
  - [ ] Proofread 
- [ ] A brief note on the changes under the hood in 2.16
  - [x] Write
  - [x] Submit
  - [ ] Put in markdown repo
  - [ ] Proofread 
- [ ] A mention in passing of the efforts to be more gender-neutral, and how we no longer use menswear/womenswear
  - [x] Write
  - [x] Submit
  - [x] Put in markdown repo
  - [ ] Proofread 
- [ ] An invitation to be interviewed
  - [ ] Write
  - [ ] Submit
  - [ ] Put in markdown repo
  - [ ] Proofread 
- [ ] Announce the code bootcamp (see #1054)
  - [ ] Write
  - [ ] Submit
  - [ ] Put in markdown repo
  - [ ] Proofread 
- [ ] We should make sure we have at least one new pattern in Q2 so we can put that in the newsletter

**Comment by nataliabarnhart** [comment]
Can check off "Write" and "Submit" for me - I dropped this the Discord channel as well

https://github.com/nataliabarnhart/freesewing-contribution-tutorial/blob/main/freesewing-contribution-tutorial.md

**Comment by Anternative** [comment]
[My Image 22.pdf](https://github.com/freesewing/freesewing/files/6604787/My.Image.22.pdf)
picture of what I was working on, to be included in interview. Hope you don't mind it's a PDF

**Comment by joostdecock** [comment]
@nataliabarnhart I've done it but, can you check whether you have permission to do so?
I would assume you do, you have permission to close the issue outright, so I'd be surprised if you can't update it.

**Comment by nataliabarnhart** [comment]
@joostdecock Surprisingly, I do not. I don't have the "Edit" option for this issue as I do on ones I've created, e.g. https://github.com/freesewing/freesewing/issues/1072.

**Comment by joostdecock** [comment]
@nataliabarnhart Congratulations on your promotion. You now have write access to all our repositories.

**Comment by joostdecock** [comment]
Draft: https://github.com/freesewing/markdown/blob/develop/newsletter/2021q3/en.md

**Comment by nataliabarnhart** [comment]
This newsletter was published on July 1st. Good work, newsletter team :)

https://freesewing.org/newsletter/2021q3/
