### ISSUE TITLE
FreeSewing code bootcamp for (aspiring) pattern designers

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1054]
This is an umbrella issue for the planned bootcamp to learn about how to design patterns in FreeSewing

- [ ] Figure out the streaming setup
- [ ] Pick a time/weekday that works
- [ ] ...

**Comment by darigovresearch** [comment]
Sounds like a great idea.

Would recommend OBS studio - https://obsproject.com/

This video is also great as a first step to see the basics and you may have all the equipment to hand - https://www.youtube.com/watch?v=L6ZJaKqALgM

Also happy to help be a moderator if the time/weekday works

**Comment by joostdecock** [comment]
I feel it would be best to postpone this until after v3; https://github.com/freesewing/freesewing/discussions/1278
