### ISSUE TITLE
The password reset email no longer has a subject set

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1060]
Pc_girl submitted this screenshot on Discord:
![Screenshot_20210530-215009.jpg](https://user-images.githubusercontent.com/1708494/120141573-09b93d00-c1dd-11eb-83e4-c3f3d76248f6.jpg)

Not sure what's going on, but we should look into it.

**Comment by starfetch** [comment]
Can confirm this, no subject set for password reset.

**Comment by joostdecock** [comment]
Fixed:

![reset](https://user-images.githubusercontent.com/1708494/120226126-dd3a0b00-c246-11eb-8f30-872dfddef016.png)
