### ISSUE TITLE
Create Hugo showcase from @hellgy's Twitter post

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#1072]
- Content:  https://twitter.com/hellgy/status/1398616084429914115
 - Permission:
   - [ ] I am the original author, and hereby grant permission to repost this content
   - [x] I am not the original author, please ask permission from them
 - Credit: @hellgy

Looking to tackle this issue? We have [a how-to that shows how to add a showcase to the site](https://freesewing.dev/editors/howtos/showcase/).

**Comment by nataliabarnhart** [comment]
I think @joostdecock already received permission to share from Lawrence / hellgy, but I'll double check with them and confirm how they'd like to be credited.

**Comment by hellgy** [comment]
Hello Natalia !

You can use these photos ! You can credit me as hellgy :)

I’m working on an other Hugo sweater for my mom with dinosaur fabric , I’ll
send you some pictures if you want !

**Comment by nataliabarnhart** [comment]
https://github.com/freesewing/markdown/pull/245
