### ISSUE TITLE
[BUG] Additional unused section in documentation

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1081]
**What seems to be the problem?**

There is a bullet point which contains no content on the freesewing documentation site

https://freesewing.org/docs/

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

![image](https://user-images.githubusercontent.com/30328618/120902603-291af480-c639-11eb-91ba-e8f53f5ae4f0.png)

**Comment by joostdecock** [comment]
Fixed by removing unused directory
