### ISSUE TITLE
Update Hugo Hoodie video description

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1084]
- Page link:  https://freesewing.org/docs/patterns/hugo/
- Relevant section: https://www.youtube.com/watch?v=W0XNvRxrw3Q&list=PL1gv5yv3DoZOHLjisuD1JcUPTkFy_IGGO&index=2
- Suggested content: Previous video content (if viewed directly in Youtube links to make my pattern site which I believe now is freesewing, is it worth noting this update in the description of the video & a link to the site? 

May also be helpful as a pinned comment in case the user does not see the description

Looking to tackle this issue? Check out our [documentation for editors](https://freesewing.dev/editors/) to learn how to contribute updates.

**Comment by joostdecock** [comment]
Updated the entire playlist with:

- updated title
- updated description
- pinned comment

Thanks for reporting this!
