### ISSUE TITLE
Add support for a sloping waistband to titan/charlie

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1102]
Titan/Charlie is drafted with a horizontal waistband. As in, when you look at it from the side, it's supposed to be horizontal.

That's fine for stick figures, but it's not so great for more curvy people. There, the waistband should slope downwards (once again when looking from the side). This will provide better fit for people who either have more pronounced behinds (and thus can use the extra height) or a bit of a belly (and are better served with a front that dips under the belly region).

Needs to be added to Titan, and inherited by Charlie. We can create an option for it. One question is how we can inform the user or perhaps automatically detect it.

**Comment by joostdecock** [comment]
Example of a problematic draft: https://freesewing.org/account/patterns/duixa/

**Comment by HaasJona** [comment]
I'm working on a prototype

**Comment by HaasJona** [comment]
See also relevant discord threads: 

* https://discord.com/channels/698854858052075530/1226466696961851442
* https://discord.com/channels/698854858052075530/1281170445244174377

**Comment by HaasJona** [comment]
Nevermind, there's already #3493 for that
