### ISSUE TITLE
Paco - probably a few bugs

### ISSUE THREAD

**Issue by econo202** [freesewing/freesewing#1113]
**What seems to be the problem?**

- [x] Changing Waistband width changes the dimensions of "front" and "back", but not the waistband (maybe it's intentional?)
- [x] Changing Ankle/Hem elastic width modifies the dimensions of both ankle cuff and the waistband
- [ ] If you save your Paco pattern, and then open the edit mode, the Waistband width resets to the default 3,5 cm and Ankle/Hem elastic width resets to the default 7 cm
  - [ ] the pattern itself isn't changed and if you try to export it it will be based on your previously saved values
- [x] When you choose not to have elasticated hem, the front and back are modified properly, but ankle cuff does not disappear from the pattern

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Comment by joostdecock** [comment]
Updated the original text to include check boxes so I can keep track of what I've checked :)

**Comment by joostdecock** [comment]
All fixed, except that loading the defaults from a saved pattern thing, for which I've created #1136 

Note that these fixes won't show up on the website until we roll out the next release.

**Comment by econo202** [comment]
Thank you!

**Comment by joostdecock** [comment]
Thanks for reporting it. Meanwhile I've also fixed the mm option thing in #1136 :tada:
