### ISSUE TITLE
Add images to Charlie instructions

### ISSUE THREAD

**Issue by tangerineshark** [freesewing/freesewing#1119]
- Page link: https://freesewing.org/docs/patterns/charlie/instructions/

Add SVG illustrations to existing text Charlie instructions.

**Comment by tangerineshark** [comment]
Don't worry - I wouldn't have added this issue if I didn't already have several of these images drafted, albeit at a slower pace than intended. Gonna follow the same style as the Paco illustrations (https://freesewing.org/docs/patterns/paco/instructions/), but super-duper open to feedback on that front.

**Comment by darigovresearch** [comment]
@tangerineshark thanks for raising this, any drafts of the image that you can either post here or in a pull request if you haven't already made a pull request?

**Comment by tangerineshark** [comment]
@darigovresearch Yes! I have SVGs through Step 8 (almost to constructing the fly), but have been pretty slow in creating them. I'm thinking perhaps it makes sense to just add them as a pull request that doesn't close this issue, and then keep working on the remainder, but I'm curious what you're looking for specifically? Are you making some Charlies and could use some visual help? Want to help with image creation? Other?

**Comment by darigovresearch** [comment]
@tangerineshark not making any Charlies, we like to encourage people to feel comfortable contributing to great open source projects. If you have some images ready feel free to make a pull request & submit what you have & then highlight what is missing as someone may be able to pick it up after you

**Comment by joostdecock** [comment]
Closing in favor of #1342
