### ISSUE TITLE
Penelope lengthBonus option is not taken into account

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#113]
The problem lies in [line 21 of shape.js](https://github.com/freesewing/freesewing/blob/develop/packages/penelope/src/shape.js#L21) 

```js
let skirtLength = measurements.naturalWaistToKnee + options.lengthBonus + options.hem;
```

But skirtLength is a percentage option. So it should be something like:

```js
let skirtLength = measurements.naturalWaistToKnee * 1 +  options.lengthBonus)
```

I also think it makes more sense to draw the exact skirt, and handle the hem length in SA since that's how it's on all other patterns (just to clarify why I left it out of the updated code)

**Comment by joostdecock** [comment]
I think the same issue applies to the seatEase and waistEase options.

I didn't really dig in to it, but sampling them seems to indicate that there's not much going on:

![Screenshot_2019-09-17 penelope(1)](https://user-images.githubusercontent.com/1708494/65068958-fbd07380-d989-11e9-8ceb-8c3cdf03c021.png)

**Comment by woutervdub** [comment]
seatEase and waistEase are very small. It's a pencil skirt, and it's supposed to be tight. They are in mm and vary between 0 and 15, defaulting at 5. 

The length was a big oops. That's what I get for trying to accomodate ant lady.

**Comment by woutervdub** [comment]
Fixed
