### ISSUE TITLE
At-mention the user when creating issues from the frontend

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1144]
If users have a GitHub username configured, we should @-mention them so they get notified.

**Comment by starfetch** [comment]
Closed by [commit in 'freesewing.org`](https://github.com/freesewing/freesewing.org/commit/0ab340512fe64cec71959119cc05fdcde8e16550).

**Comment by joostdecock** [comment]
Nah, no sweat :+1:
