### ISSUE TITLE
Documentation links updates

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#1169]
I found some broken links.

- Page link:  

    - [x] https://freesewing.dev/developers/ - _the FreeSewing basics_ and _Pattern building blocks_
    - [x] https://freesewing.dev/howtos/code/accessing-measurements - _FreeSewing uses millimeter for everything_
    - [x] https://freesewing.dev/tutorials/pattern-design/adding-measurements - _best practices_
    - [x] https://freesewing.dev/reference/plugins/bust/ - _Pattern inheritance_
    - [x] https://freesewing.dev/guides/plugins/using-hooks-without-plugin/ - _Pattern.on()_
    - [x] https://freesewing.dev/guides/plugins/macros/ - _Part_
    - [x] https://freesewing.dev/tutorials/getting-started-windows/ - _getting started on Linux guide_
   ~~- [ ] https://freesewing.dev/tutorials/pattern-design/create-freesewing-pattern/ - _our chatroom_ (switch this to https://discord.freesewing.org/)~~ _(Edit: [already done](https://github.com/freesewing/markdown/commit/1735f845eee0016204fcfc558505755d819368ce), now live :) -starfetch)_
    - [x] https://freesewing.dev/tutorials/pattern-design/conclusion/ - _join our chat room_ and _tell us what you think_
    - [x] https://freesewing.dev/tutorials/pattern-design/adding-options/ - _in the API docs_
    - [x] https://freesewing.dev/tutorials/pattern-design/constructing-the-neck-opening/ - _the high-level overview of FreeSewing_

Looking to tackle this issue? Check out our [documentation for editors](https://freesewing.dev/editors/) to learn how to contribute updates.

**Comment by nataliabarnhart** [comment]
Done! Thanks @starfetch !

https://github.com/freesewing/markdown/pull/258

**Comment by starfetch** [comment]
Yay! Go Team!
