### ISSUE TITLE
Website can be blank when avatar is not set for person

### ISSUE THREAD

**Issue by phillipthelen** [freesewing/freesewing#1170]
**What seems to be the problem?**

I have one person set up on my account. I have not set a photo for this user. I started having errors on various pages, because the `pictureUris` object of the person is null or missing, which trips up the [person.js component](https://github.com/freesewing/freesewing.org/blob/b5c374a9f1f1aabf4ad20921a6c4647a4ba8e1f2/src/components/person.js#L36). In an attempt to fix the issue, I set a photo for the person. The website then worked correctly again. After logging in again today, I am encountering the same issue again. So at some point the pictures seem to have been cleared. In case it is related to the login process, I am logging in through GitHub.

A Bandaid fix for this would be to make the website handle an empty `pictureUris` object, so that if this happens the site still works. I will try to investigate this issue more, but since I'm not yet familiar with the codebase, I'm not sure if/when I can find a solution.

**Comment by starfetch** [comment]
Did [PR #1425](https://github.com/freesewing/freesewing.org/pull/1425) resolve this?

**Comment by valadaptive** [comment]
In retrospect #1425 was a bit of a workaround. The root issue seems to be that `pictureUris` isn't being set for people within accounts authenticated via GitHub.

**Comment by joostdecock** [comment]
Sorry for the long delay, but once I deploy the new site this should be resolved
