### ISSUE TITLE
Remove duplicate "HPS to bust" page from FreeSewing.org documentation

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#1182]
- Page link:  https://freesewing.org/docs/measurements/highpointshouldertobust/
- Relevant section: N/A
- Suggested content: I think the page above can be removed as it's essentially a duplicate of this page: https://freesewing.org/docs/measurements/hpstobust/

The /hpstobust page has an illustration which we want to keep.

I'll double check whether the /highpointshouldertobust page has any extra info we want to preserve before removing it.

**Comment by starfetch** [comment]
It looks like the page without the illustration has the info about HPS included, while the other page links to it. Safe to remove, I think? Also the URL with the abbreviation for HPS would be in line with the other HPS measurements' pages.

**Comment by nataliabarnhart** [comment]
Thanks for the second pair of eyes, @starfetch . Agreed on all counts!

This is done: https://github.com/freesewing/markdown/pull/261
