### ISSUE TITLE
Documentation missing for Brian's & Simon/e's new options

### ISSUE THREAD

**Issue by starfetch** [freesewing/freesewing#1187]
The documentation for Brian's & Simon/e's new options (`shoulder seam shift: collar` and `shoulder seam shift: armhole`for both, `round back` for Simon/e) does not exist (yet).

Relevant pages:
https://freesewing.org/docs/patterns/simon/options/s3collar
https://freesewing.org/docs/patterns/brian/options/s3collar
https://freesewing.org/docs/patterns/simon/options/s3armhole
https://freesewing.org/docs/patterns/brian/options/s3armhole
https://freesewing.org/docs/patterns/simon/options/roundback
All linked from: https://freesewing.org/docs/patterns/simon/options
and https://freesewing.org/docs/patterns/brian/

Looking to tackle this issue? Check out our [documentation for editors](https://freesewing.dev/editors/) to learn how to contribute updates.

**Comment by darigovresearch** [comment]
@starfetch thanks for raising this, any chance you want to have a go at one of them so that a new joiner to the project that wants to contribute can use yours as a guide?
