### ISSUE TITLE
 Contributor call: 10 july 2021

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1191]
You are all invited to the contributor call.
Please leave a comment here or [on Discord](https://discord.freesewing.org/) to put things on the agenda.
This issue will be updated after the call with notes and todos.

Hosted by @tangerineshark and me.

### About
- Location: https://discord.freesewing.org (meeting channel/room)
- Date: Saturday 10 July, 2021 16:00 UTC, which is:
        Los Angeles: 09:00
        Chicago: 11:00
        New York: 12:00
        São Paulo: 13:00
        London: 17:00
        Paris: 18:00
        Johannesburg: 18:00
        Moscow: 19:00
        Mumbai: 21:30
        Hong Kong: 00:00 on Sunday
        Tokyo: 01:00 on Sunday
        Sydney: 02:00 on Sunday

### Agenda
- Hellgy's survey
- Feedback on newsletter
- Feedback on @nataliabarnhart's Ursula
- Feedback on @sannek's block
- Feedback on 2.17?
- Hellgy's pattern hack
- DnD updates?

### Notes
- We started brainstorming on October's newsletter, but it's a bit far away to decide on anything definitive (especially since we're now in summer and it will be cold by the next newsletter). 
@ttimearl mentioned that the newsletter is a bit text-heavy and it would be great if there were a few pictures here and there.
- We discussed Hellgy's survey for a little, but they weren't present in the call. @tangerineshark encouraged people to go check it out and leave some feedback.
- We discussed the recently released Ursula pattern from @nataliabarnhart, but there was no feedback from anyone in the call. 
- @starfetch mentioned their progress and ideas on a cloak pattern (lots of enthusiasm on cloaks in the call!) and @/bobgeorgethethird added to that with their ideas on cloaks (many customizable options), and shared their list of other ideas for (FreeSewing) patterns.
- I (@lucibytes) shared [a skirt](https://media.discordapp.net/attachments/788066844393078835/863454791618920488/iu.png) I would like to develop into a FreeSewing pattern, to which people added that pockets would be really easy to hide in the pleats.
- Lighthearted talk that many people do their projects while in call, @/shieldmaiden was ironing something for a project, @/sewicked was loomknitting a sock, plus embroidery would be a great thing to fidget with.
- @/bobgeorgethethird mentioned that they were going to write the instructions for the Holmes pattern 🙌
- @starfetch mentioned that they noticed there were a few 2 year old issues on the freesewing.org repo and suggested to move some to the monorepo.
- @starfetch mentioned that the search engine DuckDuckGo grabs [the first bit of text from the site](https://media.discordapp.net/attachments/788066844393078835/863459724719947776/unknown.png) to display, instead of what was supposed to be there. I (@lucibytes) was supposed to open an issue about that a while ago but didn't get around to it (will be a to-do).
- @/shieldmaiden suggested that a bathrobe pattern would be cool.
- @nataliabarnhart shared the process of Ursula and encouraged people to look into pattern development, and that there are people willing to help with that in the Discord server. She also mentioned that she was looking into making Paco into shorts as a pattern.
- @nataliabarnhart mentioned that she was working on the Cathrin corset and that perhaps she will write the instructions.
- There was a lot of talk about [this type of collar](https://media.discordapp.net/attachments/788066844393078835/863463842745810954/loki.png), how to reproduce it and perhaps even add it to Simon (but that's an ambitious thought).
- I (@lucibytes) mentioned that Jaeger's instructions were incomplete. Will open an issue for that.

### Todos
- Making sure the "more images in newsletter" suggestion won't be forgotten
- Open issue on descriptions of FreeSewing on platforms (community label) and add either a new one or in the same one the bug from DuckDuckGo.
- Open issue on incomplete Jaeger instructions
- Open issue on @/AnthonyMJ's suggestion (see comment below).

**Comment by lucibytes** [comment]
@AnthonyMJ in Discord:
"On the new website, it would be great to be able to input actual numbers even if they are within the constraints. Takes a lot of dexterity (and knowledge of fractions) to adjust those sliders to the exact number you want."

**Comment by lucibytes** [comment]
As a wise man once said: Call over. Notes written. Todo's created. Closing.

**Comment by joostdecock** [comment]
These notes are so much better than anything I've ever written :heart_eyes:

**Comment by lucibytes** [comment]
@joostdecock Thank you 🥺🥺 I learned from the best 😉
