### ISSUE TITLE
Use same precision in sliders and shown values for pattern options

### ISSUE THREAD

**Issue by RomanaLa** [freesewing/freesewing#1197]
For example with custom seam allowance: I can move the slider 10 units before the shown value for the seam allowance changes. I would prefer to have the same precision in the shown values as on the sliders so I can see the exact number that I chose with the slider.
I used metric units.

**Comment by starfetch** [comment]
Maybe this was fixed in a previous release, I cannot reproduce this behaviour in v2.17. @RomanaLa, could you provide some feedback?

Related: #1200

**Comment by starfetch** [comment]
No further feedback, so closing this. Please reopen if necessary.
