### ISSUE TITLE
models page stays completly blank - JS Error ? 

### ISSUE THREAD

**Issue by stsydow** [freesewing/freesewing#12]
The models page stays completely blank.
The console shows the following Errors: 

TypeError: "r.pictureUris is undefined"
    render Container.js:217
    render Container.js:193
    React 12
    v Redux
    setModels Base.js:125
    componentDidMount Base.js:55
    a es6.promise.js:75
    M es6.promise.js:92
    c _microtask.js:18
react-dom.production.min.js:194:186
TypeError: "r.pictureUris is undefined"
    render Container.js:217
    render Container.js:193
    React 12
    v Redux
    setModels Base.js:125
    componentDidMount Base.js:55
    a es6.promise.js:75
    M es6.promise.js:92
    c _microtask.js:18
react-dom.production.min.js:194:186
TypeError: "r.pictureUris is undefined"
    render Container.js:217
    render Container.js:193
    React 12
    v Redux
    setModels Base.js:125
    componentDidMount Base.js:55
    a es6.promise.js:75
    M es6.promise.js:92
    c _microtask.js:18
Base.js:60:12

**Comment by joostdecock** [comment]
Based on the error message, I assume this is on beta.freesewing.org?

That frontend has fallen behind a bit on the work that's going on behind the scenes. Please check back in a couple of weeks.
