### ISSUE TITLE
Add number input to adjust pattern sliders

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1200]
@/AnthonyMJ on Discord: On the new website, it would be great to be able to input actual numbers even if they are within the constraints. Takes a lot of dexterity (and knowledge of fractions) to adjust those sliders to the exact number you want.

Another user mentioned they would like the option to go out of the sliders range, but @joostdecock mentioned that wasn't possible because of how the pattern is configured.

**Comment by joostdecock** [comment]
This is part of [the v3 roadmap](https://github.com/freesewing/freesewing/discussions/1278) so I'm closing this in favor of that.
