### ISSUE TITLE
Search engine DuckDuckGo does not grab FreeSewing's description

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1202]
[This is what DuckDuckGo shows.](https://media.discordapp.net/attachments/788066844393078835/863459724719947776/unknown.png)

The search engine grabs the first bit of text from the site to display, and not the description that has been set.

**Comment by joostdecock** [comment]
I've added better open graph support to the roadmap for V3. I'm going to close this now for it's not that big a deal I'd say
