### ISSUE TITLE
Community updates: TikTok and Discord

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1220]
Community To-Do's I'm responsible for 🙂 

- [x] Create webhooks from Instagram, Twitter and YouTube
- [x] Turn Discord server into a Community Server and up security
- [x] Put a pinned message in #pattern-design-team as a call for people to post their drafted patterns to the channel
- [x] Add descriptions to all the channels in Discord
- [x] Send poll into #dnd asking people their preferences for a long-term campaign
- [x] Add roles for events, also add roles for translation
- [x] Start the DnD sessions already! grr
- [x] Queue showcase posts to Instagram
- [ ] Resources channel on Discord 
- [ ] Overhaul of #profile-info on Discord
- [ ] Add bot/tool for tone indicators on Discord

I keep adding stuff which makes it hard to close 😂

**Comment by joostdecock** [comment]
Pretty sure this is all taken care of. Closing.
