### ISSUE TITLE
Add clarification in measurement docs for binding

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1228]
Julian/Aristocrats in Discord:
> The breast Vs no breasts thing is awesome but I wasn't sure how it applied when you were binding, and the help didn't mention it. I figured out I'm pretty sure it means if you want the breasts to be accentuated or not, so I measured with my binder on and chose no-breasts, but it would be good if this was added to the help!

Clarify that if you bind regularly, you probably won't want to make a pattern for when you're not binding, so the breasts-while-binding circumference should be put where you'd normally put breast circumference, and that you'd choose "no breasts" instead of "with breasts". This is not stated in the docs.

I may tackle this issue in due time but if anyone else is enthusiastic about it: go ahead!

**Comment by lucibytes** [comment]
Oh I should probably clarify:
Binding flattens the chest, you could see it as a very tight tank top. So people who have breast tissue and want to have a flat chest (whether it's because they're trans or cosplaying a dude, or something else) can use this technique.

**Comment by darigovresearch** [comment]
@lucibytes thanks for raising this. It appears no one so far has wanted to tackle this just yet. Would you like to have a go making a pull request?

**Comment by lucibytes** [comment]
@darigovresearch I'm interested! Have to properly learn that first 😋
