### ISSUE TITLE
Contributor call: August 7 2021

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1241]
You are all invited to the contributor call.
Please leave a comment here or [on Discord](https://discord.freesewing.org/) to put things on the agenda.
This issue will be updated after the call with notes and todos.

Hosted by @tangerineshark and me.

### About
- Location: https://discord.freesewing.org (meeting channel/room)
- Date: Saturday 24 July, 2021 16:00 UTC, which is:
        Los Angeles: 09:00
        Chicago: 11:00
        New York: 12:00
        São Paulo: 13:00
        London: 17:00
        Paris: 18:00
        Johannesburg: 18:00
        Moscow: 19:00
        Mumbai: 21:30
        Hong Kong: 00:00 on Sunday
        Tokyo: 01:00 on Sunday
        Sydney: 02:00 on Sunday

### About
- Discuss @sannek's block
- There was some talk on the naming of Simon and Simone + Carlton and Carlita
- Changes that come with project 2022: do we gradually introduce them or do we switch everything when it's ready?
- There are other people (other than Roy) willing to make illustrations
- Discuss halloween blog post
- Discuss October newsletter
- Perhaps some talk on events? (Now that we have discord roles for party events, sewing events, coding events, and even for DnD and Overwatch - although no pressure, the roles were created for if there's ever a need for it.)

### Notes
- @eleonoremilbou mentioned she needs help with the Instagram account, too much work too little time.
    - Multiple people mentioned they could take on some work. Bob proposed the idea of "roles", certain people manage certain areas of Instagram and that spreads the workload.
    - Then there's the question of what kind of work there is. There's showcase posts, regular posts, instagram stories and replying to DMs. Bob mentioned to create posts for things that are happening, for example when a new illustration is released, and stories for smaller things that are happening, for example someone testing a new pattern.
    - Some talked about an "instagram reset", renewing the way we approach the Instagram account. Maybe we can take inspiration from other instagram accounts that represent a community (rather than a brand or person).
    - I (@lucibytes) mentioned I could queue the showcase posts.
    - Anvi mentioned we could make posts with the help of Canva, a free design program.
    - @tangerineshark and I (@lucibytes) talked about the idea to do a call for volunteers, to see if anyone is up for this.
- There was a discussion in the Discord server about "Simone" being the name for Simon with bust darts/with a different style. Same with Carlton/Carlita.
    - @joostdecock explained the regular naming pattern, they are alliterations so it's easier to remember what name means what. (E.g. Aaron A-shirt.) The reason they are "people" names is because then there's no translation needed between different languages. This way of naming patterns can continue, these names don't have to be gender neutral.
    - There was some talk about renaming Simone to "Simon with bust darts", but that can get complicated with the code. (Even if you rename the title on the site, the old name will still be in the link.)
    - Wren mentioned it could be adapted to the measurements you put in (e.g. with breasts only shows Simon with darts (Simone) instead of both) but some people with breasts may want to use the Simon without darts.
    - If renaming Simone to Simon with bust darts (or something similar) is THE solution, then it can be looked into to change the code. Bob mentioned maybe we do a poll to get people's opinions on it, most importantly non-binary people's opinions.
    - However, since the call there's been talk in the Discord server about the issue. It was mentioned that the change between Simon and Simone is not just bust darts, it's a style change too, that perhaps the issue can be resolved by adding a description of what the difference is. (Can someone verify that it's a style change too, not just bust darts?)
- Newsletter coming up, do we know what we want to write about?
    - Perhaps Bob's patterns (or one of them) will have released before the deadline, then we can write about them.
    - An likely has an interview written out to put in there.
    - Reminder to put more images in the newsletter.
    - Halloween!
       - Bob is working on a witch hat pattern, and other patterns too.
       - I (@lucibytes) mentioned we could write tutorials on adding animals ears and dinosaur spikes to hoodie patterns.
       - We also want to make a list on cosplay ideas.
       - There are many possibilities here (both cosplay and regular ideas), how will we do that? Will we do separate blog posts, as a series? Will we do one long list in one blog post? Will we look into a gallery widget?
    - Next meeting: have this figured out so we can move on to making the list.

### To-do's
- @lucibytes get on queueing the Instagram showcase posts, add to #1220 
- @lucibytes and/or @tangerineshark: post a call for volunteers in Discord (in #announcements) 
   To add to that, maybe we can do a call for volunteers for managing events too. Especially because I (current event manager, I guess) am not in the American timezones, while ~half of the people in the server are in those timezones.
- Figure out the solution for Simon vs Simone (and Carlton vs Carlita)
- Figure out how we are going to present the halloween ideas (deadline: august 21)

**Comment by tangerineshark** [comment]
You read my mind! I was just looking into agenda items! Can we add "Halloween blog post" and "newsletter"?

**Comment by lucibytes** [comment]
Oops, forgot to close.
