### ISSUE TITLE
Phrasing for constructing the (complete) neck opening is confusing in tutorial

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1259]
It is not so obvious that when *update the neck path* we mean that we're going to overwrite the `paths.neck` value and that the newly constructed path should be outside the loop using the quarter-neck.

We should rework this.

Thanks to @lucibytes for reporting this

**Comment by joostdecock** [comment]
@lucibytes When we've published the updated website, you should perhaps check these changes to see whether it's more clear now.

@starfetch Didn't realize you self-assigned this. Sorry! :see_no_evil:

**Comment by starfetch** [comment]
@joostdecock no sweat ;)
