### ISSUE TITLE
Contributor call: September 4 2021

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1277]
You are all invited to the contributor call.
Please leave a comment here or [on Discord](https://discord.freesewing.org/) to put things on the agenda.
This issue will be updated after the call with notes and todos.

Hosted by @tangerineshark and me.

### About
- Location: https://discord.freesewing.org (meeting channel/room)
- Date: Saturday September 4, 2021 16:00 UTC, which is:
        Los Angeles: 09:00
        Chicago: 11:00
        New York: 12:00
        São Paulo: 13:00
        London: 17:00
        Paris: 18:00
        Johannesburg: 18:00
        Moscow: 19:00
        Mumbai: 21:30
        Hong Kong: 00:00 on Sunday
        Tokyo: 01:00 on Sunday
        Sydney: 02:00 on Sunday

### About
- A small celebration
- Discuss @sannek's block, if possible! 
- Bee Bikini pattern by @/prudencerabbit and @bobgeorgethe3rd is in the testing phase
- Halloween blog post
- Newsletter, to discuss:
   - @hellgy's survey
   - Pattern Project and Small But Perfect
-  https://github.com/freesewing/freesewing/discussions/1278 (including sewing pattern packs, per discord request)

### Notes
- 🎉It's been one year since the very first contributor call! One of the issues of that call was that the community had trouble connecting to the developers, but since then we've seen a lot of community patterns! The Discord server even has over 1000 members.
- Schiusano joined the call, he makes inclusive pattern designs and alterations, and is interested in helping out.
- Bee bikini is out for testing! @bobgeorgethe3rd mentioned he wants the markdown parts to be done before it's published. Testing is going well so far! The pattern is similar to the pattern that Katie (@/prudencerabbit), the designer, initially made. Bee is based on the Bella block, but the initial drafted pattern isn't, so it's good that the patterns are similar despite that difference. @tangerineshark made a version with a string going through the base, which inspired @bobgeorgethe3rd. They also mentioned that it's great that there's a triangle bikini that accommodates bigger busts.
- @tangerineshark went over the things we are planning for the newsletter:
    - We will put an interview from An in the newsletter, as well as @hellgy's user survey.
    - @woutervdub and @joostdecock have been on a podcast, Sew Over 50, and it would be fun to write about it!
    - @bobgeorgethe3rd doesn't just have Bee out for testing, he also recently released Peach, a princess seam pattern block, which also needs testing.
    - @joostdecock said that 2.18 should be out somewhere this week, with Yuri. They also mentioned that it would be better to have the URL for pattern testing be consistent with the site's URL, instead of Netlify. This is for 'brand' consistency. For example, `http://pattern.freesewing.dev` is better than `http://pattern.netlify.app`.
    - @joostdecock also mentioned that there's a pattern company based on FreeSewing. They make 'pattern packs', which is basically: pick a pattern and choose a fabric, and they will send you the fabric pieces needed, pre-cut, ready to sew together. We want to mention this in the newsletter, but not in a way that we are promoting them.
    - Another thing @joostdecock mentioned is that version 3 is in the making, which would be interesting to write about.
    - On the Halloween posts, I explained that we (@lucibytes and @bobgeorgethe3rd) have finished the list of ideas and now it needs to be written. There will be two halloween posts, one for regular ideas and one for cosplay ideas. There will be a blurb in the newsletter about this, but the full posts will be on the site.
    - The deadline for all newsletter articles is September 17. @ttimearl will likely be editing and proofreading the articles in the week(s) after. Schiusano added that he has a background in editing and proofreading and that he could help.
- @bobgeorgethe3rd mentioned it would be nice to have the site fully ready with v3, so all markdown and cover art done. Then the site is not only upgraded but also finished (to the extent that's possible).
- Yuri will not just have a segment in the newsletter, it will also have a blogpost announcing and describing the new pattern. Who will write it? Probably @joostdecock or @tangerineshark.
- The Halloween blogposts would really benefit from illustrations, to show the exact combination of things to go for. Perhaps we can message one of the people who offered to do illustrations.
- @joostdecock on version 3:
    - Short explanation on how versions work: we are now on version 2.17.2, a baseline of a.b.c. "a" is the major level, only upped with a huge update (like now). "b" is the minor level, which includes a new feature with every upgrade, usually a pattern. Level of "c" changes with bug fixes.
    - So, version 3 will be a big change. New versions are usually accompanied by bugs, which need to be found and fixed. @joostdecock mentioned that it comes down to "simplified code". Discussions on things that are broken will be held on Github.
    - @joostdecock mentioned some technical things
        - JSM modules only
        - No "default" exports, only by name
        - There's currently no debugging functionality in the code, there are plans for adding this.
        - He wants to make it simpler to make modular patterns, accommodating things like "collar packs" or "sleeve packs".
        - Changes to the website that are done in the meantime will get merged into the version 3 roadmap.
    - Currently the embed of the site (when you post a link somewhere and a little description pops up) is not optimal. It doesn't show the right information in the description. Also, the search engine DuckDuckGo has trouble picking up on FreeSewing's information. This will get worked on and updated with version 3.
    - There was some talk about the interface.
        - @bobgeorgethe3rd mentioned that it would be nice to discuss upgrading the interface. Also, some things on the dev site can be confusing and would benefit from better wording. @joostdecock replied that @hellgy's survey will help with this.
        - @bobgeorgethe3rd mentioned it would be handy if dev and design and docs were merged, instead of separate, for easier navigation. @joostdecock replied that there are plans for expanded navigation on the new site.
        - @bobgeorgethe3rd also mentioned that if you're on a design page and click to view documentation for that pattern, you can't easily go back to the design page, there's no button for that (aside from going a page back in your browser, but this doesn't work if you've roamed the documentation pages and want to go back to the design page).
    - @joostdecock mentioned there are SSR issues; there are bugs if you're on a deep link of the site and refresh. This is because the refreshing is done locally, on the client's side, and not on the server side.
- @starfetch mentioned they would like to see a zoom in or out feature when developing a pattern. @joostdecock replied that such a feature exists. The program wants to show the pattern completely on your screen, but there's a miniature window where you can choose where to zoom to. This feature could use some improvement, though.

### To-do's
- Make sure all previously mentioned newsletter articles are finished before September 17. (The day before the next contributor call.)
- Also make sure that article ideas without an author will be assigned to someone, or else removed. 
- @lucibytes and @bobgeorgethe3rd: finish the halloween posts. Also find a solution for the illustration wish.
- Yuri blogpost
To-do's not mentioned are part of the version 3 plans.

**Comment by tangerineshark** [comment]
Bonus agenda item: a small celebration

**Comment by lucibytes** [comment]
I'll add it, thanks!
That's really good for collaboration 👀 Feel free to edit the call agendas anytime 😊

**Comment by joostdecock** [comment]
Perhaps that discussion about modular patterns can be replaced with: https://github.com/freesewing/freesewing/discussions/1278

**Comment by tangerineshark** [comment]
Sure thing! @joostdecock do you still want it as a discussion point in the contributor call?

**Comment by joostdecock** [comment]
I think we can mention the v3 roadmap and that people can think about what they'd like to see on it. More an announcement than a discussion perhaps as I doubt people are going to have ideas so fully formed that we can discuss them.

**Comment by tangerineshark** [comment]
A) Sounds good!
B) I might turn that discussion largely over to you if you're present @joostdecock ! Although happy to bumble my way through it to the best of my abilities 😅

**Comment by joostdecock** [comment]
I plan to be there, so I'm happy to do a little bit of talking 😊

**Comment by lucibytes** [comment]
All is done 😊
