### ISSUE TITLE
Add measurement illustration for BustPointToUnderbust

### ISSUE THREAD

**Issue by tangerineshark** [freesewing/freesewing#1292]
- Page link: https://en.freesewing.org/account/people/nslqr/measurements/bustpointtounderbust
- Suggested content: Add measurement diagram for BustPointToUnderbust, following the format of other measurement diagrams here: https://freesewing.org/docs/measurements/

Looking to tackle this issue? Check out our [documentation for editors](https://freesewing.dev/editors/) to learn how to contribute updates.

**Comment by starfetch** [comment]
Closed via https://github.com/freesewing/freesewing.org/pull/1542.
