### ISSUE TITLE
Bug report - Google results show freesewing.org/patterns, but there is no content on that page

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#1343]
**What seems to be the problem?**

When searching freesewing on google, you get a kind of map of the site with the various sections. But if you click on "Patterns" it goes to https://freesewing.org/patterns/ and there is nothing there. Either Google build that map on it's own... or there is a metadata file that google download and trust, and that one is obsolete due to change on the web site (or the patterns section should exist and there is a bug there, it is missing).

**Are you a FreeSewing patron?**

 - [x] Yes, I am :hugs:
 - [ ] No, I am not :thinking:

**Additional context**

This was [reported by David.G on Discord](https://discord.com/channels/698854858052075530/757632953097388043/890479928179568680)

**Comment by joostdecock** [comment]
Fixed (but not yet deployed). 
See https://github.com/freesewing/freesewing.org/pull/1468 for details
