### ISSUE TITLE
Developer call: October 2 2021

### ISSUE THREAD

**Issue by nataliasayang** [freesewing/freesewing#1352]
You are all invited to the **developer call**: a 30-minute brainstorm on inner workings of FreeSewing hosted by @joostdecock (supported by @nataliasayang)
If nerding out over ESM modules, default vs named exports, SSR bugs, React hooks, unit tests, merge requests, or REST APIs is your jam, then this is the call for you. Also: it's short (30 minutes) and informal. 

Please leave a comment here or [on Discord](https://discord.freesewing.org/) to add things to the agenda.
This issue will be updated after the call with notes and todos.

### About
- Location: https://discord.freesewing.org (meeting channel/room)
- Date: Saturday October 2, 2021 15:30 UTC, which is:
        Los Angeles: 08:30
        Chicago: 10:30
        New York: 11:30
        São Paulo: 12:30
        London: 16:30
        Paris: 17:30
        Johannesburg: 17:30
        Moscow: 18:30
        Mumbai: 21:00
        Hong Kong: 23:30
        Tokyo: 00:30 on Sunday
        Sydney: 01:30 on Sunday

### Agenda
- Updates on [v3 roadmap](https://github.com/freesewing/freesewing/discussions/1278) and ways to get involved
- [the snap proposal](https://github.com/freesewing/freesewing/discussions/1331) and `@freesewing/snapseries` have been implemented
- @starfetch may be interested in contributing historical patterns Lunetius, Walburga, Tiberius
- @nataliasayang has questions about line drawings and translation keys
- Check AWS support for ESM
- Zoom and Pan: D3 provides this
- Editing in an environment that resembles the website (best case scenario: edit inline)
- Potential way to custom layout: https://bitbucket.org/goatchurch/laserplacer/src/master/

### Notes
- Best ways to get involved: Share your ideas and opinions
- Lunetius, Walburga, Tiberius: @starfetch would love to contribute them. @joostdecock needs the code, so Starf shared the Github repos
- New line drawings for v3 are a nice-to-have. See https://github.com/freesewing/freesewing/issues/1282
- Considerations for SVG artists: Should set some standards for visual consistency. Thick line (primary), medium line (secondary), thin line (seamline)
- We discussed how SVGs work on the measurement pages. Starf submitted a PR to add a new measurement illustration
- Check AWS support for ESM: 99% sure not a problem
- Zoom and Pan: Haven't looked at it yet
- Editing in an environment that resembles the website: Long story short, it's complicated but we'll look into it
- Potential way to custom layout: Haven't looked at it yet, but this *will* go in v3. Not everything on the road map will be in v3, but this one will be. Has been on wish list for a long time. We are all excited about it
- @bobgeorgethe3rd mentioned that some of the cover arts, like Bruce and Cathrin, include mini line arts as well. joost is leaning towards removing those from the ones that have them because it feels like we're trying to cram too much in. We might change the layout. Might have a toggle. It's a UI question and we're considering our options

**Comment by nataliasayang** [comment]
Added notes. @joostdecock please feel free to edit as needed. Closing.

**Comment by joostdecock** [comment]
Thanks, you're a champ! :heart:
