### ISSUE TITLE
Add armhole to waist measurement

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1360]
This would help with (womenswear) blocks. Question is, where does this measurement start on the armhole side?

This is a todo from #1353

**Comment by bobgeorgethe3rd** [comment]
Would you do it from where the chest circumference is at the armpit?

**Comment by SeaZeeZee** [comment]
I dont have a drafting textbook here, but I wonder where that says to measure from, there must be a standard for it!

**Comment by stsydow** [comment]
I tried something like that in #1817 for Brian.
I previously used the paperless mode and where counting gird units quite a lot.
So I added all measurements I would use:
![pattern](https://user-images.githubusercontent.com/961256/152705739-88245aed-81cb-4bea-bde6-3d01e3416773.svg)

**Comment by SeaZeeZee** [comment]
I did some research on archive.org because I don't have a modern book on pattern drafting available. Bearing in mind these are older sources armhole to waist is usually measured from the armpit to the waist down with the arm down at the side. Sometimes with the aid of a square. Notes are to not have people clamp so hard they raise the shoulder.

Image is from a drafting manual from 1888. 

![armhole](https://user-images.githubusercontent.com/86711383/152819631-90577317-fe90-4038-93f2-4b286d06f90b.png)

**Comment by stsydow** [comment]
Oh I get it (sorry, I got the original question wrong). So `hpsToWaist - armpitToWaist` would be the minimal armhole depth?
Than we could apply the biceps ease and don't use the `armholeDepthFactor`?

**Comment by joostdecock** [comment]
FYI: Work for this started in #2060

**Comment by stsydow** [comment]
I appreciate that you introduced `armholeHeight` to brain.

I fear that it is quite indirect and therefore error-prone.
It depends on the measurements high-shoulder-to-waist, shoulder-slope, and armhole-to-waist.
I fear that the accumulated error for armholeHeight will be a problem for tight fitting cloth.

But it is a step forward in any case!

**Comment by joostdecock** [comment]
@stsydow If you have a more resilient way to determine hps, shoulder, and armhole I'd love to hear it.

But I feel that this change will make it somehow more unforegiving, and perhaps that makes it easier to spot issues with faulty measurments.

What I mean is, let's say that you measure your shoulder slope as being too steep. Currently, that will push down the entire armhole, and so you will need a bit of a trained eye to realize the underlying problem is the shoulder slope. Most people will just see a bunch of wrinkles and conclude *this fit sucks*.

With these changes, it will push down the shoulder point, but the armhole bottom will stay were it is (because it's related tot he waist, not the shoulder point) and thus you will end up with a smaller arm opening, which would be a better indicator that there's a problem somehow.

We could also potentially add a check by calculating the arm opening length and comparing it to the biceps circumference and say: "_Looks like you're arm won't fit in this armhole_".

To be clear: I'm open to suggestions for improvements. I'm just thinking about loud about the pros/cons of these changes.

**Comment by BenJamesBen** [comment]
I'm not taking full ownership of this, but I will work to gather consensus about what measurement to use and its definition/instructions.

**Comment by BenJamesBen** [comment]
I checked two professional pattern drafting books, and neither of them use any sort of armhole depth or length measurement to draft the block sloper. They do both refer to an "underarm point".

Kershaw, Gareth. Pattern Cutting for Menswear
> Underarm point – the position at which the arm joins the body under the arm

Lo, Dennic Chunman. Pattern Cutting
> There is no specific position for the underarm point.
> For a basic bodice block, a good rule of thumb is to place the underarm point approximately 1cm (3/8 in) 
above the top edge of the side of the model’s bra.

I will try to check more references to see if they might have more information or other viewpoints. However, I am leaning towards an "Underarm to waist" measurement, with possible instructions below.

---
 title: Underarm to waist
 ---
 
 The **underarm to waist** length is the measurement from your underarm point
 down to your waistline, measured on the side of your body.
 
 To measure your **underarm to waist**, locate your underarm point.
 Then measure straight down to the line that forms your waist circumference,
 making sure to measure at the side of the body.
 
 ###### Underarm point
 
 Your underarm point is the exact location below your arm where the
 arm meets the torso.
 Please note that this is different than the bottom of the armhole in garments;
 that location is almost always lower than the underarm point to provide
 wearing or fashion ease.
 
 If you have difficulty determining the location of your underarm point, 
 it might help to place a pencil or ruler underneath your arm and clamp 
 down on it lightly.
 Be sure to keep your shoulder and arm relaxed to avoid raising your shoulder.
 The underarm point will be located under your arm at the top of the ruler 
 or pencil.

**Comment by joostdecock** [comment]
Note that there's some work that was done in this PR: https://github.com/freesewing/freesewing/pull/2060

I've closed that PR because it was in the v2 codebase, but it probably has some useful info for a plan of attack to implement this.
It also added some new options (such as sleeveBulge) which I think could be useful.

**Comment by BenJamesBen** [comment]
Some of closed draft PR #2060 is outside the scope of this Issue which is to add the new measurement as a standard measurement, available to be used. It does not cover changing designs to use the new measurement. That decision to do so is up to the individual designers.

I discovered that a measurement named `waistToArmhole` already exists in the FreeSewing repository.

I'm not sure which if any files are generated, but files that I see instances of `waistToArmhole` in include:
```
config/measurements.mjs
sites/backend/src/measurements.mjs
sites/shared/config/freesewing.mjs
packages/models/src/neckstimate.mjs
packages/i18n/src/locales/en/measurements.yaml
```

**Comment by BenJamesBen** [comment]
On Discord, I asked:
> I notice that a `waistToArmhole` measurement was already added to the FreeSewing repository last year. Did we already decide to use that measurement name?

But, I didn't receive an answer. So, I assume we are free to change the measurement name to `waistToUnderarm`.

https://discord.com/channels/698854858052075530/698854858496802868/1095353518736543774
discord://discord.com/channels/698854858052075530/698854858496802868/1095353518736543774

**Comment by BenJamesBen** [comment]
Joseph-Armstrong, Helen. Patternmaking for Fashion Design
> In the 5th edition of "Patternmaking for Fashion Design" by Helen Joseph Armstrong, the author instructs people to take two body measurements for the armhole: the bust circumference and the back waist length. The book uses the terms "high bust" and "back waist length" for these measurements. The high bust measurement is taken around the body at the level of the upper bust, just under the arms. The back waist length measurement is taken from the prominent bone at the base of the neck to the natural waistline at the back.

https://discord.com/channels/698854858052075530/698854858496802868/1106265551183028274
discord://discord.com/channels/698854858052075530/698854858496802868/1106265551183028274

**Comment by BenJamesBen** [comment]
In the May 27, 2023 Contributor Call:
- It was confirmed that we had already agreed to add the measurement as an official measurement.
- The measurement will be named "Waist to Armpit".
- The Waist to Armpit measurement will be based on an actual, measured body location, not a garment armhole location. (Individual designs would be responsible for deciding where the actual armholes will be located, how much ease to include, etc.)

There is a desire to update our designs to use the new Waist to Armpit measurement, but that is an effort separate from this Issue. (I will help to convert designs, when the time comes.)

**Comment by joostdecock** [comment]
Implemented. All designs migrated. Closing.
