### ISSUE TITLE
Support wider hips than chest in Wahid

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1361]
**What seems to be the problem?**

Wahid (and potentially other patterns based on Brian) do not allow for the hips to be wider than the chest.

We should add support for this so we can fit people who have wider hips than chest (which is common).

This is todo from #1353

**Comment by stsydow** [comment]
I tried it for Brian in #1817, which is work in progress. May be I need to split it up into several smaller changes.

**Comment by SeaZeeZee** [comment]
I'm unassigning myself because I don't think I can make Brian do the required things for Wahid to work for people with hips.

**Comment by joostdecock** [comment]
Moved to the roadmap. Closing (for now)
