### ISSUE TITLE
Error when creating a maker profile

### ISSUE THREAD

**Issue by nataliasayang** [freesewing/freesewing#1362]
**What seems to be the problem?**

Creating a new maker at https://freesewing.org/new/maker/ sometimes does not work. It has worked for many users, but a few including @/RedBlaqueGolden and @starfetch have encountered issues.

Reported by @starfetch on 1 October:
> after filling everything out and pressing the button, Skully blinks at me for a few seconds, then nothing happens (still on same page), I press the button again, Skully blinks again, then I'm on the Oh no, something went wrong -page 🤔 (4 tries, same result)

**Are you a FreeSewing patron?**

 - [x] Yes, I am :hugs:
 - [ ] No, I am not :thinking:

**Additional context**

We think this could be related to other issues with the site related to certificate renewal.

**Comment by nataliasayang** [comment]
Zwaluw tried to make a maker profile and it didn't work. They attempted it on November 1st and again today, November 4th. From their end it looked like it went through but their profile (username `Zwaluw`) isn't in the list of makers.

**Comment by joostdecock** [comment]
This is a `413 Request Entity Too Large`. I'll add an error message that explains it.

**Comment by joostdecock** [comment]
![Screenshot from 2021-11-13 15-55-25](https://user-images.githubusercontent.com/1708494/141648350-9e241bba-ed1a-496a-89bb-3c0293cf18b0.png)

This will popup **before** submitting the form.
