### ISSUE TITLE
Contributor call: 30 October 2021

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1408]
You are all invited to the contributor call. 🎃👻💀
Please leave a comment here or [on Discord](https://discord.freesewing.org/) to add things to the agenda.
This issue will be updated after the call with notes and to-dos.

Hosted by @tangerineshark and @lucibytes.

### About
- Location: https://discord.freesewing.org (meeting room: `🔊voice chat`)
- Date: Saturday October 30th, 2021 16:00 UTC, which is:
        Los Angeles: 09:00
        Chicago: 11:00
        New York: 12:00
        São Paulo: 13:00
        London: 17:00
        Paris: 18:00
        Johannesburg: 18:00
        Moscow: 19:00
        Mumbai: 21:30
        Hong Kong: 00:00 on Sunday
        Tokyo: 01:00 on Sunday
        Sydney: 02:00 on Sunday

### Agenda
- FreeSewing's Bug Bounty program: Could/Should we have one? And if so, how would that work?
- Rise of the machines: Welcome to our robot overlords

### Notes
- Lunetius has linedrawings now!
- @joostdecock proposed the idea of a bug bounty program.
    - Big companies like Google give money to those who find significant bugs. We're not going to work by money.
    - Why: there was a small but overlooked bug in Simon, one user complained, it was fixed. This raises the question "how many people have made this pattern, had this problem, but didn't say anything?" The idea is to make an incentive for people to report bugs.
    - Hard to do this by automation.
    - @nataliab asked if we're looking for bugs in pattern generation or general fails or.. @joostdecock replied that if a pattern goes off the rails, we fix it, we're looking for bugs that are overlooked. (Not just generation.)
    - @woutervdub said we should make it more clear we're actually looking for these bugs. Maybe people just don't know that.
    - @eleonoremilbou mentioned it could also be a sense of "is it me or is it the pattern?" that could be holding people back.
    - @bobgeorgethe3rd said that it could be more comfortable for people to share bugs if it's anonymous, but we need data to be able to redo the bug - @woutervdub.
    - How can we motivate people?
        - @lucibytes & @bobgeorgethe3rd: we can give people a special Discord role.
        - @tangerineshark mentioned there's a lot of amino for the stickers (and buttons). Maybe we can send those around as a reward? It's a good idea, @joostdecock mentioned we do need a 'local person', someone in each country/continent who can send the stickers around (to keep shipping costs and import fees low).
    - Conclusion: stickers will be sent around as a reward for finding a bug.
    The details need to be figured out and we also need to pitch it sometime.
- We're getting some help from robots! Simply put: automated checks.
    - There are *a lot* of packages on the monorepo.
    - Robots can make life easier here, checks on quality assurance, avoiding problems and more. More of these checks will gradually be added.
    - Ambitions: 'more insightful checks' for patterns, checking if a pattern's class is right, if its draft points are correct, if the labels are right, etc. (Correct me if I misunderstood this.)
- @bobgeorgethe3rd asked if there was work to do on declarative titles. @joostdecock replied that it's not a priority right now, it's set for the v3 roadmap.
    - In the meantime we'll likely be making changes to titles anyways, so it's best to do it afterwards.
    - The point of this is that the title of, for example an option, is the exact same on the pattern page and on the documentation page.
- @starfetch mentioned that there are some duplicates on Crowdin, the site where we manage our translations. Translating one thing does not always translate the same word in other places.
    - This may be a matter of permissions and @joostdecock will look into it.
    - @tangerineshark also asked if you'd need to translate the picture (file) names. @joostdecock said that Crowdin should know how to deal with pictures as well, but you never know. So, only add content in English.
- @nataliab asked @woutervdub if he needed help on his upcoming pattern.
    - He needs a list of measurements still, to see how the pattern drafts on different bodies.
    - Origin story: in Las Vegas he saw a cool coat on display and he wanted to replicate it, now making it into a pattern. He used the Bella block and changed it into a princess seam.
    - There was some confusion on how that would work (if the seam is flat enough for a person without breasts), but it should be (it is for the mannequin at least!).
- @bobgeorgethe3rd with updates on the Laura Leggings pattern!
    - Option for higher waist is added.
    - Proper waist points, no more swirl.
    - Turns out the pattern needed the hip measurement instead of the seat measurement, after all.

### To-do's
- Figure out the details of the Bug Bounty program and how to pitch it
- Crowdin duplicate fix
- Measurements for Wouter, another pitch in Discord or another solution or?

**Comment by joostdecock** [comment]
I'm seeing what might be a trend where people are rather cavalier about changing options names.
So I'd like to add this to the next call agenda:

Renaming pattern options has non-trivial ripple effects, like:
   - It changes the path of the documenation for those options
   - It changes the filenames of the auto-generated images
   - It breaks backward compatibility with patterns that are stored in user profiles, or Github gists

So please keep this in mind:
   - Think before choosing your option names initially. When in doubt, ask around
   - Do you really need to change the name? Maybe the change can be handled in translation?
   - If you do change it, let @joostdecock know so he can make sure everything is updated

**Comment by joostdecock** [comment]
Also for the next agenda:

- Do not add a *glossary* section to documentation. That's why we have [remark-jargon](https://github.com/freesewing/freesewing/blob/develop/packages/remark-jargon/README.md)
- Do not create lists with hackish markup, please learn markdown instead

:pray:
