### ISSUE TITLE
Document Point.dist()

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1426]
It's missing somehow 🤷

**Comment by sannek** [comment]
I was just rewriting this, but I realised why it's not there in the first place: It's getting `gitignore`d because we (sensibly) gitignore `dist` folders.

**Comment by sannek** [comment]
Not sure how to fix that without including any other `dist` folders that we don't want 🙃

**Comment by starfetch** [comment]
You could force add the file with `git add -f`, without having to tamper with the `.gitignore`.

**Comment by sannek** [comment]
Ah that would work! My solution was to be more explicit and unignore that specific folder. 

```
dist
!markdown/dev/reference/api/point/dist
```

**Comment by starfetch** [comment]
That is probably the better solution long-term :smile:
