### ISSUE TITLE
Teagan pattern says "Cut 2x On the fold" on the front and back

### ISSUE THREAD

**Issue by nataliasayang** [freesewing/freesewing#1450]
**What seems to be the problem?**

Teagan says "Cut 2x On the fold" on the front and back, but only one of each piece is needed.

**Are you a FreeSewing patron?**

 - [x] Yes, I am :hugs:
 - [ ] No, I am not :thinking:

![image](https://user-images.githubusercontent.com/48160791/140250093-d71703c1-035f-4da3-a474-01bf5d203cae.png)

**Comment by starfetch** [comment]
Poked around and found the place to change it, I didn't know you could actually specify that on the pattern (in a limited way, I guess). Related: #1029.

**Comment by nataliasayang** [comment]
You're brilliant, @starfetch . I couldn't find it. Thanks for closing this!

**Comment by starfetch** [comment]
I was also very puzzled at first, found it more by chance than anything else ;)
