### ISSUE TITLE
Create showcase from this content

### ISSUE THREAD

**Issue by fast77** [freesewing/freesewing#1458]
The first Simon shirt made by ferdi with cheap fabric for testing the pattern and my skills. Oops, the button placket got on the wrong side. But no matter, overall it came out well and fits excellently.

 - Permission: I am the original author, and hereby grant permission to repost this content.

![simon-01 - 1](https://user-images.githubusercontent.com/93778943/140525466-5b393a8e-3b4b-48f8-a92f-2c73ead0f5e3.jpeg)

**Comment by joostdecock** [comment]
Hope it's ok to assign this to the :camera_flash: :crown: @nataliasayang 

Thanks for creating this issue @fast77 It seems you joined Github to do this and that's kinda awesome :heart: 
It would be double-awesome if you could create your maker profile here: https://freesewing.org/new/maker/

That allows us to properly credit you on the showcase page. Here's an example with my own maker profile: https://freesewing.org/showcase/a-tamiko-top/

**Comment by fast77** [comment]
Thank you, Joost. Just tell me if I should do something better. My profile is out now.
And … freesewing.org <http://freesewing.org/> is fantastic! Thank you so much.
Warm regards, Felix
