### ISSUE TITLE
Charlie is not drafting! It may be Titan

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#1460]
Charlie is not drafting full stop. 
With own measurements or with the standard.
I believe it has something to do with Titan has there been a recent update to it?
I noticed the Titan block now has the waist on the front of Titan drops below the side seam on the front.
This is reason why we keep getting Charlie errors.
If you click on Charlie and spin up a draft you will see that it is not drafting the titanBack or titanFront.

**Comment by joostdecock** [comment]
Fix is part of the 2.19.3 release: https://www.npmjs.com/package/@freesewing/charlie
An updated freesewing.org is build built on Netlify right now: https://app.netlify.com/teams/freesewing/builds/618577feeb8033000875be04
