### ISSUE TITLE
Simon shirt

### ISSUE THREAD

**Issue by fast77** [freesewing/freesewing#1462]
The second Simon shirt I made. Cheap cotton fabric, nothing special, but with beautiful nacre buttons from the charity shop. And I am so happy with the sleeves, which are really long enough.
 - Permission: I am the original author, and hereby grant permission to repost this content

![simon-02 - 1](https://user-images.githubusercontent.com/93778943/140564207-a459390c-96ed-4403-84e8-0cda38fd4d0c.jpeg)

**Comment by nataliasayang** [comment]
This looks fantastic! Thanks, ferdi! I'll get this added to the site.

**Comment by fast77** [comment]
Thank you! Should/can I tag my contributions with „simon“ by myself? Or was it ok like I did on Github?
Warm regards, Felix

**Comment by joostdecock** [comment]
@fast77 I've invited you to the FreeSewing organisation on GitHub. You should receive an email about this.

If you accept the invite, you'll get *triage* permissions allowing you to tag issues, assign them and so on.

Welcome aboard 🤗
