### ISSUE TITLE
Simon as overshirt

### ISSUE THREAD

**Issue by fast77** [freesewing/freesewing#1463]
My third Simon shirt, this time as an overshirt, which I therefore made a little wider (well, at the shoulders it has become a little too wide). The fabric is 60/40% merino wool / cordura - very comfy. On the left is a small zipper pocket inserted. I wear it both hiking and in the office.

 - Permission: I am the original author, and hereby grant permission to repost this content

![simon-03 - 1](https://user-images.githubusercontent.com/93778943/140565358-cfc24e61-bb3d-4fa7-8017-3dc94cf4f570.jpeg)
![simon-03 - 2](https://user-images.githubusercontent.com/93778943/140565379-72b002b0-d4c1-4bb8-a7fc-b660bcd9e4e8.jpeg)

**Comment by nataliasayang** [comment]
@fast77 All of your creations are excellent, but this one is my personal fave! A very wearable, handsome version of Simon. I'm adding the showcases to the site now so you'll be able to view them at https://freesewing.org/showcase/ the next time @joostdecock deploys the site.
