### ISSUE TITLE
Contributor call: 13 November 2021

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1468]
You are all invited to the contributor call. 
Please leave a comment here or [on Discord](https://discord.freesewing.org/) to add things to the agenda.
This issue will be updated after the call with notes and to-dos.

⚠**Important:** many countries have adapted to daylight saving time and the like. 
**Double check the call hours or check the bot in Discord!** (Find it in #meetings.)

Hosted by @tangerineshark and @lucibytes.

### About
- Location: https://discord.freesewing.org (meeting room: `🔊voice chat`)
- Date: Saturday November 13, 2021 16:00 UTC, which is:
        Los Angeles: 09:00
        Chicago: 11:00
        New York: 12:00
        São Paulo: 14:00
        London: 17:00
        Paris: 18:00
        Johannesburg: 19:00
        Moscow: 20:00
        Mumbai: 22:30
        Hong Kong: 01:00 on Sunday
        Tokyo: 02:00 on Sunday
        Sydney: 04:00 on Sunday
**The information above is (should be) accurate.**

### Agenda
- Renaming pattern options has non-trivial ripple effects, like:
    - It changes the path of the documentation for those options
    - It changes the filenames of the auto-generated images
    - It breaks backward compatibility with patterns that are stored in user profiles, or Github gists
    - So please keep this in mind:
        - Think before choosing your option names initially. When in doubt, ask around
        - Do you really need to change the name? Maybe the change can be handled in translation?
        - If you do change it, let [@joostdecock](https://github.com/joostdecock) know so he can make sure everything is updated
- Other markdown things of importance
    - Do not add a *glossary* section to documentation. That's why we have [remark-jargon](https://github.com/freesewing/freesewing/blob/develop/packages/remark-jargon/README.md)
    - Do not create lists with hackish markup, please learn markdown instead
    - Don't use **here** as link text
    - Keep links relative (not `https://freesewing.org/docs/patterns/holmes/cutting/` but `/docs/patterns/holmes/cutting/`)
    - Don't mix multiple levels of *steps*
    - Watch out for whitespace at the end of a line
    - Leave an empty line before and after custom components
    - Leave an empty line at the start and end of custom components of there's any formatting inside of them
- There are a lot of old issues present, we should take a look at them.
- It's probably time to start talking about the Jan 1 2022 newsletter.
- @bobgeorgethe3rd's proposals

### Notes
- @joostdecock on markdown guidelines
    - Documentation pages don't need a glossary, we have *remark-jargon*, which is basically a side-wide glossary: if you hover over a link that has an explanation set, it will show a description. This is especially needed to keep the translation workload low.
    - Other markdown pointers are listed above, but @lucibytes will put them in the markdown documentation as well. (There won't be an extensive "how to write documentation" guide, but it will be a list of frequently made mistakes.)
    - Renaming pattern options *can* be done, but please give it some extra thought when you initially name your pattern option. But if you do change it, let @joostdecock know about it.
- @bobgeorgethe3rd mentioned that there are a few old issues left, oldest going back two years, and maybe we can go through them to finally check them off. @joostdecock replied that a lot of those issues are easy or just have a low priority. We can take another look at it.
- @tangerineshark mentioned that the newsletter for January is coming up! Ideas?
    - The thing we always do in the January edition: all that happened in the past year, all our goals for the next year.
    - Mentioning the removal of the breasts and no breasts distinction (if it goes through around that time).
- @bobgeorgethe3rd had some ideas!
    - Overhaul of pattern pages for a more streamlined and professional look.
        - Change lay-out, use info from @/hellgy's UX survey.
        - We could upgrade the pattern pages by having the cover art, linedrawings and (good quality) photos of the garment from multiple angles, on one page, centrally.
        - However, this takes a lot of work. (And the showcase and linedrawings are already on the pattern page.)
        - But @tangerineshark suggested we could include some tips for showcase submissions, especially to ask people to make pictures from different angles.
    - A reference sheet for deploying a new pattern.
        - When Bob was making Bee, he only realized later that some things were incorrect (options, labels, some things even missing). A reference sheet that shows everything that needs to be filled out, would have solved this. Or the option to see what the pattern looks like on the site before it's actually published.
        - @joostdecock replied that people don't want to do paperwork, and open-source projects commonly go like this: publish a new thing that's not fully finished but adding changes as time goes on, instead of doing everything at once. But a preview of the upcoming FreeSewing release exists, it's at [next.freesewing.org](https://next.freesewing.org/). This went under the radar.
        - It would also be nice to have a full description - a 'biography' - of a pattern with its history (similar to @woutervdub's Cornelius article in the newsletter) and descriptions of pattern options, what it actually does. This is up to the designer and/or coder.
    - A template for what a documentation page should look like (markdown).
        - This would have solved/prevented issues.
        - Turns out: a lot of us use Aaron as a reference for documentation pages. So, Aaron is now our template!
    - Contributor pages of the coders and designers of a pattern, on the pattern page.
        - The names of these contributors are on the page, and are clickable, but it would be cool to have a new-style profile on there as well.
        - Also that it would show all the patterns and showcases a person has made.
        - This seems to basically be an extended maker profile, we're already going in that direction!
    
### To-do's
- #1513
- For people to take another look at the years old tasks
- #1512
- Aaron as a template - action needed?

See you there! 👋👋 
Notes and to-do's after the call.

**Comment by lucibytes** [comment]
Keeping the issue open to ask @joostdecock: do we want to make a markdown template from Aaron? Or do we just say "use Aaron as your reference" (and do we add that somewhere on the site)?

**Comment by lucibytes** [comment]
Bumping @joostdecock 😅

**Comment by joostdecock** [comment]
Oops, thanks for the reminder 😬

I'd prefer to just refer to Aaron as creating a template from it will create extra work to maintain that template without much added value.

**Comment by lucibytes** [comment]
Makes a lot of sense. Thanks! Finally closing.
