### ISSUE TITLE
Readjust contents order for patterns

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1476]
**What is it that you would like to see happen?**

Currently it appears that the contents of each pattern goes in alphabetical but it may be better to set the order so that it is more understandable for the reader to know which order to read the sections in

![image](https://user-images.githubusercontent.com/30328618/140645268-ae5282b1-af03-45c4-9030-17d764503c71.png)

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Not sure if there was a reasoning behind the current setup but our suggested order would be

- What you need
- Fabric options
- Required measurements
- Pattern options
- Cutting
- Instructions

However we usually recommend anyone who is building anything to read all the instructions first, cutting & instructions could be flipped in the above order

This may be a good first issue if anyone is making a contribution to freesewing

**Comment by joostdecock** [comment]
Will be a feature in the new website we're bulding. Won't fix in the current one.
