### ISSUE TITLE
Include tips for showcase submissions

### ISSUE THREAD

**Issue by lexander2002** [freesewing/freesewing#1512]
Suggestion from our last call by @tangerineshark, #1468 

Include tips on making pictures of garments.
Most importantly the request to take pictures from different angles.

~~(Where would we add these tips? Discord?)~~

Update on where:
- [ ] On the showcase page
- [ ] [In the contributors guide](https://freesewing.dev/contributors/ways-to-contribute/showcase-our-patterns/)
- [ ] Github showcase template
- [ ] In the Discord section of "How to submit a showcase"

**Comment by darigovresearch** [comment]
Thanks @tangerineshark for the suggestion & @lucibytes for turning this into an issue. Having a note on the showcase itself that contributions to that page are welcome & a link to the actual tips in the contributing guide may be helpful. Also a link from the new issue template may be helpful - https://github.com/freesewing/freesewing/issues/new?assignees=&labels=%F0%9F%91%8D+good+first+issue%2C+%F0%9F%93%B8+showcase%2C+%F0%9F%A4%97+community&template=showcase-template.md&title=Create+showcase+from+this+content

**Comment by lucibytes** [comment]
Thank you! That sounds good! I added them.

**Comment by lucibytes** [comment]
List of tips to include:
- Multiple angles
- Daylight
- No flash
- Neutral background
(The tips written out in a full sentence preferably 😆)

Left out composition on purpose (I assume it's obvious to have the whole garment in frame (if possible) + composition tips aren't relevant as we're not asking for professional photography).

**Comment by SeaZeeZee** [comment]
I would add seated pictures to the tips as well, since those are very helpful for anyone who uses a wheelchair!
