### ISSUE TITLE
Add frequently made mistakes to markdown guide

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1513]
Add @joostdecock's list of overlooked mistakes to the markdown guide. This won't be an extensive guide to documentation.

I will do this but also I am slow 🐌

**Comment by darigovresearch** [comment]
Thanks @lucibytes for having a go at this, have added extra tags to encourage any people looking at the issue to have a go if they are interested in contributing and think they may be able to resolve this faster

**Comment by lucibytes** [comment]
Awesome, thanks!

**Comment by SeaZeeZee** [comment]
Closing this issue since the documentation got merged!
