### ISSUE TITLE
[Feature Request] Instructions on how to upload a pattern to the site

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1515]
**What is it that you would like to see happen?**
After attempting the [pattern design](https://freesewing.dev/tutorials/pattern-design/) tutorial and having four ideas for new patterns it would be great to know how to contribute a pattern back to the main site. I.e. you've completed a pattern, In which repo do you make a pull request & what format etc.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**
This may already exist but couldn't be found easily, could be added as a new how to, guide or as a new section in the pattern design tutorial

Outstanding issues which this issue would help contribute towards:
Bucket hat - https://github.com/freesewing/freesewing/issues/1431
Bib - https://github.com/freesewing/freesewing/issues/1469
Eye patch - https://github.com/freesewing/freesewing/issues/1479
Garment cover/carrier - https://github.com/freesewing/freesewing/issues/1480
Ushanka hat - https://github.com/freesewing/freesewing/issues/1491

**Comment by darigovresearch** [comment]
Not sure if it will need to be rewritten but we would be happy to use your guide with patterns we're trying to build @SeaZeeZee 

@joostdecock & @nicholasdower do you know if it would need to be rewritten?

**Comment by joostdecock** [comment]
I think it would make sense to use the new development environment in the monorepo as a target for documentation.

It's not entirely finished, but it's useable and writing docs is a good way to bring out pain points we need to address.

Essentially it boils down to running `yarn prebuild` followed by `yarn develop` in the `freesewing.lab` folder.

However, what we need is to add some automation around starting a completely new design.

**Comment by joostdecock** [comment]
The new development environment new exists in two varieties:

- Stand alone: Pretty much a drop-in replacement for the previous development environment
- Monorepo: This is for people who want to contribute their pattern

Furthermore, the development docs now list both options as such:
![Screenshot from 2022-07-09 11-35-58](https://user-images.githubusercontent.com/1708494/178100248-768b4f38-b69e-4ba2-bf86-95fc161b6452.png)

As such, I consider this resolved.
