### ISSUE TITLE
[Bug report] Weird indentation of code in tutorials

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1520]
**What seems to be the problem?**

When there are code samples on the site (like [here](https://freesewing.dev/tutorials/pattern-design/your-first-part/)) the first line is often indented one space further than subsequent lines.

![image](https://user-images.githubusercontent.com/30328618/143228399-e1811c89-58b6-4504-8f3c-698dfb6826aa.png)

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

This may be an easy fix for someone wanting to make a contribution to the project.

**Comment by joostdecock** [comment]
Fixed in the new NextJS based website:

![Screenshot 2022-01-04 at 20-34-55 Your first part](https://user-images.githubusercontent.com/1708494/148113904-e9d7d7f3-3627-47b5-87bb-eae3f4e9c13b.png)
