### ISSUE TITLE
Contributor call: 11 December 2021

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1562]
You are all invited to the contributor call. 
Please leave a comment here or [on Discord](https://discord.freesewing.org/) to add things to the agenda.
This issue will be updated after the call with notes and to-dos.

Our last call of the year 🥺🎄
(The next call would be on Christmas, but it's on the 8th of January instead!)

Hosted by @tangerineshark and @lucibytes.

### About
- Location: https://discord.freesewing.org (meeting room: `🔊voice chat`)
- Date: Saturday December 11, 2021 16:00 UTC, which is:
        Los Angeles: 09:00
        Chicago: 11:00
        New York: 12:00
        São Paulo: 14:00
        London: 17:00
        Paris: 18:00
        Johannesburg: 19:00
        Moscow: 20:00
        Mumbai: 22:30
        Hong Kong: 01:00 on Sunday
        Tokyo: 02:00 on Sunday
        Sydney: 04:00 on Sunday
Or check the bot in Discord! `#meetings`

### Agenda
- How are the patterns in testing doing?

### Notes
- @bobgeorgethe3rd on Laura Leggings
    - The top part needs an update, the crotch curves specifically: they get too tight when the measurements are 'too big', which is when the hip measurement gets sort of near the upper leg measurement.
    - Going through Titan's code could help to find a solution, and maybe with help from @joostdecock too.
    - @eleonoremilbou suggested that there may be a problem with the butt/seat measurement. Seat measurement turned out not to be a part of the pattern, might help fix it.
    - Post-call Discord update: progress has been made by sorting out the crotch depth math and the use of the total hip measurement with the upper leg measurement.
- Peach Block is back in progress!
    - @bobgeorgethe3rd was inspired by @woutervdub's Noble Block - also a princess seam block - to pick this old project up again.
    - The differences between the two princess seam blocks are that Noble's princess seam connects to the shoulder and Peach's princess seam connects to the armhole.
    - @bobgeorgethe3rd has also been working on adding a lot of different dart placement options to Bella (which Peach is based on).
    - @eleonoremilbou suggested the option of splitting one dart into two darts, to avoid big and pointy darts. This would be especially helpful for those with big chest measurements.
    - @tangerineshark shared [a guide on how to do that](https://www.sewalongs.com/hawthorn/hawthorn-fba-bonus-splitting-the-dart/).
    - @nataliasayang mentioned that [in the Bella blogpost](https://freesewing.org/blog/bella-bodice-block/), @joostdecock shared that the pattern was initially going to come out with a shoulder dart option, but basically, womenswear is time consuming. Now, @bobgeorgethe3rd's dart options will make that dream come true after all.
- Eleonore mentioned that some sewing places use drawings to show what someone's body looks like, because with measurements alone you have to make assumptions on what someone's body looks like. She mentioned that there's a site for this, but it's been hard to find.
- @bobgeorgethe3rd asked if there were any ideas needed for the end of year newsletter.
    - @tangerineshark replied that the end of year newsletter is mainly to say thanks to all the volunteers. Because of this, there isn't much content needed and there is no deadline either. This version of the newsletter is usually done by @joostdecock.
    - But, we could add an interview! It will be looked into if @eleonoremilbou's interview is saved somewhere.
    - @bobgeorgethe3rd's article ideas still: pattern 'biographies' and a write-up on working together on projects, since the Laura Leggings collaboration is only the beginnig!
- There was *some* talk about a small, casual meeting next Saturday, since we're skipping the next one due to Christmas.

### To-do's
- Eleonore's interview
- Add Eleonore's link to call notes when she finds it (if possible)
- Casual meeting next week yes/no?

**Comment by lucibytes** [comment]
Notes and to-do's done! <3

**Comment by tangerineshark** [comment]
I'm in if you end up doing a casual meeting!

**Comment by joostdecock** [comment]
What @tangerineshark  said!

**Comment by lucibytes** [comment]
Awesome! 😄 I'll add it to Discord
