### ISSUE TITLE
Link to beginner pattern ideas from developer site

### ISSUE THREAD

**Issue by lucibytes** [freesewing/freesewing#1563]
To-do of #1514
Credits to @starfetch and @darigovresearch!

Add a link to [open issues with the label "pattern design" and "good first issue"](https://github.com/freesewing/freesewing/issues?q=is%3Aissue+is%3Aopen+label%3A%22%3Ashirt%3A+pattern+design%22+label%3A%22%3A%2B1%3A+good+first+issue%22+) on the developer site, the developer tutorial specifically.

**Comment by darigovresearch** [comment]
Thanks @lucibytes & @starfetch  for organising this. Happy to have a go at resolving this but will currently leave this open to encourage first time GitHub contributors and first time contributors to freesewing

For reference see below
- https://freesewing.dev/
- https://freesewing.dev/tutorials/
- https://freesewing.dev/tutorials/pattern-design/

**Comment by darigovresearch** [comment]
Pull request @1574 should resolve this issue if merged

**Comment by darigovresearch** [comment]
Just noted that the pull request did not update the relevant page.

@starfetch & @joostdecock did the changes not propagate out to the site or was the wrong file edited?

Page - https://freesewing.dev/tutorials/pattern-design/conclusion/

**Comment by starfetch** [comment]
The changes are in the correct place, they will show up on the site the next time @joostdecock deploys the '.dev' site :)

(You can check by clicking on the pencil icon in the top right, which then takes you to the relevant file in the repo.)

**Comment by darigovresearch** [comment]
@starfetch thanks for the guidance, was unsure of the release schedule for the site.

Will reclose this issue for now
