### ISSUE TITLE
Sleevecap ease on simone is not zero when option is set to zero

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1579]
Discord user `dreamingfifi` writes:

> I'm on Simone, making a different shirt. The Sleevecap ease is set to 0%, but as I discovered while pinning it, there's about 1 inch of ease in there anyways. Did I suck at cutting and pinning, or is this a website error?

I've asked for a pattern reference, but this should be trivial to reproduce if it is indeed an issue.

**Comment by joostdecock** [comment]
Checked it, and the sleevecap lenght is matched. I assume this user mixed up the extra SA

**Comment by SeaZeeZee** [comment]
Had another report on the discord about having to ease the sleeve on Simon. Will try to repro or make a full on mockup soonish.
