### ISSUE TITLE
Create showcase from this content

### ISSUE THREAD

**Issue by bjeppson** [freesewing/freesewing#1583]
- Content: Here are two garments I made from Freesewing patterns! Bruce boxer and Wahid vest
 - Permission:
   - [x ] I am the original author, and hereby grant permission to repost this content
   - [ ] I am not the original author, please ask permission from them

![IMG_4230_edited](https://user-images.githubusercontent.com/31866441/146650985-92f21eab-407b-45bc-9e44-a1a981c5f254.JPG)
![IMG_4241](https://user-images.githubusercontent.com/31866441/146650987-505bd1b5-87e3-4437-ad04-1ebf28333b01.JPG)

**Comment by nataliasayang** [comment]
Hey @bjeppson ! Welcome and thanks for contributing to FreeSewing! Your Bruce and Wahid look great.

Could you please create a maker profile here: https://freesewing.org/new/maker/

Here's an example (by @joostdecock ): https://freesewing.org/showcase/paco-by-joost/

I'll add the showcases to the FreeSewing site and link them to your maker profile.

Thanks again, and let me know if you have any questions :)

**Comment by joostdecock** [comment]
I've added these and (for now) attributed them to an anonymous FreeSewing makes (well, I did link to this issue, so people will know it's yours).

The offer stands for @bjeppson to [create a maker profile](https://freesewing.org/new/maker/), but in the meanwhile let's get this moving along.

**Comment by bjeppson** [comment]
I have a profile. Username Buck. I get errors trying to update the profile, add pic, etc. I’ll keep at it.
