### ISSUE TITLE
Good first pattern link in tutorial no longer works

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1630]
**What seems to be the problem?**

At the end of the pattern sewing tutorial it linked to open issues for pattern designs but now that they are no longer issues it displays a blank page.

Page in question - https://freesewing.dev/tutorials/pattern-design/conclusion
Old link - https://github.com/freesewing/freesewing/issues?q=is%3Aissue+is%3Aopen+label%3A%22%3Ashirt%3A+pattern+design%22+label%3A%22%3A%2B1%3A+good+first+issue%22+

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

New link should probably be - https://github.com/freesewing/freesewing/discussions?discussions_q=label%3A%22%3Ashirt%3A+pattern+design%22+label%3A%22%3A%2B1%3A+good+first+issue%22

**Comment by bobgeorgethe3rd** [comment]
Closed as of #1631
