### ISSUE TITLE
[Feature Request] One page view of documentation

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1660]
**What is it that you would like to see happen?**

For how-tos and pattern documentation that have multiple sub pages, is it possible to auto-generate a single page to not have to have 5 tabs open or to switch between pages?

This may greatly reduce friction for new and existing users and the user can choose what they want depending on their internet speed/data plan etc.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Not sure if the documentation framework supports this already but some do this already, see examples below

Adafruit
Example documentation segmented - https://learn.adafruit.com/diy-trinkey-no-solder-air-quality-monitor
One page version of the docs - https://learn.adafruit.com/diy-trinkey-no-solder-air-quality-monitor?view=all

Sphinx 
It has the `singlehtml` feature - https://www.sphinx-doc.org/en/master/man/sphinx-build.html

**Comment by joostdecock** [comment]
Could you be more specific, because all pattern instructions are on 1 page &  each howto is on 1 page.
So I'm not sure what precisely you'd like to see. Perhaps an example of something that you experience as frustrating could help?

> This may greatly reduce friction for new and existing users and the user can choose what they want depending on their internet speed/data plan etc.

It is perfectly fine to say: I would like this because I like what I like. No need to up-sell it ;)

**Comment by darigovresearch** [comment]
Say for Albert it would be great to be able to read all the documentation for it in one page, i.e. having an additional page saying "View as single page" so I can view all the content of cuttting, fabric options, required measurements etc on one page and not have to switch between tabs when wanting to get an overview of all the steps needed

The same goes for Tutorials on the dev site etc. Idea is to "precompile" current content files to create an additional single page along with the original multiple sub pages.

https://freesewing.org/docs/patterns/albert/

Current view 
![image](https://user-images.githubusercontent.com/30328618/149659159-f5c759f1-2cba-416d-af68-8dfea68c2b1d.png)

Expected view
![image](https://user-images.githubusercontent.com/30328618/149659203-2c1f83f1-b59f-40ba-a582-3d3465d111c8.png)

Is this more clear?

**Comment by joostdecock** [comment]
Given the work on our plate now, this is not going to happen.
I don't think this is a common use-case, but it's also a hackish way to work around what is more of style choice: Limited content on many pages, or more content on fewer pages.

We'll be revisiting this as we build the new website, so if you'd like to influence the direction, you're free to join that effort.
But at this point, this seems more opinion than anything else, and we have enough work with more pressing matters.

Sorry, saying no is part of the job.
