### ISSUE TITLE
[BUG] Top scroll button missing on Dev side panel

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1661]
**What seems to be the problem?**

For various sizes of screens, the left sidepanel does not display the scroll up button, likely it is hidden by the header, see image below

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

![image](https://user-images.githubusercontent.com/30328618/149655859-70be0d9c-c8c3-4092-bede-47d144b7bef8.png)

**Comment by darigovresearch** [comment]
Thanks for taking a look and resolving this @joostdecock !

**Comment by joostdecock** [comment]
Still need to deploy it, but I'll get around to it 😉
