### ISSUE TITLE
Missing Walburga and Tiberius Github Labels

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#1718]
Noticed that these two were missing their github labels. I would add them but I have no idea how.

**Comment by starfetch** [comment]
Done :)

**Comment by starfetch** [comment]
For reference: Via the github UI you can click on `labels`, and at the very bottom is `Edit labels`, which takes you to a big list with all labels. Some rights may be needed though to access it.

**Comment by nicholasdower** [comment]
I also wondered how the auto-label feature worked. Added some missing ones to https://github.com/freesewing/freesewing/pull/1719

**Comment by nicholasdower** [comment]
> I also wondered how the auto-label feature worked. Added some missing ones in #1719

I'm not sure that config is used after all. I think the real config is in `.github/boring-cyborg.yml`. And that contains the ones mentioned here.

**Comment by joostdecock** [comment]
The old labeler was superseded by the boring-cyborg one which has more features (like welcoming new contributors anf so on). It will add labels, but won't create them. So when a new package/pattern is added, a label for it should be created.

So thanks for doing that @starfetch

**Comment by bobgeorgethe3rd** [comment]
Awesome and yea by looks of it I don't have the permission
