### ISSUE TITLE
Provide a standard way for conditional display of options in the frontend

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1723]
This is feature request from [our roadmap](https://github.com/freesewing/freesewing/discussions/1278).

The idea is that we would hide options from the user/frontend/UI when those options are not relevant.
For example: If you say you don't want back pockets on charlie, there's no point in asking whether the user wants back pocket facing.

**How would it work**

We can't magically figure it out, so somehow this should be part of the option configuration.
I also feel it's too complex to put this into some DSL, so what I think makes most sense is a method that can be called and will return the answer to the question: *should we show you?*. 
To make that decision, the method should receive the current pattern options/config.

**Example**

This is from the top of my head, but something like:

```js
options: {
  myAwesomeOption: {
    pct: 50,
    min: 0,
    max: 100,
    show: function(settings) => {
      if (settings.options.myOtherOption === 2) return true
      else return false
    }
  }
}
```

Or, with fat arrow notation and object destructuring:

```js
options: {
  myAwesomeOption: {
    pct: 50,
    min: 0,
    max: 100,
    show: ({ options }) => (options.myOtherOption === 2) ? true : false
  }
}
```

Then in the frontend, we could check if the method exists on the option, and only show it if it either does not exists, or returns true.

PS: Naming things is hard, so perhaps `show` is not the best name? 

**First steps**

We could try this out with one pattern, and then integrate it into the development environment.

**Comment by bobgeorgethe3rd** [comment]
Mm this would be very useful. I know for a fact Bee will benefit from this and clear up the confusion between the Default and Cross Back Ties variations.

**Comment by joostdecock** [comment]
While not all frontend code is updated, the *standard way* as requested in this issue is implemented. Closing.
