### ISSUE TITLE
Hugo pocket has seam allowance on the left, even though it's cut-on-fold

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1731]
![Screenshot from 2022-01-26 13-07-29](https://user-images.githubusercontent.com/1708494/151160346-cd17975c-ee6e-4214-8521-7c247db48497.png)

While we're at it, it seems the SA path is not closed either.

Reported by `rik` on Discord. I'll let him know this qualifies for our bug bounty program.

**Comment by RikHekker** [comment]
This is indeed what I meant in the discord

**Comment by joostdecock** [comment]
@all-contributors please add @RikHekker for bug
