### ISSUE TITLE
Vulnerabilities when trying to extend a pattern

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1736]
**What seems to be the problem?**

When trying to extend a pattern following the guide there appears to be many vulnerabilities for the tutorial pattern

https://freesewing.dev/howtos/code/extend-pattern

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**
After running `npm install --save @freesewing/tutorial`
![image](https://user-images.githubusercontent.com/30328618/151247053-01e3d571-3012-4bfb-b29a-bffdb6d08e5c.png)

After running `npm audit fix`
![image](https://user-images.githubusercontent.com/30328618/151247178-8518189f-cd18-4c7b-93d7-de6ab6f888f1.png)

Still seeing the vulnerabilities so not sure if this needs to be fixed in the tutorial before proceeding with trying to make bob the bib with #1615

Can anyone please advise?

**Comment by joostdecock** [comment]
The dependencies of create-freesewing-pattern are managed out-of-band of our regular dependencies because of the way the package has it's own template package.json.

So updating these will need to be done manually here: https://github.com/freesewing/freesewing/blob/develop/packages/create-freesewing-pattern/template/freesewing/package.json

We'll get around to it. Thanks for letting us know.

**Comment by joostdecock** [comment]
After the updates:

```
found 2 moderate severity vulnerabilities in 1356 scanned packages
```

We'll put out a new release for this, although I'd like to squeeze in fixes for #1731 and #1732 first.

**Comment by joostdecock** [comment]
Resolved in 2.20.1

**Comment by joostdecock** [comment]
We had to downgrade again to react-scripts 4 because there's a regression bug that breaks our development environment: https://github.com/facebook/create-react-app/issues/11771

So vulnerabilities are back, but this time around I will simply ignore them until we throw out all this CRA stuff.

**Comment by darigovresearch** [comment]
No worries, thanks for taking the time to look into it and trying to fix it!
