### ISSUE TITLE
Wrong Pattern Option pages being displayed for Patterns.

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#1774]
This is a bug that has come over from when the shared pages where split. It is part of #1342 but it's beyond me.
The good news is that the separate pattern options exist the bad news is that the website still uses the shared pages. e,g, Carlton using Carlita's pattern options, The url display is correct but the info is taken from the wrong place, you can see this by clicking the edit button.
If it is as simple as changing something in a file I can do it if shown the file but it it's more complex then I am not sure how much help I can be

Here's the list:

- [ ] Carlton using Carlita's Pattern Options <-All of them
- [ ] Carlita Back neck cutout
- [ ] Carlita Front armhole extra cutout
- [ ] Carlita Shoulder slope reduction
- [ ] Diana Across back factor
- [ ] Diana Sleeve width guarantee
- [ ] Diana all of the Sleevecap options
- [ ] Huey Biceps Ease
- [ ] Huey Chest Ease
- [ ] Huey Cuff Ease
- [ ] Huey Collar Ease
- [ ] Huey Shoulder Ease
- [ ] Huey Length Bonus
- [ ] Huey Sleeve length bonus
- [ ] Huey Advanced Section
- [ ] Huey Sleevecap Section
- [ ] Hugo Biceps Ease
- [ ] Hugo Chest Ease
- [ ] Hugo Cuff Ease
- [ ] Hugo Length Bonus
- [ ] Hugo Sleeve length Bonus
- [ ] Hugo Across back factor
- [ ] Hugo Back neck cutout
- [ ] Jaeger Biceps Ease
- [ ] Jaeger Collar Ease
- [ ] Jaeger Shoulder Ease
- [ ] Jaeger Back Neck Cutout
- [ ] Jaeger Front armhole extra cutout
- [ ] Jaeger Shoulder slope reduction
- [ ] Simon Sleevecap Section
- [ ] Simon Sleeve width guarantee
- [ ] Simone using Simons
- [ ] Sven Collar Ease
- [ ] Sven Armhole depth factor
- [ ] Sven Back neck cutout
- [ ] Sven Front armhole extra cutout
- [ ] Sven Sleeve width guarantee
- [ ] Sven Sleevecap Section
- [ ] Teagan Across back factor
- [ ] Teagan Armhole depth factor
- [ ] Teagan Sleevecap Section
- [ ] Yuri Advanced Section
- [ ] Yuri Sleevecap Section

I believe these are all of them but I cannot say that for certain.

**Comment by joostdecock** [comment]
Thanks for reporting this. I've removed the duplication of pages on freesewing.org altogether, so that should take care of this.

I've also merged you other markdown changes and triggered a deploy, so if all goes well it should be sorted in a little while.
