### ISSUE TITLE
[simon] Sleeve grainline is off-grain

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1780]
**What seems to be the problem?**

The top of the grainline on the simon sleeve is slightly off. It should be on X-coordinate zero and it's not.

You can see that it's not parallel to the cuff folds in the screenshot below:
![Screenshot from 2022-01-30 14-34-15](https://user-images.githubusercontent.com/1708494/151701929-b0f4d56b-4898-4a04-a5d5-b47d442a6348.png)

The problem is here:

https://github.com/freesewing/freesewing/blob/7ae2c4b1eb7002178b13c518a6373dca12c4f0d8/packages/simon/src/sleeve.js#L149

The `sleeveTip` point is not guaranteed to be smack in the middle because of how the sleevecap is constructed.
It should be replaced with something like:

```js
macro('grainline', { 
  from: points.cuffMid, 
  to: new Point(
    points.cuffMid.x,
    points.sleeveTip.y
  )
}) 
```

**Comment by SeaZeeZee** [comment]
Not sure how to link a pull request but Ive fixed the code for the point and now the grainline is straight. (Im not however!)

**Comment by nicholasdower** [comment]
@SeaZeeZee you can link a pull request here by referencing it like #1802. You also do it by referencing this issue (#1780) in the pull request.
