### ISSUE TITLE
SVG styling is broken on Safari

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1843]
**What seems to be the problem?**

This:
![IMG_7133](https://user-images.githubusercontent.com/1708494/153365011-3a493097-a194-4202-a93f-93a7544e4fa1.jpeg)

Only seems to happen on Safari.

@nicholasdower points out that https://simon.freesewing.dev/ is not broken so this is probably related to the recent CSS changes for the `scale` factor, making this a regression.

**Comment by nicholasdower** [comment]
@joostdecock do you mean specifically on the drawing-circles page you linked to? That page is not broken on Safari but it isn't using css vars.

Are you thinking this isn't simply the units thing?

What do you mean by "old site" and "new site"?

Also, what is react render? I only ever see SVGs in the DOM.

Sorry if I am being dense. I am a newb.

**Comment by nicholasdower** [comment]
I am still piecing this together but is it fair to say that the "new site" or freesewing.dev involves code like:
```xml
<Example pattern="tutorial" part="step6">
```

or

```xml
<Example pattern="rendertest" options_only="snippets">
```

?

**Comment by joostdecock** [comment]
I don't always know what you don't know, so forgive me if this is repetitive:

```jsx
<Example pattern="tutorial" part="step6">
```

That's [JSX](https://reactjs.org/docs/introducing-jsx.html) syntax, which is a [React](https://reactjs.org/) thing.

So React is all about **components**. A component is (under the hood) just a method that takes parameters and should return something React can render (a string, or array or strings or another method/JSX).

JSX is a way to write out your UI in a more declarative way. So this:

```
<Example pattern="tutorial" part="step6">
```

Will under the hood be:
```js
function Example(props) {
  /* props looks like:
   * {
   *    pattern: "tutorial",
   *    part: 'step6",
   * }
   */
   
   // Do something smart here
   
   return "Hello"
 }
 ```
  
Those components allow us to split things up in smaller re-usable parts.
Whereas core spits out SVG as one string, React allows us to have a component just to render a path (for example).
And in that component, we can easily do things like add extra features when the path is clicked on and so on.

Since React is Javascript, all this works only in the browser. For export, we need the plain simple SVG string that's spit out by core.

So both the new site (freesewing.dev) and the (current) old site (freesewing.org) use React to render a pattern.
Ultimately, in the DOM you will see SVG. But it's SVG that's rendered by Javascript, and not by our core library.

Here's what our core library does to render an SVG path:
https://github.com/freesewing/freesewing/blob/e8802d8c4fe5c0c60df11e0637793bc2c4ca9363/packages/core/src/svg.js#L166-L172

And here's the React component that renders a svg path: 
https://github.com/freesewing/freesewing/blob/e8802d8c4fe5c0c60df11e0637793bc2c4ca9363/packages/freesewing.shared/components/workbench/draft/path/index.js#L4-L32

Notice the `xray` bit which is the extra features in the dev env that allow you to click on a path and get more info about it (see the `onClick` handler).
All of that is browser-only and is done in React. Whereas  SVG is just a string that represents the pattern, React does that + interactivity.

**Comment by joostdecock** [comment]
@nicholasdower If you'd like I'm happy to have a call to further unpack some of this stuff

**Comment by nicholasdower** [comment]
> @nicholasdower If you'd like I'm happy to have a call to further unpack some of this stuff

I think that would be very useful. There are a lot of parts that are new to me. I'll be in the office tomorrow but maybe you are free some time this weekend? Otherwise, next week works too.

I also need to reread this entire thread carefully tomorrow with a fresh set of 👀.

**Comment by nicholasdower** [comment]
A better fiddle to try on Chrome and Safari: https://jsfiddle.net/tw2se8ub/
```html
<style>
  :root {
    --with-units: 10px;
    --without-units: 10;
  }

  rect {
    fill: white;
    stroke: pink;
  }
</style>

<svg width="130" height="130">
  <!-- Top left -->
  <rect x="10" y="10" width="50" height="50" style="stroke-width: calc(var(--with-units)*0.7px);" />

  <!-- Bottom left -->
  <rect x="10" y="70" width="50" height="50" style="stroke-width: calc(var(--without-units)*0.7px);" />

  <!-- Top right -->
  <rect x="70" y="10" width="50" height="50" style="stroke-width: calc(var(--with-units)*0.7);" />

  <!-- Bottom right -->
  <rect x="70" y="70" width="50" height="50" style="stroke-width: calc(var(--without-units)*0.7);" />
</svg>
```

Chrome:
![image](https://user-images.githubusercontent.com/9117775/153938720-cd5754f2-eac9-4102-bf0f-2c67eaf70476.png)

Safari:
![image](https://user-images.githubusercontent.com/9117775/153938758-d45a8cca-a953-4733-8727-0ab6619a912b.png)

**Comment by joostdecock** [comment]
Honestly can't remember whether this is fixed or not. But it's very stale, so closing
