### ISSUE TITLE
Scale setting is not respected on the website

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#1868]
**What seems to be the problem?**

![Screenshot from 2022-02-14 18-02-31](https://user-images.githubusercontent.com/1708494/153911145-874e6bec-4092-4647-9bb8-f16e416207e0.png)

**Additional context**

Not sure whether this is a regression or we somehow missed that this never looked good, but it's not great.

**Comment by nicholasdower** [comment]
@joostdecock what are the steps to reproduce? The screenshot looks like what I see if I increase the scale setting while configuring a pattern. But I think that is expected so I'm assuming this is something else.

**Comment by joostdecock** [comment]
Must admit, I didn't think to check the scale. It's a url shared by a user: https://freesewing.org/patterns/jkscx/

**Comment by joostdecock** [comment]
Exported gist here: https://gist.github.com/c1f8047f349a179708af77247ed262e5

I don't see scale set, but I am on my phone so take it with a grain of salt

**Comment by nicholasdower** [comment]
I can easily reproduce by opening any of my own patterns. It is only happening when viewing a pattern on the website, not when editing.

**Comment by nicholasdower** [comment]
The scale variable is set to an empty string. This resolves the issue locally:
```javascript
document.documentElement.style.setProperty('--freesewing-pattern-scale', '1');
```

**Comment by nicholasdower** [comment]
I guess it isn't set to an empty string. It just isn't set. I don't see it in the DOM.

**Comment by nicholasdower** [comment]
Ah, maybe this belongs in freesewing.org! I see https://github.com/freesewing/freesewing.org/commit/a2162034cc0098f8a1271d436ca7110a399189db added it to draft. But I don't see it in preview. 

https://github.com/freesewing/freesewing.org/pull/1585

**Comment by nicholasdower** [comment]
Before:
![image](https://user-images.githubusercontent.com/9117775/153923139-a809f244-3611-4293-8c87-6b5ae0fa7c0e.png)
After:
![image](https://user-images.githubusercontent.com/9117775/153923209-a0b3bb6e-123c-4c57-8dc4-0b0112f49e49.png)

Btw, this is not working on Safari and adding `px` units does not help. See #1843.

**Comment by nicholasdower** [comment]
Ah, I think it is broken in Safari because we use units in the math like:
```css
font-size: calc(22px * var(--freesewing-pattern-scale));
```

**Comment by joostdecock** [comment]
I'm AFK but this is some quality digging ⛏️

**Comment by joostdecock** [comment]
I have been busy, but I've cut a new release and it resolves the scale issue.
When it's deployed on freesewing.org, could you have a look with Safari to see if by any chance that too has been resolved?
If not, we'll need to find the right combo of units/not units.

To that extend, I feel that `scale` should be without units even as a CSS var. It just seems more intuitive to me that scale is a number.
In the frontend code, this caused the text to not be properly displayed (that's what this issue is for). So I've updated to add `px` units to the font size in the CSS which seems like the more logical place to me (rather than in the scale var): https://github.com/freesewing/freesewing/commit/c5eea00b8085b1b81689f7d75662e9bc92646fcd

**Comment by nicholasdower** [comment]
@joostdecock agreed it makes way more sense for the var not to have units. I think I originally thought units had to be in the variable to work around the Safari issue but that is clearly not the case.

Did you also mean to update [src/components/draft/ui.js](https://github.com/freesewing/freesewing.org/blob/develop/src/components/draft/ui.js#L360) and [packages/components/src/Workbench/index.js](https://github.com/freesewing/freesewing/blob/develop/packages/components/src/Workbench/index.js#L323)?

**Comment by joostdecock** [comment]
My main concern was shipping something that works ASAP (on freesewing.org I mean).
To that extend, I rolled out 2.20.6 last night (but the build broke due to issues in the markdown, so that was all for nothing).

It's more like, going forward I think it makes more sense to have the var not include units, and figure out the magic combo that works. But I did not really have time to follow through with all that so I tried to get something out the door that would at least address the preview issue. (and it does, but the build failed because of some invalid markdown).

**Comment by nicholasdower** [comment]
> My main concern was shipping something that works ASAP (on freesewing.org I mean). To that extend, I rolled out 2.20.6 last night (but the build broke due to issues in the markdown, so that was all for nothing).
> 
> It's more like, going forward I think it makes more sense to have the var not include units, and figure out the magic combo that works. But I did not really have time to follow through with all that so I tried to get something out the door that would at least address the preview issue. (and it does, but the build failed because of some invalid markdown).

I might be confused but I think before https://github.com/freesewing/freesewing/commit/c5eea00b8085b1b81689f7d75662e9bc92646fcd everything worked because units were always specified exactly once. Now units are sometimes specified twice, sometimes never, and sometimes once. So preview and draft are both broken on Safari.
