### ISSUE TITLE
Strange path on wahid.

### ISSUE THREAD

**Issue by grimlokason** [freesewing/freesewing#187]
Hello,

There is probably 3 "issues" with Wahid:
- With my principal model without modification ( https://en.freesewing.org/create/wahid/for/idcke ) we can see 2 strange path on the armhole. 
- Without any modification, it crashed and asked me to disable seam allowance.

The output of the model :   [pattern-full.pdf](https://github.com/freesewing/freesewing/files/3784649/pattern-full.pdf)

Best Regards,

**Comment by joostdecock** [comment]
Thank you for your feedback. I will look into the armhole issues adap.

The other problem is due to #19 which is unfortunately an upstream issue.

**Comment by grimlokason** [comment]
My bad, you're right, there was some issue with the way we took my measurments due to some lack of  english anatomy vocabulary.

Thank you !

**Comment by joostdecock** [comment]
Glad we could help :) Don't hesitate to reach out next time you bump into something.
