### ISSUE TITLE
An (almost) straight curve breaks the path offset code in bezierjs with error "cannot scale this curve. Try reducing it first."

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#19]
If you see a **cannot scale this curve. Try reducing it first.** you've hit this issue.
Strictly speaking, this is not an issue in freesewing/core, but in the upstream [bezierjs library](https://github.com/Pomax/bezierjs). Specifically, https://github.com/Pomax/bezierjs/issues/102 It happens when a Bezier curve becomes so straight it almost becomes a line. At which point the offset algorithm goes off the rails.

The issue has been open since October 2018, and tagged with 'help-wanted', so it is unlikely to get fixed by the upstream author (pomax).  A fix is going to be non-trivial. Not only because it's not our code, but because offsetting Bezier curves is just not easy. 

We hit this problem far too often to ignore it. So we should try to address it. Especially since this library does make our life significantly either, and if we tried to implement all the Bezier-juggling ourselves, we would very likely end up with our own set of bugs. So we can't  simply swap it out for a drop-in replacement.

It seems like what we need here, is a hero.

**Comment by joostdecock** [comment]
This needs to be rolled back once this issue is resolved: https://github.com/freesewing/freesewing/commit/75f935298d98ddbf0ef62b705e1078dddc90702a

(well, not the shorthand fix, that was actually a bug).

**Comment by jliu1016** [comment]
I'm going to try look into it. (no promises though aha)

**Comment by joostdecock** [comment]
No pressure. It's amazing you're willing to take a stab at it in the first place 🙏

**Comment by joostdecock** [comment]
Upstream fix is part of v2.1.9
