### ISSUE TITLE
Add condensed theme to dev site

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1905]
**What is it that you would like to see happen?**

A theme for the dev (and future .org site) that allows for more content to be fit on screen by reducing padding, spacing & font size

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Users can zoom out currently but the margin & padding still takes up a lot of space. A minimal viable product (MVP) could be cloning the standard theme but adjust padding, margin & font size.

**Comment by lucibytes** [comment]
@darigovresearch @joostdecock 
Following up on [our previous meeting](https://github.com/freesewing/freesewing/discussions/1833), do we want to turn this into a Discussion? Or close it?

**Comment by darigovresearch** [comment]
Happy to follow your lead on this @joostdecock

**Comment by joostdecock** [comment]
Given the work on our plate now, and the fact that padding is not easily themeable, this is not going to happen.
You can override styles in your browser, there's plenty of plugins to do that. But we can't accommodate everyone's personal preferences :shrug: 

Sorry, saying no is part of the job.
