### ISSUE TITLE
All Contributors: Please add @drowned-in-books

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#1915]
### Who made the contribution(s)?

- GitHub username: @drowned-in-books

Please provide the GitHub username of the contributor.
(If it is you, you can skip this part, as your username will be available in the issue)

### What type(s) of contribution did they make?

- Contribution type(s): question

The most common contribution types are: 

 - `doc` for documentation work
 - `translation` for translation work
 - `code` for code contributions
 - `blog` for blog posts or showcase posts
 - `question` for helping others by answering questions (on Discord for example)
 - `bug` for reporting bugs

A complete list of contribution types is available [on the all contributors website](https://allcontributors.org/docs/en/emoji-key).

**Comment by darigovresearch** [comment]
@all-contributors please add @drowned-in-books for question

**Comment by darigovresearch** [comment]
@tangerineshark following the call thought `question` was most appropriate given the context but feel free to add other items which you deem were relevant for the work that @drowned-in-books has done!

The pull request will need to be merged by someone who has the rights to merge pull requests

**Comment by joostdecock** [comment]
Merged by @nicholasdower , closing.
