### ISSUE TITLE
Make personal information of bug reports more private

### ISSUE THREAD

**Issue by lexander2002** [freesewing/freesewing#1958]
Explained by @joostdecock and @nicholasdower in [our last meeting](https://github.com/freesewing/freesewing/discussions/1833), this is a copy paste of the section's notes:

- We want to make personal information of bug reports more private, instead of it being posted publicly to GitHub.
    - @nicholasdower explained that when you file a bug report via the site to GitHub, it includes your measurements. A negative comment was made about someone’s measurements on an issue that is now deleted. On the site it does say that it will share measurements and settings, and we do need this information to fix bugs, but we wanted to discuss ways to avoid information being public on the internet.
    - @joostdecock proposes that only a small group of people will have access to the personal information that comes with a bug report.
    - It takes a bit of work to implement, maybe somewhere next month.

Not sure if the label is right! Also, feel free to convert this to a Discussion if that fits better.

**Comment by joostdecock** [comment]
First stab at prhasing:

![Screenshot from 2022-03-18 19-10-17](https://user-images.githubusercontent.com/1708494/159059690-98176540-358d-44c4-b09f-257e22b29752.png)

You need to tick the checkbox to be able to escalate the issues (and submit the data).
Button doesn't actually do anything yet, I'm just looking for feedback on whether this is clear or not.

**Comment by joostdecock** [comment]
v3 handles this differently, so I think keeping this open is not all that useful.
