### ISSUE TITLE
Add additional information about each Pattern to that Pattern's documentation

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#2024]
Sometimes it's useful to have extra information about a pattern, sometimes that's about how to get the best fit for a given shape, other times it's about really understanding a pattern so you can enhance it. As this information varies with each pattern, it would be good to include it in the pattern documentation.

**Proposal**

Add a page to the documentation for each pattern in the "Pattern Instructions" section. The page title shall be "Additional information". [Note: it may be preferable to break into two pages, one for fit related advice and one for pattern background]

The page shall contain the following sections:

- **Pattern origins**
  - Describe whether the pattern is a block or derived from a block
  - Describe if the pattern is based on another existing pattern or style of garment
- **Pattern intent**
  -  Describe the sort of person the pattern was originally designed for, why the designer chose to make this pattern, what sort of outcomes does the designer hope for
  - Design decisions relating to the pattern itself. e.g. why is the armscye designed this way, why are there additional options for the gusset, how much ease to expect at a given part of the garment.
- **Fit recommendations for particular bodies**
  - Include suggestions from the designer, e.g. to accomodate a bulge you may want to increase the gusset by X%, to account for breasts you may want to add an armhole dart to improve shaping
  - Include fit experiences from the community, e.g. as a fat person I recommend increasing the cross seam by X%
- **Include known issues**
   - Link to known issues where they exist in the github. 
   - Offer workarounds on the information page while we wait for a fix. e.g. for Brian blocks and large biceps, use a fake small bicep and do a full bicep adjustment on the sleeve.
   - Note where there may not be enough pattern testing for a given size and suggest the sewer provides feedback to the discord.
   - Where the same question arises again and again on Discord, it would be a good candidate for this section
- **Suggested alterations**
  - Where people have made modifcations beyond the pattern configuration, add examples and links to the showcase. e.g. converting Wahid to have full princess seams to the shoulder, adding patch pockets to Charlie to create cargo pants.

**Considerations**
- Translation
  - This will add quite a bit of work for the translation community
- Can some information be put into blog posts and linked, in order to streamline content on the page
  -   e.g. can pattern intent be an "interview with the designer" blog post
  -  e.g. can common adjustments be described in linked blog posts
  - How does this impact translations.
- Find a way to remind people, the patterns may have been designed and optimised for a given shape, but that does not mean the pattern is not for them, there just may be a few additional tweaks to get it right. (and they're not so daunting, and the community is here to support you!)

**Comment by bobgeorgethe3rd** [comment]
Inclusion of you the Current Maintainers are forthe pattern so people know who to contact about issues.

**Comment by joostdecock** [comment]
All patterns now have designer notes. Closing.
