### ISSUE TITLE
Showcases are not displaying.

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#2107]
Pointed out by @hellgy in discord https://discord.com/channels/698854858052075530/787402509543145532/964088903927738418

The images from the showcase are not displaying and a broken image icon is there, I recall this has happened before but I can't remember what the fix was. 

![image](https://user-images.githubusercontent.com/16866285/163387177-c95d6eba-95b4-4488-8541-6b4917631714.png)

I assume this is something along the lines off broken communication with Strapi?

**Comment by joostdecock** [comment]
Fixed
