### ISSUE TITLE
Add a link to the documentation when you export your pattern and in the side bar

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#2153]
**What is it that you would like to see happen?**
When I go to export my pattern, I'd like to see a quick link to the documentation so I can catch up on them while my pattern prints. 
A quick link in the side bar of my patterns might help me get to the documenation quickly too.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [ ] No, I am not :thinking:

**Additional context**

![image](https://user-images.githubusercontent.com/4170521/166122172-51d6be78-8e7e-442e-87a5-059ba0d664e9.png)
![image](https://user-images.githubusercontent.com/4170521/166122222-e18174b4-d87b-43a4-85ae-af8a95b830ad.png)
![image](https://user-images.githubusercontent.com/4170521/166122293-21e09f80-fdf0-495a-924e-72d66a1a4af4.png)

**Comment by joostdecock** [comment]
v3 sidebar has link to docs. Closing.
