### ISSUE TITLE
Notches Plugin Page Is Broken

### ISSUE THREAD

**Issue by iocouto** [freesewing/freesewing#2163]
Trying to view the page in the docs for the **[notches plugin](https://freesewing.dev/reference/plugins/notches)** currently gives the visitor a 'client error' on all 3 major browsers. Tested on a Mac running MacOS Monterey, and using the latest versions of Safari, Firefox and Chrome. 

This is the message the visitor gets:

<img width="736" alt="Screen Shot 2022-05-05 at 12 54 20 pm" src="https://user-images.githubusercontent.com/75245963/166857424-24138f2f-44fc-4489-9cf0-b09c80be6abc.png">

Opening the browser console, we see the following:

<img width="1188" alt="Screen Shot 2022-05-05 at 12 54 41 pm" src="https://user-images.githubusercontent.com/75245963/166857458-80e35a87-fbc1-4f32-9921-75cee5389cf8.png">

**Comment by joostdecock** [comment]
@all-contributors please add @iocouto for bug

**Comment by joostdecock** [comment]
Fix has been deployed. Thanks for reporting this @iocouto 🙏

![Screenshot_20220505-093923.png](https://user-images.githubusercontent.com/1708494/166880656-6e5b2185-32fe-4382-a247-c6b30fc1914a.png)
