### ISSUE TITLE
Bug report - Shin is missing grain lines

### ISSUE THREAD

**Issue by nataliasayang** [freesewing/freesewing#2165]
**What seems to be the problem?**

As [reported by comixminx in Discord](https://discord.com/channels/698854858052075530/757632180980547686/959835580366192741), the Shin pieces don’t have a grain line on them, though the documentation shows some sample pieces that do have grain lines printed.

**Are you a FreeSewing patron?**

 - [x] Yes, I am :hugs:
 - [ ] No, I am not :thinking:

**Comment by bobgeorgethe3rd** [comment]
Fixed as of #2166
