### ISSUE TITLE
Feature request: disclose the missing measurements for incomplete people in the new pattern page

### ISSUE THREAD

**Issue by vegaelle** [freesewing/freesewing#2168]
When creating a new pattern, we can choose either standard measurements, or use a custom set, namely a "people". However, if any of the people attached to the current account are missing requirements, they appear at the bottom of the page, but there’s no easy way to see how many and what measurements are missing. It should be very useful to show the needed measurements, at least, and maybe provide quick links to add those measurements.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not **yet** :thinking:

**Additional context**

**Comment by BenJamesBen** [comment]
#5822 and #5915 were subsequently filed and are duplicates of this Issue. Although this Issue is older and the right thing to do might be to work this original, older issue, I may instead work the two new issues since they neatly divide the overall issue into two specific tasks.

**Comment by BenJamesBen** [comment]
This enhancement request was fulfilled by #5822 and #5915 which were completed via #6033 and #6034. Closing.
