### ISSUE TITLE
Ran out of Back End Storage Again.

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#2177]
Mercury was having trouble updating her measurements and get being prompted with "Request Failed"
https://discord.com/channels/698854858052075530/757632953097388043/974459409054990336

Upon looking at the site instantly saw our Showcase were down and when trying to update measurement you are prompted with "Backend or network seems down"

So two and two together the Backend ran out of storage again.

**Comment by joostdecock** [comment]
Well spotted. Fixed.
