### ISSUE TITLE
Clarify neck finish on Teagan 

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2207]
The instructions currently assume a knit binding at the neck. But the pattern is designed for a knit band finish.

This is causing some confusion so either we explain both, or make it an option in the pattern or...?

**Comment by tangerineshark** [comment]
Is there a preference between knit band and knit binding? I have this vague memory of original samples being made with knit binding, but obvy it's pretty easy to go either way.

Related, would you rather have the instructions just give options for both, or alter the design to default to a knit binding?

**Comment by joostdecock** [comment]
I always use knit band on T-shirt. I also think that's what you typically see in store-bought T-shirts, but it's not the hill I want to die on :)

**Comment by joostdecock** [comment]
Fixed by @tangerineshark in https://github.com/freesewing/freesewing/pull/3359/commits/e1c90dfc80d0e6ba43348e864d5e5afe7cb58440

Closing
