### ISSUE TITLE
useMemo() breaks gists updates in measurements input

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2281]
**What seems to be the problem?**

The way `useMemo()` is used breaks gists updates:

https://github.com/freesewing/freesewing/blob/78d22259d922d19dbce8be6c1c8b2ea36550cde4/sites/shared/components/workbench/inputs/measurement.js#L56

**Additional context**

Only one measurement will/can be used per page load.
What I mean is:

- Go to measurments
- Add a new measurement => works fine
- Add another measurement => replaces the previous measurement in the gist
- Navigate away (to draft or whatever)
- Add a new measurement => works fine

I'm going to comment out the use of `useMemo()` for now as that solves the issue.
I defer to @eriese for a more permanent fix since it's her baby so I think she'll do better than me.

**Comment by joostdecock** [comment]
I have (temporary) added debug info to the lab to make this easier to troubleshoot:

![Screenshot from 2022-06-22 15-00-53](https://user-images.githubusercontent.com/1708494/175035337-5b5a11b0-8bd7-41a6-bd29-ab24cf6b89f9.png)

**Comment by eriese** [comment]
@joostdecock is there something in particular that had you identify `useMemo` as the culprit? I have an alternate theory, but I want to have all the facts

**Comment by woutervdub** [comment]
Is there a way to 'clear' the lab? Going to `noble` errors out before I can get to `measurements`. It works fine for other designs I hadn't visited before.

**Comment by eriese** [comment]
> Is there a way to 'clear' the lab? Going to `noble` errors out before I can get to `measurements`. It works fine for other designs I hadn't visited before.

The only thing I can think of is to go into your localstorage and change the `_state` value of `fs_noble_gist` to `{view: 'measurements'}`

**Comment by eriese** [comment]
> How do I get to localstorage?

in your javascript console (in the browser), enter
```
let b = JSON.parse(localStorage.getItem('fs_noble_gist'))
b._state={view: 'measurements'}
localStorage.setItem('fs_noble_gist', b)
```

then refresh the page
