### ISSUE TITLE
Ursula is not drafting in 2.21.0

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#2307]
With either inputed measures or the "standard measurses* Ursula is not drafting in 2.21.0. I'm not 100 but I suspect this is the splitting packages folders.

**Comment by joostdecock** [comment]
This sounds like it's perhaps something on your end. As far as I know there was no issue with Ursual in 2.21.0 and there's no issue in 2.21.1 even though I made no changes to it.

![Screenshot 2022-06-28 at 10-17-40 New Ursula undies for Size 38 With breasts](https://user-images.githubusercontent.com/1708494/176129890-bb9806ee-d3c1-4e13-ba8d-c9b4a39be489.png)

So I'm closing this, but feel free to re-open if I have it wrong somehow

**Comment by joostdecock** [comment]
Truth
