### ISSUE TITLE
Documentation is inaccesible for Bob, Hi, Lucy, Noble and Unice in 2.21.0

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#2308]
For all the new patterns you cannot currently access there documentation on the website. You just the get the 404 page.
They also do not appear in the drop down for the patterns under the documentation tab.
![image](https://user-images.githubusercontent.com/16866285/176043060-4e2ee003-44d8-4ab1-ad33-52bf73acf778.png)

![image](https://user-images.githubusercontent.com/16866285/176042978-b0313230-6805-45ac-be0c-afa73334413a.png)

**Comment by joostdecock** [comment]
https://freesewing.org/docs/patterns/bob/
