### ISSUE TITLE
Create showcase from this content

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2454]
- Content:  https://www.instagram.com/p/CWqGGoesEu6/?utm_source=ig_web_copy_link
 - Permission:
   - [ ] I am the original author, and hereby grant permission to repost this content
   - [ ] I am not the original author, please ask permission from them
- [x] Permission granted by the original author 
 - Credit: `sewingdentist` on Instagram 

Looking to tackle this issue? We have [a how-to that shows how to add a showcase to the site](https://freesewing.dev/editors/howtos/showcase/).

**Comment by nataliasayang** [comment]
Showcase has been created.
