### ISSUE TITLE
[bug]: Figure text on freesewing.org is too big [fix but needs deploy]

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2485]
### What seems to be the problem? 🤔

On freesewing.org, text in Figure elements is too big. 

For example, in https://freesewing.org/docs/various/notation/buttons/ the "button", "buttonhole", "snap-stud", and "snap-socket" text is too big:
![Buttons_original](https://user-images.githubusercontent.com/109869956/181169215-539acea2-72d2-4027-b00e-68812c0c746d.png)

The problem seems to be that when I inspect the element style in Chrome, I see:
```
font-size: calc(6px*var(--freesewing-pattern-scale));
```
But, Chrome web inspector tells me that `--freesewing-pattern-scale is not defined`. So, a font-size of 18px is instead inherited from the body, I believe.

The `calc(6px*var(--freesewing-pattern-scale))` seems to come from `packages/css-theme/src/components/_pattern.scss`, but I wasn't able to locate where `--freesewing-pattern-scale` is defined.

(I note that a way to brute force a fix would be the following in `packages/components/src/Legend/index.js`. However, it isn't the right way to fix the issue)
```
-      <div className="shadow">
+      <div className="shadow" style="font-size: 6px">
```

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Hmm, this seems to be reappearance of #2375 

Need to check whether this was never deployed, because I remember fixing this 🤔

Issue #2375 is closed by the commit with the fix if you're curious

**Comment by joostdecock** [comment]
Seems I forgot to deploy this fix in production 🙈 I'll take care of that. Let's keep this issue open until then to make sure

**Comment by BenJamesBen** [comment]
I verified that the fix is now seen on the freesewing.org website. I am closing this Issue.
