### ISSUE TITLE
[bug]: [lab] Sliding to 0 cm SA invisibly toggles Seam Allowance to "no"

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2501]
### What seems to be the problem? 🤔

In the lab, if you slide the seam allowance slider to 0 cm, it seems to toggle the value of Seam Allowance to be "no" in an invisible and semi-persistent manner. That is, when the seam allowance is slider is subsequently set to a non-0cm value, even though Seam Allowance is set to "yes", the tool incorrectly behaves as if Seam Allowance was set to "no".

Steps to Reproduce:
1. On lab.freesewing.dev start a new pattern, for example *Simon* without breasts 40, and go to the DraftDesign page.
2. Under Settings, set Seam Allowance to "Yes". The seam allowance appears in the pattern, as expected.
3. Slide the Seam Allowance slider back and forth. The seam allowance grows and shrinks, as expected.
4. Slide the Seam Allowance slider to 0 cm. The seam allowance disappears, as expected.
5. Slide the Seam Allowance slider back to a non-0cm value, for example 1.5 cm, and slide the slider back and forth. Note that Seam Allowance is still set to "Yes". However, unexpectedly the seam allowance does not reappear in the pattern. This is the bug.
6. Slide the Seam Allowance slider to a non-0cm value, for example 1.5 cm. Toggle Seam Allowance to "No" and then back to "Yes". Note that the seam allowance reappears in the pattern. This is the workaround.

When in the bug state, switching to/from the LayoutThing page does not fix the problem. The bug is also seen in the localhost:8000 version of the lab. The bug is also seen when using Imperial units. The bug mainly affects customers who accidentally slide the SA slider to 0, slide it back to a non-zero value, and then wonder why the seam allowance didn't reappear as expected.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
Not sure if the change might have any unwanted side effects, but a fix seems to be `sites/shared/components/workbench/menu/core-settings/core-setting-sa-mm.js`:
```diff
17c17
<     if (props.gist.sa) props.setGist({
---
>     if (props.gist.saBool) props.setGist({
```

**Comment by joostdecock** [comment]
Just want to say: excellent bug report 👌
