### ISSUE TITLE
[feature]: Belly support in patterns

### ISSUE THREAD

**Issue by vanrein** [freesewing/freesewing#2531]
### What is it that you would like to see happen? 🤔

I think many people may be struggling with patterns that have no support for a belly.  I checked Wahid and Brian and they take **waist circumference** into account, but they do not seem to use the **waist back** to distinguish front/back sizes.  This would mean that the side is pulled forward on people with a belly and the fit would be imperfect.

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

When you walk behind a person with a belly, you can see the pull on their shirts in the waist area -- which actually makes them look thin from behind, but it makes a snug fit impossible and it may not be comfortable either.

It may be relatively simple to solve and it is just up the streak of FreeSewing:

  * Brian might distinguish front/back sizes to accommodate this, although the body is more curved and would only fit as well as the flat front allows.  But the sides would be straight and not pull.
  * Wahid has extra seams going up from the pockets, and these might be used to expand, rather than contract, the pattern.  The lower end sizing might also be taller, of course.
  * *I did not check other designs* for distinguishing waiste back.

This is just a general idea towards the wonderful goal of being all-inclusive; it is not a problem I experience or that I have heard others about.  But while studying how FreeSewing works this is something that struck me.  I hope it makes sense :-)

**Comment by vanrein** [comment]
In Wahid, the button series in the middle joins two straight lines, so it forms a flat area; that could be considered a missed opportunity to fit a bodily curve.

An image from the TV series *Der Dicke* can make this more graphical.
https://cdn.prod.www.spiegel.de/images/f3b00151-0001-0004-0000-000000338184_w1528_r1.5207286432160805_fpx64.36_fpy49.88.jpg

**Comment by joostdecock** [comment]
In general this is of course a lofty goal that we should try to reach. But just wanted to comment on your follow-up message about missed opportunities.

Front closure is always straight because it looks really weird/wonky when you add shaping because now the grainline/fabric is no longer parallel to the closure.

Also, Wahid has front dart and back darts, in addition to the side and back seams. Which means that around the body, there are already 7 different places where shaping happens or can happen.

**Comment by vanrein** [comment]
Of course.  It generally looks very sharp on slim people, I think it is a really good design.

**Comment by vanrein** [comment]
This issue is a specific example of something more general I was wondering when I heard about FreeSewing, and that is a possible connection to 3D models and deriving curves from them.  I think a little bit of intuitive math could be really helpful &mdash; and be very much in line with how FreeSewing appears to me.

So, after some exploration of possibilities I wrote down my thoughts in a newly opened [Bézier's Mannequin](https://github.com/freesewing/freesewing/discussions/2544) discussion.

**Comment by joostdecock** [comment]
Moved this to our roadmap. Closing (for now)
