### ISSUE TITLE
[bug]: Cathrin has a cut-on-fold seam with seam allowance

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2545]
### What seems to be the problem? 🤔

The cathrin pattern's center-front seam has a cut-on-fold indicator **and** seam allowance.
If it's cut on the fold, it should not have seam allowance.

### Design / Plugin / Package 🧐

designs/cathrin

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

As reported by Discord user `halbmoki`: https://discordapp.com/channels/698854858052075530/757632180980547686/1005818064396353616

**Comment by bobgeorgethe3rd** [comment]
Ok so this is not as simple as changing it too one or the other.
The instructions suggest it should be cut - on - the fold.
The line drawing suggest it should be a seam
And the Covert Art suggests that there should be a busk in the front therefore not cut - on - the fold.
I will look into this further.

**Comment by bobgeorgethe3rd** [comment]
Ok so I went to the original article.

Cut - on - fold is the way intended by Cathrin.

This may be that the line art and covert art need updating.

**Comment by BenJamesBen** [comment]
I submitted PR #2548 to fix the design code https://github.com/freesewing/freesewing/pull/2548 , and I believe merging the PR will automatically cause this bug to close.

If there are additional issues with Cathrin line art or cover art that need to be fixed, please file a separate bug to make sure those issues continue to be tracked.
