### ISSUE TITLE
[feature]: add small GitHub guide for first-time contributors 

### ISSUE THREAD

**Issue by starfetch** [freesewing/freesewing#2550]
### What is it that you would like to see happen? 🤔

Adding a section to the devdocs contributors' guide about how to get started with git/GitHub might be useful (i.e. a short step-by-step of how to create a fork, etc).

### Are you a FreeSewing patron? 😃

Yes, I am a tier-4 patron ❤️  💙

**Comment by bobgeorgethe3rd** [comment]
https://discord.com/channels/698854858052075530/757631165531291771/1002574737026863196

For reference.

**Comment by starfetch** [comment]
(I assigned myself, but probably won't get around to it in the next few days, so if anyone's game, feel free!)

**Comment by joeschofield0** [comment]
> (I assigned myself, but probably won't get around to it in the next few days, so if anyone's game, feel free!)

I am happy to make a start on this tomorrow.  I'll read through the contributor and markup guidelines first. ;)

**Comment by joeschofield0** [comment]
Page drafted and submitted.  I should have forked a new branch for this first.  Instead, I drafted the new page and Github created a new branch called _patch-1_.   Ah, the irony of writing a Github How To when I can't even work Github!   I hope you can access the .md and .pngs OK.

**Comment by joeschofield0** [comment]
After a bit of a false start yesterday, and some very helpful guidance on Discord (thank you!), I think is ready for review.  I resized all images to be 500px wide, and they look OK on my monitor.  I'm happy to edit this draft content / close the issue based on feedback.

**Comment by starfetch** [comment]
Closed via #2580, thanks @joeschofield0!
