### ISSUE TITLE
Broken 'Getting started' link on github page for maker website 

### ISSUE THREAD

**Issue by joeschofield0** [freesewing/freesewing#2556]
The following URL in the "source code for our maker website: freesewing.org" page results in a 404 error.  Sorry, I'm not familiar enough with the .dev site to fix this myself.
"Getting started ⚡
Please refer to the online documentation for this repository at: _https://freesewing.dev/reference/repos/org/_"

**Comment by BenJamesBen** [comment]
The problem web page is https://github.com/freesewing/freesewing.org
The problem file is `README.md` in the root of the org repository.

**Comment by joostdecock** [comment]
I've update the README, thanks for reporting this
