### ISSUE TITLE
[feature]: Add notches to the Titan block to indicate specific points and aid alignment

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#2558]
### What is it that you would like to see happen? 🤔

As the Titan block is used for generating subsequent patterns (whether by hand or through FreeSewing), it would be useful to mark key notches on the block.

Hip and knee would be useful notches to help when choosing where to place style elements. It would also be helpful to verify the block is landing at the correct points during fitting.

Notches additionally help with alignment of pattern pieces during sewing. A double notch on the back seam would help identify front from back quickly (and help with alignment when sewing the crotch curve).

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by bobgeorgethe3rd** [comment]
I will look into adding these. Though I suspect the hip is going to be a bit tricksy.

**Comment by bobgeorgethe3rd** [comment]
Closed as of #2568
