### ISSUE TITLE
[bug]: Whaid pattern seem to have lost its grainlines.

### ISSUE THREAD

**Issue by OysteinHoiby** [freesewing/freesewing#2564]
### What seems to be the problem? 🤔

When generating Wahid, there is no grainlines on yhe design. The documentation mentions the grainline briefly so they should be there i think.. 

### Design / Plugin / Package 🧐

designs/wahid

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

**Comment by OysteinHoiby** [comment]
I've now added the grainline to all parts. And I've just got two questions.

1: Should the grainline on the pocket welt correspond with the pocket welt angle?
2: I just opened the freesewing/freesewing repo in Gitpod, how do i share the changes? (Commit, commit & push, commit & sync, or commit & create pull request)

**Comment by joostdecock** [comment]
@OysteinHoiby 

1) the grainline should be the same as the front when it's assembled. So yes :)
2) commit & create pull request

Thanks for this :+1:

**Comment by bobgeorgethe3rd** [comment]
Fixed as of #2583
