### ISSUE TITLE
Explain that pattern names are bound by the constraints of NPM package names (in create-freesewing-pattern)

### ISSUE THREAD

**Issue by globalcitizen** [freesewing/freesewing#257]
I decided to try your framework out to mark up a simple library bag, but couldn't.

## Steps to reproduce

Using [get started in seconds](https://freesewing.dev/) instructions:

```
npm init freesewing-pattern
```

## Expected behavior

Everything installs and we can try it out.

## Observed behavior

Crashes asking for `Pattern name:` and refuses to continue when pressing enter. Only possible to break out with CTRL+C.

<img width="372" alt="Screen Shot 2020-01-17 at 23 19 44" src="https://user-images.githubusercontent.com/505366/72612094-e42cea00-397f-11ea-8819-8bdfeb7f58ef.png">

## Environment

 * System: `Darwin laptop.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
 * npm: `6.13.6`
 * node: `v12.9.1`

**Comment by globalcitizen** [comment]
I seem to have figured it out. It won't work with a leading capital. This is sort of ridiculous.

**Comment by joostdecock** [comment]
Well that ain't great. Thanks for reporting this, I'll look into it ASAP.

**Comment by joostdecock** [comment]
> I seem to have figured it out. It won't work with a leading capital. This is sort of ridiculous.

Those are the rules for NPM package names. We should perhaps make it more clear that the name you choose here will become the name of the package (should you decide to publish it).

**Comment by globalcitizen** [comment]
I suggest making it clear you expect lowercase, or automatically converting to lowercase.

As a new user, knowing nothing about your setup or npm package naming rules, I just want to try the adjustable size pattern thing, and I get stuck at step 1 with no explanation.

**Comment by joostdecock** [comment]
v2.2 is planned to go out next weekend, and this should be addressed in it.

**Comment by joostdecock** [comment]
Fixed:

![cfp](https://user-images.githubusercontent.com/1708494/73123105-5eff9180-3f8c-11ea-9314-5bf76c6bd63a.png)
