### ISSUE TITLE
[bug]: errors.requestFailedWithStatusCode0 when trying to log into freesewing.org

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2579]
### What seems to be the problem? 🤔

Attempts to log into freesewing.org fail with a red errors.requestFailedWithStatusCode0 error message.
![image](https://user-images.githubusercontent.com/109869956/184461073-e16bfa5d-3872-4b72-a57d-8b6bd34bcb03.png)

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

In the console, I see:
> [Error] Preflight response is not successful. Status code: 502
[Error] XMLHttpRequest cannot load https://backend.freesewing.org/login due to access control checks.
[Error] Failed to load resource: Preflight response is not successful. Status code: 502 (login, line 0)

When I try to visit https://backend.freesewing.org/login I get:
> 502 Bad Gateway
nginx/1.10.3

The problem appears to have started a few hours ago earlier today, per Discord discussion.

In the console, I also see 502 errors when trying to access posts.freesewing.org:
> [Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (large_IMG_7901_239d0b5218.jpg, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (large_pexels_snapwire_6989_a0cc374a66.jpg, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (large_pexels_anna_doschechko_6204137_6fd7f57df2.jpg, line 0)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (large_pexels_marcus_woeckel_883466_a7f3f9757f.jpg, line 0)

**Comment by vanrein** [comment]
Before the login problems, I was logged in but could not save measurements.  Probably the same thing.

**Comment by joostdecock** [comment]
Thank you for reporting this. We had an infrastructure issue, but it's been resolved and everything is back to normal.
