### ISSUE TITLE
[bug]: Titan front part degrades with large Waist to Upper Leg measurements

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2596]
### What seems to be the problem? 🤔

The Titan front part can become degraded with a large Waist to Upper Leg measurement. All the points seem to be in wildly wrong locations.

Steps to Reproduce:
1. In lab.freesewing.dev, select Titan without breasts Size 50.
2. Set Waist to Upper Leg to 52 mm. Observe that the front part is still fine.
3. Set Waist to Upper Leg to 53 mm. Observe that the front part is degraded. 

![52 mm Waist to Upper Leg](https://user-images.githubusercontent.com/109869956/185018118-9d72ce46-6c19-432a-b8fc-a7a58e825a8b.png) 
![53 mm Waist to Upper Leg](https://user-images.githubusercontent.com/109869956/185018159-61925f36-ef4c-4952-9bd2-f9ecfbce1ce3.png)

### Design / Plugin / Package 🧐

designs/titan

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The degradation seems to start at 52.9 mm:
![52 9 mm](https://user-images.githubusercontent.com/109869956/185019910-105e9c25-c80e-4374-a61d-54e459c3a805.png)

**Comment by BenJamesBen** [comment]
Using the measurements from #2595 and uncommenting debug code in Titan, it looks like the problem might be occurring during the iterative crossSeam fit process, both "Remedy A: Slash and spread" and "Remedy B: Nudge the fork inwards/outwards".

The process iterates 15 times to try to get crossSeamDelta as small as possible. For the first 5 or so iterations the delta decreases, approaching 27 at the nadir. However, after that it stops getting smaller. Instead the process makes the delta increase so the full 15 iterations are run. It would keep going, too, if we allow it to run more iterations.
![Screen Shot 2022-08-16 at 8 56 43 PM](https://user-images.githubusercontent.com/109869956/185031831-04afe593-2fde-41d7-852a-218c0edc7a33.png)
![Screen Shot 2022-08-16 at 8 53 55 PM](https://user-images.githubusercontent.com/109869956/185031836-d4453c94-d7d7-4c1b-8bd4-40e830d8c1bf.png)

**Comment by BenJamesBen** [comment]
The proposed fix is to iterate the front and back crossSeam adjustments for as many times as they produce improved results. Once we see that they are starting to produce worse results, stop and revert back to the last, good iteration.

There's also a new warning system to alert the customer when the design has produced a pattern that is likely to need alterations. We will try to be as specific as possible about what and where each problem is, to help customers know where adjustments are likely to be needed.

The crossSeam adjustment process can move points to locations that break the current design at several different places (mostly because they break assumptions about where the points will be in relation to the seamline). The design will be fixed at these places so it does not break, and we will warn customers whenever there is a deviation in the pattern that might affect fit.

```js
   if (options.fitCrossSeam && options.fitCrossSeamFront) {
     let delta = crotchSeamDelta()
     let previous_delta = delta
     let rotate = ['waistIn', 'waistOut', 'cfWaist']
     let saved = []
     let run = 0
     do {
       previous_delta = delta
       run++
       // Remedy A: Slash and spread
       for (const i of rotate) {
         saved[i] = points[i]
         points[i] = points[i].rotate(delta / -15, points.seatOut)
       }
       // Remedy B: Nudge the fork inwards/outwards
       saved.fork = points.fork
       points.fork = points.fork.shift(180, delta / 5)
       drawCrotchSeam()
       delta = crotchSeamDelta()
       // Uncomment the line below this to see all iterations
       // paths[`try${run}`] = drawPath().attr('class', 'dotted')
     } while (Math.abs(delta) > 1
         && run < 15
         && (Math.abs(delta) < Math.abs(previous_delta)))
     if (Math.abs(delta) > Math.abs(previous_delta)) {
       for (const i of rotate) {
         points[i] = saved[i]
       }
       points.fork = saved.fork
     }
     if (Math.abs(delta) > 1
       || Math.abs(delta) > Math.abs(previous_delta)) {
       raise.warning("Unable to adjust the front crotch seam to fit the given measurements.")
       adjustment_warning = true
     }
   }
```

![Screen Shot 2022-08-17 at 2 53 05 AM](https://user-images.githubusercontent.com/109869956/185090400-eca298db-9e43-48cf-b24e-01892b5435a2.png)

**Comment by joostdecock** [comment]
These sort of issues, where it goes off the rails suddenly and dramatically, are (almost) always caused by finding the intersection of two lines. And when those lines become more and more parallel, things go wrong hard and fast.

This is no exception:
https://github.com/freesewing/freesewing/blob/c2ae5ba5d67c6df809ced1673ace0f1887801616/designs/titan/src/back.js#L69-L74

While we could put it more checks and balances to avoid things going off the rails, it might be worthwhile to re-evaluate this call to `beamsIntersect()` and see if there's a way we can get the same result that is less prone to falling apart.

**Comment by BenJamesBen** [comment]
The changes in #2704 address this bug. However, additional "check if points are inside or outside the seamline" code will need to be added to the PR for the seatIn point, to address #2809 .

**Comment by BenJamesBen** [comment]
PR https://github.com/freesewing/freesewing/pull/3506 was submitted to address this issue.

(Fit Guides were removed/reverted from Titan, so the seatIn issue is no longer reproducible and no longer needs to be addressed.)
