### ISSUE TITLE
[bug]: The `:` character is not escaped in design options, causing it to be mistaken for a namespace by i18next

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2604]
### What seems to be the problem? 🤔

In lab.freesewing.dev and the localhost version of the lab, the Breanna dart options are not displayed correct. The options should be text like "06:00", "07:00", "11:30" (clock hand positions). However, the options are instead displayed as "00", "00", and "30". This makes the two settings (bust dart and secondary dart) quite difficult to use.

![Screen Shot 2022-08-17 at 9 04 34 PM](https://user-images.githubusercontent.com/109869956/185291188-ce19c499-cbf5-488f-ad3b-8440852968e2.png)

The options do work correctly when selected in the UI, so the problem seems to be cosmetic. The problem is not seen in freesewing.org or breanna.freesewing.dev which uses a differently-formatted web page to display design options. I suspect that the problem is within the web page display infrastructure and not with the Breanna design itself.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Good catch. This is a frontend issue. The options are listed as clock times (`06:00`, '07:00`, `08:00` and so on).

However, `:` is the namespace separator in [i18next](https://www.i18next.com/) so we'd have to escape it.
Will update title accordingly to reflect this. Changes should be made in:

- `sites/shared/components/workbench/inputs/design-option-count.js`
- `sites/shared/components/workbench/inputs/design-option-list.js`
- `sites/shared/components/workbench/inputs/design-option-pct-deg.js`
