### ISSUE TITLE
[bug]: Link in documentation is 404

### ISSUE THREAD

**Issue by gregsadetsky** [freesewing/freesewing#2605]
### What seems to be the problem? 🤔

At the top of the README.md, there is a 404 link, specifically [here](https://github.com/freesewing/freesewing/blob/develop/README.md?plain=1#L51).

The link is -> "This repository is our *monorepo* holding [all our NPM packages](https://freesewing.dev/reference/packages/)."

That same 404 link appears at least in one other place, like [here](https://github.com/freesewing/freesewing/blob/develop/packages/core/README.md?plain=1#L58).

### Design / Plugin / Package 🧐

packages/core

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
I am not sure what the link should be corrected to.

In any case, the 404 link appears in 96 README files in the repository. There seem to be two template files and a script that will change most of the README files automatically.
1. Edit the `/config/templates/readme.dflt.md` and `/config/templates/rreadme.main.md` files.
2. Run `yarn reconfigure`.

However, these 3 remaining files are untouched by the script, and they will need to be edited manually:
```
/sites/lab/README.md
/sites/strapi/README.md
/sites/svgtopdf/node_modules/@freesewing/prettier-config/README.md
```

**Comment by joostdecock** [comment]
Thanks for reporting this. It's a link that dates back to before we migrated our docs site to NextJS and split our one `packages` yarn workspace into multiple.

I've removed the link and updated the phrasing to reflect the new reality.

**Comment by joostdecock** [comment]
@all-contributors please add @gregsadetsky for docs
