### ISSUE TITLE
[chore]: Add AWS SES to the SPF record for freesewing.org

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2616]
Joost recently added an SPF record to the freesewing.org DNS. He mentioned in today's Contributor Call that there is some other email-related task that needs to be performed. I am unclear about what the task specifically is (DKIM?), but apparently it needs to be performed before we send out our next newsletter. This GitHub Issue has been filed for tracking purposes, so the task does not get overlooked or forgotten.

**Comment by joostdecock** [comment]
Thanks @BenJamesBen we need to add AWS SES to the SPF record.

**Comment by joostdecock** [comment]
Done
