### ISSUE TITLE
[docs]: Unice documentation missing for Front Exposure and Use Crossseam

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2621]
### Where can we see the problem? 🤔

https://freesewing.org/docs/patterns/unice/options/

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The documentation for Unice's Use Crossseam design option is incomplete, with the web page being a placeholder that says "undefined".
https://freesewing.org/docs/patterns/unice/options/usecrossseam/
The en file is: `markdown/org/docs/patterns/unice/options/usecrossseam/en.md`

The documentation for Unice's Front Exposure design option is missing entirely.
There is no `markdown/org/docs/patterns/unice/options/frontexposure/` directory.

The "Front Exposure" link on the design options documentation web page incorrectly links to the documentation for "Taper to gusset".

The "Taper to gusset" option is missing on the design options documentation web page (or, it is mislabeled as "Front Exposure").

**Comment by bobgeorgethe3rd** [comment]
The Front Exposure has been changed to Taper to gusset for Ursula as well. https://github.com/freesewing/freesewing/commit/077c25416db6172f6c0917f6b2f60a04549bd468

I was just going to go fix the ymls and add the missing unice page but I am perplexed why the Front Exposure was changed as it doesn't change the bottom Width which attaches to the gusset. So I unassign myself till @joostdecock can explain the change.

**Comment by joostdecock** [comment]
Both patterns have been left in a state that is a bit if a mess after recent contributions.

I've opened #2403 to address this

**Comment by bobgeorgethe3rd** [comment]
Front Exposure will need to be changed back on Ursula as this was changed to matched Unice.

**Comment by anna-puk** [comment]
> Front Exposure will need to be changed back on Ursula as this was changed to matched Unice.

I'm not sure what change was made, but #2638 includes documentation for useCrossSeam and replaces 'taper to gusset' with 'front exposure' in the documentation text _for Unice_. The variable name is still the same taperToGusset, as was used in Ursula.

**Comment by BenJamesBen** [comment]
This bug was addressed by #2638 for Use Crossseam. (The issue is still present in the current v2 web site, but the fix was merged and will be deployed in v3.)

The Front Exposure/taperToGusset issue is Not a Bug, as explained above.

Closing.
