### ISSUE TITLE
[bug]: [design].freesewing.dev pages not loading due to secure connection problem

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2651]
### What seems to be the problem? 🤔

The [design].freesewing.dev workbench web pages are not loading due to a problem making a secure connection.
- On Safari: "can’t open the page ... because Safari can’t establish a secure connection to the server".
- On Chrome: "Your connection is not private... NET::ERR_CERT_COMMON_NAME_INVALID"

This will mostly affect the gist recreation links generated for GitHub issues.
Example: https://charlie.freesewing.dev/recreate/gist/1515b362fee5c39101f1ce1b29f83382

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

If this is now the correct and intended new behavior, related to the v2/v3 transition process, please close this bug as "Not a Bug".

**Comment by joostdecock** [comment]
Those sites were legacy and have been removed. 

Please use https://lab.freesewing.dev/ instead
