### ISSUE TITLE
Add linters for JS and YAML files

### ISSUE THREAD

**Issue by nchilada** [freesewing/freesewing#2657]
Ideally run this in both [the pre-commit hook](https://github.com/freesewing/freesewing/blob/bae39f714b9f7cc8f9b209a3e438a14ae45de2b0/package.json#L49) (for convenience) and in CI (as a backstop).

**Comment by joostdecock** [comment]
Started doing some work on this in the `eslint` branch: https://github.com/freesewing/freesewing/tree/eslint
For now, focus is on the core library, but I plan to extend it beyond that.

**Comment by joostdecock** [comment]
I made an effort to add it initially as I was doing dome major refactoring of our core library and wanted to include the linting step.

But yeah, it needs some fine-tuning as you point out.
The reason things are at a design/olugin/package level is because it's all auto-generated from `config/templates/eslintrc.yml`

Happy to get some help with this as I'm currently writing v3 docs

**Comment by nchilada** [comment]
Okay, thanks for the background on that! I'll push the centralized `.eslintrc` to my PR so you can judge how it looks.

**Comment by bobgeorgethe3rd** [comment]
^ Has this been solved by the above merged PR request? If so can it be closed?

**Comment by nchilada** [comment]
> ^ Has this been solved by the above merged PR request? If so can it be closed?

Mostly done. I think we can close this issue.

But I should note that there is a gap in coverage, IIRC: eslint configs in lerna workspaces end up shadowing the root eslint config, which ultimately makes the linter excessively lenient in those workspaces. IMO it would be  less confusing if we had a _single_ eslint config (the one at the root). I was working on this but I couldn't keep up with @joostdecock and @eriese's rate of development in the codebase…maybe the correct approach is to get that config change into mainline even if it (temporarily) causes the lint.all.yml action to fail again.

**Comment by joostdecock** [comment]
> Mostly done. I think we can close this issue.

Let's :)
