### ISSUE TITLE
Code QA for Albert in v3

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2676]
### What is it that you would like to see happen? 🤔

While porting Albert to v3 I noticed there is a lotbof duplicated code in the different parts.

Someone should go through it and sort it out.
However, please do ao on the `v3` branch 

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

**Comment by joostdecock** [comment]
@BenJamesBen If you're interested, this would be a nice contribution, and allows you to get familiar with v3.

You won't be able to use it in the lab (yet) but you can run the unit tests to make sure any changes are ok (`yarn test`).

**Comment by BenJamesBen** [comment]
Many of the same variable names for points are re-used in different parts for different purposes, making it seem as if there is more duplication than there actually is. There are only a few actual duplications of some of the calculated lengths and the pocket points.

I was not able to get `yarn test` to run successfully in my version of the "v3" branch. I am tabling work on this Issue until v3 is stable enough to run the lab.

**Comment by joostdecock** [comment]
It's the length calculations at the start of the files that made me create this issue, so yeah :)
But you're right, there's no rush

**Comment by BenJamesBen** [comment]
PR https://github.com/freesewing/freesewing/pull/3305 was submitted for this issue.
