### ISSUE TITLE
[bug]: [albert] Crossboxes and hemlines do not appear if seam allowance is disabled or zero

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2677]
### What seems to be the problem? 🤔

With the Albert design, if seam allowance is disabled or set to zero, the strap attachment crossboxes and hemlines do not appear correctly in the pattern. (They first appear to be missing, but actually they are there on the seamline with zero width.)
![Screen Shot 2022-08-28 at 10 09 43 AM](https://user-images.githubusercontent.com/109869956/187086629-1a636504-bcf5-481b-9e1d-bf374ee680dd.png)
![Screen Shot 2022-08-28 at 10 09 56 AM](https://user-images.githubusercontent.com/109869956/187086635-5333ba34-012e-4eb8-a854-eda25302113c.png)

### Design / Plugin / Package 🧐

designs/albert

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The position/size of both elements are based on `hemWidth` which is based on the `sa` seam allowance value.

**Comment by bobgeorgethe3rd** [comment]
I believe that is intentional because those are seam allowance lines but I could be wrong. Best to ask @woutervdub .

**Comment by woutervdub** [comment]
Definitely a 'bug'.

Or maybe I should call it a 'sloppy, careless, shortcut'. Basically use the SA to create the hem. I'll create an option for it.

Of course, what should the initial value for such an option be (considering Dolls & Giants)?

**Comment by BenJamesBen** [comment]
I would suggest inputting your measurements for a sample aaron, deciding what specific distance you want the hem/crossboxes for those measurements, and then calculate what percent of the waist circ or waist-to-knee measurements the distance corresponds to. Then test whether that percent value works for dolls and giants.
