### ISSUE TITLE
[bug]: 'npx @freesewing/new-design' files missing from main branch

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2679]
### What seems to be the problem? 🤔

The `npx @freesewing/new-design` command is producing 404 errors trying to retrieve the following files. The problem seems to be that the files are missing from the main branch.
```
sites/shared/components/icons/flip.js
sites/shared/components/icons/sheet.js
sites/shared/components/mdx/tabs.js
sites/shared/components/workbench/exporting/index.js
sites/shared/components/workbench/layout/draft/buttons.js
sites/shared/components/icons/rotate.js
sites/shared/components/error/view.js
sites/shared/components/error/error-boundary.js
sites/shared/components/error/error-boundary.js
sites/shared/components/error/reset-buttons.js
sites/shared/components/workbench/exporting/pdfExporter.js
```

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

Discussion about the issue is [on Discord](https://discord.com/channels/698854858052075530/698862765053575188/1013557515939762357).

**Comment by joostdecock** [comment]
Fixed through #2683
