### ISSUE TITLE
[bug]: Node 16 "npx @freesewing/new-design" with npm "Failed to install dependencies"

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2684]
### What seems to be the problem? 🤔

Using Node 16 and the "npx @freesewing/new-design" command with the npm package manager, dependencies fail to install.
```
$ npx @freesewing/new-design
...
✔ What template would you like to use? 📑 › From Scratch
✔ What name would you like the design to have? 🏷️ ([a-z] only) … bbb
✔ Last but not least, what package manager do you use? 📦 › npm

✔ 🟩⬜⬜⬜  Copied template files
✖ 🟩🟥⬜⬜  Failed to install dependencies  |  Development environment will not function
✔ 🟩🟩🟩⬜  Downloaded web components
✔ 🟩🟩🟩🟩  Initialized git repository
```

### Design / Plugin / Package 🧐

packages/new-design

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The problem is not seen when using Node 14 or when the yarn package manager is selected.

I note that `npm install` fails with the following dependency error. `npm install --force` allows the installation to complete.
```
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @freesewing/bbb@0.0.1
npm ERR! Found: axios@0.27.2
npm ERR! node_modules/axios
npm ERR!   dev axios@"^0.27.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"^0.25.0" from @freesewing/utils@2.22.1
npm ERR! node_modules/@freesewing/utils
npm ERR!   dev @freesewing/utils@"latest" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by joostdecock** [comment]
V2 requires node 14 as listed in the docs: https://v2.freesewing.dev/tutorials/getting-started-linux/installing-node

**Comment by BenJamesBen** [comment]
Re-opening. As I understand it, eventually v2 will be going away, and this bug will eventually need to be fixed for v3.

**Comment by BenJamesBen** [comment]
Re-closing. Will address via documentation instead, for this transition period.
