### ISSUE TITLE
[bug]: [v3] [albert] Local crossBox plugin not working

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2705]
### What seems to be the problem? 🤔

Albert was ported to v3 via #2700 . However, the local `crossBox` macro/plugin was not fully ported over, and it has been commented out in the `front.mjs` for now.

I was not able to avoid getting `ReferenceError: Cannot access 'crossBox' before initialization` errors. I even tried moving the plugin to a separate file outside of `index.mjs`, but that did not work. It is likely that there is a v3 way to implement local plugins that I am not aware of.

### Design / Plugin / Package 🧐

designs/albert

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Fixed in https://github.com/freesewing/freesewing/commit/8a39e43300f1e16b9a3f5a599c2c9fc09155324d
