### ISSUE TITLE
[docs]: snapseries needs documentation

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2716]
### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

The snapseries package is currently undocumented. Its exports probably should be documented: elastics, zippers, smallsteps, steps, bigsteps.

**Comment by SeaZeeZee** [comment]
Since this is listed in issue #3214 I'm gonna close this issue. We have so many issues open and we don't need duplicates.
