### ISSUE TITLE
Initial port of existing designs to v3

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2731]
### What is it that you would like to see happen? 🤔

Designs need to be ported to v3. Here's the list to keep an eye on what's been done and what not:

- [x] aaron
- [x] albert
- [x] bee
- [x] bella
- [x] benjamin
- [x] bent
- [x] bob
- [x] breanna
- [x] brian
- [x] bruce
- [x] carlita
- [x] carlton
- [x] cathrin
- [x] charlie
- [x] cornelius
- [x] diana
- [x] examples
- [x] florence
- [x] florent
- [x] hi
- [x] holmes
- [x] hortensia
- [x] huey
- [x] hugo
- [x] jaeger
- [x] legend
- [x] lucy
- [x] lunetius
- [x] noble
- [x] octoplushy
- [x] paco
- [x] penelope
- [x] plugintest
- [x] rendertest
- [x] sandy
- [x] shin
- [x] simon
- [x] simone
- [x] sven
- [x] tamiko
- [x] teagan
- [x] tiberius
- [x] titan
- [x] trayvon
- [x] tutorial
- [ ] unice
- [x] ursula
- [x] wahid
- [x] walburga
- [x] waralee
- [x] yuri

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

Everybody is free to help out. Refer to this excellent guide by @BenJamesBen for details: https://github.com/freesewing/freesewing/discussions/2715

**Comment by BenJamesBen** [comment]
- Bruce is already done/merged.
- I am working on Carlton and Carlita right now.
- I am working my way up the alphabet.
- I will skip designs that depend on another that hasn't yet been done.
- I'll also skip designs that other people are working on. Please let everyone know if you will be working on a design.

**Comment by joostdecock** [comment]
Thanks for the help @BenJamesBen 
I'm going down the alphabet, so while it's just us two, we'll meet in the middle ;)
If somebody else wants to join in, they should let us know.

**Comment by BenJamesBen** [comment]
I am working on Diana.

**Comment by BenJamesBen** [comment]
PRs for Cornelius and Diana were submitted. I am now working on Florent.

**Comment by BenJamesBen** [comment]
It appears that Urusla and Unice haven't yet been ported?

**Comment by joostdecock** [comment]
Ah yes, I skipped them because we we're going to discuss them during the most recent contributor call, but then forgot that I had skipped them.

I've un-ticked their boxes, I'll probably be able to handle them today

**Comment by joostdecock** [comment]
Rolled back ursula and ported it to v3.
Dropped unice until it's fixed by the designer now that the ursula it relies on is backported.

Closing
