### ISSUE TITLE
[bug]: [v3] Option inheritance issues

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2742]
### What seems to be the problem? 🤔

There seem to be issues with how options are inherited in v3. 
- For the Carlita port, it was not possible to remove the draftForHighBust option from the menu. Also, it didn't seem possible to change its default state from `false` to `true`. See #2733 .
- For the Charlie port, it did not seem possible to move options from the Titan locations, for example Waistband Width was in Advanced instead of Style.
- And, in general it no longer seems possible to specify the arrangement of settings menus and menu options. Instead, they seem to be set in the order that they get loaded. But previously, Designs had the ability to specify the exact arrangement for these menus and options, to arrange them in a logical manner.

So, it seems that option values and locations might be getting set early in the inheritance process, and that later inheritance isn't changing them.

Also, because options are now set in individual parts, it is unclear what happens if a sleeve part inherits ExampleOption=true in the 'Fit' menu, while the front part inherits or sets ExampleOption=false and wants to move it to the 'Style' menu. Who wins?

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
> Also, because options are now set in individual parts, it is unclear what happens if a sleeve part inherits ExampleOption=true in the 'Fit' menu, while the front part inherits or sets ExampleOption=false and wants to move it to the 'Style' menu. Who wins?

The option that is *closest* to the design wins. With each level of inheritance, we increase the *distance*. When an option is configured twice, the one with the lowest *distance* wins.
This way, when you inherit a part with a given option, but also configure that option in your own part, it will also be your own configuration that wins.

The reason it didn't work was a simple typo, it's fixed now.

As for the menu, I've updated it to be displayed alphabetically with one exception: If there is an `advanced` entry, it will get pushed to the bottom.
