### ISSUE TITLE
[docs]: todo.freesewing.org points to an old/closed Github project 

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2785]
### Where can we see the problem? 🤔

https://todo.freesewing.org

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

It was [pointed out on Discord](https://discord.com/channels/698854858052075530/944926520282054666/1017980586339598446) that https://todo.freesewing.org currently redirects to https://github.com/orgs/freesewing/projects/1  a closed GitHub project (closed in May 2021).
> The project has been closed. It is now read-only.

- We should change it to point to a more relevant website, perhaps https://github.com/freesewing/freesewing/issues .
- And/or we should change the README.md file that references it as a "Kanban board".
- Or, we could remove the link entirely from the README.md file.

### Additional context

The README:
![bug](https://user-images.githubusercontent.com/109869956/189469375-2142fc24-9ede-459b-ad97-12660cb8129e.png)

**Comment by joostdecock** [comment]
fixed
