### ISSUE TITLE
[bug]: dead link on reversible Ursula and Bee showcase

### ISSUE THREAD

**Issue by jdhoek** [freesewing/freesewing#2788]
### What seems to be the problem? 🤔

In showcase https://en.freesewing.org/showcase/ursula-and-bee/ there is a link to the modified Ursula in the second paragraph, but the link text and the link location differ.

The link text (`https://freesewing.org/patterns/feaxz/`) leads to an Ursula v2 pattern.

The link location users get when you click the link though, is (`https://en.freesewing.org/showcase/ursula-and-bee/link`), which gives the 404 page.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by tangerineshark** [comment]
Pretty sure I just fixed this in Strapi! Although probably smart to double-check after the next update and before closing.

**Comment by tangerineshark** [comment]
Okay on second thought, I know how links work and how Strapi works - gonna listen to my inner Joost and say, "Yep, this is done!" Should be updated the next time the website is. In the meantime, you can get the pattern by going to the link directly: https://freesewing.org/patterns/feaxz/
