### ISSUE TITLE
Port designs to v3 stage 2

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#2791]
### What is it that you would like to see happen? 🤔

All designs need to be ported to the second stage of v3. This should happen in the [v3-stage2](https://github.com/freesewing/freesewing/compare/v3-stage2) branch.

**Changes required**

- The draft method no longer receives the `part` as a parameter, but rather the result of `part.shorthand()`. So object desctructuring should happen in the method parameters
- Make sure to add `part` to the destructured parameters and return it
- there is no more `raise`, it is now called `log`. 

**Progress**

- [x] aaron
- [x] albert
- [x] bee
- [x] bella
- [x] benjamin
- [x] bent
- [x] bob
- [x] breanna
- [x] brian
- [x] bruce
- [x] carlita
- [x] carlton
- [x] cathrin
- [x] charlie
- [x] cornelius
- [x] diana
- [x] examples
- [x] florence
- [x] florent
- [x] hi
- [x] holmes
- [x] hortensia
- [x] huey
- [x] hugo
- [x] jaeger
- [x] legend
- [x] lucy
- [x] lunetius
- [x] noble
- [x] octoplushy
- [x] paco
- [x] penelope
- [x] plugintest
- [x] rendertest
- [x] sandy
- [x] shin
- [x] simon
- [x] simone
- [x] sven
- [x] tamiko
- [x] teagan
- [x] tiberius
- [x] titan
- [x] trayvon
- [x] tutorial
- [x] ursula
- [x] wahid
- [x] walburga
- [x] waralee
- [x] yuri

### Additional context

For an example, check this commit porting aaron: https://github.com/freesewing/freesewing/commit/bd4b7bb9e7d0732cd9fc94500931b5eb8f6a1471

**Comment by BenJamesBen** [comment]
My localhost lab gets an unhandled runtime error when loading v3 stage 2 designs. Is this the current expected behavior?
![Screen Shot 2022-09-10 at 6 16 48 PM](https://user-images.githubusercontent.com/109869956/189508765-a6d01539-15a4-4836-839c-67f388cd78c0.png)

(I can help with the porting, but I first want to know what to expect regarding how the designs should appear in the lab.)

**Comment by joostdecock** [comment]
@BenJamesBen you need to be on the `v3-stage2` branch (which is where I'm porting these) because there are a bunch of breaking changes in the core library.

But in `v3-stage2` the ported designs should work (they do for me).

**Comment by BenJamesBen** [comment]
Hmm...  the v3-stage2 branch was where I saw those runtime errors. I'll look into the issue further.

**Comment by BenJamesBen** [comment]
I am now able to run localhost lab in v3-stage2 branch. I believe that your recent `core-setting-only.js` change fixed the issue for me:
```diff
-  const list = props.design.config.draftOrder
+  const list = props.draft.config.draftOrder
```

**Comment by joostdecock** [comment]
Yeah, I had fixed this a while ago, but only now realized I forgot to commit that change :shrug:

**Comment by BenJamesBen** [comment]
(FYI, there is a bug in v3-stage2 where `hideDependencies: true` isn't causing the inherited parts to be hidden. You can see this bug in Charlie and Diana, among others.)

- Now working on Waralee.

**Comment by joostdecock** [comment]
I had to run an errand, so I stopped after Trayvon :)

**Comment by joostdecock** [comment]
That `hideDependencies: true` issue should be resolved

**Comment by joostdecock** [comment]
Thanks for the help @BenJamesBen :+1:
