### ISSUE TITLE
[bug]: [v3] [lab] LayoutThing: ForPrinting is blank

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2803]
### What seems to be the problem? 🤔

In the localhost lab, the LayoutThing: ForPrinting view is blank:

![Screen Shot 2022-09-11 at 3 25 10 PM](https://user-images.githubusercontent.com/109869956/189551432-e5123db7-cf78-4f4e-9240-4f47abd82f65.png)

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

#2802 ("[bug]: [v3] [lab] Runtime error when exporting to PDF") is another, possibly-related issue introduced around the same time.

**Comment by eriese** [comment]
fixed by #3608
