### ISSUE TITLE
[bug]: [v3] [lab] LayoutThing: ForCutting results in Runtime Error

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2804]
### What seems to be the problem? 🤔

In the localhost lab, switching to the LayoutThing: ForCutting view results in a runtime error:

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'draftOrder')

Source
../shared/components/workbench/menu/core-settings/core-setting-only.js (7:34) @ CoreSettingOnly

   5 | const CoreSettingOnly = props => {
   6 | const { t } = useTranslation(['app', 'parts', 'settings'])
>  7 | const list = props.draft.config.draftOrder
     |                                ^
   8 | const partNames = list.map(part => ({ id: part, name: t(`parts:${part}`) }))
   9 | 
  10 | const togglePart = part => {
```

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by bobgeorgethe3rd** [comment]
@eriese Is this being dealt with/been fixed? I recall that this one may have been fixed.

**Comment by BenJamesBen** [comment]
This bug was fixed with the addition of the Cutting Layout feature last month. The problem behavior is no longer seen in the `develop` localhost lab. Closing as Resolved. 

(The changes have not yet been pushed to lab.freesewing.dev yet, but no Runtime Errors are seen there currently. Instead, a "Fixme: Cut layout settings here" message is seen.)
