### ISSUE TITLE
[bug]: [v3] [lab] Grid is missing and boundary box is visible in Paperless mode

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2836]
### What seems to be the problem? 🤔

Previously Paperless mode would show a grid and dimensions. However, there was a recent change that caused the grid to no longer appear. Also, the boundary box outline seems to be incorrectly visible now.
![Screen Shot 2022-09-20 at 12 08 20 PM](https://user-images.githubusercontent.com/109869956/191343734-8abaa651-fbb4-4438-bd42-f29b2febd244.png)

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Grid is missing because it's provided by `plugin-theme` which needs to be migrated to the recent changes in v3. See #2856
