### ISSUE TITLE
[bug]: [v3] round macro paths are no longer hidden by default, affecting existing Designs

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2844]
### What seems to be the problem? 🤔

In localhost lab, the Bob design is now unexpectedly and incorrectly showing a new path:
![Screen Shot 2022-09-20 at 11 42 56 PM](https://user-images.githubusercontent.com/109869956/191435117-d48e6146-bf31-42c8-8b86-2198ef09102f.png)

This path is created via two `round` macros in `bib.mjs` (the ones named 'tipRightTop' and 'tipRightBottom').

The cause is a change in the default behavior of the `round` macro. Via commit 5dc740130894546ffbed98fbd313215e8cc4ee0d, the `round` macro was changed such that the prefix+'Rounded' paths created by the macro are not hidden by default. Previously these paths were hidden (not rendered) by default.
```js
--- a/plugins/plugin-round/src/index.mjs
+++ b/plugins/plugin-round/src/index.mjs
@@ -31,9 +31,8 @@ export const plugin = {
           this.points[prefix + 'End']
         )
         .attr('class', so.class ? so.class : '')
-      if (typeof so.render !== 'undefined' && so.render)
-        this.paths[prefix + 'Rounded'].render = true
-      else this.paths[prefix + 'Rounded'].render = false
+      if (so?.hidden) this.paths[prefix + 'Rounded'].hide()
+      else this.paths[prefix + 'Rounded'].unhide()
     },
   },
 }
```

### Design / Plugin / Package 🧐

plugins/plugin-round

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

It might be that this will be deemed a 'Will Not Fix' bug, with the remedy being to change existing Designs to conform to the new API (by adding `hidden: true` to the macro calls):
```js
    macro('round', {
      from: points.edgeTop,
      to: points.tipRight,
      via: points.tipRightTop,
      prefix: 'tipRightTop',
      hidden: true,
    })
```

**Comment by joostdecock** [comment]
You are correct, we should not change the default behaviour. Fixed in https://github.com/freesewing/freesewing/commit/71904f240c188c91af39b954ef8a23af91869aa8
