### ISSUE TITLE
[bug]: [v3] [lab] Patterns are initialized twice

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2852]
### What seems to be the problem? 🤔

Based on the Logs/Events messages, patterns are being initialized twice in the `develop` localhost lab:
![Screen Shot 2022-09-22 at 12 41 34 PM](https://user-images.githubusercontent.com/109869956/191836700-b587b12b-14fa-46d4-a420-eeb660e61f3a.png)

This does not occur in the current lab.freesewing.dev version of the lab:
![Screen Shot 2022-09-22 at 12 41 46 PM](https://user-images.githubusercontent.com/109869956/191836737-92f1217f-d50e-41a3-83a5-029e03907b4c.png)

It is unclear whether or not this new behavior is a problem. (It appears to be unusual and unexpected.) It is also unclear if it might be related to the other problems seen in `develop`.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
There are some issues still the be cleared up, obviously. They typically come in three categories:

- Issues with the core library
- Issues with designs
- Issues with the lab

The most disruptive are obviously issues in the core library. Where issues can also just be changes, as those too will break things. I am currently working on those but I have not (yet) gotten to the point where it's ready to merge in. It will probably take a few more days before I get there.

Issues with designs are typically few and far between. Once they work, they should keep working. When we make a breaking change in core, we tend to port them as we have been doing diligently.

Issues with the lab are all over the place currently. But there really is not much point in working on them as long as we know there are issues in core. So while opening these issues is a good reminder of things that need to be resolved, they are not going to get much TLC until we can at least to a point where they should not happen.

Almost all problems in core and the lab today are related to the bootstrapping/initializing of the pattern.
Which is probably not so surprising as that's where most of the v3 changes were.

So I will be working on that, and once that's taken care of will adapt the lab to all those changes. Then, we can revisit these issue.

Apologies if that makes running things in develop a hassle now. You can always branch from an earlier commit if that's easier.
