### ISSUE TITLE
[bug]: [v3] Design name and version displayed as "No Name" and "No version"

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2858]
### What seems to be the problem? 🤔

In the `develop` lab, design name and version information seem to be no longer loaded during pattern generation. Instead, they are displayed as "No Name" and "No version" in Logs and in the title macro.

### Design / Plugin / Package 🧐

packages/core

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

I suspect that this issue might have been introduced in 6cd953d82561725c902cd9d22b79eb794a2a0d20 .

**Comment by joostdecock** [comment]
Fixed in https://github.com/freesewing/freesewing/commit/bc8b742cb7248c41ca04f756156a0d2912853276
