### ISSUE TITLE
[bug]: [v3] Log view isn't constrained horizontally, causing the tabs to go out of view

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2859]
### What seems to be the problem? 🤔

Log messages are no longer displayed in the Logs view (or perhaps instead they aren't being saved). These include error messages and traceback information when an error occurs during pattern generation as well as log messages created during pattern generation via `log.info()`, `log.error()`, `log.warning()`, and `log.debug()` calls. 

(However, log messages produced by the core infrastructure still appear in Logs normally.)

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

This problem started happening in the past day.

**Comment by joostdecock** [comment]
![Screenshot 2022-09-26 at 09 52 39](https://user-images.githubusercontent.com/1708494/192223608-5921e910-ac33-4971-bb1d-ebebeaca7b74.png)

Looks fine to me ;)
Are you perhaps behind HEAD?

**Comment by BenJamesBen** [comment]
The problem occurred because the new "Set 0", "Set 1", etc. tabs are on the right side of the browser window, and the View menu covered them up so they were not seen.
![Screen Shot 2022-09-26 at 8 12 23 AM](https://user-images.githubusercontent.com/109869956/192315823-9db32550-cda0-4f03-a08d-450e132016d5.png)

The "Set 0" menu can be seen and accessed by horizontal scrolling or adjusting font size in the browser.

**Comment by joostdecock** [comment]
Thanks, I've updated the title to better describe the issue.

**Comment by joostdecock** [comment]
This is fixed now in a way that only impacts the log lines.
