### ISSUE TITLE
[bug]: [Jaeger] Front, Back, and Side parts are incorrectly short

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2881]
### What seems to be the problem? 🤔

In the `develop` localhost lab, Jaeger's Front, Back, and Side parts are incorrectly short. This is most visible in the Front part where the pocket outline falls below the hem.

In `develop` localhost lab:
![Screen Shot 2022-09-28 at 11 47 01 AM](https://user-images.githubusercontent.com/109869956/192864432-a81270c0-799a-462d-ad17-3c721ee81cfb.png)

In lab.freesewing.dev:
![Screen Shot 2022-09-28 at 11 47 11 AM](https://user-images.githubusercontent.com/109869956/192864478-23a02c02-1e4b-4b34-b6fe-36b58d693358.png)

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
Simone's Front Left, Front Right, and Back parts also seem to be affected by this issue. Looking at the Paperless dimensions, using the same body measurements the `develop` localhost lab produces a shorter garment compared to the version on lab.freesewing.dev.

**Comment by joostdecock** [comment]
Fixed in Simone too, it was the same underlying problem.
