### ISSUE TITLE
[bug]: [legend] TextSize element does not show different text sizes.

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2894]
### What seems to be the problem? 🤔

Because of its name, it seems as if the TextSize element of the Legend design might have been intended to show different sized text? If this is so, it does not appear to be doing this. Instead all the text is the same size.
![Screen Shot 2022-09-29 at 4 54 02 PM](https://user-images.githubusercontent.com/109869956/193162014-d2141883-2914-488b-8374-0513957407db.png)

### Design / Plugin / Package 🧐

designs/legend

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

This element appears the same in the lab.freesewing.dev and `develop` localhost versions of the lab, so it might have always been broken.

**Comment by BenJamesBen** [comment]
(I started working on a possible fix for this, but then I realized that I am not certain whether or not this actually is a bug. And, I do not know what the fixed element was intended to look like.)

**Comment by joostdecock** [comment]
It's a text label to marks which line style is used for which size.
It's perhaps not the greatest name, but it works as intended. Text size is not supposed to be different for the different labels.
