### ISSUE TITLE
[bug]: [v3] [lab] Patterns share a single state of measurements and options

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2926]
### What seems to be the problem? 🤔

In the v3 `develop` version of localhost lab, it appears that a single state for measurements and options is shared among all patterns. This can result in incorrect scenarios where the valid option values of pattern A are used for pattern B, even if those values are invalid for pattern B.

Steps to Reproduce:

0. In the `develop` localhost lab.
1. Go to the Titan design and the Measurements view.
2. Select cisFemale Size 28. Observe that the Cross Seam Front measurement is 66.2 cm.
3. In the DraftDesign view, in Design Options -> Fit -> kneeEase, select 1% (the minimum allowed value for Titan).
4. Go to the Charlie design and the Measurements view.
5. Observe that the Cross Seam Front measurement is still 66.2 cm. The Titan measurement state has been shared with Charlie.
6. Select cisMale Size 50. Observe that the Cross Seam Front measurement is now 103.5 cm.
7. In the DraftDesign view, observe that Design Options -> Fit -> kneeEase is still 1%. The Titan option state has been shared with Charlie. This is even though the minimum kneeEase value for Charlie is 10%. _The 1% value is invalid!_
8. In Design Options -> Fit -> kneeEase, select 30% (the maximum allowed value for Charlie).
9. Go to the Titan design and the Measurements view.
10. Observe that the Cross Seam Front measurement is now 103.5 cm. The Charlie measurement state has been shared with Titan.
11. In the DraftDesign view, observe that Design Options -> Fit -> kneeEase is now 30%. The Charlie option state has been shared with Titan. This is even though the maximum kneeEase value for Titan is 25%. _The 30% value is invalid!_

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

This issue is also seen if Titan is modified such that fitGuides becomes a user-configurable menu option: `fitGuides: { bool: true, menu: 'Fit'}`. If fitGuides is set to False and then back to True in Titan, this option state is shared with Charlie. The fitGuides are incorrectly displayed, even though Charlie explicitly sets the constant `fitGuides: false`.

**Comment by joostdecock** [comment]
Fixed in https://github.com/freesewing/freesewing/commit/6688f75db7eacd89ba55b66d5692543bd73dc99d
