### ISSUE TITLE
[docs]: Broken links in freesewing.dev bib tutorial

### ISSUE THREAD

**Issue by jfirwin** [freesewing/freesewing#2937]
### Where can we see the problem? 🤔

https://freesewing.dev/tutorials/pattern-design#prerequisites

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

I haven't worked to much with Monorepos, and I understand that things are being refactored currently, but I noticed some broken links when I was working my way through the tutorial. Not sure if the location I found `bib.js` is the actual location that you want to direct users, but the link is definitely outputting a 404.

I'm really excited I found this project! Can't wait to tinker with it.

Broken link locations:
- https://freesewing.dev/tutorials/pattern-design#prerequisites
- https://freesewing.dev/tutorials/pattern-design/conclusion

Current Link:
- https://github.com/freesewing/freesewing/blob/develop/designs/tutorial/src/bib.js

Actual Location:
- https://github.com/freesewing/freesewing/blob/freesewing.dev/designs/tutorial/src/bib.js

**Comment by joostdecock** [comment]
Thanks for letting us know @jfirwin 

We're indeed refactoring things. The file in question is in our `v2` branch.

You can find it here: https://github.com/freesewing/freesewing/blob/v2/designs/tutorial/src/bib.js

I'll keep this open so we can fix the broken link.

**Comment by joostdecock** [comment]
FIxed in v3 which will be deployed this weekend.
