### ISSUE TITLE
[bug]: <Examples> mdx component missing functionality

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2943]
### What seems to be the problem? 🤔

The new, v3 \<Examples> mdx component is missing functionality covered by the old, v2 \<Example> component:
- ~~The old default `examples` pattern.~~
- ~~The `pattern=<design>` attribute to use named patterns other than Tutorial.~~
- The `sample` and `settings` attributes for sampling.
- The `settings_paperless` attribute.
- ~~The `options_focus` attribute.~~
- ~~The `settings_complete` attribute.~~
- ~~The `options_only` attribute.~~
- Currently nothing is done with the content between `<Examples> </Examples>` tags. (The v2 \<Example> component would display the content as a caption. It is unclear if any functionality was intended for v3 \<Examples>.)

Currently, old, not-yet-updated web pages that use the old, v2 \<Example> tag are resulting in runtime errors because they do not conform to the new v3 \<Example> API (which expects draft function code as the content).

And, new tutorial web pages that use the new, v3 \<Examples> tag with the unimplemented attributes are not showing the expected example images.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
The c4937602c58e38583ef90f8a39303c24248ce936 commit message says:
>     chore: Removed examples as it's no longer needed
>    
>    We no longer need a dedicated examples design.
    It was used to showcase examples in the dev docs.
    But the new dev site Example component will use the actual example code
    to generate the example. Which is much better since we don't have to
    keep the example code and code of the the example design in sync.

So, the pages that depend on using the old Examples design or the Rendertest design will need to be changed to use the new \<Example> component, where the actual example drafting code is the content. These pages are:
```
./guides/patterns/snippets/en.md
./guides/patterns/snippets/en.md
./guides/patterns/en.md
./guides/patterns/config/en.md
./guides/patterns/paths/en.md
./guides/patterns/points/en.md
./guides/patterns/parts/en.md
./guides/patterns/pattern/en.md
./guides/patterns/store/en.md
./guides/prerequisites/coordinate-system/en.md
./guides/prerequisites/bezier-curves/en.md
./guides/markdown/custom-components/en.md
./guides/markdown/custom-components/en.md
./howtos/code/adding-text/en.md
./howtos/code/adding-text/en.md
./howtos/code/adding-snippets/en.md
./howtos/code/macros/en.md
./howtos/code/drawing-circles/en.md
```

However, the remaining parts of this bug still need to be addressed.

**Comment by joostdecock** [comment]
I believe all of these are addressed:

- Sample example: https://freesewing-23vfeuu1e-freesewing.vercel.app/guides/patterns/sets
- Paperless example: https://freesewing-23vfeuu1e-freesewing.vercel.app/tutorials/pattern-design/paperless (grid is not shown, but that''s a general thing

Note that the `Examples` component is (currently) not used anywhere. I'm keeping it around just in case, but so far so good
