### ISSUE TITLE
[docs]: (pattern-design-tutorial) Change instances of "your" to "our".

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2982]
### Where can we see the problem? 🤔

https://freesewing.dev/tutorials/pattern-design/structure

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

The v3 pattern design tutorial has been updated so the old `your-first-part` file name/directory is now `our-first-part`, and `completing-your-pattern` was renamed `completing-our-pattern`. The conclusion page was also updated to link to the new `our-first-part` and `completing-our-pattern` URLs. Based on this, it appears that the intention is to use "our" instead of "your" wording in the tutorial going forward.

The tutorial currently uses an inconsistent mix of "your" and "our" wording. And, there is now a 404 link to the old `your-first-part` URL. 

This bug is that instances of "your" should be changed to "our" in filenames, links, and text throughout the pattern design tutorial for consistency. (This would also require renaming the `testing-your-pattern` directory.)

**Comment by SeaZeeZee** [comment]
I commented this on the PR but adding it here as well:

**Comment by BenJamesBen** [comment]
I added this topic to the Feb. 4 agenda: https://github.com/freesewing/freesewing/discussions/3460

**Comment by BenJamesBen** [comment]
From the February 4, 2023 Contributor Call notes:
> There's a consensus that for tutorials, we use _we_, for reference and other
documentation, we use _you_.

Closing.
