### ISSUE TITLE
Ensure packages can be built from the stand-alone development environment 

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3003]
### What is it that you would like to see happen? 🤔

We currently don't ship a `build.mjs` file in the stand-alone development environment, nor is esbuild a development dependency.

We should address that so people can build their own packages 

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

**Comment by eriese** [comment]
possible duplicate of #2444?

**Comment by joostdecock** [comment]
@eriese is right. Closing
