### ISSUE TITLE
[bug]: Exporting Paperless pattern to PDF or SVG results in error or undefined file

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3008]
### What seems to be the problem? 🤔

In the v3 `develop` localhost lab, when a pattern with Paperless enabled is exported as SVG, the resulting file is a 9-byte file consisting of the text characters "undefined" (with no EOL at the end of the line).

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
Exporting a Paperless pattern to PDF (using the updated exporting functionality in #3068) results in an error message printed to the web page:
```
WARNING | ERROR: somethingWentWrong
```

**Comment by eriese** [comment]
For PDF, do we want it to automatically turn paperless off, or do we want it to export with all the paperless markup? @joostdecock thoughts?
