### ISSUE TITLE
[bug]: (hugo) There is no notch on the hood.

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3036]
### What seems to be the problem? 🤔

The Hugo instructions for "Step 5: Add a Drawstring to the Hood" mention a notch on the hood. https://freesewing.org/docs/patterns/hugo/instructions/
> The hole should be located above the notch on the hood rim. The notch shows where the sides of the hood overlap at center front , so the cord should exit above that point.

However, there is no notch on the hood pattern pieces. It is unclear whether the problem is with the design or if it is with the documentation. It seems that either the notch is missing and needs to be added or the instructions are incorrect and need to be changed to not mention the notch.

### Design / Plugin / Package 🧐

designs/hugo

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The Hugo hood pattern pieces:
![Screenshot 2022-11-02 at 8 47 51 AM](https://user-images.githubusercontent.com/109869956/199539515-9252b865-a5b2-4fa3-9da7-12a8de1c729d.png)

**Comment by bobgeorgethe3rd** [comment]
clsed as of #3811
