### ISSUE TITLE
[bug]: Offset curves can include spurious lines

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3038]
### What seems to be the problem? 🤔

Offset curves can sometimes include spurious lines. For example, the two diagonal lines seen in the seam allowance and the path distance dimensions in this screenshot:
![Screenshot_20221102-171342](https://user-images.githubusercontent.com/109869956/199628686-1b1e4429-9570-4916-9107-b48693d334da.jpg)

The issue is an edge case occuring with some curves but not others, depending on the geometry of the curve.

Steps to reproduce:
1. In lab.freesewing.dev, generate a Hugo pattern Without Breasts Size 50.
2. In the DraftDesign view, enable Paperless and Include Seam aallowance.
3. Observe that the diagonal lines are seen in Part 6 HoodSide.
4. Generate the same Hugo pattern Without Breasts Size 32.
5. Observe that the diagonal lines are no longer seen. (The Size 32 curve happens to not result in the issue.)

### Design / Plugin / Package 🧐

packages/core

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The root cause is a combination of a behavior in the `bezier-js` package and how our `Path.offset()` code interacts with the behavior.

The `Bezier.offset()` method returns an array of Bezier curves that approximate a curve that is offset from an input Bezier curve. However, an unexpected behavior is that this array can sometimes contain spurious Bezier curves which are noops. That is, all 4 points are identical when the x and y values are rounded to the nearest integer.
https://pomax.github.io/bezierjs/#offset

For example, these 8 Bezier curves were returned for one offset() operation. Note the 3 noop Bezier curves at #<span/>129, #<span/>135, and #<span/>136.
```
129 | 9,312 : 9,312 : 9,312 : 9,312
130 | 9,312 : 8,309 : -3,285 : -14,250
131 | -14,250 : -23,222 : -32,188 : -36,154
132 | -36,154 : -37,142 : -38,131 : -38,120
133 | -38,120 : -38,67 : -21,20 : 23,-6
134 | 23,-6 : 43,-18 : 70,-25 : 104,-25
135 | 79,0 : 79,0 : 79,0 : 79,0
136 | 79,0 : 79,0 : 79,0 : 79,0
```

Then, in our `path.mjs` the `__asPath()` method converts the noop Bezier curves to spurious Paths with spurious `move()` and `curve()` operations.

And finally, when we `__joinPaths()` these paths together, a spurious `move()` operation gets turned into a spurious `line()`:
```js
} else if (op.type !== 'close') {
  // We're using sitsRoughlyOn here to avoid miniscule line segments
  if (current && !op.to.sitsRoughlyOn(current)) joint.line(op.to)
 ```

In the above example, a spurious line gets drawn from 104,-25 to 79,0 when paths/curves #<span/>134 and #<span/>135 are joined.

A possible fix, in `packages/core/src/path.mjs`:
```diff
@@ -1279,7 +1279,22 @@ function __pathOffset(path, distance, log) {
         { x: cp2.x, y: cp2.y },
         { x: op.to.x, y: op.to.y }
       )
-      for (let bezier of b.offset(distance)) offset.push(__asPath(bezier, path.log))
+      for (let bezier of b.offset(distance)) {
+        // Bezier.offset() sometimes includes noop Bezier curves (consisting
+        // of 4 effectively-identical points) in its returned array. This
+        // can cause problems if we later try to join these noop curves to
+        // a Path. The workaround is to ignore these noop curves.
+        if (
+          (Math.round(bezier.points[0].x) === Math.round(bezier.points[1].x)) &&
+          (Math.round(bezier.points[0].x) === Math.round(bezier.points[2].x)) &&
+          (Math.round(bezier.points[0].x) === Math.round(bezier.points[3].x)) &&
+          (Math.round(bezier.points[0].y) === Math.round(bezier.points[1].y)) &&
+          (Math.round(bezier.points[0].y) === Math.round(bezier.points[2].y)) &&
+          (Math.round(bezier.points[0].y) === Math.round(bezier.points[3].y))) {
+          continue
+        }
+        offset.push(__asPath(bezier, path.log))
+      }
     } else if (op.type === 'close') closed = true
     if (op.to) current = op.to
     if (!start) start = current
```

**Comment by BenJamesBen** [comment]
Re-opening as Fix Failed. 

Steps to reproduce:
1. In the `develop` localhost lab, Hugo, cisMale size 40, with Seam Allowance enabled.
2. Observe that the diagonal line is still seen in Part 6 HoodSide.

https://github.com/freesewing/freesewing/commit/fab1e2f8777e75ef950016b594230435752ccf30 introduces a `clean()` method, but it does not fix this bug. The `clean()` function works on curve ops by:
```js
       if (!(op.cp1.sitsRoughlyOn(cur) && op.cp2.sitsRoughlyOn(cur) && op.to.sitsRoughlyOn(cur)))
         ops.push(ops)
```
However, the preceding and problem offset Bezier curves are:
```
134 | 23,-6 : 43,-18 : 70,-25 : 104,-25
135 | 79,0 : 79,0 : 79,0 : 79,0
```
The two Bezier curves are translated to these operations:
```
A: .move(23,-6)
B: .curve(43,-18, 70,-25, 104,-25)
C: .move(79,0)
D: .curve(79,0, 79,0, 79,0)
```

`clean()` drops operation D, but it does not drop operation C (which is what we needed it to do, since it is operation C that causes the diagonal line) If operation C is not dropped, `__joinPaths()` eventually converts the `.move()` to a `.line()`. So, what ends up happening is:
```
A: .move(23,-6)
B: .curve(43,-18, 70,-25, 104,-25)
C: .line(79,0)
```

**Comment by BenJamesBen** [comment]
PR https://github.com/freesewing/freesewing/pull/3056 was re-opened to implement the workaround for this issue.

**Comment by joostdecock** [comment]
Fix implemented in new https://github.com/freesewing/freesewing/commit/5ba6e124690cea6b9ab9b91934268ce558a669f2 and confirmed in the lab.

See #3056 for my reasoning about this fix.
