### ISSUE TITLE
[bug]: freesewing.dev search results for "getid" include nonexistent URL

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3144]
### What seems to be the problem? 🤔

On the freesewing.dev site, the search results for "getid" include the nonexistent URL: https://freesewing.dev/reference/api/part/draft/getid

Missing from the search results is the actual URL: https://freesewing.dev/reference/api/part/getid

![Screenshot 2022-12-05 at 6 24 47 PM](https://user-images.githubusercontent.com/109869956/205793801-428a749d-6315-4622-93da-a9e740b2a732.png)

The same problem can be seen when searching for other terms like "hide", "unhide", "sethidden", and "units".

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
The site uses the Algolia system for search functionality. Whenever the site is re-deployed a new search index is generated. So, it is likely that this issue will no longer be seen the next time the freesewing.dev site is re-deployed. Keep this bug open for now and re-check after the next re-deployment.

**Comment by bobgeorgethe3rd** [comment]
Has the site been recently re-deployed? If so this is still a problem.

**Comment by joostdecock** [comment]
Fixed

**Comment by BenJamesBen** [comment]
I verified that the issue no longer appears on the current freesewing.dev site.
