### ISSUE TITLE
[docs]: Part methods not documented

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3156]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/api/part

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

There are 4 Part methods that are missing in the documentation:
- Part.asProps()
- Part.attr()
- Part.shorthand()
- Part.units()

It is unclear whether these are intentional or if the omissions are accidental. 

There also exists a Utils.units() method, and it might be that the intention was to remove Part.units().

The intention might be to remove Part.shorthand() since we can access the shorthand parts directly in v3.

**Comment by SeaZeeZee** [comment]
@joostdecock Do these part methods also need to be added? (I can write the barebones documentation but I don't know enough code to make these decisions.)

**Comment by SeaZeeZee** [comment]
Merged!
