### ISSUE TITLE
[docs]: Hi update to side fin instructions

### ISSUE THREAD

**Issue by SeaZeeZee** [freesewing/freesewing#3167]
### Where can we see the problem? 🤔

https://freesewing.org/docs/patterns/hi/instructions/

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

I tripped over the instructions for the side fins as they currently only refer to the side fins as topFin and that suggests the top fin of Hi. Since we cant update the pattern itself to clarify until V3 Wouter suggested we update the instructions a little to make it clear the side fins have a bottom part and a top part.

**Comment by joostdecock** [comment]
Fixed by @tangerineshark in https://github.com/freesewing/freesewing/pull/3359/commits/f2043c6eaf3a588f4b780fd794d93002d10ff31d

Closing
