### ISSUE TITLE
[docs]: preRender and postRender hooks pages do not contain Examples

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3194]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/hooks/prerender

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

I do not know whether this is a bug or intentional, but each of the `preRender` and `postRender` hooks documentation pages does not include an Example. All of the other Lifecycle Hooks pages do include an Example. If the omission was unintentional, then Examples should be added to these pages.

https://freesewing.dev/reference/hooks/prerender
https://freesewing.dev/reference/hooks/postrender

**Comment by SeaZeeZee** [comment]
@joostdecock Since Ive been working on some of the missing documentation Ben has requested, do `preRender` and `postRender` need examples?

**Comment by joostdecock** [comment]
There's a `preRender` example on this page: https://freesewing.dev/reference/api/pattern/on

For a `postRender` example, I am not even sure I have a good use case.

**Comment by SeaZeeZee** [comment]
Given what Joost said I think I will close this, we can reopen if things change.
