### ISSUE TITLE
[bug]: When settings.only is set to a string, hideDependencies=true shows after: parts

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3223]
### What seems to be the problem? 🤔

When `settings.only` is set to a string with a single part and `hideDependencies=true`, `after:` parts are incorrectly included. The problem does not occur when `settings.only` is set to an Array containing a single part.

The following script can be used to reproduce the bug:
```js
import { Paco as PatternName } from "@freesewing/paco"
import { cisFemaleAdult34 } from "@freesewing/models"
import { writeFileSync } from 'fs'
import { pluginVersionfreeSvg } from "@freesewing/plugin-versionfree-svg"
import { pluginTheme } from "@freesewing/plugin-theme"

const pattern = new PatternName( {
  measurements: cisFemaleAdult34,
  embed: true,
  complete: false,
  only: 'paco.front',
  //only: ['paco.front'],
})
  .use(pluginTheme)
  .use(pluginVersionfreeSvg)

const svg = pattern.draft().render()
writeFileSync('output.svg', svg)
```

When the script is run with `only: 'paco.front',`, both the Front and Back parts are seen in the SVG. The part confg is `hideDependencies=true` and `after: back`, so the Back part being seen is incorrect.

When the script is changed to `only: ['paco.front'],`, only the Front part is seen, as expected. 

### Design / Plugin / Package 🧐

packages/core

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
Per the discussion in https://discord.com/channels/698854858052075530/698862765053575188/1076219332037726278 , it is intended that `hideDependencies` does not hide `after` parts. Instead, it hides only `from` parts. The documentation was corrected to reflect this, via PR #3563 .

Regardless, the behavior is incorrect and the Paco Back part should not be seen when Only includes only the Paco Front part. (The initial explanation of why the behavior was a bug was incorrect.)

**Comment by bobgeorgethe3rd** [comment]
Can this be closed hideDependencies no longer a thing? And I believe the current hide behaviour is working as intended?

**Comment by BenJamesBen** [comment]
I retested the script, and the problem behavior is no longer seen. One of the v3 changes over the past months must have fixed or eliminated the issue. Closing as Resolved.
