### ISSUE TITLE
[bug]: Examples stacks are no longer stacking

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3273]
### What seems to be the problem? 🤔

The Examples design previously produced a pattern that looked like a face. The individual elements of the face were individual layers, and when stacked together the layers would produce the face. However, something has changed such that the parts no longer stack and are instead spread out.

![Screenshot 2022-12-21 at 10 36 56 AM](https://user-images.githubusercontent.com/109869956/208979013-f21edf38-c974-4104-bbf2-e2c96ab859f3.png)

### Design / Plugin / Package 🧐

designs/examples

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
@eriese ?

**Comment by eriese** [comment]
@joostdecock you think this is a layout issue?

**Comment by eriese** [comment]
What did this used to look like?

**Comment by joostdecock** [comment]
Not accusing anyone. Just wondering if you had an idea of some recent change that could have caused this.

Iy used to stack parts on top of each other and look like a smiley face 😀

**Comment by eriese** [comment]
Ok, what I think is happening here is that these parts are made with the assumption that the bounds of a stack are (0,0) to `bottomRight`, but the bounds of a stack are `topLeft` to `bottomRight`. I'm trying to see if eliminated workarounds for this and it looks to me like we did

**Comment by eriese** [comment]
Never mind, it was an index issue
