### ISSUE TITLE
[docs]: Resolve Part.getId() method documentation confusion

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3282]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/api/part/getid

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

The `Part.getId()` method was removed as a prototype of `Part`, so normally the documentation should also be removed.

The method was moved into part shorthand that can be destructured as `getId`, and this was already added to the `Part.draft()` documentation. However, the `Part.draft()` documentation just refers users back to the `Part.getId()` method documentation.

We should either remove the `Part.getId()` method documentation and improve the `Part.draft()` documentation to explain what `getID` does. Or, keep the `Part.getId()` method documentation but improve it to specify that it isn't actually a prototype method.

Removing the method doc page is the right thing to do, but it will cause confusion since `Part.draft()` isn't set up to explain `getId`. Keeping the method doc page might be the wrong thing to do, but it would better explain `getId` to users, though the existence of the documentation page is likely to confuse users since `getId()` isn't a prototype method.

Finally, we might want to consider re-adding the `Part.getId()` prototype method, the same way that `hide` and `unhide` shorthand and their prototype methods co-exist. That way no documentation changes would be needed.

**Comment by joostdecock** [comment]
@BenJamesBen makes sense to add it (again) as a prototype method. I've done so in #3285

**Comment by BenJamesBen** [comment]
PR https://github.com/freesewing/freesewing/pull/3285 was merged, adding back the `Part.prototype.getId()` method and resolving this bug. Closing.
