### ISSUE TITLE
[feature]: Add a Utils.beamIntersectsCurve() method

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3290]
### What is it that you would like to see happen? 🤔

There is a `Utils.lineIntersectsCurve()` method but no corresponding method for beams. Having such a method would be helpful, so designers wouldn't have to use potentially-problematic hacks like this:
```js
       points.bottomOut = utils.lineIntersectsCurve(
          points.bottom.shift(0,999),
          points.bottom.shift(180,999),
          points.kneeOut,
          points.kneeOutCp2,
          upperCp,
          upperPoint)
``` 

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by bobgeorgethe3rd** [comment]
Added as of #3931
