### ISSUE TITLE
[docs]: Add Howto for title: and order: Frontmatter keys

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3300]
### Where can we see the problem? 🤔

https://freesewing.dev/howtos/editors/frontmatter

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

Add a documentation page to explain how `title:` and `order:` keys can be used on documentation pages.
- `title:` is required. If it is missing then the page won't be generated.
- `order:` is optional. If present its value will be prepended to the `title:` value, and the result will be used to sort pages in ascending order in the navigation.

(Currently, the `linktitle:` key is not parsed on regular markdown documentation pages. Instead, the value eventually just gets assigned the value of `title:`. So, `linktitle:` does not have to be documented.)

**Comment by SeaZeeZee** [comment]
Merged!
