### ISSUE TITLE
[bug]: Development environement (and tutorial) is currently broken

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3338]
### What seems to be the problem? 🤔

The recent changes have caused the current alpha version of v3 to break when installing the development environment.
This is not a great look because it's what we ask people to do during the pattern design tutorial.

Jan from Germany is one of the people who pointed this out. Thanks for reporting it :pray: 

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

Related PR: https://github.com/freesewing/freesewing/pull/3268

**Comment by eriese** [comment]
Not currently seeing this when running `npx @freesewing/new-design@next` for `brian`, `scratch`, or `tutorial`
