### ISSUE TITLE
[bug]: Hugo pattern does not include the neck binding

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3341]
### What seems to be the problem? 🤔

Subject says it all

### Design / Plugin / Package 🧐

designs/hugo

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

**Comment by BenJamesBen** [comment]
There is another Hugo bug https://github.com/freesewing/freesewing/issues/3036 where a notch is missing from the hood rim. I am not sure whether that bug might be related, whether the missing notch might be located on the missing binding?

**Comment by SeaZeeZee** [comment]
I just checked the [instructions on Hugo](https://freesewing.org/docs/patterns/hugo/instructions/#step-8-preparing-a-neckband-and-attaching-the-hood)

Which say the following: 
Cut a cross-wise strip of fabric out of your main fabric, your neck opening + 2cm (3/4 inch) long and triple your neck seam allowance wide.

**Comment by SeaZeeZee** [comment]
I tried to work on this today but I am too eepy (sleepy) so will try to tackle it another day.

**Comment by BenJamesBen** [comment]
> Cut a cross-wise strip of fabric out of your main fabric, your neck opening + 2cm (3/4 inch) long and triple your neck seam allowance wide. 
> Place good sides together on the neck binding piece, then sew a 1cm seam allowance along the short side to make the binding into a circular band. 

- For the neck opening + 2 cm, the extra 2 cm is the seam allowance on both sides. The nett length is just the neck opening.
- "3x neck seam allowance" probably means about 3x 1 cm = 3 cm, but, that width includes 2 cm seam allowance on both sides, so the nett width is about 1 cm. 
- Looking at our 4 curated measurement sets, their neck openings are 501, 436, 401, and 430 mm. The average neck opening is 442 mm so we'll use 44.2 cm as our exemplar length.
- The ratio of 44.2 cm length to 1 cm width is 44.2/1.0 = 44.2. We will use the formula: width = length / 44.2
