### ISSUE TITLE
[bug]: <TITLE> element missing on freesewing.dev web pages

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3388]
### What seems to be the problem? 🤔

`<TITLE>` is a required element for HTML pages. However, all the pages on freesewing.dev and lab.freesewing.dev are missing this tag in the `<HEAD>` section.

This bug also will affect freesewing.org once v3 is deployed. (The bug is currently seen on the localhost version of freesewing.org in the `develop` branch.)

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by eriese** [comment]
I agree page titles are important for a variety of reasons, but can you please help me understand the value of appending the name of the site to every page title?

**Comment by BenJamesBen** [comment]
I wasn't sure about including the site name as part of the title, and i would be fine with removing it.

I included it because I noticed that it was a common practice on other major sites, like Google, Apple, Next.js, etc. I imagine that it might be for SEO-type reasons.

**Comment by BenJamesBen** [comment]
Fixes for this bug were merged. Closing.
