### ISSUE TITLE
[docs]: Establish a place for UI documentation

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3392]
### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

In the December 10, 2022 Contributor Call, we determined that we would establish place in the documentation for UI docs. This was because I was going to put them in the Reference API section under Part Options, but we determined that this section would be strictly for the FreeSewing core. (This was in response to PR #3169 .)

I am filing this bug for tracking purposes. This bug is strictly for the issue of establishing the place for the UI documentation. It is not for the creation of the actual documentation itself.

### Additional context

@joostdecock , I am assigning this bug to you because you said you would be doing this, I believe.

**Comment by eriese** [comment]
If `menu` is the only ui option that the lab expects and uses but we don't feel is core, I think the best route is to keep it in the documentation for core and just make a note that it's not used by core. It's a setting that's pretty important to getting our frontends to work, and I think the majority of people looking at our documentation will be using our frontends, not super bothered with what's core and what's ui-only, and will be confused at having to go find this one thing elsewhere. In contrast I think that most people using core for their own purposes completely separate from our frontend are going to be able to see the note in the docs and be like, "oh, ok, I'll skip that one then"

**Comment by BenJamesBen** [comment]
If we implement the proposed FreeSewing.dev layout in #3386, the UI documentation would go under _For all Developers_ -> _Lab UI documentation_. 

And, as eriese suggested, we can add a section on the Core API in the [Part configuration options page](https://freesewing.dev/reference/api/part/config/options) to mention the `menu` and `hide` properties and to refer readers to the Lab UI documentation for more details. The section would have text or a `<Note>` or `<Warning>` specifically mentioning that "The `menu` and `hide` option properties are not part of the FreeSewing Core API. Instead, they are unofficial extensions to Part options used by the FreeSewing UI, and are included here only for the convenience of those developing patterns for the FreeSewing site."

**Comment by BenJamesBen** [comment]
Closing. The task and contents were merged into Discussion #3988.
