### ISSUE TITLE
[docs]: "GitHub" misspelled in image in How we structure our documentation

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3395]
### Where can we see the problem? 🤔

https://freesewing.dev/guides/docs

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

GitHub is misspelled as "Githbub" on the "How we structure our documentation" page.

The image file is `sites/dev/public/mdx/docs-4a5b95bf80.png`in the repository.

![Screenshot 2023-01-07 at 11 10 18 AM](https://user-images.githubusercontent.com/109869956/211166984-e0bee9b0-796b-4605-acfa-a73681abb5ee.png)

**Comment by SeaZeeZee** [comment]
I am trying to get to the file so I can fix it, but it does not appear to be in the suggested place and I personally don't know where to find it otherwise.

**Comment by BenJamesBen** [comment]
Sorry about that. It looks like the file gets copied over to a new directory during the dev site build or pre-build.

The original files are found in:
`markdown/dev/guides/docs/docs.svg`  
`markdown/dev/guides/docs/docs.png`
