### ISSUE TITLE
[feature]: Find solution for code-tags in opening paragraphs

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3419]
### What is it that you would like to see happen? 🤔

The opening paragraph is extracted from documentation pages to be used in open graph (OG) images.
A paragraph with a tag in it currently breaks this. Like this:

> I am an opening paragraph with an `<svg>` tag in it

We should find a workaround for this, rather than restrict how people can write documentation.

@BenJamesBen suggested escaping the tags with `&lt;` ( < ) and `&gt;` ( > ) or `&lsaquo;` ( ‹ ) and `&rsaquo;` ( › ), which is a great idea.
Another option might be to run the paragraph through some sort of sanitizer.

I'm creating this issue so I/we don't forget about it.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

See comments here: https://github.com/freesewing/freesewing/commit/256242936340ac005852ec3caec89590b0812526#commitcomment-95732920

**Comment by eriese** [comment]
What's responsible for this extraction?

**Comment by joostdecock** [comment]
@eriese The `remarkIntroPlugin` here: https://github.com/freesewing/freesewing/blob/develop/sites/shared/prebuild/md-intro.mjs
