### ISSUE TITLE
[bug]: sites/shared/tlds/index.json is missing

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3436]
### What seems to be the problem? 🤔

In `sites/shared/utils.mjs`, commit 8598bfe49b1b78b7aa65f0b4789fd76031333181 added:
```diff
+import tlds from 'tlds/index.json' assert { type: 'json' }
...
+/** Validates the top level domain (TLT) for an email address */
+export const validateTld = (email) => {
+  const tld = email.split('@').pop().split('.').pop().toLowerCase()
+  if (tlds.indexOf(tld) === -1) return tld
+  else return true
+}

```

However, the `tlds/index.json` file does not exist. 

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
tlds is an nom package that's installed as a dependency: https://www.npmjs.com/package/tlds

It us this package that provides the JSON file, it's not a file that's supposed to be present in our repository.

Does that clarify the matter, or am I misunderstanding what the issue is?

**Comment by BenJamesBen** [comment]
Yes, it was a `yarn kickstart` that i needed to perform to pick up the new package and fix the issue. Closing this bug.
