### ISSUE TITLE
[bug]: Replace placeholder favicon with FreeSewing logo

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3472]
### What seems to be the problem? 🤔

The current `favicon.ico` used on freesewing.dev and lab.freesewing.dev is the Vercel logo. And freesewing.org is currently set up to use the same Vercel logo when v3 gets deployed.

We might want to replace the favicon with our own FreeSewing logo instead, based on `media/logo.svg`. This will need to be done for all our websites.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Done; https://freesewing.dev/

**Comment by BenJamesBen** [comment]
Verified that the https://freesewing.dev/favicon.ico icon is the Skully logo.
