### ISSUE TITLE
[bug]: Compress support.jpg and splash.jpg

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3473]
### What seems to be the problem? 🤔

When I look at my Vercel usage for bandwidth, I see that `support.jpg` is the top bandwidth user. And, `splash.jpg` is also near the top. 

Using the Preview app on my Mac computer, it was a trivial task for me to generate compressed versions of these files. `support.jpg` compressed from 320 KB to 76 KB, and `splash.jpg` compressed from 121 KB to 33 KB. The image quality for the compressed files is not as good. However, I feel that the difference is not noticeable, especially since the images are used only as background images on our websites.

We might want to consider replacing these image files with the compressed versions. The files would need to be replaced in 3 places: `sites/dev`, `sites/org`,and `sites/lab`. However, I am not sure whether the bandwidth savings is worth doing this. It might not be as much of an issue with browser caching.

The compressed versions:
![support compressed](https://user-images.githubusercontent.com/109869956/214403459-84b918c9-cda1-4164-a9da-3ac003e0fc6e.jpg)
![splash compressed](https://user-images.githubusercontent.com/109869956/214403508-1f5c5aaf-b075-4b0f-aaed-0552b8c5f5f3.jpg)

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by raphaelsiz** [comment]
Just to add some additional input: even if compressing the files doesn't save enough bandwidth to be worth the money savings or whatever, I think we should strive to make the site as accessible as possible, and there are probably more people who have bad internet than there are people who need the images to be super high quality. I don't have a bad computer or anything but I can't even see the difference between the images you uploaded and the high-bandwidth versions, so I doubt it would cause any harm to compress them. It would only make a big difference to people with super vision (and high-res screens) or huge screens, and in my opinion making someone look at a lower quality image than they want is worth making the site easier to load for people with bad internet

**Comment by joostdecock** [comment]
This was always a great idea, but unfortunately one for the v2 branch which is frozen.
Please focus on v3 instead.
