### ISSUE TITLE
[bug]: Issue with drafting Bruce

### ISSUE THREAD

**Issue by Psycheblood** [freesewing/freesewing#3494]
### What seems to be the problem? 🤔

Trying to create the Bruce pattern with measurements continue to get this message. What should I do?

Error: Unable to draft part front

Error: We got stuck trying to calculate an optimal tusk length. Please report this.

### Design / Plugin / Package 🧐

designs/bruce

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

I have plugged in the measurements that were taken of the subject that the bruce would be made for does it matter if the size isn't already listed as a selectable option?

**Comment by BenJamesBen** [comment]
Sorry for the issues you experienced. This sort of problem occurs when the pattern encounters measurements it isn't expecting. Historically, other people have seen this issue with Bruce when they've taken measurements incorrectly. For this reason, that is our first suspicion when this error is seen.

Please re-take your subject's measurements and re-try generating the pattern using the new measurements. When taking the measurements, please make sure that you are following the instructions at https://freesewing.org/docs/measurements/ to make sure the measurements are correct.

If you continue to see the error with the new measurements, please let us know and we will investigate the issue further. (I am also pinging the pattern designer @joostdecock so he is aware of your issue.)

**Comment by Psycheblood** [comment]
Thank you, I will try to retake the measurements and see if that helps.

**Comment by joostdecock** [comment]
I'm going to assume this is resolved by fixing the measurements. If not, I'm sure @Psycheblood will let us know :)
