### ISSUE TITLE
[feature]: Merge annotation plugins into one

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3517]
### What is it that you would like to see happen? 🤔

This is a todo from the contributor call #3460

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

Annotation plugins are things that annotate the pattern. Like grainline, cut on fold, and so on.

**Comment by joostdecock** [comment]
@woutervdub volunteered for this on Discord. Assigned to him.

**Comment by bobgeorgethe3rd** [comment]
closed as of #3625
