### ISSUE TITLE
[bug]: Jaeger's options are being overwritten by Bent's sleeves

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3543]
### What seems to be the problem? 🤔

Jaeger's options are incorrectly being overwritten by Bent, even though Jaeger inherits from Bent. 

This is especially seen in the incorrect length of Jaeger's front, back, and side parts. Note how the front extends down only halfway across the pocket.
![Screenshot 2023-02-14 at 1 19 46 PM](https://user-images.githubusercontent.com/109869956/218872036-c3eb20a4-a837-4bca-8cc0-9b594a425827.png)

This is caused because Jaeger's 19% `lengthBonus` option is overwritten with Bent's sleeve 0% `lengthBonus`.

Lines 21, 94, 118, 135, 152, and 171:

# | MESSAGE
-- | --
0 | ⚪️  jaeger.backBase options priority is 4
1 | ⚪️  jaeger.frontBase options priority is 4
2 | ⚪️  jaeger.side options priority is 1
3 | ⚪️  jaeger.collarStand options priority is 2
4 | ⚪️  jaeger.collar options priority is 1
5 | ⚪️  jaeger.underCollar options priority is 1
6 | ⚪️  jaeger.pocket options priority is 2
7 | ⚪️  jaeger.pocketLining options priority is 1
8 | ⚪️  jaeger.chestPocketWelt options priority is 1
9 | ⚪️  jaeger.chestPocketBag options priority is 1
10 | ⚪️  jaeger.topSleeve options priority is 1
11 | ⚪️  jaeger.underSleeve options priority is 1
12 | ⚪️  jaeger.innerPocketBag options priority is 1
13 | ⚪️  jaeger.innerPocketWelt options priority is 1
14 | 🔵  centerBackDart option loaded from part jaeger.backBase
15 | 🔵  hipsEase option loaded from part jaeger.backBase
16 | 🔵  waistEase option loaded from part jaeger.backBase
17 | 🔵  rollLineCollarHeight option loaded from part jaeger.backBase
18 | 🔵  reduceWaistStandardFraction option loaded from part jaeger.backBase
19 | 🔵  reduceWaistDartFraction option loaded from part jaeger.backBase
20 | 🔵  reduceHipsStandardFraction option loaded from part jaeger.backBase
21 | 🔵  lengthBonus option loaded from part jaeger.backBase
22 | 🔵  brianFitSleeve option loaded from part brian.base
23 | 🔵  brianFitCollar option loaded from part brian.base
24 | 🔵  collarFactor option loaded from part brian.base
25 | 🔵  bicepsEase option loaded from part brian.base
26 | 🔵  chestEase option loaded from part brian.base
27 | 🔵  collarEase option loaded from part brian.base
28 | 🔵  cuffEase option loaded from part brian.base
29 | 🔵  draftForHighBust option loaded from part brian.base
30 | 🔵  shoulderEase option loaded from part brian.base
31 | 🔵  s3Collar option loaded from part brian.base
32 | 🔵  s3Armhole option loaded from part brian.base
33 | 🔵  acrossBackFactor option loaded from part brian.base
34 | 🔵  armholeDepthFactor option loaded from part brian.base
35 | 🔵  backNeckCutout option loaded from part brian.base
36 | 🔵  frontArmholeDeeper option loaded from part brian.base
37 | 🔵  shoulderSlopeReduction option loaded from part brian.base
38 | 🟠  hips measurement is required in jaeger.backBase
39 | 🟠  waist measurement is required in jaeger.backBase
40 | 🟠  biceps measurement is required in brian.base
41 | 🟠  chest measurement is required in brian.base
42 | 🟠  hpsToWaistBack measurement is required in brian.base
43 | 🟠  neck measurement is required in brian.base
44 | 🟠  shoulderToShoulder measurement is required in brian.base
45 | 🟠  shoulderSlope measurement is required in brian.base
46 | 🟠  waistToHips measurement is required in brian.base
47 | 🟡  highBust measurement is optional in brian.base
48 | 🔵  centerFrontHemDrop option loaded from part jaeger.frontBase
49 | 🔵  frontPocketPlacement option loaded from part jaeger.frontBase
50 | 🔵  frontPocketWidth option loaded from part jaeger.frontBase
51 | 🔵  frontPocketDepth option loaded from part jaeger.frontBase
52 | 🔵  frontPocketRadius option loaded from part jaeger.frontBase
53 | 🔵  frontDartPlacement option loaded from part jaeger.frontBase
54 | 🔵  sideFrontPlacement option loaded from part jaeger.frontBase
55 | 🔵  backVent option loaded from part jaeger.side
56 | 🔵  backVentLength option loaded from part jaeger.side
57 | 🔵  collarSpread option loaded from part jaeger.collarStand
58 | 🔵  frontOverlap option loaded from part jaeger.front
59 | 🔵  innerPocketPlacement option loaded from part jaeger.front
60 | 🔵  innerPocketWidth option loaded from part jaeger.front
61 | 🔵  innerPocketDepth option loaded from part jaeger.front
62 | 🔵  innerPocketWeltHeight option loaded from part jaeger.front
63 | 🔵  frontCutawayAngle option loaded from part jaeger.front
64 | 🔵  frontCutawayStart option loaded from part jaeger.front
65 | 🔵  frontCutawayEnd option loaded from part jaeger.front
66 | 🔵  hemRadius option loaded from part jaeger.front
67 | 🔵  chestPocketDepth option loaded from part jaeger.front
68 | 🔵  chestPocketWidth option loaded from part jaeger.front
69 | 🔵  chestPocketPlacement option loaded from part jaeger.front
70 | 🔵  chestPocketAngle option loaded from part jaeger.front
71 | 🔵  chestPocketWeltSize option loaded from part jaeger.front
72 | 🔵  lapelStart option loaded from part jaeger.front
73 | 🔵  collarHeight option loaded from part jaeger.front
74 | 🔵  collarNotchDepth option loaded from part jaeger.front
75 | 🔵  collarNotchAngle option loaded from part jaeger.front
76 | 🔵  collarNotchReturn option loaded from part jaeger.front
77 | 🔵  chestShaping option loaded from part jaeger.front
78 | 🔵  buttons option loaded from part jaeger.front
79 | 🔵  buttonLength option loaded from part jaeger.front
80 | 🔵  chestShapingMax option loaded from part jaeger.front
81 | 🔵  lapelReduction option loaded from part jaeger.front
82 | 🔵  collarRoll option loaded from part jaeger.collar
83 | 🔵  pocketFoldover option loaded from part jaeger.pocket
84 | 🔵  sleeveVentLength option loaded from part jaeger.topSleeve
85 | 🔵  sleeveVentWidth option loaded from part jaeger.topSleeve
86 | 🟣  brianFitSleeve option overwritten by bent.sleeve
87 | 🟣  brianFitCollar option overwritten by bent.sleeve
88 | 🟣  collarFactor option overwritten by bent.sleeve
89 | 🟣  chestEase option overwritten by bent.sleeve
90 | 🟣  collarEase option overwritten by bent.sleeve
91 | 🟣  bicepsEase option overwritten by bent.sleeve
92 | 🟣  cuffEase option overwritten by bent.sleeve
93 | 🟣  shoulderEase option overwritten by bent.sleeve
94 | 🟣  lengthBonus option overwritten by bent.sleeve
95 | 🔵  sleeveLengthBonus option loaded from part bent.sleeve
96 | 🔵  sleeveBend option loaded from part bent.sleeve
97 | 🟣  draftForHighBust option overwritten by bent.sleeve
98 | 🟣  s3Collar option overwritten by bent.sleeve
99 | 🟣  s3Armhole option overwritten by bent.sleeve
100 | 🟣  acrossBackFactor option overwritten by bent.sleeve
101 | 🟣  armholeDepthFactor option overwritten by bent.sleeve
102 | 🟣  backNeckCutout option overwritten by bent.sleeve
103 | 🟣  frontArmholeDeeper option overwritten by bent.sleeve
104 | 🟣  shoulderSlopeReduction option overwritten by bent.sleeve
105 | 🔵  sleevecapHeight option loaded from part bent.sleeve
106 | 🔵  sleevecapEase option loaded from part bent.sleeve
107 | 🟠  shoulderToElbow measurement is required in bent.sleeve
108 | 🟠  shoulderToWrist measurement is required in bent.sleeve
109 | 🟠  wrist measurement is required in bent.sleeve
110 | 🟣  brianFitSleeve option overwritten by bent.sleeve
111 | 🟣  brianFitCollar option overwritten by bent.sleeve
112 | 🟣  collarFactor option overwritten by bent.sleeve
113 | 🟣  chestEase option overwritten by bent.sleeve
114 | 🟣  collarEase option overwritten by bent.sleeve
115 | 🟣  bicepsEase option overwritten by bent.sleeve
116 | 🟣  cuffEase option overwritten by bent.sleeve
117 | 🟣  shoulderEase option overwritten by bent.sleeve
118 | 🟣  lengthBonus option overwritten by bent.sleeve
119 | 🟣  draftForHighBust option overwritten by bent.sleeve
120 | 🟣  s3Collar option overwritten by bent.sleeve
121 | 🟣  s3Armhole option overwritten by bent.sleeve
122 | 🟣  acrossBackFactor option overwritten by bent.sleeve
123 | 🟣  armholeDepthFactor option overwritten by bent.sleeve
124 | 🟣  backNeckCutout option overwritten by bent.sleeve
125 | 🟣  frontArmholeDeeper option overwritten by bent.sleeve
126 | 🟣  shoulderSlopeReduction option overwritten by bent.sleeve
127 | 🟣  brianFitSleeve option overwritten by bent.sleeve
128 | 🟣  brianFitCollar option overwritten by bent.sleeve
129 | 🟣  collarFactor option overwritten by bent.sleeve
130 | 🟣  chestEase option overwritten by bent.sleeve
131 | 🟣  collarEase option overwritten by bent.sleeve
132 | 🟣  bicepsEase option overwritten by bent.sleeve
133 | 🟣  cuffEase option overwritten by bent.sleeve
134 | 🟣  shoulderEase option overwritten by bent.sleeve
135 | 🟣  lengthBonus option overwritten by bent.sleeve
136 | 🟣  draftForHighBust option overwritten by bent.sleeve
137 | 🟣  s3Collar option overwritten by bent.sleeve
138 | 🟣  s3Armhole option overwritten by bent.sleeve
139 | 🟣  acrossBackFactor option overwritten by bent.sleeve
140 | 🟣  armholeDepthFactor option overwritten by bent.sleeve
141 | 🟣  backNeckCutout option overwritten by bent.sleeve
142 | 🟣  frontArmholeDeeper option overwritten by bent.sleeve
143 | 🟣  shoulderSlopeReduction option overwritten by bent.sleeve
144 | 🟣  brianFitSleeve option overwritten by bent.sleeve
145 | 🟣  brianFitCollar option overwritten by bent.sleeve
146 | 🟣  collarFactor option overwritten by bent.sleeve
147 | 🟣  chestEase option overwritten by bent.sleeve
148 | 🟣  collarEase option overwritten by bent.sleeve
149 | 🟣  bicepsEase option overwritten by bent.sleeve
150 | 🟣  cuffEase option overwritten by bent.sleeve
151 | 🟣  shoulderEase option overwritten by bent.sleeve
152 | 🟣  lengthBonus option overwritten by bent.sleeve
153 | 🟣  draftForHighBust option overwritten by bent.sleeve
154 | 🟣  s3Collar option overwritten by bent.sleeve
155 | 🟣  s3Armhole option overwritten by bent.sleeve
156 | 🟣  acrossBackFactor option overwritten by bent.sleeve
157 | 🟣  armholeDepthFactor option overwritten by bent.sleeve
158 | 🟣  backNeckCutout option overwritten by bent.sleeve
159 | 🟣  frontArmholeDeeper option overwritten by bent.sleeve
160 | 🟣  shoulderSlopeReduction option overwritten by bent.sleeve
161 | 🔌  Resolved @freesewing/plugin-bundle plugin in brian.base
162 | 🔌  Resolved @freesewing/plugin-bust conditional plugin in brian.base
163 | 🟣  brianFitSleeve option overwritten by bent.sleeve
164 | 🟣  brianFitCollar option overwritten by bent.sleeve
165 | 🟣  collarFactor option overwritten by bent.sleeve
166 | 🟣  chestEase option overwritten by bent.sleeve
167 | 🟣  collarEase option overwritten by bent.sleeve
168 | 🟣  bicepsEase option overwritten by bent.sleeve
169 | 🟣  cuffEase option overwritten by bent.sleeve
170 | 🟣  shoulderEase option overwritten by bent.sleeve
171 | 🟣  lengthBonus option overwritten by bent.sleeve
172 | 🟣  draftForHighBust option overwritten by bent.sleeve
173 | 🟣  s3Collar option overwritten by bent.sleeve
174 | 🟣  s3Armhole option overwritten by bent.sleeve
175 | 🟣  acrossBackFactor option overwritten by bent.sleeve
176 | 🟣  armholeDepthFactor option overwritten by bent.sleeve
177 | 🟣  backNeckCutout option overwritten by bent.sleeve
178 | 🟣  frontArmholeDeeper option overwritten by bent.sleeve
179 | 🟣  shoulderSlopeReduction option overwritten by bent.sleeve
180 | Running preDraft hooks

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

Pattern initialized. Draft order is: brian.base, brian.back, jaeger.backBase, brian.front, jaeger.frontBase, jaeger.side, jaeger.back, jaeger.front, jaeger.collarStand, jaeger.pocket, jaeger.chestPocketWelt, jaeger.chestPocketBag, jaeger.innerPocketBag, jaeger.innerPocketWelt, bent.sleeve, jaeger.collar, jaeger.underCollar, jaeger.pocketLining, bent.topSleeve, jaeger.topSleeve, bent.underSleeve, jaeger.underSleeve

There was a previous bug #2881 causing the length issue, but that bug was fixed. This is a different bug with the same symptom.

**Comment by BenJamesBen** [comment]
The problem might be worked around by editing Bent's `sleeve.mjs`. I suspect that a lot of the options listed in that file are not actually used directly by Bent. instead, they seem to be simply copied from Brian. If this is the case, then the options are superfluous and can be removed from Bent's source code.

**Comment by eriese** [comment]
I believe this should be fixed by #3564
