### ISSUE TITLE
[docs] update docs to use 'Measurements Sets' throughout

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3575]
In v2, and in earlier versions of v3 we used **models** or **people** to refer to, what in the end are a set of measurements.
For the v3 release, we will simplify that to use **Measurements Sets** to refer to, you know, sets of measurements.

This [has been implemented in backend and the upcoming org site](https://github.com/freesewing/freesewing/pull/3573), but the documentation needs to be updated to reflect these changes.

Essentially, every instance of the following needs relpacing:

- **person** or **model** must become **measurements set** (note: plural measurements)
- **people** or **models** must become **measurements sets** (note: double plural)

In addition, all references to **with breasts** or **without breasts** have to go.

This is something anybody can work on, and a good candidate for those not sure what they can contribute :)

**Comment by SeaZeeZee** [comment]
We use Person to refer to measurement sets that people have saved, does that also need changing?

**Comment by SeaZeeZee** [comment]
Comment for my own notetaking since this is a lot of changes to keep track of: 

All people instances besides code in the markdown folder are replaced. Breast language not tackled yet

**Comment by joostdecock** [comment]
Done
