### ISSUE TITLE
Simon shirt pattern re-create leads to a crash

### ISSUE THREAD

**Issue by csantosumich** [freesewing/freesewing#3576]
Hey, so I have a Simon shirt pattern, but when I try to recreate the legacy pattern, the site crashes.  What to do?

**Comment by BenJamesBen** [comment]
Sorry that you are experiencing this issue. 

How are you trying to re-create the Simon pattern? What steps are you performing? (Or, how can we re-create the problem so we can see what might be happening?)

**Comment by csantosumich** [comment]
Hi Ben, many many thanks for looking into this, I've tried to recreate the bug but it seems to be resolved! The error message was something along the lines of "this (Simon pattern) was created with a prior version" of the pattern and it queried whether I wanted to migrate it to the current version (at which point it failed and pointed me to Github).  This is no longer happening as of now.

**Comment by BenJamesBen** [comment]
I am glad that your issue is now resolved. I'm not sure what might have happened-- perhaps some temporary server problem. Sorry again for the inconvenience it caused you.

I am closing this bug now, but please re-open it if the issue re-appears.
