### ISSUE TITLE
[bug]: Option sub-groups are not sorted into parent groups.

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#3594]
### What seems to be the problem? 🤔

Sub-groups such as `advanced.sleevecap` are not being placed into their parent group. 

Example:
![image](https://user-images.githubusercontent.com/16866285/222921825-495a70f0-41c6-49ca-b699-b5138807d22f.png)

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
I don't understand all the changes that were made, but I believe that the Design Option menu ordering in `sites/shared/utils.mjs` was working correctly previously. Things started changing via c016b0fbcd59cbe918770f9374a3c2446899ad08 when an intermediate behavior started where options were listed flat and not sorted into menus. Then, I believe that the current behavior started after ecc7cfdacb6b9238637170dacb9cff3a30977a93.

I note that the following code change reverting `sites/shared/utils.mjs` seems to fix the issue (but again, I don't understand why the previous changes were made, so I don't know whether the revert is appropriate):
```diff
@@ -170,7 +170,8 @@ export const optionsMenuStructure = (options) => {
   // Fixme: One day we should sort this based on the translation
   for (const option of orderBy(sorted, ['menu', 'name'], ['asc'])) {
     if (typeof option === 'object') {
-      if (option.menu) set(menu, [option.menu, option.name], optionType(option))
+      if (option.menu)
+        set(menu, option.menu ? `${option.menu}.${option.name}` : option.name, optionType(option))
       else if (typeof option.menu === 'undefined') {
         console.log(
           `Warning: Option ${option.name} does not have a menu config. ` +
```

**Comment by bobgeorgethe3rd** [comment]
Can confirm this fix does appear to work in both test & design pages. Maybe best to PR it and note the changes that had occured like above.

**Comment by BenJamesBen** [comment]
I think I now understand why the previous changes were made and how they led to this bug occurring. `utils.mjs` should not be reverted back to the original code, even if it does result in the behavior being "fixed".

Instead, I believe that either of the below code change style variations might be better fixes. 

In `sites/shared/utils.mjs`:
```diff
@@ -190 +190,2 @@ export const optionsMenuStructure = (options) => {
-      if (option.menu) set(menu, [option.menu, option.name], optionType(option))
+      if (option.menu)
+        set(menu, option.menu + '.' + option.name, optionType(option))
```
or:
```diff
@@ -190 +190,2 @@ export const optionsMenuStructure = (options) => {
-      if (option.menu) set(menu, [option.menu, option.name], optionType(option))
+      if (option.menu)
+        set(menu, `${option.menu}.${option.name}`, optionType(option))
```

**Comment by bobgeorgethe3rd** [comment]
I'm trying out the 2nd option. I have noticed something interesting with this. if an option is the same name as a group then the option does not appear.
For instance if you have an option called options.backPockets and an option group called backPockets the option backPockets will not appear. The work around is to simply re-name the option so in this case simply optioins.backPocketsBool (it's a option in this case) but I thought it was worth mentioning.
