### ISSUE TITLE
Discuss: Revert on the use of breast/no-breasts when we mean men/women while respecting that gender is a fluid concept

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#361]
On freesewing.org, we refer to people either having breasts or no breasts when we mean men/women.
We do this because we want to be inclusive. Men/Women comes with a whole lot of bagage/expectations whereas breasts/no-breasts just says what it comes down to: do you have breasts or not?

While that is a good thing, the reality is that for the vast majority of people, this phrasing is confusing. To the point where we should perhaps try to think of a way to make things more intuitive without alienating people whose gender doesn't fit neatly into one of these boxes.

My personal preference is:

 - menswear
 - womenswear

For the following reasons:

 - We already use this to sort patterns into categories
 - (wo)menswear does not strictly imply gender. It's merely a way to categorize garments (as in, womenswear on the first floor, menswear in the basement => This is clearly just a way to organize things)
 - I think everyone can agree that just because you're a woman it doesn't mean you can't wear menswear, and vice versa

**Proposal**

To rename things on the website so that we consistently use the terms menswear/womenswear when we try to describe either a certain garment category, or whether a garment was designed to accommodate breasts or not.

**Comment by Slylele** [comment]
yes... it is complicated...
Mainly if you look at this distinction on the standard sizing tables... Here we can see that Men/Women is a real sexual morphology consideration as for a same measure, the size won't be the same...
From my point of view menswear/womenswear is not really better than men/women because for a hoodie (for example); it's neither menswear or womenswear...
I'm going to think about it but it's not simple :D

**Comment by stoffsuchti** [comment]
I understand the trouble it can do, when you use gender inclusive terms like „with breasts/without breasts“ but for me it was always a symbol that FreeSewing is really really strong on this inclusive path, finds ways to overcome the term used by the (fast) fashion industry und being really inclusive, modern, and postgender. So i would love, when the term with breasts/without breast can stay on FreeSewing.org. But I agree, that a bit more and esay accessible explanation about that term ist needed for those not understandig it at a glance.

**Comment by joostdecock** [comment]
I think things have gotten more complicated since we started offering standard sizes.
When adding people, I think it still makes sense:

![Screenshot_2020-04-12 Add Person](https://user-images.githubusercontent.com/1708494/79067223-271c0680-7cbe-11ea-8ee5-77300b35916e.png)

But in the standard sizes, it is really confusing:

![Screenshot_2020-04-12 Choose a person](https://user-images.githubusercontent.com/1708494/79067234-30a56e80-7cbe-11ea-92d2-5749fbdd049a.png)

If we were to update, I think it would make sizes a lot more intuitive:

![Screenshot_2020-04-12 Choose a person(1)](https://user-images.githubusercontent.com/1708494/79067279-80843580-7cbe-11ea-89eb-0e281084b391.png)

While this still seems fine to me (but what do I know) :

![Screenshot_2020-04-12 Add Person(1)](https://user-images.githubusercontent.com/1708494/79067294-9560c900-7cbe-11ea-9dfa-d79bf6f03af2.png)

**Comment by stoffsuchti** [comment]
I really like the elegance of the Term #withbreasts / #withoutbreasts. I would be really sad if we sacrifice them. 

I would rather call also the standard sizes like that, and a an explanation/translation for persons not fluent to gender inclusive language and term. Like you add al little i in a circle at the end of that term #withbreasts and when the user clicks on she/he can see the explanation, what the terms mean at the standard sizes and in the made to mesure area when your logged in.

**Comment by joostdecock** [comment]
> I would be really sad if we sacrifice them.

Well I for one am not in the business of making @stoffsuchti sad :)

I think that terminology is fine when referring to people. It's just confusing in the context of standard sizes. Could we perhaps use icons to side-step having to 'name' those?

![heshe](https://user-images.githubusercontent.com/1708494/79068006-dc9d8880-7cc3-11ea-930d-3b5eff7709dd.png)

Would this be clear to everyone?

**Comment by CatherineH** [comment]
I started making a pattern for baby clothes. Is that menswear, womenswear or accessories?

**Comment by joostdecock** [comment]
> I started making a pattern for baby clothes. Is that menswear, womenswear or accessories?

We can add a category. That's not a problem :)

**Comment by stoffsuchti** [comment]
> > I would be really sad if we sacrifice them.
> 
> Well I for one am not in the business of making @stoffsuchti sad :)
> 
> I think that terminology is fine when referring to people. It's just confusing in the context of standard sizes. Could we perhaps use icons to side-step having to 'name' those?
> 
> ![heshe](https://user-images.githubusercontent.com/1708494/79068006-dc9d8880-7cc3-11ea-930d-3b5eff7709dd.png)
> 
> Would this be clear to everyone?

Yaeh it would be clear, but the symbol are a bit sex centred someperson can argue. What are the main difference in our standard size tables? Total body length, breasts / no breasts and the ratio of chest with, waist with and hip with? The Symbols we use should illustrate that main differences and not focus on iconising primary sexual organs. In this way I hope it should be intuitive to the most humans and it is also focussed on body shapes not on sexual attributes. 😃👍

**Comment by CatherineH** [comment]
little off topic, but as an American I already find the "standard sizes" confusing.

**Comment by joostdecock** [comment]
Could you clarify why @CatherineH ?

 - Is it because you expect **S M L XL** and so on?
 - Is the word **standard** confusing?
 - Some other reason?

**Comment by CatherineH** [comment]
I would expect S M L etc or the US dress size standard (0, 2, 4, 6, etc). I can walk into an American or Canadian clothing shop and know what size to pick up in those sizing standards, but not what freesewing uses. The UK uses a different dress size standard too.

**Comment by joostdecock** [comment]
I'll try to make a mockup to see if we can use some sort of symbolism and make the sizes more straight-forward.

**Comment by Slylele** [comment]
I think that for size table we can just add an explanation that these sizes come from Standard industry and then is still relative to gender... Just set 
- "With breasts (based on women standard sizes)"
- "Without breasts (based on men standards sizes)"
Then we keep this notion on the size table (as it comes from existing tables actually based on sexual distinction), but everywhere else on the web site we could keep breasts/wo breasts...

**Comment by stoffsuchti** [comment]
@Slylele yay your suggestion ist great. 😍👍

**Comment by bendybytch** [comment]
I’m going to be blunt. If this reversion happens, it will mean I can’t use the site anymore. Dysphoria is real and it is deadly- look up the suicide rates among trans people, then double it to account for all of the closeted or uncategorizable people. I have breasts, but that does not mean anything about my gender. 
I also don’t think that breasts/no breasts is confusing anyone. Declaring that people will be ~confused~ and must be protected is a classic TERF strategy, and it’s utter bull. Nobody is confused; look down at your chest and take inventory, then click the button. Nothing could be simpler. 
Again: if this is changed back to gendered terms, a lot of people who came to freesewing SPECIFICALLY BECAUSE OF THIS FEATURE are going to leave, feeling hurt and betrayed. Let me tell you, we have plenty of that in our lives already. Please don’t contribute to that.

**Comment by AlfaLyr** [comment]
This is not simple. While yeah, I agree that breasts/not breasts is not confusing, there are a lot of cases to consider, not only trans people. The thing is that the standard sizes separate men and women not only by breasts/no breasts, but the proportions are different. If you categorize sizes into breasts/no breasts you are leaving out, for example, as someone mention, women that went through a mastectomy and have no breasts, but still have proportions more according to the "with breasts" set of standard sizes. It's not possible to include everyone in a standard, because we are not standard. For that, I think the icons can be a good option, because they show the actual difference between the two different sets of standard sizes. And, for creating a new person in the website, maybe there's no need to separate, people can just leave out the with-breasts kind of measurements if they are going to only make patterns that don't require them, or they can fill them even if they don't have breasts to make clothes that require them.

**Comment by joostdecock** [comment]
@bendybytch I should clarify that our concern is with how we label our range of standard sizes.
The people who go through the trouble of adding their measurements to the site are more invested, more likely to read the explanations, and as you say, you know your own body.

The situation is slightly different for the casual visitor who just wants a pattern. For example, we put out a face mask pattern, that drew in a lot of first-time visitors to the site. Now they can have the pattern in "with breasts" and "without breasts" sizes and they are (understandably) confused.

I think that confusion is valid, and I think that phrasing "with or without breasts" in the context of *standard sizes* is a poor fit. But I'd like to underscore that we're not talking about people, we're talking about sizes.

I initially thought that perhaps *menswear*/*womenswear* could be fine to talk about sizes. I understand now that it's not, and I guess that just goes to show that I don't really know.
But that doesn't mean that there's not a UX problem that needs solving, so that's what I'd like to do.

I've made these icons to help tell the difference between size ranges:

![icons](https://user-images.githubusercontent.com/1708494/79075473-6284f800-7cf3-11ea-8654-b5133979ca49.png)

The idea being that if you see a size range with these icons next to it, it's somewhat self-explanatory.

Curious to hear whether such a solution would improve the UI and ensure all people feel welcome.

**Comment by Slylele** [comment]
From my point of view, if the modification is **only** for both pages "sizing tables" & on pattern creation (when asked to choose people or standard size), it could be ok to use Menswear/Womenswear.
Maybe it could be useful to add a (i) next to "standard sizes" to explain that it is based on commercial standard sizes... and refers to  the dedicated pages...

**Comment by joostdecock** [comment]
Below is a preview of the new UI:

![Screenshot_2020-04-13 Choose a size(1)](https://user-images.githubusercontent.com/1708494/79114831-93613d80-7d84-11ea-916d-f976d175da3e.png)

**Comment by jefferypink** [comment]
I like the current terminology. Whatever direction is taken, it should be possible to make both "menswear" and "womenswear" using the same model measurements without the need to gender the model themselves. I don't want to have to pick between menswear and womenswear when entering in my measurements, and I'd like to be able to choose the whole range of patterns with my measurements. In standard sewing patterns, I can modify the bust of a dress to fit my male body, but the sizing is different around the shoulders and sometimes waist. With freesewing based on my measurements, you are already better at being gender inclusive.

**Comment by joostdecock** [comment]
The new UI has been deployed. Thanks everyone for your inputs ♥️
