### ISSUE TITLE
feat: add a design system to freesewing.org

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing#362]
to make it easier to make design decisions, let's add a very simple design system or find the system that's already in use to make improving the UX and UI a little bit more straight forward.

We use material UI ad a DS, but we do also a lot of custom things and have custom layouts. It would be nice to have everything defined a bit.

**Comment by joostdecock** [comment]
This is a great initiative :)
Some things that are perhaps not obvious to the casual observer:

 - We use [material-ui](https://material-ui.com/), but not really the layout components. Really just form elements, buttons and so on
 - We use colors from [open-color](https://yeun.github.io/open-color/) Not all of them obviously, but if you need a color or gray tint, this is the place to be. We also have the sass plugin in the site, so you can import it and then use something like `$oc-gray-6`
 - Material-ui ships with all the material icons, [they are documented here](https://www.material.io/resources/icons/?style=baseline)

**Comment by joostdecock** [comment]
While this is a good idea, I don't think we have the bandwidth to work on this. Since it's stale, I'm closing it.
