### ISSUE TITLE
Placement of notches on carlton

### ISSUE THREAD

**Issue by SennettTailor** [freesewing/freesewing#373]
Hope all are keeping well. Being locked at home has definitely given the opportunity (or push) to try one of your patterns. I did the first trial with the Carlton after the correction of the tail width. I have few comments and questions:

I assume in the attached pattern template: the No.1 and No.2 markings are actually in order to fit correctly the front & back arm pieces. Cant see the corresponding points on the arm pieces. I tried to match the point where the front and back arm pieces join (seam) but can’t. I assume the markings are missing on the pattern (on the arm pieces).
I assume the marking on front bodice No.3 is where the “Back” and “Tail” piece of pattern meets? If this is correct, might be an idea to put a marking on the “Belt” piece (in middle)?
Could not figure out where the corresponding point of the No.4 marker on pattern is (unless it is just a regular point to match the lining?!)
I assume the marker No.5 is for collar? – there is no corresponding point on the “Collar” (and/or “Collar Stand”)
Again, cant simply thank enough to you and the community for your amazing work.
I have taken notes/pictures on first round – will work on a more pleasing visual ‘instructions” along the 2nd trial and provide a copy for your website.
<img width="1595" alt="Screenshot 2020-04-20 at 12 05 32" src="https://user-images.githubusercontent.com/55401821/79716332-f153cf00-8308-11ea-8eb6-6b1bfe8d26a2.png">

**Comment by joostdecock** [comment]
Thank you for this detailed report. 
> I assume in the attached pattern template: the No.1 and No.2 markings are actually in order to fit correctly the front & back arm pieces. Cant see the corresponding points on the arm pieces. I tried to match the point where the front and back arm pieces join (seam) but can’t. I assume the markings are missing on the pattern (on the arm pieces).

Those notches on the armhole are a holdover from a single part sleeve, and don't make a lot of sense with a 2-part sleeve. So I've instead notched the shoulder point and top of the (upper) sleeve so these can be matched when setting the sleeve.

> I assume the marking on front bodice No.3 is where the “Back” and “Tail” piece of pattern meets? If this is correct, might be an idea to put a marking on the “Belt” piece (in middle)?

Yes. The notch indicates the waistline, but it's also the middle of the belt, so I've added a notch there as you suggested.

> Could not figure out where the corresponding point of the No.4 marker on pattern is (unless it is just a regular point to match the lining?!)

It makes the seat line (fullest part, it's straight down from there). It's not so much a construction notch, but more to help you visualize where the pocket falls relative to your body.
Perhaps we should come up with a new style to differentiate between notches for construction and more helper-like visual aids.

> I assume the marker No.5 is for collar? – there is no corresponding point on the “Collar” (and/or “Collar Stand”)

That notch marks the center front.

**Comment by joostdecock** [comment]
Oh, and thank you for your kind words. They mean a lot to me.
