### ISSUE TITLE
Create showcase from this content

### ISSUE THREAD

**Issue by fast77** [freesewing/freesewing#3736]
Hi there

I have two fresh Simon shirts for you to add to the showcase please, a blue and brown one. 

The pattern of the blue fabric prompted me to use eight buttons in the front instead of just seven. I was afraid it would look odd otherwise if the buttons were on different parts of the design. Even though this is my fifth Simon shirt, I made the super stupid mistake of sewing the buttonholes on the wrong side. Luckily, I was able to save it by sewing another buttonhole placket over it. Positive side result: the buttonhole placket is now nice and stiff. Delighted.

The brown shirt was easier to handle with the geometric fabric design. No stupid mistakes here. Pleased as well.

Thanks for everything - Freesewing is awesome.

![blue_Simon6052](https://user-images.githubusercontent.com/93778943/229302339-a7cfbd30-6996-418d-a69f-ca13f06a4576.jpeg)
![blue_Simon6060](https://user-images.githubusercontent.com/93778943/229302341-8cd1a4c8-6e45-480f-8e30-13bb8f444780.jpeg)
![blue_Simon6066](https://user-images.githubusercontent.com/93778943/229302345-a1950acc-f181-43c3-87c4-28786c942231.jpeg)
![blue_Simon6070](https://user-images.githubusercontent.com/93778943/229302346-1ddacbd0-0b91-4e1a-a079-3c5ee734de09.jpeg)
![blue_Simon6081](https://user-images.githubusercontent.com/93778943/229302347-556746e8-0db4-4ffb-842f-9d9d04ec62bf.jpeg)
![blue_Simon6083](https://user-images.githubusercontent.com/93778943/229302348-9520e690-b0c2-4082-898b-c64879598b61.jpeg)

![brown_Simon6009](https://user-images.githubusercontent.com/93778943/229302401-81d38849-8f3d-4910-8cfb-7f1159cc730b.jpeg)
![brown_Simon6025](https://user-images.githubusercontent.com/93778943/229302404-44ff0305-053a-4362-93cf-a2517a889657.jpeg)
![brown_Simon6075](https://user-images.githubusercontent.com/93778943/229302405-03be6d3e-bbcb-432e-a876-21ea7f208edd.jpeg)
![brown_Simon6076](https://user-images.githubusercontent.com/93778943/229302406-8db5b004-8e63-48f7-89d8-6edc6ba92e41.jpeg)
![brown_Simon6077](https://user-images.githubusercontent.com/93778943/229302407-6f8e32a7-76ae-4d2e-a658-3c09a83cc440.jpeg)
![brown_Simon6080](https://user-images.githubusercontent.com/93778943/229302408-c8f18b3a-964c-4640-8823-b76827afa24a.jpeg)
![brown_Simon6085](https://user-images.githubusercontent.com/93778943/229302410-2f8d1e6a-a6f3-48d5-910b-c36c33a85cea.jpeg)

**Comment by joostdecock** [comment]
Great work @fast77 :heart_eyes: 

@tangerineshark I've assigned this to you, but don't hesitate to bounce it back ;)

**Comment by tangerineshark** [comment]
On it! These shirts are awesome and these pics are amazing, @fast77 ! Is there any way you'd like to be credited in the Showcases (name, social media handle, etc.)?

**Comment by fast77** [comment]
Dear Karen
Thank you for appreciating. And no, please no crediting. 
Warm regards, Felix

**Comment by tangerineshark** [comment]
Sorry for being a slowster! This is added to Strapi now, and will be available the next time Showcaseposts are updated!
