### ISSUE TITLE
[bug]: (ursula) Graphic elements are not controlled by complete setting

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3747]
### What seems to be the problem? 🤔

The `title`, `miniscale`, and `grainline` macros are not inside the `if (complete)` block for Ursula's Front and Back parts. They should be.
![Screenshot 2023-04-02 at 10 08 35 PM](https://user-images.githubusercontent.com/109869956/229416585-93fadda0-0c06-4965-9ad8-1952aaf0b135.png)

Additionally, the `paperless` dimensions are also not inside the `if (complete)` block. Pending confirmation about how `paperless` and `complete` are supposed to interact, the dimensions also should be moved inside the block.

### Design / Plugin / Package 🧐

designs/ursula

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by bobgeorgethe3rd** [comment]
So we are planning to overhaul the macros so they call complete individually. This means this issue will need to be address after this or during that. I will keep myself assigned and keep an eye out for the changes so I can complete this issue.

**Comment by joostdecock** [comment]
Ursual no longer exists. Closing.
