### ISSUE TITLE
[docs]: (charlie) Fly and belt loop instructions may be incorrect and they also need improvement

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3748]
### Where can we see the problem? 🤔

https://freesewing.org/docs/patterns/charlie/instructions/

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

Per [Discord discussion](https://discord.com/channels/698854858052075530/698854858496802868/1092288633148538931), the instructions for Charlie's fly construction might be incorrect. Even if they are aren't incorrect, the instructions need improving, possibly with the information found in a [Twitter thread](https://twitter.com/j__st/status/1516078829550411782).

Also, the belt loops instructions might need clarification, where there is some confusion because there are two places in the instructions that seem to describe the attachment process in two different/contradictory ways.

Part of this bug will be determining if anything is incorrect and what improvements are needed.

**Comment by tangerineshark** [comment]
Hi! Attaching an incomplete but still pretty big pile of SVG illustrations I've made for Charlie but not gotten around to uploading! There's two steps missing in fly construction (10e - attach zip to fly, and 10f - sew zip to fly facing), and then 11b is just where I'd gotten to so far

![step01](https://user-images.githubusercontent.com/70777269/233088702-b1657d1f-5791-4401-bbf6-120e54c21029.svg)
![step03](https://user-images.githubusercontent.com/70777269/233088704-3efafb72-0b2e-4d7c-8104-808abc6424dd.svg)
![step04a](https://user-images.githubusercontent.com/70777269/233088707-f621936a-17f8-4446-bc8b-d399f2383c2b.svg)
![step04b](https://user-images.githubusercontent.com/70777269/233088709-d842a614-8b2a-496a-bed9-67c12d466c72.svg)
![step04c](https://user-images.githubusercontent.com/70777269/233088711-07962406-124b-46f6-a9e2-35e238231761.svg)
![step04d](https://user-images.githubusercontent.com/70777269/233088712-da80a4f7-fe4a-4eec-8171-48dbc41d77ed.svg)
![step05a](https://user-images.githubusercontent.com/70777269/233088715-9ba42460-6d58-4a6d-b578-aaf815ba5852.svg)
![step05b](https://user-images.githubusercontent.com/70777269/233088717-d0eb51cb-02bb-4486-886a-53520a821f98.svg)
![step06a](https://user-images.githubusercontent.com/70777269/233088721-592b03db-20a3-41cd-b21d-d05912626b5c.svg)
![step06b](https://user-images.githubusercontent.com/70777269/233088723-720db5e1-5b3b-49e5-879a-83688a860cc9.svg)
![step07](https://user-images.githubusercontent.com/70777269/233088724-c36d7fd2-ca10-4138-9eb8-28e881513bf8.svg)
![step08](https://user-images.githubusercontent.com/70777269/233088726-90f7085a-ac3f-492c-8090-46b2ec56cbac.svg)
![step09](https://user-images.githubusercontent.com/70777269/233088727-4766f087-e7aa-4122-9989-0cffca024fbb.svg)
![step10a](https://user-images.githubusercontent.com/70777269/233088728-6f9a1510-551b-49e4-a77b-c2097fc20d58.svg)
![step10b](https://user-images.githubusercontent.com/70777269/233088731-e9df5821-ffa9-4916-a52b-49884365ccc2.svg)
![step10c](https://user-images.githubusercontent.com/70777269/233088733-04239074-eec2-4ea9-9bf8-6576067e9c2f.svg)
![step10d](https://user-images.githubusercontent.com/70777269/233088735-83614e13-e8ff-4b67-b422-13c76ad3490d.svg)
![step10g](https://user-images.githubusercontent.com/70777269/233088738-acd9b285-fc11-4883-ad42-d4b6eee076dd.svg)
![step10h](https://user-images.githubusercontent.com/70777269/233088739-975b577e-4898-4428-98eb-3ed6382845a7.svg)
![step10z](https://user-images.githubusercontent.com/70777269/233088741-1c7f9920-4547-4d9f-b46d-1d7cd6b38158.svg)
![step11a](https://user-images.githubusercontent.com/70777269/233088743-16d2fa30-d0ea-4e50-982a-03ad7887683d.svg)
![step11b](https://user-images.githubusercontent.com/70777269/233088744-3844f85d-43c8-444a-b705-ea9133d3fc67.svg)

**Comment by tangerineshark** [comment]
Ooh, also 10z is nothing, just essentially a template for some of the other steps

**Comment by bobgeorgethe3rd** [comment]
Closing in favour of #3869
