### ISSUE TITLE
[bug]: Improve New Pattern measurement selection page to reduce confusion

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3749]
### What seems to be the problem? 🤔

A customer reported that the New Pattern page is confusing, where they did not realize that you could select saved measurements as opposed to using the S-M-L model sizes:

https://discord.com/channels/698854858052075530/757632180980547686/1089996977900630117
> Hello
I'm going to try my first design with the Waralee Wrap pants.
But I'm a bit confused, the description says Required measurements Crotch depth, Inseam, Seat circumference, Waist to hips
When I click on NEw Waralee pattern, it just offers the standard sizes like S, M, L, etc.
Where or when do those measurements come into play?

> I'm an idiot, I didn't realise that I need to click on my name 😄
I was searching for a good 5 minutes
But I know why, maybe this could be a UI improvement for later: the button you need to press with the persons name contains the same info as the one in Account -> People, so I assumed that it did the same: bring me to that persons options.

This bug is to have the page improved to help avoid this confusion. Possibilities include renaming the page from "Choose a size" to "Select measurement set to use". Or, separating or hiding the S-M-L model sizes so they aren't as prominent.

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

This is what the page for Waralee currently looks like, https://freesewing.org/create/waralee/ 
![Screenshot 2023-04-03 at 8 06 24 AM](https://user-images.githubusercontent.com/109869956/229551469-0d142708-16f7-4b50-8ed9-ace37ef1bd5a.png)

**Comment by BenJamesBen** [comment]
If the customer doesn't have any measurements saved, below is what they see.

I suggest hiding the S-M-L model sizes by default and having a button/toggle to expose them. Perhaps also have a warning, telling people they probably shouldn't use the model sizes.

![Screenshot 2023-04-03 at 8 45 55 AM](https://user-images.githubusercontent.com/109869956/229567981-5a220878-4a36-4af1-8efc-1f86d36e3e41.png)

**Comment by joostdecock** [comment]
Not backporting fixes to v2. V3 page is very different, so hopefully better :crossed_fingers:
