### ISSUE TITLE
[docs]: (org) FAQ for why are seam allowances tapered? 

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3774]
### Where can we see the problem? 🤔

https://freesewing.org/docs/faq/

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

https://discord.com/channels/698854858052075530/757632180980547686/1093897092851830846

On Discord, a customer experienced confusion because of the way the seam allowance tapers on the bottom of Charlie's leg. And, apparently this question has come up before.

(The Pattern Notation Guide already mentions that seam allowance corners get trimmed, but it was suggested that perhaps the issue should be documented more prominently and with details of the "whys" this is so.)

**Comment by SeaZeeZee** [comment]
Merged!
