### ISSUE TITLE
[bug]: (org) Newly-added measurements sets not immediately seen in other language login sessions

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3782]
### What seems to be the problem? 🤔

Measurement sets added under one login session in a language are not immediately seen in other login sessions under different languages. Logging out and then back in fixes the issue.

Steps to Reproduce:
1. Go to en.freesewing.org.
2. Log into en.freesewing.org.
3. Switch site language to French, using the icon menu in the upper right of the web page. The page will switch to fr.freesewing.org.
4. Log into fr.freesewing.org.
5. Browse to the "Personnes" People page https://fr.freesewing.org/account/people/ (Mon Compte -> Personnes).
6. Add a new measurement set, via "Ajouter Personne" button. Name the measurement set "Test Person"
7. Go back to the Personnes page.
8. Observe that the newly-added "Test Person" is seen.
9. Switch site language to English, using the icon menu in the upper right of the web page. The page will switch to en.freesewing.org.
10. Browse to the People page https://en.freesewing.org/account/people/ (Account -> People).
11. Observe that the expected, newly-added "Test Person" is not seen. You have reproduced the bug.
12. Log out, log back in, and go back to the People page.
13. Observe that "Test Person" is now seen.

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

It was reported that the same issue is seen for newly-added Patterns.

**Comment by BenJamesBen** [comment]
Per Joost:
https://discord.com/channels/698854858052075530/757632953097388043/1094597586264018944
> t's because the account data stored locally gets out of sync with the backend.
This happens because different languages use a different (sub) domain (like fr.freesewing.org) so your browser keeps a different local storage for both.
You do not need to re-login to fix it. You can just force a re-sync of your local data with the backend by reloading the account data on this page: https://freesewing.org/account/actions/reload/
>
> In version 3, this will no longer be a problem as we'll serve all languages from the same domain and instead use i18n routing in the URL (eg freesewing.org/blog would be English whereas freesewing.org/fr/blog would be French).

So, it is likely that we will close this bug as Will Not Fix, probably once the switchover from v2 to v3 has been made.

**Comment by joostdecock** [comment]
> So, it is likely that we will close this bug as Will Not Fix, probably once the switchover from v2 to v3 has been made.

Why keep this open if we're not fixing it?

**Comment by BenJamesBen** [comment]
I added the issue of whether to close "broken in v2 but fixed in v3" issues to the April 29 Contributor Call.

**Comment by joostdecock** [comment]
Don't remember what was decided on that call (and there don't seem to be notes). But I've added a `fixedInv3` label and I'm closing this as we need to get the amount of open issues under control.
