### ISSUE TITLE
[docs]: Document plugin-annotations

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3791]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/plugins

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Suggested content

We need to not only change the docs so that all plugins that have been consolidated in plugin-annotations are removed/updated, we also need to document the new macros (`bannerbox`, `pleat`, `crossbox`).

### Additional context

At the time of writing, this work is still in the `annotations` plugin

**Comment by SeaZeeZee** [comment]
I'm assigning this to myself because I think I can handle updating and writing new docs once the PR goes through

**Comment by joostdecock** [comment]
Implemented as part of #3625 closing.
