### ISSUE TITLE
Compare Pattern should show the name of the size an outline corresponds to

### ISSUE THREAD

**Issue by Lobotomik** [freesewing/freesewing#381]
When producing a new pattern using custom measurements, there is a feature to overlay the shapes obtained with the standard sizes. When this feature is selected, the outline for each size is shown in a different color.

It would be helpful if there was a legend, or a pop-up tag on hovering on a line with the corresponding size (XXXS to XXXL).

**Comment by joostdecock** [comment]
Closing in favor of https://github.com/freesewing/freesewing.org/issues/713
