### ISSUE TITLE
[feature]: Allow overwriting of snippets by plugins

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3819]
### What is it that you would like to see happen? 🤔

This comes on the heels of #3625 and what I'd like to see is to make it easier tor plugins to overwrite what other plugins provide.

Specifically, there was a bit of discussion on whether or not to keep `logo` in the plugin-annotions package, or keep it out because it's typically something people will want to overwrite when they implement their own designs.

However, we must assume that almost everyone loads the plugin-bundle package, which also includes the logo. So keeping it out of the annotations plugin is in practice probable not all that helpful, not to mention that it's a bit counter-intuitive.

So, instead it would be better if people could just load their own plugin that would provide a `logo` snippet that simply overwrites the previous logo.

However, the way things are handled right now this would not work because plugins set snippet definitions for the SVG `defs` section by adding it to `svg.defs` which is a string.

We should isntead extend the svg object so that defs can by set together with an ID (and concatenated for rendering) so that people can do something like 

```js
svg.defs.set('logo', 'my new logo here')
```

This would make it a lot simpler for people to overwrite some of the default snippets. And it would mean we don't have to worry about what we do or do not bundle.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

This would predominantly impact core and the new annotations plugin.

**Comment by woutervdub** [comment]
@joostdecock ,

Where / how were you envisioning this code would be used by someone who would want to replace our logo?
`svg.defs.set('logo', 'my new logo here')`

**Comment by joostdecock** [comment]
So in the plugin, we now typically have something like:

```js
svg.defs += "[svg string here]"
```

I'd like to use something like this:

```js
svg.defs.setIfUnset('logo', "[svg string here]")
```

For this, I'd propose to make a light version of the current attributes facility that has `set`, `setIfUnset`, `unset`, and `toString` methods.

We might want to re-use it for setting CSS too. Since that's also kept as one big string right now.

**Comment by joostdecock** [comment]
By hooking into the lifecycle and setting the snippet themselves. Either through a plugin, or via the `pattern.on()` method.

That part doesn't change. It's just that now it will be possible to do so without generating an ID conflict in the SVG output.
