### ISSUE TITLE
Development environment setup script crashes for Node > 11

### ISSUE THREAD

**Issue by Lobotomik** [freesewing/freesewing#383]
Hello,

The user documentations tells you to install the development environment with the command:

> npm init freesewing-pattern

WSL in Windows runs Ubuntu LTS 18.04 which has nodejs version 8. 
Unfortunately, in Node8,  the parameter after "init" is ignored, so the script does not much other than creating a ten-line json file.

* I installed Node12 using a Nodesource PPA, and it crashed almost immediatelly, with an error discussed below.
* Then I installed Node11 from the same PPA, and the script worked.
* I do not know if it runs on Node 10 or 9, but I know it does not on Node 8.

I think that at the very least, [freesewing.dev](https://freesewing.dev) should tell the what version (or versions) of Node are known to work before asking it to run "npm init freesewing-pattern". And it should really work with the latest LTS which is 12.

The issue with Node12 was this:

```
$ sudo npm init freesewing-pattern
npx: installed 258 in 19.033s
internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/nacho/.npm/_npx/2843/lib/node_modules/create-freesewing-pattern/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /home/nacho/.npm/_npx/2843/lib/node_modules/create-freesewing-pattern/node_modules/is-promise/index.js from /home/nacho/.npm/_npx/2843/lib/node_modules/create-freesewing-pattern/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/nacho/.npm/_npx/2843/lib/node_modules/create-freesewing-pattern/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/nacho/.npm/_npx/2843/lib/node_modules/create-freesewing-pattern/node_modules/is-promise/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/nacho/.npm/_npx/2843/lib/node_modules/create-freesewing-pattern/node_modules/run-async/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'ERR_REQUIRE_ESM'
}
```
So the crash happens because an issue with the use of "Require" (which is older-style CommonJS) and "import", which is the ES6 way.
Indeed, I think line 3 in .../node_modules/run_async/index.js could be changed from 

> "var X = Require('is_promise')" 

to
 
> "import * as X from 'is_promise'"

and maybe it would solve the problem. I made the changes, but when  I ran the script, the untouched version was downloaded and my changes were ignored, so I don't currently know. 

And maybe there's a world of difference between the two, I don't really know, I'm not an expert in JS. And even if that line is fixed, it still might crash on the next one, as this code has clearly never been run with NodeJS later than 11.

Once I check out everything from Git and make some sense of it, I will take a deeper look.

**Comment by joostdecock** [comment]
You and the half of the JS ecosystem have been bitten by the same bug: https://github.com/then/is-promise/issues/13

This was on HN and a bunch of other places: https://news.ycombinator.com/item?id=22979245

We support node LTS, that hasn't changed. We should perhaps make it more obvious in the documentation, but this is not a freesewing issue, but an issue with a dependency of create-react-app.

Still, I'll keep this open until we have a new release out.

**Comment by joostdecock** [comment]
Oh, and I should add: thank you for taking the effort to report this, as well as the detailed info. Much appreciated 🤗

**Comment by joostdecock** [comment]
Update: We do now check for node version < 10 (the oldest LTS) and throw an error when it's too old.
You can override that error by passing the --no-check-version parameter.

It also works with v12 (as it always had), the issue you bumped into was because of an upstream issue. The 2.6.0 release will include all these fixes. 

Below is a screenshot of it running on 2.6.0-rc.1, as we're still road testing it. You can see the new pan&zoom interface too :)

![Screenshot_2020-04-26 testa](https://user-images.githubusercontent.com/1708494/80314686-4608b580-87f3-11ea-8fcb-46a575a4a0c8.png)
