### ISSUE TITLE
[feature]: Create CI test to catch changes that break `npx @freesewing/new-design@next`

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3852]
### What is it that you would like to see happen? 🤔

When v3 is out, the `new-design` package which is used to bootstrap the stand-alone development environment will load its code from the `main` branch, which will make it stable.

However, currently (v3 is in alpha) it loads code from the `develop` branch which means that changes in the `develop` branch can break it.

It would be good to have an automated test to detect this so we could merge with confidence.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

**Comment by eriese** [comment]
If anyone wants to take this on, I think you don't need deep knowledge of the code base. Here's an outline of what I think is needed:

1. A script in `packages/new-design`, let's call it `packages/new-design/test.mjs`
    - basically copies `packages/new-design/lib/cli.mjs` 
    - replaces line 12 with something that parses command line arguments to get choices
2. A github workflow
    - uses a matrix strategy to test `from scratch`, `tutorial` and an extended pattern, let's say `from bent`
    - sets up node
    - checks out the repository into a folder
    - cd into that folder
    - `yarn kickstart`
    - cd out of that folder
    - `node ./packages/new-design/test.mjs ${matrix args}`
    - cd into the folder for the new design
    - yarn dev
    - some kind of end to end tests? very simple just check that the design page loads without errors?

Seems like this could open the door for us to have some frontend testing, and I, for one, welcome our new headless overlords

**Comment by eriese** [comment]
On @joostdecock's suggestion, I'm checking out [playwright](https://playwright.dev/docs/api/class-locator#locator-get-by-title), writing some starter tests for `lab`. I think including some playwright tests in the generated new design will simplify this process. If we don't want to include things standalone users will never use, maybe there's a `includeTests` flag that defaults to false
