### ISSUE TITLE
[docs]: (scale) Corrections and additions

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3873]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/settings/scale

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

Per Discord discussion, the documentation for the `scale` setting is incorrect and incomplete.
https://discord.com/channels/698854858052075530/944926520282054666/1099624004333080587
discord://discord.com/channels/698854858052075530/944926520282054666/1099624004333080587

1. The correct behavior is that `scale` only scales down, not up. The documentation is currently incorrect, implying that `scale` also scales up "to better support very large" patterns.
2. The 10 cm x 5 cm scalebox and 2.5 cm x 2.5 cm miniscale don't just shrink in size, keeping the same labels. Instead, they are replaced by different, smaller scaleboxes and miniscales, with different dimensions and dimension labels. This needs to be documented.
3. We should document exactly what other specific elements are affected by `scale` and how they are affected. (Most are probably scaled linearly.)

**Comment by joostdecock** [comment]
There's a misunderstanding here, and re-reading the Discord discussion I'm afraid I created it 🙈

This comment:

> The wanted behavior is that if scale is small, we render a smaller scalebox.
> Just like we render a smaller button.
> The only difference is that buttons can be scaled linearly whereas the scalebox has a number of different incarnations depending in the scale setting.
>
> And the roadmap is not wrong. We only want it to scale down. We never have gotten a request to scale up.

Was specifically about the **scalebox**.

The **scale** setting itself scales both up and down. But the **scalebox** only acales down.

Given that, the current documentation is correct although I gladly admit it does not include a whole lot of detail about what happens umder the hood. So we should still improve it.

**Comment by joostdecock** [comment]
Tranks train connection for first pretending my comment was lost, and then after I write it again showing both 😌
