### ISSUE TITLE
Add scale support for text in React render

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3902]
### What seems to be the problem? 🤔

As pointed out by @woutervdub the React view (aka the website) only partially supports the wcale setting, with text not adapted. 
Thus is unlike the SVG output which uses CSS that takes the scale into account.

Similar CSS should be generated in the fly in the frontend, taking the scale setting into account.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

**Comment by bobgeorgethe3rd** [comment]
Implemented as of #3999
