### ISSUE TITLE
[docs]: Document the cutlist plugin methods & plugin store methods

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3929]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/plugins/annotations

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Suggested content

The various store methods for the `cutlist` functionality in the `annotations` plugin are not documented.
In general, we should do two things:

- We should add *store methods* to the overview of what is provided by the annotations plugin
- We should have reference documentation for these methods, just as we do for snippets and macros (which are also provided by the plugins).

Currently, the reference documentation for how to use these methods is included in a howto.
So while it's good that this is written already, it's in the wrong place and we should restructure things in line with the how we organize our documentation.

I would suggest we use **Store methods** as title, and `methods` as slug. Then follow a similar structure as we do with macros/snippets.

**Comment by eriese** [comment]
They're documented, just in a weird place: https://github.com/freesewing/freesewing/blob/develop/markdown/dev/reference/plugins/annotations/en.md#methods

**Comment by SeaZeeZee** [comment]
The documentation for how to include the cutting list is currently under common design challenges, if I understand this right that is not the correct place, but can someone tell me where I need to move it to instead? 

Do the store methods also need to be moved elsewhere and if so where?

**Comment by joostdecock** [comment]
Implemented in #5323
