### ISSUE TITLE
[bug]: (bob,penelope): Optional measurements are accessed via `measurements`, not `optionalMeasurements`

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3933]
### What seems to be the problem? 🤔

Steps to Reproduce:
1. In lab.freesewing.dev, select the Bob design.
2. Enable `paperless`, and note that the neck opening width is 10.08 cm.
3. In the Measurements view select With Breasts Size 28, and note that the Head circumference is set to 53 cm.
4. Switch back to DraftDesign view, and note that the neck opening width is still 10.08 cm.
5. In the Measurements view select Without Breasts Size 50, and note that the Head circumference is set to 65.5 cm.
6. Switch back to the DraftDesign view, and note that the neck opening width is still 10.08 cm.

The same behavior is seen in the `develop` localhost lab.

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

I note that the below code addition seems to fix the issue, though I don't fully understand the code so I don't know if it is an appropriate fix.

In `packages/core/src/part.mjs`:
``` diff
@@ -175,6 +175,12 @@ Part.prototype.shorthand = function () {
     },
     set: (measurements, name, value) => (self.context.settings.measurements[name] = value),
   })
+  shorthand.optionalMeasurements = new Proxy(this.context.settings.measurements, {
+    get: function (optionalMeasurements, name) {
+      return Reflect.get(...arguments)
+    },
+    set: (optionalMeasurements, name, value) => (self.context.settings.optionalMeasurements[name] = value),
+  })
   shorthand.options = new Proxy(this.context.settings.options, {
     get: function (options, name) {
       if (typeof options[name] === 'undefined')
```

**Comment by eriese** [comment]
`optionalMeasuments` is not documented in the pattern draft method. Is it expected to be available separately from measurements? Or is `bob` trying to access it incorrectly (and if so, is the correct way working?)

**Comment by BenJamesBen** [comment]
I confirm that using `measurements` works, via the code change below.

In `designs/bob/src/bib.mjs`:
```diff
@@ -19 +19 @@ export const bib = {
-    optionalMeasurements,
+    measurements,
@@ -30 +30 @@ export const bib = {
-    const head = (optionalMeasurements?.head || 360) * options.headSize
+    const head = (`head` in measurements ? measurements.head : 360) * options.headSize
```

There are 7 designs that use the `optionalMeasurements` config setting. 
- Five of the designs (Brian, Diana, Tamiko, Unice, and Waralee) use the `measurements` property to access the optional measurements.
- Two designs (Bob, Penelope) use the `optionalMeasurements` property.

I assume that using `measurements` property is the correct practice. 

I'll change Bob and Penelope to use `measurements`. I will also add a note to these two documentation pages to make it explicit that the `measurements` property will contain the measurements from both the `measurements` and `optionalMeasurements` config settings.
https://freesewing.dev/reference/api/part/config/measurements
https://freesewing.dev/reference/settings/measurements
