### ISSUE TITLE
[bug]: Florent top part fold location is not specified

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3937]
### What seems to be the problem? 🤔

In the Florent construction and cutting instructions a fold is mentioned for the top part. For example: https://freesewing.org/docs/patterns/florent/cutting/
> Cut 1 top on the fold but don't include the center seam allowance, or 2 top with the center seam allowance.

However, the top part doesn't have an optional foldline; none is marked on the pattern. Either the instructions should be updated to provide information where the optional foldline is located, or notation should be added to the pattern.

### Design / Plugin / Package 🧐

designs/florent

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

Without changing the instructions or the pattern to add an actual `cutonfold` line, to avoid actually changing the design, the issue could be fixed by adding annotation-only text and possibly a line as well. One possible fix:
In `designs/florent/src/top.mjs`:
```diff
@@ -177,6 +177,12 @@
         .length() + store.get('topDistanceToFirstNotch')
     )
 
+    paths.foldline = new Path()
+      .move(points.midMid.shift(-90, 0.5))
+      .line(points.midFront.shift(-90, 0.5))
+      .attr('class', 'note dashed')
+      .addText('(optional foldline)', 'center')
+
     if (sa) paths.sa = paths.seam.offset(sa).attr('class', 'fabric sa')
 
     if (paperless) {
```

Before:
![Screenshot 2023-04-30 at 5 50 36 AM](https://user-images.githubusercontent.com/109869956/235354175-50647d79-f640-4eb3-be45-7583d8963a59.png)

After:
![Screenshot 2023-04-30 at 5 50 08 AM](https://user-images.githubusercontent.com/109869956/235354170-a5ff5771-2782-4bb8-a682-53ac93d5d411.png)

**Comment by bobgeorgethe3rd** [comment]
Thsi would probably bette4r to be macro cutonFold rather than what is existing. For example look at Holmes crown part

**Comment by BenJamesBen** [comment]
Using the `cutonFold` macro would create an actual foldline, causing the part to mirror in the cutlist. I am trying to avoid this, leaving the part as one that by default is 2 separate parts. (The foldline is just optional.)

**Comment by bobgeorgethe3rd** [comment]
But you would typically cut it how the cutlist mirrors it. You generally don't cut this piece on the actual fold, rather cut it as one piece. In this case fold is essentialy fold in paper.

**Comment by bobgeorgethe3rd** [comment]
You can also bias cut this piece
