### ISSUE TITLE
[bug]: `options` are `undefined` in the reset state when setting up lab menus

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3955]
### What seems to be the problem? 🤔

Using this debug code in a design:
```js
bottomArmReduction: {
     pct: 90,
     min: 75,
     max: 125,
     menu: 'style',
     //hide: ({ options }) => options?.type == undefined
     hide: ({ options }) => {console.log('t ' + options); console.log ('v ' +    options?.type); if (options?.type == undefined) return true; return false}
   },
```

We see that when a design is first loaded in the lab or when the ClearThing button is used, the `options` object is `undefined`:
```
t undefined
v undefined
```

As soon as any option is selected, the options object then starts to exist and continues to exist:
```
t [object Object]
v octopus
```

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

This issue prevents the use of this code when a design is first loaded in the lab.
```js
hide: ({ options }) => options.type == 'octoplushy'
```
And, it generates messages in the console when trying to access the `type` property of `undefined`.

**Comment by joostdecock** [comment]
See #3956
