### ISSUE TITLE
[bug]: List options are `undefined` when set to the default value

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3956]
### What seems to be the problem? 🤔

Using this debug code in a design and view the design it in the lab UI:
```js
bottomArmReduction: {
     pct: 90,
     min: 75,
     max: 125,
     menu: 'style',
     //hide: ({ options }) => options?.type == undefined
     hide: ({ options }) => {console.log('t ' + options); console.log ('v ' +    options?.type); if (options?.type == undefined) return true; return false}
   },
```

We see that when a non-default setting is selected fo `options.type`, it is correctly set to the value:
```
t [object Object]
v octopus
```

However, when the default setting is selected, `options.type` is unexpectedly `undefined`:
```
t [object Object]
v undefined
```

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

This prevents the use of this code:
```js
hide: ({ options }) => options.type == 'octoplushy'
```

The value of `options.type` will never be set to `octoplushy` (the default).

**Comment by joostdecock** [comment]
This was resolved a while ago. The first parameter of the `menu` function receives the settings as provided by the user.
If you want to know what an option's current value is -- and not what the user asked -- you should use the second parameter which holds `mergedOptions` which merges the user's choices with the defaults.

Here's how it is currently implemented:
https://github.com/freesewing/freesewing/blob/7bf47552a7ea9fdb92a5f74fc4515bf5c0db6e4d/designs/octoplushy/src/head.mjs#L649-L655
