### ISSUE TITLE
[feature]: Keep FreeSewing's logo DRY

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3965]
### What is it that you would like to see happen? 🤔

The logo plugin defines the pathstring of the FreeSewing logo.
This is lengthy string, and we're keeping it in more than one place.

So it should be adapted to:

```js
import { logoString } from '../../sites/shared/components/logos/freesewing.mjs'
```

So that we can keep the code DRY.

Note that we might need to apply a transform as this path string is probably built for a different viewBox.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

**Comment by sohamtembhurne** [comment]
Hi @joostdecock, is this issue completed or it still needs some work to be done ? If so, I am ready to contribute

**Comment by joostdecock** [comment]
> Hi @joostdecock, is this issue completed or it still needs some work to be done ? If so, I am ready to contribute

No, it's still open. I see it's assigned to @woutervdub but he's got plenty on his plate, so if you'd like to tackle this, you can do so.
The file to edit is `plugins/plugin-annotations/src/logo.mjs`
