### ISSUE TITLE
[feature]: The abillity to add Custom Fonts to the PDF Export

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [freesewing/freesewing#4047]
### What is it that you would like to see happen? 🤔

Currently the pdf exporter does not support fonts/characters such as Kanji & Cyrillic. This means if we wanted to translate into a language that uses these fonts/characters it will not currently export the text in the pdf. Having this support embedded already would make easier for anyone who wishes to come in and translate freesewing into the language without the worry of the pdf not supporting fonts/characters in their language.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Come on y'all, what's the point of issues like these?
If ever we get to the point where we are going to support such a language, we'll deal with it at that time.
