### ISSUE TITLE
Macro: To rotate a path.

### ISSUE THREAD

**Issue by devanshkain** [freesewing/freesewing#406]
Have to rotate the points for slash and spread.
Would be really good to have a function or a macro to rotate a path.

**Comment by joostdecock** [comment]
Makes sense. Thanks for the suggestion.

**Comment by joostdecock** [comment]
Couldn't find the time to include this in 2.7. Re-assigning to the 2.8 milestone.

**Comment by joostdecock** [comment]
This is very stale, so I'm closing it. But I've added it to [our roadmap](https://github.com/freesewing/freesewing/discussions/1278).
