### ISSUE TITLE
[docs]: Add Pattern* to core API

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#4076]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/api

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

These new Pattern-related items are found in `packages/core/src/pattern/*.mjs`

Specific things to be documented:
- [ ] PatternConfig general documentation
- [ ] PatternConfig.addPart() (** how is this different than `Pattern.addPart()`?)
- [ ] PatternConfig.asConfig()
- [ ] PatternConfig.isPartValid()
- [ ] PatternConfig.logPartDistances()
- [ ] PatternDraftQueue general documentation
- [ ] PatternDraftQueue.addPart() **
- [ ] PatternDraftQueue.contains()
- [ ] PatternDraftQueue.hasNext()
- [ ] PatternDraftQueue.next()
- [ ] PatternDraftQueue.peek()
- [ ] PatternDraftQueue.start()
- [ ] PatternDrafter general documentation
- [ ] PatternDrafter.draft() **
- [ ] PatternDrafter.draftPartForSet()
- [ ] PatternPlugins general documentation
- [ ] PatternPlugins.loadConfigPlugins()
- [ ] PatternPlugins.on() **
- [ ] PatternPlugins.use() **
- [ ] PatternRenderer general documentaion
- [ ] PatternRenderer.getRenderProps() **
- [ ] PatternRenderer.render() **
- [ ] PatternSampler general documentation
- [ ] PatternSampler.sampleMeasurement() **
- [ ] PatternSampler.sampleModels() **
- [ ] PatternSampler.sampleOption() **

### Additional context

Part of this Issue will be to determine how pattern documentation is organized within the API. Are `PatternConfig`, `PatternDraftQueue`, etc., listed at the top level along with `Pattern`? Or, are they listed in a subdirectory in a hierarchy? Does the existing `Pattern` docs get moved as well?

A number of new methods, like `PatternPlugins.on()` and `PatternSampler.sampleModels()` seem to mirror existing methods like `Pattern.on()` and `Pattern.sampleModels()`. Part of this Issue is to figure out how these things are different and how they should be documented. It might require changing the existing `Pattern` docs.

**Comment by joostdecock** [comment]
This is internal. Only `Pattern` is part of the public API. The rest is not. Furthermore, it's highly likely this will change in the future, so we don't want people to rely on this.

Closing.
