### ISSUE TITLE
[docs]: Add utils new methods

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#4078]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/api/utils

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

New methods to be documented:
- [ ] utils.applyTransformToPoint()
- [ ]  utils.combineTransforms()
- [x]  [utils.generateStackTransform()](https://freesewing.dev/reference/api/utils/generatestacktransform)
- [x]  [utils.getTransformedBounds()](https://freesewing.dev/reference/api/utils/gettransformedbounds)

Found in `packages/core/src/utils.mjs`.

**Comment by Yash-Ambekar** [comment]
@BenJamesBen Can I please work on this issue?

**Comment by joostdecock** [comment]
> @joostdecock @BenJamesBen Can I please work on this issue?

Sure thing. Just keep in mind that some of the work has already been done. I've updated the issue description to illustrate that.

You would need to create the files at `markdown/dev/reference/api/utils/` 
Make sure to keep everything lowercase in folder names, and put the content in `en.md`. 
Check the other methods for an example.

**Comment by Yash-Ambekar** [comment]
@joostdecock Please review my PR and request changes if any. Thank you
