### ISSUE TITLE
[bug]: (new-design): ERR UNSUPPORTED_ ESM_URL_SCHEME on MS Windows

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#4290]
### What seems to be the problem? 🤔

The `npx @freesewing/new-design@next` script fails on MS Windows systems with an error:

> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
...
at createEnvironment (file:///C:/Users/Sarah/AppData/Local/npm-cache/ px/580e4cec4814ed1f/node modules/@freesewing/new-design/lib/utils.mis:441:52){
code: 'ERR UNSUPPORTED_ ESM_URL_SCHEME'

![image](https://github.com/freesewing/freesewing/assets/109869956/2634c5ed-fda2-40ec-afad-d43ca778b569)

The issue was reported on Discord and seen with `new-design` version `3.0.0-alpha.12`.
https://discord.com/channels/698854858052075530/698862765053575188/1118675858006224897
discord://discord.com/channels/698854858052075530/698862765053575188/1118675858006224897

### Design / Plugin / Package 🧐

packages/new-design

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The issue occurs because Windows fllepaths start with characters like "c:" and the path string gets interpreted as a URL rather than a path, resulting in an invalid URL being used. A possible fix is to convert the path to an actual, valid URL using `pathToFileURL()`.

In `packages/new-design/lib/utils.mjs`:
```diff
@@ -11 +11 @@
-import { fileURLToPath } from 'url'
+import { fileURLToPath, pathToFileURL } from 'url'
@@ -441 +441 @@
-  config.templateData = await import(config.source.templateData)
+  config.templateData = await import(pathToFileURL(config.source.templateData))
```

Until the fix is available in the published `npm` package, a workaround might be to download the `new-design` package, apply the fix to the local files, and then run the package locally:

1. In the directory that you want things to be installed into and run from...
2. `npm install @freesewing/new-design@next`
3. That creates a `node_modules` subdirectory and installs things into it, including `@freesewing/new-design`.
4. Edit the `node_modules/@freesewing/new-design/lib/utils.mjs` file, as described above.
5. Back in the directory that you wanted things run from...
6. `npx new-design`

**Comment by joostdecock** [comment]
This is not a bug because there is no (official) support for Windows, only community support. So I will re-label this accordingly.
