### ISSUE TITLE
[enhancement]: (sandy) Provide dimensions for the skirt arcs 

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#4339]
### What seems to be the problem? 🤔

>  I’m trying to make a sandy circle skirt using the paperless method with dimensions included, but I noticed that it has no arc length for the skirt, o￼nly hem length. Is there a way to add it that I’m not seeing?

https://discord.com/channels/698854858052075530/1121540974284378122/1121540974284378122
discord://discord.com/channels/698854858052075530/1121540974284378122/1121540974284378122

### Design / Plugin / Package 🧐

designs/sandy

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

In `designs/sandy/src/skirt.mjs`:
```diff
@@ -207,0 +208,14 @@ function sandySkirt({
+    const outerArc = new Path()
+      .move(points.ex1Rotated)
+      .curve(points.ex1CFlippedRotated, points.ex2CFlippedRotated, points.ex2FlippedRotated)
+      .curve(points.ex1CFlipped, points.ex2CFlipped, points.ex2Flipped)
+    const innerArc = new Path()
+      .move(points.in2Flipped)
+      .curve(points.in2CFlipped, points.in1CFlipped, points.in2FlippedRotated)
+      .curve(points.in2CFlippedRotated, points.in1CFlippedRotated, points.in1Rotated)
+    macro('pd', {
+      path: outerArc,
+    }),
+    macro('pd', {
+      path: innerArc,
+    }),
```

**Comment by joostdecock** [comment]
@BenJamesBen Could you add these paths to the `paths` object and `hide()` them? That way they are available to people who want to extend this pattern.

Apart from that, thus is ready to be a PR.

**Comment by joostdecock** [comment]
@BenJamesBen This seems to be getting stale.
From the comments on Discord, you sort of say yourself that these dimensions aren't needed:

> I think that lasermonkey12 is right. The pattern designer didn't include those arc dimensions because they aren't needed by the sewist or pattern transcriber. Instead, you would just take a string and use it like a compass to generate the arcs.
> However, I've filed an enhancement request to add those dimensions. 

Since my suggestion to submit a PR did not gain any traction, can I assume you don't really care about this?

**Comment by joostdecock** [comment]
No update, no traction, and not even sure this is wanted/needed. Closing.
