### ISSUE TITLE
Exporting a paperless pattern in imperial, measurements overlap at top. 

### ISSUE THREAD

**Issue by jodo3k** [freesewing/freesewing#437]
I created a paperless pattern with imperial measurements. I exported and the additional measurements for paperless, the numbers all overlap at the top of the pdf. see attached image..
![Screen Shot 2020-07-03 at 23 26 00](https://user-images.githubusercontent.com/3046027/86504282-a46a8b00-bd84-11ea-9fd8-61ab0e24dd47.png)

When I created a paperless pattern with metric measurements I can export and all the additional measurements are lined up with the lines.

**Comment by joostdecock** [comment]
Thanks for reporting this. It seems like the `"` symbol in the imperial measurements is not properly escaped, breaking the XML.
