### ISSUE TITLE
The blue graph for a person's measurements is so small it's unreadable.

### ISSUE THREAD

**Issue by jodo3k** [freesewing/freesewing#438]
I created person and entered the measurements needed for the Simon pattern. I see the blue graph at the bottom of the page. (see attached image) It's so small that it's unreadable. You can hover of it and see colors change. I can see there's some kind of text there, but too tiny. I'm on a Mac, and it happen using both Safari and Chrome. 

![Screen Shot 2020-07-03 at 23 29 29](https://user-images.githubusercontent.com/3046027/86504368-789bd500-bd85-11ea-8c2d-f4b8c253daa6.png)

**Comment by joostdecock** [comment]
Thanks for reporting this. It's an issue on high-resolution screens, we'll fix it.

**Comment by joostdecock** [comment]
Fixed in develop branch
