### ISSUE TITLE
[bug]: Compare Pattern shows old measurements/pattern for pattern recreated using updated measurements

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#4393]
### What seems to be the problem? 🤔

On freesewing.org, when using Compare Pattern for an old pattern made from a Person that had subsequently updated measurements and a new pattern recreated from the old one, Compare Pattern on the old pattern incorrectly shows the new pattern, not the expected old one.

https://discord.com/channels/698854858052075530/757632953097388043/1122967323398127797
discord://discord.com/channels/698854858052075530/757632953097388043/1122967323398127797

> I'm seeing an odd behavior with the "Compare Pattern" feature - I have two patterns, the second recreated from the first with updated measurements.  They appear different in the "show pattern" view, as expected, but the "compare pattern" view shows them being the same.  What's weirder to me is that the compared pattern being shown is the updated one, not the original.
https://freesewing.org/account/patterns/aujgk
https://freesewing.org/account/patterns/lswmb 

> Tested it out some more, and I think I can safely say that the "compare pattern" pattern is being generated from whatever my current measurements are, not the ones used to generate the pattern.  To test, I made my waist measurement 10x what it actually is.  I opened an incognito window, loaded up a pattern, and in that incognito session they all are now wildly out of proportion only in the Compare Pattern view 

> there does appear to be some caching issues involved, but that i think is separate to this issue (since it is reproducible in separate browsing sessions).  changing my measurement back, logging out, and logging back in seems to re-generate the compare pattern views (again to the current measurments, not the individual patterns') 

![image](https://github.com/freesewing/freesewing/assets/109869956/25cf327b-b9ce-4c24-93d2-519a68060309)
![image-1](https://github.com/freesewing/freesewing/assets/109869956/34ee0f98-f787-495e-8c5d-f21c08bf9053)
![image-2](https://github.com/freesewing/freesewing/assets/109869956/01655b72-efbb-42e7-a798-0d16c76c815b)
![image-3](https://github.com/freesewing/freesewing/assets/109869956/5cfc82b3-a5e6-48cb-84b2-58ad70467b74)

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

I'm filing this for tracking purposes. I don't understand what might be happening in this strange bug, but I think that we should test this scenario once v3 is released. I am hoping that the issue will be no longer reproducible in v3 and that we will be able to simply close this bug.

**Comment by joostdecock** [comment]
With 3.0.0 release, we should focus on that. Closing as WONTFIX
