### ISSUE TITLE
Feature request: Add a mandarin collar to Simon(e)

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#444]
Jesse writes:

> it would be great if there were a "no collar" or "mandarin" collar option

**Comment by stoffsuchti** [comment]
Great idea with the mandarin collar

**Comment by DocSpencer77** [comment]
Just yesterday was thinking to suggest multiple collar options.  Thought drafting a collar is about a match for my skill level. Maybe.

**Comment by joostdecock** [comment]
This is very stale, so I'm closing it. There's the *packs* idea on [our roadmap](https://github.com/freesewing/freesewing/discussions/1278) so perhaps it can be part of that effort.
