### ISSUE TITLE
Create showcase from this content

### ISSUE THREAD

**Issue by CloLimb** [freesewing/freesewing#4500]
Hello I made the Bruce. It fits so well! Photos of it on a human attached if you would like them for showcase. I made a little tag out of some vintage batik to cover my messy elastic join. 
![IMG_8139](https://github.com/freesewing/freesewing/assets/139929920/51731c97-93b7-486d-993c-65ad17e423fd)
![IMG_8142 2](https://github.com/freesewing/freesewing/assets/139929920/9f472f53-4b9a-4565-bfd0-7b08bfba4510)

**Comment by CloLimb** [comment]
Awesome. Thank you!

**Comment by nataliasayang** [comment]
Done! https://github.com/freesewing/freesewing/pull/5304

**Comment by MtnViewJohn** [comment]
@CloLimb , how did you did you get the pattern to be so short? I am trying to use the Bruce pattern to make booty shorts, similar to your shorts. But the shortest I can get them is still way too tall. Did you modify the pattern after printing it?
