### ISSUE TITLE
Link to API doc broken

### ISSUE THREAD

**Issue by DocSpencer77** [freesewing/freesewing#460]
The link on this page:  https://freesewing.dev/tutorials/pattern-design/constructing-the-neck-opening/ that says, "Points come with a bunch of these methods. You can find them all in the Point API docs." 
and contains this URL:
https://freesewing.dev/referene/api/point/
is broken.

Thanks,
@DocSpencer77

**Comment by joostdecock** [comment]
There's a c missing:

> https://freesewing.dev/referene/api/point/

should be 

> https://freesewing.dev/reference/api/point/

If you're up for it, you can edit it online here: https://github.com/freesewing/markdown/blob/develop/dev/tutorials/pattern-design/constructing-the-neck-opening/en.md

**Comment by DocSpencer77** [comment]
I’m happy to make the change.  I’ll figure it out.  <g>  A good start to make a chance of one letter.

**Comment by DocSpencer77** [comment]
I am just faking it till I make it with this Github collaboration.  %)  Thanks for your patient tutoring. I made the change, but now should I create a pull request.

**Comment by joostdecock** [comment]
If you create the change via the Github website (just click the pencil icon on the file) it will auto-create the pull request for you.

If you've forked the repository, then yes, you need to first push your change, then create a pull request. Also not the end of the world, but a bit more advanced then just using the website.

Let me know if you need any assistance. I'm a faker just like you ;)
