### ISSUE TITLE
Make simon & simone support button placement for left-handed people 

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#462]
Update from Discord by @joostdecock :

> I personally find it difficult to motivate myself to work on this because of the history.
> Women's shirts are inverted because (wealthy) women would not dress themselves but had a chamber maid for that.
> So the buttons are inverted to make it easier for a person standing in front of you to button them (so in reality, both women's and men's shirts are optimized for right-handed people, the majority)
> So while I understand that women are used to this, I find it personally difficult to justify spending my weekends trying to implement the continuation of a traditional that throws all women under the bus because that makes it a bit easier for the servants of the wealthy.
> 
> But, as I'm writing this, I realize there's a loophole to bypass my own moral block: we can make it about right-handed vs left-handed people. And that makes it a matter of going the extra mile to support a minority.
> And I for one find that far easier to get excited about 🤗

Original description:

> Both simon and simone have their buttons and buttonholes as men are used to them.
>
> The idea here is to have the option to reverse that. And perhaps have that option enabled by default for simone.

**Comment by bobgeorgethe3rd** [comment]
[Example of Classic Style Button and French Style (Seamless) Buttonholes ](https://cdn.discordapp.com/attachments/550472363922423808/885687322820112404/unknown.png)
https://github.com/bobgeorgethe3rd/freesewing/tree/develop/packages/simon

So I thought I would take a stab at this and the above is what I have come up with ^. Essentially it flips and renames the left and right Fronts so the options for buttons and the options for buttonholes do not get twisted and tangled.

The option is buttonholePlacement: {dflt:'Left over Right', list:['Left over Right','Right over Left']} and is in the closure sub-catergory. <- Names can be changed just best mine could come up with.

The reason this is not a pull request right now is the paperless is not done and I just want to check I am on the right track before going down the rabbit hole of paperless. Also just in case I have missed anything.

**Comment by bobgeorgethe3rd** [comment]
I have yet to figure out how this will factor onto Simone and/or how to make a Simone to use a development Simon when drafting. But we'll cross that bridge when Simon is ready.

**Comment by bobgeorgethe3rd** [comment]
Added the collar stand but I feel like buttons and butonholes are Right over Left to begin with? I haven't changed it as the default but I thought I'd get a second pair of eyes on it because to me they look the Right over Left on the current Pattern.

**Comment by joostdecock** [comment]
Please submit a PR, you can label it a draft, but it makes it easy to compare changes and test them out in a feature branch.

I also suggest taking a moment to go through the best practices: https://freesewing.dev/guides/best-practices/
They wilake your PRs easier to merge

**Comment by bobgeorgethe3rd** [comment]
Done. #1311 
Updated options.buttonholePlacement to {dflt:'leftOverRight', list:['leftOverRight','rightOverLeft']} to.
I was iniately going to do it this way too so not sure why I didn't.

**Comment by joostdecock** [comment]
Moved this to the roadmap as it's something we'd like to do but have no current plans to work on it.
