### ISSUE TITLE
[docs]: Using `DocsTitle` in a heading breaks the generation of the table of contents

### ISSUE THREAD

**Issue by cyejia** [freesewing/freesewing#4776]
### Where can we see the problem? 🤔

https://freesewing.dev/api

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

I wasn't sure if I should file this as a bug report or docs report.

Using `DocsTitle` (or `DocsLink`, which uses `DocsTitle`) in a heading breaks the generation of the table of contents because [`nodeAsTocEntry`](https://github.com/freesewing/freesewing/blob/dada1e263021ddf947fc9fda7020710bfc972391/sites/shared/mdx/mdx-plugin-toc.mjs#L7) expects the title in the `value` field (e.g. for text nodes), but the node received in this case would have the form
```ts
{
      type: 'link', // because DocsTitle is used in a Markdown link (see note after screenshot), or this might be 'mdxJsxTextElement' with name 'DocsLink'
      title: null,
      url: string,
      children: [
          {
               type: 'mdxJsxTextElement',
               name: 'DocsTitle',
               attributes: [ { type: 'mdxJsxAttribute', name: 'slug', value: string } ],
               children: [], // <-- This is an empty array
               position: [Object],
               data: Object
          }
     ],
      position: [Object]
}
```

So this results in a Table of contents where the links say "FIXME: Title not found in toc":
<img width="359" alt="image" src="https://github.com/freesewing/freesewing/assets/10645593/db511be6-fa28-406d-baa2-37cd7c04b572">

Additionally, using `DocsLink` or `DocsTitle` in a Markdown link (which is all the places that `DocsTitle` is used?) gives the error `<a> cannot appear as a descendant of <a>`. So I'd suggest rewriting these headings/sections to put the link in the section body instead, and either figuring out how to get `DocsTitle` to have the title show up in the node, or manually writing the titles (but then you'd need to keep them in sync with the doc title).

From what I can tell, this affects the following pages:
- https://freesewing.dev/api
- https://freesewing.dev/design
- https://freesewing.dev/contribute
- https://freesewing.dev/i18n

**Comment by joostdecock** [comment]
Nice write-up @cyejia :+1: I'll get to it when I have some time to spare.
