### ISSUE TITLE
[bug]: Waralee front welt placement

### ISSUE THREAD

**Issue by lasermonkey12** [freesewing/freesewing#4828]
### What seems to be the problem? 🤔

the front pocket welt in my Waralee pattern is very low (so low that if I anchor the front pocket in the waistband, the bottom is only barely below the end of the welt).

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

![image](https://github.com/freesewing/freesewing/assets/55415375/772f4735-f063-4fb4-9753-c9303ac51984)
![image](https://github.com/freesewing/freesewing/assets/55415375/eae80410-30ab-4101-8395-fd02a118d7cf)
Also a note: the width of the waist band isn't indicated on my mini, and only one corner of each welt; I had to open the full view to get where to put the other corner of the front welt.
![20230824_082621](https://github.com/freesewing/freesewing/assets/55415375/91154158-f10e-4d3b-8a9f-ffdba014f2a9)
This is a patch pocket modeled off the front pocket bag as printed, the chalk is where the pattern places my welt

**Comment by joostdecock** [comment]
@woutervdub is this something you'd like to take a look at?

**Comment by woutervdub** [comment]
Yes, I asked for the issue to be created in discord. There is something not quite right here.

**Comment by joostdecock** [comment]
Fixed by #5156
