### ISSUE TITLE
[bug]: Measurement units stuck in cm after migrating v2 account to v3

### ISSUE THREAD

**Issue by evilrobotfromouterspace** [freesewing/freesewing#4939]
### What seems to be the problem? 🤔

A few bugs sort of combined here, guessing they're all related

Steps to reproduce
1. Have a v2 account with measurement sets defined with imperial units
2. Go to next.freesewing.org and migrate your v2 account to v3
3. Go to Your Account and look at the measurement sets
4. Expected: migrated measurement set retains imperial unit of measure
4. Observed: migrated measurement set displays in cm

5. Expected: in the data section (under measies section) it says "units imperialUnits"
5. Observed: in the data section (under measies section) it says "units imerialUnits"

6. Click editThing and switch to cm, save, editThing switch to imperial, save
7. Expected: units would switch between cm and inches per your setting
7. Observed: units stay in cm no matter what

![image](https://github.com/freesewing/freesewing/assets/143673955/50d0baf5-db77-489d-bf78-0da34f8ff001)

### Are you a FreeSewing patron? 😃

Yes, I am a tier-4 patron ❤️  💙

**Comment by evilrobotfromouterspace** [comment]
Perhaps related to line 413 of [sites/shared/components/account/sets.mjs](https://github.com/freesewing/freesewing/blob/d57c4908e3b388b8b2265386a277c2bb426440b1/sites/shared/components/account/sets.mjs#L413)

![image](https://github.com/freesewing/freesewing/assets/143673955/a3145099-d5ed-417d-af58-8c9f460e2977)

**Comment by joostdecock** [comment]
Thanks for reporting this @evilrobotfromouterspace 🙏 

@all-contributors please add @evilrobotfromouterspace for bug
