### ISSUE TITLE
[magde]: Prepare for v3 beta

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#4983]
@clegganator259 There's no documentation for this pattern. Is that something you are willing to work on in the somewhat short term, or not?

I'm asking because I am trying to get to a v3 beta release, and without documentation it's not going to go in and we'll make it part of 3.1.

So no pressure, just trying to plan things.

**Comment by clegganator259** [comment]
Hey, I'm part way through writing docs but stalled out due to work and life, I can try picking this up again and finishing it off but can't really give you an ETA. I'm happy to be pulled out of the critical path and will update when life gets a bit more sensible.

**Comment by joostdecock** [comment]
@clegganator259 Sounds good. Let's put a pin in this and revisit it when we have more breathing room :+1:
