### ISSUE TITLE
[feature]: Migrated `use-persisted-state` to `use-local-storage-state`

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#5125]
### What is it that you would like to see happen? 🤔

We currently use this, but it's unmaintained: https://github.com/donavon/use-persisted-state
It's also spawning annoying errors because it does not support React 18 as a peer dependency.

We should migrate to this: https://github.com/astoilkov/use-local-storage-state

It's typically used in the hooks in `sites/shared/hooks`

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

This is a good candidate for people looking to contribute :)

**Comment by vaibhavpnimkar** [comment]
I would love work on this can you assigned this task to me if nobody is working on this

**Comment by joostdecock** [comment]
> I would love work on this can you assigned this task to me if nobody is working on this 

Sorry @vaibhavpnimkar I noticed this comment only now, but I've assigned this issue to you.

Let me know if you have any questions.

**Comment by vaibhavpnimkar** [comment]
do i have to do something like this .This code is  from use-account.js i have replaced is this is what want?

import useLocalStorageState from 'use-local-storage-state';
const usePersistedAccount = useLocalStorageState('fs-account')
const usePersistedAdmin = useLocalStorageState('fs-admin')
const usePersistedToken = useLocalStorageState('fs-token')
const usePersistedSeenUser = useLocalStorageState('fs-seen-user')
