### ISSUE TITLE
Contibutor call: September 5th 2020

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#515]
## About

 - Date: Sep 5, 2020 16:00 UTC
 - Location: https://zoom.us/j/94087732509

## Agenda

- Welcome
- A quick round of introductions
- What are some of the challenges we face today
  - Our ambitions exceed our (time) resources
    - We'd like to make more patterns
    - We'd like to do more technical work (tests/infrastructure/online development environment/...)
    - There's a growing backlog of support inquiries (because we've made it easier to report problems)
    - Providing good documentation is a continuous challenge
    - We need some *fresh pairs of eyes* to help us with the user experience
  - Our community feels somewhat disjointed
    - Our maker and developer communities co-exists, but rarely cooperate
    - Our social media presence is fragmented
    - Our website(s) should do do more to put a spotlight on our community
    - What does it mean to us to be *successful*? What should we optimize for?
  - Diversity & Equality
    - We mean well, but do we even know what we're doing?
    - Are our choices in technology leaving people on the sidelines?
- How can we capture the enthusiasm and distill it into steps we can take
    - Can we make a todo list?
    - Should we have another call / regular calls? When? What time slot?
- How can we capture the enthusiasm and distill it into steps we can take
- Anything else?
- Goodbye

## Notes

 - This was the very first FreeSewing Contributor Call (FSCC) 🎉
 - 14 people were on the call from the US, Canada, the UK, mainland Europe, and Kenya
 - After a welcome and initial round of introductions, @joostdecock went over some of the things that lead to the initiative to setup this call
 - From this moment forward, an open discussion ensued with people pitching in ideas or raising questions
 - A few noteworthy highlights include:
   - Genevieve has extensive experience writing technical documentation, and offered to help writing pattern instructions. She might need some illustrations to help envision the steps that require a lot of spatial awareness as a medical condition makes that sort of thing difficult for her.
   - @creasyo offered to help with video editing, which would allow others to shoot the *raw* video and then hand it over to him to edit it
   - The topic of FreeSewing's revenue came up, @joostdecock explained that while all revenue went to charity, that wasn't made very obvious on the site because it seemed people were more willing to contribute when they were under the assumption they are *paying for the site*. The charity aspect was news to some, which goes to show it's not very obvious.
   - @woutervdub suggested that the large amount of things that could possible be done could be made more tangible by creating *roles* that people could volunteer for
   - @enyachoke also feels roles are important to make sure that good intentions have the follow-through that leads to results. He used the term *champions* do refer to people championing a certain role/topic.
   - @enyachoke also voiced enthusiasm for presenting patterns as a 3D render, while pointing out that something like that would require automation to be manageable
   - @tangerineshark suggested to divide the work into *buckets* so it would be easier to get involved
   - @creasyo suggested to setup per-pattern hashtags and make a direct appeal on the website for users to use these hashtags when posting
   - @creasyo , Tawney, @annekecaramin , and @tangerineshark all expressed an interest to help out with social media. The idea was put forward to setup a call with the current social media stewards and them 
   - @DocSpencer77 was hoping to get a more easy on-ramp into programming patterns for those people who already have pattern design experience
   - @woutervdub suggested that a team of designer + developer can work together, and offered to help any designer with the coding aspects
   - @dfbean chimed in that based on her experience of designing Paco while @joostdecock implemented it, this system does work. The only learning curve is to understand that what is easy or hard for a computer is different to what is easy or hard on paper (or for a human)
   - @creasyo and @woutervdub mentioned that perhaps a video of how one makes a FreeSewing pattern (in code) could be helpful
   - @DocSpencer77 mentioned that she's been trying to improve FreeSewings measurements table (with a focus on the *with-breasts* side of things) and invited others to join that effort
   - There was a suggestion to use the input of users who could submit their set of measurements 
   - @creasyo suggested to take that one step further and have people share submit their measurement in a (social media) campaign focused on body positivity
 - there was an interesting discussion on *measures of success* - Is it donations, number of downloads, or some quantifiable measure of community engagement?
 - @dfbean suggested a roadmap to drive efforts and also considering what's **not** on the list. Both of these could them help inform where people spend they're efforts and make sure they're not *miss-spent*
 - @creasyo questioned whether we should consider other/additional platforms for collaboration
 - We agreed to make these calls a recurring event on a bi-weekly schedule (once every two weeks)
 - The meeting ran 15 minutes over time

## Todo

**Note**: All of these link to an issue that was setup specifically to track their progress.

 - [Schedule a new call 2 weeks from now](https://github.com/freesewing/freesewing/issues/522)
 - Social media
   - [Setup a call with the current team (@woutervdub for Facebook, Eleonore for Instagram, and @joostdecock for Twitter) and @tangerineshark, Tawney, @annekecaramin , and @creasyo who'd like to get involved](https://github.com/freesewing/freesewing/issues/523)
   - [Agree on a hashtag structure for our patterns](https://github.com/freesewing/freesewing/issues/524)
   - [Publish said hashtags prominently on the pattern pages and ask people to use them](https://github.com/freesewing/freesewing/issues/525)
 - [Establish a *developer pool* that designers could call on to implement their patterns](https://github.com/freesewing/freesewing/issues/526)
 - [Think about how collecting/sharing measurements could or would work](https://github.com/freesewing/freesewing/issues/527)
 - [Start (working on) a list of *roles* to fill ](https://github.com/freesewing/freesewing/issues/528)
 - [Find people to fill those roles, or champion those topics](https://github.com/freesewing/freesewing/issues/528)
 - [Compile a list of (patterns with) missing documentation](https://github.com/freesewing/freesewing/issues/529)
 - [What platform should we use to coordinate collaboration?](https://github.com/freesewing/freesewing/issues/530)

**Comment by amysews** [comment]
For the agenda, is it worth you or other core members describing the biggest pains or gaps you're experiencing? I appreciate you've listed potential roles in your blog post but I'm guessing some are more important than others?

**Comment by joostdecock** [comment]
> is it worth you or other core members describing the biggest pains or gaps you're experiencing?

Great suggestion :+1: 
I've added that to the agenda. I think it's easier to briefly describe it on the call, rather than write a lengthy block of text :)

**Comment by stoffsuchti** [comment]
Pleeeease consider using privacy respecting tools for the conf-calls. Like Mumble oder Big Blue Butten or Jitsi.

Ah free Mumble server can be found for example on treff.top, administrated by @paratexception (twitter nick)

And Big Blue Button you can find: https://meeten.statt-drosseln.de/ the link to the twitter profile of admin at the bottom of the page. 

I will not use zoom.

**Comment by joostdecock** [comment]
@stoffsuchti I understand your concern for privacy, but the choice for Zoom is a pragmatic one given the time that we have to set this up, and the fact that this is new to everyone.
However, this does not mean we're committed to Zoom in the long run.

Before you jump to the conclusion that we can't be bothered to even try. Please note that I've:

 - Setup a landing page at https://meet.freesewing.org/
 - Deployed our own Jitsi instance at https://meetup.freesewing.org

I did a few tests, and people had problems joining the call, and there was a few other issues too.
In the end, I felt uncertain that I would be able to guarantee the well-functioning of the call, and worried that it would be plagued by technical issues.

I am certain this is due to my own limited understanding of the platform. But in the end, that hardly matters.
So, I made a choice to go the *safe* road and use something that works.

I am aware that none of this will convince you to join the call. I just hope that you understand that this decision was not taken lightly.

**Comment by stoffsuchti** [comment]
No it can not convince me, since the possibility i pointed out, dit not require any installation on your servers. 

Yes mumble has a client that need to installed, but its well documented on n several languages. It hals also mobile apps. 

BBB works in the Browser like zoom.... 

Where will future meetings be held? Will you continue to exclude persones like me?

**Comment by joostdecock** [comment]
I have updated this issue with the call notes and a todo list (linking to different issues I created).

I've at-mentioned those people where I know their Github handle by heart. Please leave a comment if you would like to be mentioned (which facilitates collaboration) since I can't tie every face (or zoom name) to a handle (sorry, bad memory).

Speaking of bad memory, I scribbled down notes during the meeting which I can now barely read :joy: so I may have associated things that people said with the wrong names, for I didn't always include a name with something that was said.
Please forgive me a feel free to point out any mistakes.

**Comment by amysews** [comment]
Thanks everyone for the call yesterday, definitely topped up my creative energy bar 😀  

@joostdecock thanks for writing up the notes, I have a few amendments from scanning through my rough notes:

- it was Karen who first suggested the buckets, but I completely agree with the idea 😄 
- there was an interesting discussion on 'measures of success' - you said you've used donations as the measure so far but questioned whether this was the best measure. I think ideas of number of downloads or some quantifiable measure of community engagement were mentioned. I think it's worth defining this at some point as then you have some way of knowing if you are making FreeSewing 'better'
- Debra mentioned having a roadmap to drive efforts and also considering what's NOT on the list. Both of these could them help inform where people spend they're efforts and make sure they're not 'miss-spent'

---

I've been thinking about the 'roadmap' concept a bit more and it made me realise I had 2 assumptions I don't know are true or not so I'd like to check in on them...

1. **Does time matter?** Roadmaps often have loose timings but they don't HAVE to. Would it help bring focus? Or is it not appropriate for voluntary projects?

2. **Should tasks/projects be driven by the project desires or the individuals?** It was something Joost said about people should be able to just do what they love/enjoy doing, that got me thinking (and apologise if I misremembered or misinterpretted what you said Joost). If we all just did the tasks we want to do there are 2 risks; the less sexy stuff never gets done and the project direction may become lost and uncohesive. But I get that we're all just donating our time so shouldn't be forced into doing stuff we don't want to do. So is the compromise that there is some shared vision and therefore 'task list', where people can make suggestions, but it's peer voted? So I'm picturing there's a list of tasks that I would know need doing, in some priority order, and I can choose what to do - recognising sometimes I'll pick the unsexy but urgent stuff but sometimes I might pick off a more fun less urgent thing. There was probably a more concise way of articulating that 😂

**Comment by joostdecock** [comment]
Thank you @amysews I've corrected/updated the notes with your inputs. Onto the questions you rase :)

##### About the _measure of success_

I realized (after the call) that there's an entry in our FAQ titles [What's your end game](https://freesewing.org/docs/about/faq/#whats-your-end-game) which I feel might be a bit to high-level to be measurable.

##### Does time matter?

Not to me. What I mean is that I think it is more realistic to have a roadmap/release schedule that is feature-based, rather that time-based. I prefer to take extra time to work on things rather than releasing them, rather than shipping something half-assed because we have a (self-imposed) deadline to meet.

That being said, it's probably a good idea to put some sort of indication of when we expect to get things done on paper. Like:
 - Add a jeans pattern: Q1 2021
 - Add 3D renders: 2022

##### Should tasks/projects be driven by the project desires or the individuals?

Hmm, this becomes difficult when the project and the individuals are no longer the same.
I feel that right now, the project is steered by the people who put the work in. As such, this question is mostly theoretic.
But this becomes a lot harder to manage when people come in with ideas or suggestions for which they depend on others to implement them.

I feel that in general, it is better to strive for consensus than to force things through via voting as votes tends to divide people.
To make sure the *unintersting* work doesn't get left behind, I was hoping to instill a sense of *ownership* by giving people agency over their own domain. 

A bit like a distributed model of what I do: I appreciate all the help, and any work that's left behind I will take on for at the end of the day, FreeSewing is *my baby*.
I you imagine that (a part of) FreeSewing becomes *your baby* you might also be willing to put in the grunt work because you understand that's what needs to happen.

For the record: I know nothing about babies :joy: I'm just thinking out loud here

**Comment by Sewanista** [comment]
I'm so sorry I missed the call, I just couldn't manage a midnight meeting this weekend. 

I'd like to introduce myself. I'm an experienced custom patternmaker in Perth Western Australia. I am particularly interested in plus size drafting and parametric tools. I've been teaching myself to program Seamly 2D by drafting an example of the block drafts I most commonly use (I collect patternmaking books dating back to the 19th century), but I like the idea of a pattern ecosystem that is more accessible to the end user, as my other passion is teaching patternmaking and building communities of hobby sewers. I founded and host on Facebook both a patternmaking interest group and a large social sewing club in my city. 
I work in high school as the technical support officer in the sewing classes, and I do custom work when I have time. 

I am also halfway through postgrad studies in design, with a focus on hobbyist participation in the fashion system through the use of digital tools. I am interested in becoming involved in freesewing as this very closely aligns with my values and interests.

My online username/handle/business name/instagram is Sewanista.

**Comment by joostdecock** [comment]
Thanks for popping in @Sewanista Sounds like you have a lot to contribute :slightly_smiling_face:

**Comment by creasyo** [comment]
Hi Joost, it's James. Mine is @creasyo

**Comment by joostdecock** [comment]
@creasyo Such consistency 😃 ok, I'll be at-mentioning you from now on

**Comment by tangerineshark** [comment]
Hi! It's Karen. My username's @tangerineshark - I've updated it in Github, but it doesn't seem to have populated its way over to gitter yet

**Comment by tangerineshark** [comment]
Hi! It's Karen - I'm @tangerineshark

**Comment by tangerineshark** [comment]
Also, for what it's worth, if it would help @DocSpencer77 to have another human to test the measurements table against, I'm happy to help out. I've got a pretty good idea of where/how I should deviate up or down from the average measurements, at least!

**Comment by joostdecock** [comment]
Thanks @tangerineshark I've updated the notes, and will at-mention you going forward.

I also just remembered that @creasyo questioned the platforms we use for collaboration, so I've added that to the notes/todo list and created an issue for it.

You should also all have received an invite to join the freesewing organisation on Github. If you accept it your github profile will list you as a contributor and it will add some official aura to you participation :)
Note that not accepting it does not stop you from contributing.

**Comment by lusty** [comment]
Hi, Diana here. I’m @lusty on Github

**Comment by DocSpencer77** [comment]
@Sewanista  Was just typing about our need to understand Plus Size fitting better in our "[Think about how collecting/sharing measurements could or would work" discussion](https://github.com/freesewing/freesewing/issues/527)!  Sounds like your expertise would be very helpful.  Also, we didn't talk about sewing education (at least I don't remember that) in our call, but that is also a subject near and dear to my heart.  Let's talk about that next time we can do a call.  :smile:

**Comment by joostdecock** [comment]
Closed in favor of #553
