### ISSUE TITLE
[bug]: Cannot scroll or zoom in/out with the mouse

### ISSUE THREAD

**Issue by Thrunic** [freesewing/freesewing#5168]
### What seems to be the problem? 🤔

I'm having trouble scrolling and zooming in the lab.patternEditor today. I can zoom in and out of the pattern using the buttons on the top bar (zoomIn and zoomOut), but control+mouseWheel doesn't work. I can't scroll with the mouse, and I don't see any buttons to do so.

This functionality is also broken in the Print Layout screen.

I believe this issue is caused by an update in the last 24 hours, since my older branches are still working fine.

I'm guessing it's from one of the PRs #5157 to #5162 that were merged 4 hours ago, updating the version of various libraries, and that one of the library updates broke it.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
It's probably #5160
