### ISSUE TITLE
Schedule the next FSCC

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#522]
After #515 we should schedule another call for the weekend for 19/20 September.

On question is whether we stick to the same time slot or change it? (no matter what time we pick, it will always be difficult for people on certain time zones).

Another possibility is to setup a different calls for people more or less 12 hours earlier/later (assuming there would be enough interest).

**Comment by Sewanista** [comment]
From the look of the last timetable, I am the person who has the most awkward time slot (midnight on Saturday night for me) I'm fine with sticking to this, if that particular time works best for everyone else, as I'm a bit of a night owl who is too old for clubbing and too young for early nights.

**Comment by creasyo** [comment]
Saturday 19th at the same time works for me

**Comment by DocSpencer77** [comment]
Seems that previous timing was so easy for me that I am tempted to feel guilty.  If we have some folks who are always disadvantaged by the previous timing, I'm happy to trade off the time of day.  But the Saturday the 19th at the same time is good.
