### ISSUE TITLE
[feature]: Update the Twitter Logo to it's new logo (X).

### ISSUE THREAD

**Issue by niranjan-kurhade** [freesewing/freesewing#5225]
### What is it that you would like to see happen? 🤔

I would like to update the Twitter's logo to it's latest logo (X).
To Reproduce-
Go to the footer of the website.  https://freesewing.org/ 

![image](https://github.com/freesewing/freesewing/assets/97905637/4efc3280-281a-4eca-862d-f8730b88689a)

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by niranjan-kurhade** [comment]
Please assign me this issue.

**Comment by SeaZeeZee** [comment]
This is fixed on the new version of freesewing, it probably won't be changed on v2

**Comment by joostdecock** [comment]
Fixed by @TheTanay902 in #5203 Closing.
