### ISSUE TITLE
Setup a call with the social media team

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#523]
See #515 for details. This call should include:

 - @eleonoremilbou (Instagram)
 - @woutervdub (Facebook)
 - @joostdecock (Twitter)
 - @creasyo 
 - Tawney
 - @tangerineshark
 - @annekecaramin

**Comment by creasyo** [comment]
Hello, I think I am going to have a few office days next week but will be done around 1600. Other wise Tuesday and Thursday I am not free from 1830 - 1930. These are UK times.

**Comment by annekecaramin** [comment]
I'm free most evenings around 19:00 (Belgian time). I'll probably be out of town on Thursday and Friday!

**Comment by eleonoremilbou** [comment]
I'm available every day after 7 pm; earlier on Wednesday and Friday.

**Comment by creasyo** [comment]
> I'm available every day after 7 pm; earlier on Wednesday and Friday.

What time zone are you on @eleonoremilbou ?

**Comment by creasyo** [comment]
Can I propose 6pm UK time on Wednesday? How does that sound?

**Comment by eleonoremilbou** [comment]
Belgian, so 1800 UK time.

**Comment by annekecaramin** [comment]
Works for me as well!

**Comment by tangerineshark** [comment]
That works for me!

**Comment by woutervdub** [comment]
I'm so lazy, I googled what that was in my timezone.

I can make that.

**Comment by joostdecock** [comment]
Call scheduled for Wednesday September 9th, 19:00 CET which is:

 - 18:00 in the UK
 - 12:00 for @tangerineshark 
 - 10:00 for @woutervdub

Join meeting at: https://zoom.us/j/93801600725

Does anyone know how to reach Tawney? I'm kicking myself for not asking on the call :see_no_evil: 

(I'm closing this as the actual todo (scheduling the call) is done) But you can still comment

**Comment by joostdecock** [comment]
@TawniS Am I correct in assuming you're Tawney? Because we were trying to organise this call and I didn't know how to reach you 🙈

**Comment by TawniS** [comment]
@joostdecock correct! I will be working during that time on Wednesday but should still be able to join in the call. I may just have to step away for a moment if anything comes up. See you all then 😁

**Comment by TawniS** [comment]
Also just going to pop the link to the discord server in here as I'm hoping we'll be able to get some folks using it! https://discord.gg/YDV4GvU
