### ISSUE TITLE
Agree on a hashtag structure for our patterns

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#524]
We should agree on a hashtag structure that is consistent (and sufficiently unique) to facilitate people sharing posts about our patterns (and us finding them).

See #515 for more info

**Comment by TawniS** [comment]
I think we've sort of come to a conclusion on this in the other thread? #FreeSewingSimon, #FreeSewingCarlton etc.

**Comment by joostdecock** [comment]
You're right. I'll close this.
