### ISSUE TITLE
Establish a 'developer pool' of people who can help pattern designers implement their ideas/designs

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#526]
This is a todo from the FSCC: #515 

The list so far:

 - @woutervdub 
 - @joostdecock 
 - @DocSpencer77 
 - @enyachoke 
 - @rrolon47
 - @AlfaLyr 

If you'd like to be part of this pool, please comment below :)

**Comment by DocSpencer77** [comment]
If you were looking over my shoulder yesterday while I cut out my first t-shirt pattern, you might not want my help.  ;)  But I'm going to make it work!  I'm happy to jump into the pool if you'll have me.

My sleeves were not right... luckily, I had enough fabric to cut them out again.

**Comment by woutervdub** [comment]
This is to bring pattern designers and code developers together. No need to be able to sew!

(I made a shirt some years ago with both the sleeves cut out identical, and the placket sewn in the same. So the shirt had two left sleeves. I discovered this after I had sewn the sleeves in, and I did not have enough fabric. It's a short sleeved shirt now)

**Comment by DocSpencer77** [comment]
Perhaps no need to be able to sew... but it surely helps if the pattern is "sew-able"!  The pattern was wrong.
Sometimes I think I've made every sewing mistake possible... and then I find another possible way to go awry.

**Comment by enyachoke** [comment]
I would like be in this pool as well. I have tried to practise coding patterns for freesewing mostly from tutorials but never really get to complete them especially when stuff don't make sense it will be nice to have a designer hold my hand through this.

**Comment by rrolon47** [comment]
I am maybe a lil late to the game but I would like to join this group too, if possible

**Comment by AlfaLyr** [comment]
I'm a bit late too, and I am a bit away from freesewing at the moment because I'm crazy busy, but I would also like to hepl people who want their patterns translated to freesewing.

**Comment by joostdecock** [comment]
Awesome :slightly_smiling_face: 
I've given all of the contributors who volunteered here the `development` tag to indicate that they are into that kind of stuff.

I think we can close this and keep track of the discussion around pattern design in #563
