### ISSUE TITLE
[bug]: Setting up the dev environment fails due to lerna changes

### ISSUE THREAD

**Issue by timorl** [freesewing/freesewing#5284]
### What seems to be the problem? 🤔

Trying to follow [the docs](https://freesewing.dev/tutorials/getting-started-linux/dev-setup) I run
```
cd freesewing
yarn kickstart
```
and I get
```
yarn run v1.22.19
$ npx lerna bootstrap && yarn reconfigure && yarn buildall && yarn prepare && yarn tips
ERR! bootstrap The "bootstrap" command was removed by default in v7, and is no longer maintained.
ERR! bootstrap Learn more about this change at https://lerna.js.org/docs/legacy-package-management
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The [lerna docs link](https://lerna.js.org/docs/legacy-package-management) suggest replacing the command with a `npm install` and I tried that, but it also fails with a different error.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Is it possible your repository is out of date?
We removed the use of `lerna bootstrap` ... checks notes ... at the end of July.

Perhaps a `git pull` so you have the latest version is in order?
I'll keep this open for now, but I suspect this is an issue on your site.
I just ran (in a new folder):
```
git clone git@github.com:freesewing/freesewing.git
cd freesewing
yarn kickstart
```

and that went smoothly.

**Comment by timorl** [comment]
Yup, terribly sorry, I am terrible at working with yarn/npm/node and when trying to work around that I managed to confuse myself enough to repeatedly try this on a non-updated branch. The current `develop` indeed works properly. <_<"

**Comment by joostdecock** [comment]
No worries, glad it's resolved 😊
