### ISSUE TITLE
What platform should we use to coordinate collaboration?

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#530]
This is a Todo issue from #515 

The question is whether we should consider other/additional tools to foster collaboration between collaborators.
We use github/gitter now, which is geared towards the developer side of our community, and perhaps a bit of a hurdle for the maker side.

If you have ideas and/or suggestion, please feel free to comment on this issue.

**Comment by TawniS** [comment]
Would it be worth setting up a discord server for ease of communication?

**Comment by joostdecock** [comment]
I did that a while back: https://discord.gg/YDV4GvU

It would not only make my life a lot easier (since I use it for work) it also provides a bunch of things that I miss. Like notifications (that work) and a good mobile app.

I've been reluctant to force it upon others, but I'd be delighted to start using it 🙂

**Comment by joostdecock** [comment]
Question is answered, move to Discord is ongoing, closing.
