### ISSUE TITLE
[feature]: Change Twitter Logo

### ISSUE THREAD

**Issue by Vijaykv5** [freesewing/freesewing#5301]
### What is it that you would like to see happen? 🤔

Change the Twitter Logo to X

<img width="1325" alt="Screenshot 2023-10-28 at 12 13 03 AM" src="https://github.com/freesewing/freesewing/assets/94985341/1b2d0fa6-2991-49f9-90fc-72f7e1b05557">

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

I would love to work on this issue

**Comment by joostdecock** [comment]
@Vijaykv5 hi there, I'm sorry that this was assigned to you because it's already implemented in #5275
