### ISSUE TITLE
[bug]: Develop won't build, tests won't build

### ISSUE THREAD

**Issue by Thrunic** [freesewing/freesewing#5313]
### What seems to be the problem? 🤔

Attempting to run kickstart or buildall on the current develop build causes errors, notably

$ node build.mjs
       (node:4593) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
       (Use `node --trace-warnings ...` to show where the warning was created)
       (node:4593) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
       ✘ [ERROR] The JSX syntax extension is not currently enabled

           ../../sites/shared/components/logos/freesewing.mjs:23:4:
             23 │     <svg {...svgProps}>
                ╵     ^

ESLint Changed Files, ESLint All Files, and All Tests (the tests that are run on PRs on Github) fail with the same error message.

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

I believe the problem was introduced in the past few days.

**Comment by joostdecock** [comment]
Introduced in #5292 by a new contributor, so tests didn't run without approval.
Fixed in #5314
