### ISSUE TITLE
[bug]: /scripts/optiondocsimages.mjs doesn't work.

### ISSUE THREAD

**Issue by Thrunic** [freesewing/freesewing#5321]
### What seems to be the problem? 🤔

When I try to run node ./scripts/optiondocsimages.mjs to generate the design option .svg files, it tries to look in markdown/org/docs/patterns/..., which no longer exists.

I'm not sure if the script is still used. If it is still in use, it should be updated, otherwise deleted.

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

⚠️  markdown/org/docs/patterns/bee/options/reversible/bee_reversible_sample.svg
Error: ENOENT: no such file or directory, open '/home/thrunic/onyx/freesewing/markdown/org/docs/patterns/bee/options/reversible/bee_reversible_sample.svg'
    at Object.openSync (node:fs:603:3)
    at Object.writeFileSync (node:fs:2324:35)
    at createImages (file:///home/thrunic/onyx/freesewing/scripts/optiondocsimages.mjs:65:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/thrunic/onyx/freesewing/markdown/org/docs/patterns/bee/options/reversible/bee_reversible_sample.svg'
}
(repeated for every option of every design)

**Comment by joostdecock** [comment]
That script is no longer used, and those images are no longer part of the documentation.
