### ISSUE TITLE
[feature]: Add the strap dimensions to the non-expanded Waralee mini dimensions

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#5328]
### What is it that you would like to see happen? 🤔

At the moment, if you choose the non-expanded Waralee pattern, you get a minilayout that helps with the paper free dimensions of the main trouser, but doesn't include the dimensions of the straps (which can be found on the expanded layout, or if it's not expanded, found in the notes for which pieces are not shown).
Propose to include the strap dimensions as part of the minilayout (or just printed on the crotch curve as there's space there too)

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

Not sure if there's other patterns this could benefit offhand.

**Comment by joostdecock** [comment]
I am in general not in favor of this *use patterns as documentation* approach.
SVG is an absolute nightmare to layout text in, plus translation is non-trivial.

The *minilayout* as exists now is IMHO already muddling the waters between pattern and documenation, so I'm not certain that going further down that road is a good idea.

That being said, I'm going to assign this to @woutervdub and I'll let him make the final decision.

**Comment by woutervdub** [comment]
I'm agreeing with @joostdecock in principle. What I do think would be a good idea is to allow the printing process to include the designer's notes. Probably as part of the first page, or as separate pages included in the PDF. This should probably be an option in the printing dialogue. And it may be useful to allow the designer in the code to set a note to be printable or not.

**Comment by TriploidTree** [comment]
It's a subtle one, because it's pattern specific notes rather than general documentation. Where docs aren't made to measure, I'm used to seeng tables like this for rectangular included in the docs, but also, I've started to see people include more notes on their patterns. After I make a pattern once, I tend to write the notes on the pattern so I never need to look at the docs again (so waistband rectangles, note about the version, seam allowance, etc). As the minipattern is more notes for a pattern rather than a doc, it would make sense to include the strap measures with it. 
I think @woutervdub is on to the right thing putting it in the first page of the pattern export (though if you export the svg you wouldn't benefit from the notes).

**Comment by woutervdub** [comment]
In the same way, it may be useful to allow the `measurements` and `options` to be printed too. That way you have a record of how the pattern was generated.

**Comment by woutervdub** [comment]
I'm closing this in favour of a more generic one.
