### ISSUE TITLE
[docs]: The link to bluesky on the bottom of the next webpages links to the youtube

### ISSUE THREAD

**Issue by TriploidTree** [freesewing/freesewing#5329]
### Where can we see the problem? 🤔

https://next.freesewing.org/

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

At the foot of each webpage, the links to social media, the bluesky icon links to the youtube account.
Link to the bluesky account or hide the icon.

**Comment by TriploidTree** [comment]
https://bsky.app/profile/freesewing.org is the correct link

**Comment by sohamtembhurne** [comment]
hey @TriploidTree ,can I make a pull request on this ?

**Comment by TriploidTree** [comment]
Consider yourself assigned!

**Comment by sohamtembhurne** [comment]
Hi @TriploidTree , on which branch is the source code for v3 ? 
I can only see the footer component of v2 on development branch

**Comment by TriploidTree** [comment]
Good question, as of yesterday the V3 site is now the main site, and it looks like the issue is fixed?

**Comment by joostdecock** [comment]
This was fixed as part of the last batch of fixes prior to migrating the website.
Sorry about that @sohamtembhurne I didn't realize this was assigned to you (nor was it very actively on my radar)
