### ISSUE TITLE
Setup/Establish a hashtag that people can use to ask questions about freesewing, our patterns, fit issues and so on

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#540]
This is a todo from #593 -- I hope the title is self-descriptive./

I'm assigning this to @creasyo to avoid paralysis by distributed responsibilities. But obviously everyone's input is welcome.

**Comment by joostdecock** [comment]
Am I showing my age when I suggest `#askFreeSewing` ? :thinking:

**Comment by TawniS** [comment]
#askfreesewing makes a lot of sense to me and doesn't seem to already be in use on Instagram. I think it might also help to make mention of the @freesewing_org handle on the website and encouraging people to tag it when they post their makes.

**Comment by creasyo** [comment]
Yep I think simple is best. Sounds good to me. 

Have you had a think about the pattern hashtags? 

#SimonFreeSewing
#TheoFreesewing

Ect?

**Comment by joostdecock** [comment]
Does that risk that people misunderstand things?

Like, `#ShinFreeSewing` => wtf? What is it with people without shins and sewing that's so special?

Would `#FreeSewingShin` perhaps be better for that?
It would also help with the auto-suggest since all our various hashtags would start the same :thinking:

**Comment by creasyo** [comment]
Yep that is very true. Happy with that.

**Comment by joostdecock** [comment]
Seems like this is settled. I'll start adding these to the website.
