### ISSUE TITLE
Setup a FreeSewing YouTube channel

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#541]
This is a ToDo from #539 
The idea is to have a channel for freesewing, rather than videos under @joostdecock 's YouTube account because who the heck is that guy anyway.

I think the issue here is that these accounts are always linked to a Google account, or they not?
So that might need some consideration for what happens when people come and go?

I know next to nothing about YouTube so please chime in.

**Comment by TawniS** [comment]
I can do a bit more digging into this after work today but here's some information about having multiple people managing a YouTube channel to start with.

https://support.google.com/youtube/answer/4642409?hl=en

**Comment by TawniS** [comment]
If I'm reading this correctly setting up the channel with a brand account would allow us to add or remove users as they come and go. Sounds like what we're looking for, I think!

**Comment by joostdecock** [comment]
I think you're right @TawniS So I'm going to go ahead and assign this to you ;)

**Comment by TawniS** [comment]
I should have known :P on it, I'll let you know what I come up with!

**Comment by TawniS** [comment]
So, from what I've found it will need to be tied to a Google account. Once a channel is created with this account we can add contributors so they can update, add content, etc. @joostdecock  Do you already have a Google account for free sewing, and if not are you alright with me setting one up?

**Comment by joostdecock** [comment]
tx @TawniS 

> Do you already have a Google account for free sewing

No

> are you alright with me setting one up?

What are you waiting for? :slightly_smiling_face:

**Comment by joostdecock** [comment]
Great work!
I'm going to close this, as the actual todo is done. Managing the channel is more of an ongoing thing :)
