### ISSUE TITLE
Setup a Facebook group (note that we currently have a Facebook page but a group is perhaps a better fit)

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#543]
This is a Todo from #539 

The idea is to setup a Facebook group as that will foster more community participation than a page.
Since @annekecaramin volunteered to (help) moderate, and @creasyo came up with the plan in the first place, I'm assigning this to both :slightly_smiling_face:

**Comment by creasyo** [comment]
I think this one can be closed as @annekecaramin has set the group up :)

**Comment by joostdecock** [comment]
I've added the both of you to the `mods` group, which gives you `triage` permissions on all of FreeSewing's repositories.
Long story short, you can close it yourself :) And you can assign issues to people, add labels, and whatnot.

Let me know if you have any questions.

**Comment by creasyo** [comment]
Set up by @annekecaramin and closed by @creasyo :D
