### ISSUE TITLE
[bug]: `rmcutonfold` macro does not remove the `store.cutlist.setCutOnFold`

### ISSUE THREAD

**Issue by woutervdub** [freesewing/freesewing#5448]
### What seems to be the problem? 🤔

Removing the cutonfold macro does not remove the store.cutlist entries that correspond to it

### Design / Plugin / Package 🧐

cutonfold.mjs

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

**Comment by joostdecock** [comment]
Resolved in #5449
