### ISSUE TITLE
Edit the Teagan tutorial video

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#548]
Raw footage is being uploaded here: https://www.dropbox.com/sh/ykdf9fs851x3r5n/AAATj6pmJpZPBavIn42ajQJGa?dl=0

Note that I always find that getting good (voice) sound quality is tricky, so I stopped talking during the videos and did a separate voice-over.
Obviously, I only decided to do that 2 videos in or so, so sorry about that.

I'm not certain the end result is usable at all. Feel free to tell me this is all garbage and give pointers of what I can do better next time.

Also, sorry for just assigning this to you @creasyo :wink:

**Comment by joostdecock** [comment]
Upload is complete now. Note that there's no part 4. I just messed up the numbering :see_no_evil:

**Comment by creasyo** [comment]
Hey, just downloaded the footage. The voice over works with the footage where you can't see you talking. It wont work when you are doing bits to camera and the lip sync is out. It's just a bit visually confusing. 

I have just done a very quick tide up of the GoPro audio as a test. It takes out the hissing and sounds allot better. In places it can sound like you are underwater but i think that is only because you hear the two in a comparison. Once you get used to it you won't notice. If you are happy I can work a bit more on the audio and it will be a bit better. 

I think how you fix it is by purchasing a lav mic and recording the audio separately. That will really improve the quality. 

Have a look at the test clip and let me know what you think. 

https://drive.google.com/file/d/1JZY4yK132cj2axYyKY67Fwwpoi9aNGXf/view?usp=sharing

Love your workspace by the way!!

**Comment by joostdecock** [comment]
I have a lav mic (bought it for this kind of stuff). But since I control the GoPro with my phone, and the lav mic is connected to my phone, the recording stops when the app goes to the background. I couldn't get it to keep recording. (but perhaps I'm just a noob)

I got fed up fiddling with it, and essentially wanted to send you a pile of stuff so you would tell me the best way to record things next time for I clearly have no idea what I'm doing.

**Comment by creasyo** [comment]
hmmm ok, how long is the cable for the lav mic? Could it be plugged into a laptop/ipad or other device? 

Would you be up for filming it again or was the audio ok?

**Comment by joostdecock** [comment]
I could not access that link. It had a 'request access' button which I clicked :) But I still can't access it

**Comment by creasyo** [comment]
Sorry try again 

https://drive.google.com/file/d/1JZY4yK132cj2axYyKY67Fwwpoi9aNGXf/view?usp=drivesdk

**Comment by joostdecock** [comment]
That sounds fine to me. I will try to do better next time, but if I'm going to record another one, perhaps it makes more sense to do another pattern?

**Comment by creasyo** [comment]
Amazing! Do you have the logo files anywhere? Could you drop it in the Dropbox folder?

**Comment by joostdecock** [comment]
The SVG is available here: https://freesewing.org/logo.svg

Perhaps good to know what FreeSewing black is `#212529`, or gray-9 (we use [open color](https://yeun.github.io/open-color/) for our colors)

**Comment by creasyo** [comment]
Amazing.

I think i have done the main edits. I think there might be some bits missing.

I have 10a-KnitBindingFinish.mp4 video but no audio and 10b audio and no video
There is also 13-voice.mp3 but no 12 video

Also you mentioned a sewing machine version of this. Is that still to come?

**Comment by creasyo** [comment]
What do you think to this? A simple title style? 

https://drive.google.com/file/d/1_9zUvw-wSdyUqSUWkR8EQWI8dkn40z3q/view?usp=sharing

**Comment by joostdecock** [comment]
> What do you think to this? A simple title style?

That works for me :) 

> I have 10a-KnitBindingFinish.mp4 video but no audio and 10b audio and no video

I probably shouldn't have uploaded that one. I re-did it in 10b, which is why I added no audio for it.

> There is also 13-voice.mp3 but no 12 video

You mean no 13 video right?
I'm uploading it now, but it's just boring shots of me hemming :wink:

**Comment by joostdecock** [comment]
> Also you mentioned a sewing machine version of this. Is that still to come?

Before making any more videos, I'd like to get a better flow going so we can get better results.
Since you're the expert, I'd like your opinion on this.

**Audio**

I feel this is important to get right. Since sewing machines can be noisy, it's probably best to record a separate audio track.
My attempts to do that with my phone turned out to be too cumbersome, and recording a separate voice-over is just weird.
So I was thinking about investing into something to address that. Perhaps [the Zoom F1-LP](https://zoomcorp.com/en/de/handheld-video-recorders/field-recorders/f1-lp/). Thoughts?

**Video**

I like using the GoPro because it's a lot easier than hauling my DSLR around. It also has a super-wide angle which makes it easier to bring things up close.

That being said, do you think the *fisheye* view a problem? 

**Vantage point**

I hang it on my ceiling for the sort of *top-down* views where I explain how things are done. While I agree it's a bit of a weird view, I do think it's a good pov, although I might need to center it a bit.

For the actual sewing, I'd like to look into ways that I can place the camera in front of my so you can get more of a real point-of-view as if you were making it yourself. I have a tripod for my DSRL, so perhaps [a GoPro adapter](https://www.amazon.com/Ecosystem-Conversion-Mounting-Aluminum-Accessory/dp/B07L17W3BQ) + [gooseneck](https://gopro.com/en/us/shop/mounts-accessories/gooseneck/ACMFN-001.html) ?

Thanks for your advice :)

**Comment by creasyo** [comment]
> I probably shouldn't have uploaded that one. I re-did it in 10b, which is why I added no audio for it.

sorry i might be being slow but the video is only 24 seconds long and the audio is 2 mins. Feels like there is something missing there.

**Comment by creasyo** [comment]
> **Audio**
> 
> I feel this is important to get right. Since sewing machines can be noisy, it's probably best to record a separate audio track.
> My attempts to do that with my phone turned out to be too cumbersome, and recording a separate voice-over is just weird.
> So I was thinking about investing into something to address that. Perhaps [the Zoom F1-LP](https://zoomcorp.com/en/de/handheld-video-recorders/field-recorders/f1-lp/). Thoughts?

Audio is normally overlooked when people try and do videos so it makes me happy you are willing to invest in getting it right. Its something that improves overall quality. We use zoom recorders at work, i have not tried out this one but it looks great! If you are able to i would get one. 

> Video
> 
> I like using the GoPro because it's a lot easier than hauling my DSLR around. It also has a super-wide angle which makes it easier to bring things up close.
> 
> That being said, do you think the fisheye view a problem?

No i like the gopro. Its easy to use and you can get it into position easily. If its easy its more likely to get done. 

> Vantage point
> 
> I hang it on my ceiling for the sort of top-down views where I explain how things are done. While I agree it's a bit of a weird view, I do think it's a good pov, although I might need to center it a bit.
> 
> For the actual sewing, I'd like to look into ways that I can place the camera in front of my so you can get more of a real point-of-view as if you were making it yourself. I have a tripod for my DSRL, so perhaps a GoPro adapter + gooseneck ?

Top down view works for me to. It can be hard to see the details sometimes but maybe you can shoot those seperatly so viewers can see a bit closer. 

All great ideas, the machines sometimes shift your gopro so something to anchor it in place like the gooseneck would be great. Gives you real flexibility to get the gopro in the right position. 

I realise its a financial investment but all those bits would really improve the videos. Its basically what i would have recommended haha when can you get them??

**Comment by joostdecock** [comment]
Ok, I've ordered the Zoom recorder, and a GoPro goosneck thingie. Should be here towards the end of the week.

**Comment by creasyo** [comment]
@joostdecock can you have a look at clip 10. The audio is too long for the video so i am not sure what you want to do with it.

**Comment by joostdecock** [comment]
You're asking my to look at myself? Do you have any idea how much I hate that?! :joy: 

I don't think we need part 10. I did a few takes for the neck binding, and god knows what I was thinking, but I don't think part 10 provides anything that isn't available in the other parts.

Also, my recorder thingie arrived today :slightly_smiling_face: Are you going to be on the call later today? Perhaps we can discuss how to move forward.

**Comment by creasyo** [comment]
Cool then I think those first videos are done. 

I have uploaded them as drafts on YouTube. They just need renaming and directions done ect. Writing is not my strong point as I am dyslexic so if we could task that to someone else I would be grateful.

That's exciting about the new kit! Yes I will be there later let's talk then.

**Comment by joostdecock** [comment]
No worries. You've done more than enough :) we can get someone to write the titles and whatnot :+1:

**Comment by TawniS** [comment]
Perhaps I can be of some help there? Since I'm already on the YouTube channel, I might as well make myself useful 😝

**Comment by TawniS** [comment]
I was also thinking I'd put it all in a playlist so it's easier to find all of the relevant videos once we start uploading more to the channel. On that note, it looks like there's not a way to just move the videos from your channel, Joost. We'll just have to re-upload if we want to move them.

**Comment by creasyo** [comment]
Amazing, thank you both. I am going to close this now as this part is done and a new todo has been raised for the second set of videos.

**Comment by joostdecock** [comment]
There are few things I enjoy more than other people closing issues 😂 thanks @creasyo 

@TawniS I lf you could make sure videos get titles and tags and so on, and put them in playlists, that would be a great help. As far as I'm concerned you run our Youtube channel now 😋
