### ISSUE TITLE
Who has had a first look at Teagan?

### ISSUE THREAD

**Issue by creasyo** [freesewing/freesewing#550]
To keep track of who has had early access to Teagan. We should follow up for content later. Please add who you send it out to here

List:

 - Charlotte from englishgirlathome
 - Julian Collins of Sew Manly
 - Kelly Hogaboom

**Comment by joostdecock** [comment]
I shared it on Discord, and the Discord link itself is on Gitter, which is on our website. So in principle, anyone can stumble upon it :wink: 

That being said, I know these people have made one:

 - @joostdecock 
 - @annekecaramin 
 - @tangerineshark 

I know the intent here was more to keep track of what *outsiders* we're sending it to, but just wanted to bundle up this info in case we forgot who made what again.

**Comment by annekecaramin** [comment]
I contacted Charlotte from @englishgirlathome and she wants to make one for herself and her partner so she can compare results! Probably around late September/early October. She'll post on her accounts and we can reshare her content :)

**Comment by creasyo** [comment]
Julian Collins of Sew Manly
Kelly Hogaboom

**Comment by joostdecock** [comment]
I've put the list in the initial issue (sorry for putting words in your mouth @creasyo ) as that might be easier to keep track of things than scrolling down comments.

**Comment by stoffsuchti** [comment]
What is of pattern is Teagan? Can I have access too please? I'm nether on discord nor on zoom. So i would appreciate if you could share it with me.

**Comment by stoffsuchti** [comment]
What is of pattern is Teagan? Can I have access too please? I'm nether on discord nor on zoom. So i would appreciate if you could share it with me.

**Comment by joostdecock** [comment]
@stoffsuchti You can keep track of the changelog to see what's going on: https://github.com/freesewing/freesewing/blob/develop/CHANGELOG.md
In addition, https://next.freesewing.org/ always runs the develop branch of our website which includes all features that are in the pipeline. You can try Teagan there today.

You can also check the milestones: https://github.com/freesewing/freesewing/milestones
You'll see there that Teagan is scheduled for release on the 3rd of October.

**Comment by joostdecock** [comment]
Teagan has been out for a while. Closing.
