### ISSUE TITLE
[bug]: `path.split()` missing parts in one of the resulting segments

### ISSUE THREAD

**Issue by woutervdub** [freesewing/freesewing#5569]
### What seems to be the problem? 🤔

When a part is `split()` using a `point` that was obtained with a `intersects()` method, sometimes the `path` is split into two parts where one part is missing most parts in the `ops` array. This only occurs in very limited cases.

Attached are two JSON files with objects containing the path (path), the intersecting path (intersectingPath), the intersecting point (intersectPoint), and the result (results). One (`correct.json`) is where the `split()` results in a correct array of segments, and the other (`wrong.json`) where the second segment is missing most of the parts at the end. Included are also two screen captures of the problem, which correspond with the JSON files.

May of may not be useful: The path used to be split was generated using the `offset()` method. The path was then extended on both ends with a `line()` to make sure there is always a intersecting point.

Code segment:
```javascript
      paths.front = ExtendPath(paths.front.offset(gussetWidth)).hide()
      paths.waistTemp = new Path().move(points.frontWaistband).line(points.centerWaistband)
      points.frontWaistband = paths.front.intersects(
        new Path().move(points.frontWaistband).line(points.centerWaistband)
      )[0]
      console.log({
        path: paths.front,
        intersectingPath: paths.waistTemp,
        intersectPoint: points.frontWaistband,
        results: paths.front.split(points.frontWaistband),
      })
```

[correct.json](https://github.com/freesewing/freesewing/files/13502921/correct.json)
[wrong.json](https://github.com/freesewing/freesewing/files/13502922/wrong.json)

![wrong](https://github.com/freesewing/freesewing/assets/24414629/24286802-99ee-423f-8a17-d6d88602e79a)
![correct](https://github.com/freesewing/freesewing/assets/24414629/08800edb-e577-45a3-95d6-b6a617d02bd6)

### Design / Plugin / Package 🧐

packages/core

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

**Comment by joostdecock** [comment]
Can we see this code somewhere? There's things in here that make it more involved that a minimal reproducible bug (like the `ExtendPath` call).

**Comment by woutervdub** [comment]
I figured that the two JSON files would allow you to reproduce the exact paths that caused the error, and the one that did not.

The `ExtendPath()` code  is here:

```Javascript
    const ExtendPath = (path, length = 100) => {
      return new Path()
        .move(path.shiftAlong(1).shiftOutwards(path.start(), length))
        .line(path.start())
        .join(path)
        .line(path.shiftAlong(path.length() - 1).shiftOutwards(path.end(), length))
    }
    ```
    
    The full code can be seen in `/designs/lumira/src/shape.mjs` in https://github.com/woutervdub/freesewing/tree/lumira
