### ISSUE TITLE
Feedback: New homepage design

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#558]
Hi all,
I have reworked the homepage a bit because I wanted it to focus more on the fact that Freesewing is built by a community.

You can preview the new home page design here: https://next.freesewing.org/

I started out with this *all shapes welcome* idea (all colours too) but dropped that slogan in the end because it's cheesy AF.
Still the random shapes and colours are somewhat referring to that idea.

The most important things to note (and give your feedback on) are:

 - the slogan has been replaced by the top left text
 - a (random) contributor is *showcased* on the homepage to highlight that we're just a bunch of people working together

Please note that I've quickly put together [an example contributors file](https://github.com/freesewing/freesewing.org/blob/develop/contributors.yaml). If you're not in the list, please don't be offended, I just added a few and left it at that for now (I'm not on the list, if that makes you feel better 😉)

Questions :

 - Do you hate it?
 - Will contributors be willing to have their name/face/role on the website?
 - Do you feel it gets the message across?
 - What would you do differently?

As always, all feedback welcome 🤗

**Comment by joostdecock** [comment]
Tip: You can toggle dark mode to force a re-render (which will give you a new randomized layout)

**Comment by eleonoremilbou** [comment]
I like the blobs, although they could maybe be refined a bit colour-wise. I also like the showcase. Some tweaks to the copy could clarify a bit more that "we are" not just this person that you're seeing right now. I can make a few copy suggestions if you'd like.

I'm not sure about the icon menu. I think people need a bit more hand-holding at this stage (they're on the homepage, maybe for the first time, so clearer is always better).

**Comment by joostdecock** [comment]
- I've updated the icon navigation 😇
 - I'll take your suggestions for better copy 🙂
 - Not sure what you mean by *being refined colour-wise*. Do you not like the colors? We use [open-color](https://yeun.github.io/open-color/) for our color scheme. The blobs can appear in all its colours (except gray) in shades 3 and up. I've changed it so the text is black/white depending on the color shade. But I have changed nothing else

**Comment by woutervdub** [comment]
I like the design. I won't comment on colours, since I seem to be terrible at those things.

The ration between width and height could be favoured a bit more to wider on a desktop browser. The bottom navigation is gone when I do full screen on a standard laptop screen.

I don't mind being in the list. It probably should be an opt-in thing.

As far as getting the message across, I'm not sure. If we really want to emphasize the different body type catering, should we maybe have some library of silhouettes that could randomly be ghosted over/under the graphics on the page?

**Comment by tangerineshark** [comment]
I like it!!

I would agree the contributor list should be opt-in. You're welcome to keep me on it!

I'm also missing the bottom navigation on laptop.

For the colors, I'm pondering accessibility with respect to contrast. Aesthetically, I love that the blobs cut across text, but the shift in color mid-word might be difficult for some folks. Especially when the blob color is light, the text outside the blob is fairly light on white / low-contrast. You could solve a bunch of ways. Some options are: make the blobs encompass the entirety of the text, shift the color range darker, select a specific subset of colors that you feel really good about...

One cool thing about the blobs changing is that it could make things easier for some folks with lower vision. If you can daylight that the blobs can change somehow, you could give someone the ability to toggle through until they find one that works for them. (Sorry if this doesn't make sense, feel free to ask for clarification. I'm thinking of, for instance, one colleague with low vision who uses red/black/white color schemes for everything in her life, even though red on black is generally considered low-contrast and not ideal.)

**Comment by tangerineshark** [comment]
I should add that that last thought above re: changing color schemes is definitely a bonus, not a necessity. Also if you solve for contrast, it becomes way less relevant. I may have just gotten enamored with the notion of picking a color scheme that suits your eyes/vision.

**Comment by eleonoremilbou** [comment]
Maybe my "issue" with the colours is just that they are so random. I think I'd prefer a more curated colour scheme, but it looks like that's just me.

As for copy: I like that "we are" refers back to #WeAreFreeSewing, but it looks strange coupled with a picture of just one member. Some alternatives:
- Meet the team
- Meet the community
- Join the community
Or simply:
- Meet: (Wouter/Karen/Joost/whoever)

**Comment by joostdecock** [comment]
I've published another update that hopefully addresses the most pressing issues.
I'll leave it at this for now, but I've added it to the agenda of the next call. See #553

**Comment by joostdecock** [comment]
I have published another update to improve the legibility.
Since less is more, I've also made an update to only use 1 (randomized) color. Hopefully that makes @eleonoremilbou happy :wink: 
And there's better support across different breakpoints. (read, across devices)
