### ISSUE TITLE
Contibutor call: October 3rd 2020

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#561]
You are all invited to the contributor call.
Please leave a comment to put things on the agenda. This issue will be updated after the call with notes and todos.

## About

 - Location: https://meet.freesewing.org (redirects to https://zoom.us/j/5168598687 )
 - Date: Saturday October 03, 2020 16:00 UTC, which is:
   - Los Angeles: 09:00
   - Chicago: 11:00
   - New York: 12:00
   - São Paulo: 13:00
   - London: 17:00
   - Paris: 18:00
   - Johannesburg: 18:00
   - Moscow: 19:00
   - Mumbai: 21:30
   - Hong Kong: 00:00 on Sunday
   - Tokyo: 01:00 on Sunday
   - Sydney: 02:00 on Sunday

## Agenda

 - Welcome (are there new faces?)
 - Today is the planned 2.9 release date. Did we make it?
 - Picking a release date for 2.10 (and perhaps a word about minor releases vs patch releases)
 - So we have a newsletter now. Now what?
 - What are we going to work on/prioritize next?
 - Free discussion on what comes to mind

## Notes

- @joostdecock welcomed people to the call, there were plenty of familiar faces, no new participants this time around
- @joostdecock announced that we had released 2.9 a few hours prior to the call, but to make that happen he removed two things from the milestone:
   - Planning of contributor calls: Since this was not ready, we were out of time, and so it was dropped as a blocking factor
   - Newsletter: Since this idea felt a bit undercooked
 - He also explained briefly how we handle minor releases (every time there's a new pattern) and patch releases (to fix bugs). And that changes to the website (to content or style and so on) are out-of-band of the release schedule and can happen multiple times per day
 - Since @woutervdub has already submitted a new pattern (albert) a preliminary release date of 17 October was floated for 2.10
 - @DocSpencer77 wanted to hear from @enyachoke about the collaboration with @Sewanista 
 - @enyachoke explained that they had started working on porting @Sewanista 's skirt block to FreeSewing. That was a warm-up exercise prior to tackling the bodice block. He explained that it was a fairly straight-forward process and that by using the Discord chat, he was able to get quick feedback and inputs whenever he had questions. Feedback and inputs not only from @Sewanista but also from other people. He's happy with the process that's been made and since it's been a bit of a learning process, he looks forward to refactoring the code. In general, he feels this is a good way to work
 - After this @joostdecock brings up the topic of the newsletter. What do we want it to be?
 - @tangerineshark feels that rather than being beholden to a regular release, it would be better to sent out a newsletter when we have something to say. 
 - This suggestion of a content-driven release schedule initially seemed to gather steam, but @rrolon47 countered with the proposal of a quarterly (4 times per year) release schedule, which would guarantee we had something to say. 
 - This every-three-months release cycle would make it into a slightly different type of content, allowing more long-form writing and would avoid that it is just the latest blog post in an email form
 - @DocSpencer77 would like to see this sort of long-form content and @eleonoremilbou pointed out that we have different audiences (from more sewing inclined to more coding inclined) and it could be an opportunity to bring together some content of all those different aspects of freesewing into a single publication
 - @enyachoke would like to see the cool things that the community is doing in such a publication
 - @joostdecock pointed out that if we send out newsletters once every 3 months, it could take up to 3 months after subscribing before somebody got the first message. How would we deal with that. It was proposed to keep an archive of prior content and send a 'welcome' message with links to it.
 - The following people expressed an interest at contributing to the newsletter (for content):
   - @eleonoremilbou 
   - @tangerineshark 
   - @DocSpencer77 
   - @joostdecock 
 - @joostdecock raises the question of whether we need to provide multi-lingual documentation for developers (since it's a lot more work). Is it realistic that somebody who cannot understand English would develop on/with FreeSewing, and if they do, how do we support them? The consensus is that we should _ask around_ to see if people need this
 - Katie, who participated in #570 would like an update on what's going on on the pattern design front. @enyachoke gave a brief status update about the work he is doing with @Sewanista on the block they are working on.
 - Katie was also wondering where the Paco documentation was, and @joostdecock admitted he had yet to write it.
 - There was a brief discussion about different techniques of finishing the cuffs on Paco, and @eleonoremilbou pointed out that people were asking about the docs to see if they could perhaps help. @joostdecock explained that everyone can help writing documentation. Even if currently how to get them added to the site is not well documented (see todo's) you can just write them and we'll deal with it later
 - @joostdecock also said that making the illustrations for documentation is a real time-sink. @tangerineshark suggested that using pictures might be faster, while @rrolon47 said she had some experience with making illustrations
 - @joostdecock also promised he'd add the list of all patterns that lack documentation to the call notes: see #529 
 - @rrolon47 asked for feedback on [her video](https://www.youtube.com/watch?v=-_8IetccPi8) which was well received with several people encouraging her to make more such content
 - @DocSpencer77 remaked that she found it difficult to find information on the freesewing.dev website, and that the navigation wasn't the most intuitive. @joostdecock confirmed that this was a bit of a neglected area, and on his todo list for some TLC
 - Called wrapped up shortly after the hour. For the next call, see #593

## Todo

 - Ask around whether we need to keep multi-lingual developer docs: #594
 - Bring developer documentation site in line with recent work on website: #595

**Comment by joostdecock** [comment]
Oops, closed this by accident

**Comment by Sewanista** [comment]
I'm not going to make this call, I need an early night. I'm away from my studio next week but I'll keep up with the discussions on Discord.

**Comment by joostdecock** [comment]
Thanks for letting us know @Sewanista Sweet dreams :sleeping:

**Comment by joostdecock** [comment]
While writing these notes I was wondering: should we setup a newsletter-team (which would mean at least a discord channel) to coordinate the newsletter things?

**Comment by joostdecock** [comment]
I'm closing this as the call is over, but don't let that discourage you from commenting

**Comment by tangerineshark** [comment]
Hey! If you'd like, I can have a go at the Paco documentation before Oct. 17th. I'll probably have to check back in on the elasticated cuff to see what people like best, but I could at least take care of some of the legwork.

**Comment by joostdecock** [comment]
> I could at least take care of some of the legwork

I see what you did there :slightly_smiling_face: 

That would be awesome. Really :heart:

**Comment by tangerineshark** [comment]
Hi! So I have a rough draft of Paco documentation, and I'm currently editing it as I work through making the pants myself, so I can catch errors. I'm taking pictures as I go (they're just photos for now, but I could translate them to digital sketches/illustrations with a bit of time). Do you have a preferred method for editing documentation (and is it just uploading via pull request)? Do you like to edit things, or do you prefer to wait for users to share where shifts in documentation are needed? And lastly, would you rather wait until illustrations are complete before seeing the documentation, or is it helpful to see the text first, then add imagery?

**Comment by joostdecock** [comment]
@tangerineshark hey that's awesome 🎉

You can publish what you have. And iterate on it later.

The idea that something has to be perfect before you put it online can be paralyzing. If what you have is one iota better than what's on the site now (which is nothing), then push get out there.

Also: pictures are fine 👍
