### ISSUE TITLE
[feature]: include different dart shaping in Noble

### ISSUE THREAD

**Issue by lasermonkey12** [freesewing/freesewing#5616]
### What is it that you would like to see happen? 🤔

I like my princess seams to do more of the shaping in the side panel, leaving the center front panel mostly straight on the side where it connects to the side front panel.  Carlita is a good example of the shaping I prefer.  It would be great if Noble could include that style of shaping as an option.  First comment will have a reference picture and information

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

**Comment by lasermonkey12** [comment]
Left 2 pieces are from a vest with the shaping I like, center is Tristan, right is an armhole-darted Noble
![20231209_174744](https://github.com/freesewing/freesewing/assets/55415375/44076d3a-19f3-42d2-aced-aba22fb4c023)
The left side pieces give me a dart shape where the seam follows the curve of my waist (red vest with blue line) instead of curving in (muslin Noble mockup) 
![20231207_165325](https://github.com/freesewing/freesewing/assets/55415375/12f35a06-9a43-4141-8d4a-0912732c9a69)
![20231204_125421](https://github.com/freesewing/freesewing/assets/55415375/ba7c0509-db7d-4ac9-8fad-3ce8e4f72e6d)

**Comment by lasermonkey12** [comment]
Example of carlita pattern and resulting seam shape
![20230915_114249](https://github.com/freesewing/freesewing/assets/55415375/6cc73e83-e0ee-4e91-9272-fb5fba4db7be)
![20231209_181540](https://github.com/freesewing/freesewing/assets/55415375/c7f652b4-41d1-412c-904a-be6841589b64)

**Comment by woutervdub** [comment]
Implementing with `tristan`
