### ISSUE TITLE
Setup a pattern design team to work on those specific topics

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#563]
This is a todo from #553 

I do think it's best to keep the general contributor call sufficiently high-level and have in-depth discussions on other things branch of into a specific team :slightly_smiling_face: 

Since several people have expressed a willingness to be involved in the pattern design side of things, I think it makes sense to setup a dedicated *team* to work on this. Whether or no that group does its own calls (like the *community* team does is something we can figure out.

You should join this team if you are interested in:

 - Pattern design/drafting (like you would do it on paper)
 - The adaptation of classic drafting techniques to parametric designs
 - The implementation of said designs in code

People who volunteered for #526 should join this team. The following people expressed an interest on the #553 call:

 - @sewanista
 - @rrolon47
 - @woutervdub 
 - @DocSpencer77 

Bonus: You get your own `pattern design` label for issues :slightly_smiling_face:

**Comment by joostdecock** [comment]
I just realized I at-mentioned @amysews in this rather than @sewanista, I've corrected that now.
However, that obviously does not mean Amy can't join, just that it was @sewanista who said she'd love to.

As I'm writing this, I also realize how the mistake happened:

![Screenshot_2020-09-20 Screenshot from 2020-09-20 16-23-57 png (PNG Image, 3844 × 2110 pixels) - Scaled (44%)](https://user-images.githubusercontent.com/1708494/93713705-df978180-fb5d-11ea-9447-5356f58ac916.png)

When I type `@sew` github suggests `@amysews` and I blindly accepted that suggestion. I assume it's not suggesting `@sewanista` because she hasn't joined the freesewing organisation yet.
I've sent an invite for that while ago, I'll send a new one. If you can accept it, that would make it easier for people to mention you (as only people inside the organization or already taking part in a particular issue are suggested)

**Comment by Sewanista** [comment]
I've just joined, sorry I missed the last invitation. Hopefully that makes things easier.

**Comment by amysews** [comment]
@joostdecock I'd like to get added to the group please 😄  (sorry I missed the call this weekend, I was with family)

**Comment by joostdecock** [comment]
@amysews If you approve [this merge request](https://github.com/freesewing/freesewing.org/pull/1014), it's official :)

**Comment by rrolon47** [comment]
how do I join the group?

**Comment by joostdecock** [comment]
I'll submit a PR to list you as a collaborator, and also be in the group. But consider yourself in :)

**Comment by DocSpencer77** [comment]
@rrolon47 I'm so glad you did an "annotated" bib tutorial as you mentioned in Discord!  I've been working on an annotated project code/tutorial sort of thing that hopefully can provide folks with a jumping off place to make their own modifications.  

@joostdecock What do you think?  What's the best place for us to share/build some learning tools like that? I'd hope that you would help us review/refine them, too.

**Comment by joostdecock** [comment]
I must admit that 'm not really certain what way to steer this. The idea was to bring people who are interested in making patterns together.

I typically advocate for teaming up a person who has a programming background with people who have a pattern drafting background. That way, you can work together and get results relatively fast.

However, there's a number of people who want to wear both of those hats. Typically people who already know how to draft patterns, and no want to learn how to program them with/in freesewing.

That is of course wonderful. But it does raise the question what this *pattern design* group is about.
Imagine a scenario where people @DocSpencer77 and @rrolon47 take a deep dive into setting up the development environment. Chances are we'll end up alienating people like @dfbean or @Sewanista who are mainly looking to contribute by sharing their pattern drafting skills. They don't really want to learn how to program, nor should they.

Essentially, we have two things here:

 - Pattern design: Desiging patterns with/for freesewing
 - Developer relations aka devrel: What needs to happen to make it easy for (aspiring) developers to get started

I prefer to let people work on the thing(s) they would like to work on. Which is why I am hesitant to steer this debate in one way or another.

Perhaps you could be inspired by the *community* team. Once they deemed themselves a team, they had a zoom call among themselves to talk about what they wanted to do, make some actionable todos and so on. (see #523).

The way I see it, these are the people who are all gravitating around this *pattern design* team:

 - @Sewanista
 - @rrolon47
 - @woutervdub
 - @DocSpencer77
 - @amysews 
 - @enyachoke 
 - @joostdecock 

I'd suggest we get them around the table and do some consensus building about what needs to happen or what people want to work on.

I should also mention @AlfaLyr and @QuentinFelix who are pattern design alumni. They might be interested too.

**Comment by DocSpencer77** [comment]
@joostdecock  All good input.  Thanks.  
Is @dfbean  Deb/Debra from the Titan block building and from our meetings?  Didn't she also express interest in being here?

My thought is that some of the tutorial annotation effort is just as much for someone who doesn't want to actually do the coding as it is for someone who is interested only in the coding.  It's a way for both ends of that spectrum to figure out how to meet in the middle.  The person who has drafted a pattern on paper needs to know how much of their work needs to be communicated to the person creating the code.  Both "camps" need to know, to some extent, how to communicate with the other.  My hope is that we can demystify the process enough to work together in whatever middle ground is appropriate.

Yes, as people figure out where they want to work in that range between traditional approaches and "the brave new world" <g> we'll talk.  And learn. And talk.

**Comment by joostdecock** [comment]
Sorry, added Deb to the list (I did tag her, just forgot her at the bottom)

**Comment by enyachoke** [comment]
@joostdecock  I like the idea of meeting up and deciding on how to move forward and also believe there are really no extremes. I write code but am always fascinated with pattern design so I will definitely benefit from being paired with someone who is good with pattern design.

**Comment by dfbean** [comment]
To paraphrase @joostdecock and @DocSpencer77, there are three separate efforts that we could undertake:

Teach me to code
Teach me to design
Teach me to work with a code/design partner

Each of these is worthy, but each also represents potentially significant workloads with different skill sets needed to complete them.  And Joost is right, not everyone in the group will want to slog through discussions of their complementary skill set, just so they can learn to contribute the one skill they're interested in.  So I think it might be helpful to tackle these tasks as separate initiatives. 

It's also likely that the workload involved means that we can't realistically tackle all three tasks at the same time.  So we should probably have a bit of discussion about which task will generate the most value-added at this time, or which task has the most enthusiastic contributors who want to tackle it first, or however we want to frame the issue of prioritizing/sequencing these tasks.

IMHO, the first two tasks are both immense and well-covered in books, schools, on-line classes, youtube, etc.  While there's value in teaching aspects of these skills that relate to Freesewing specifically, teaching someone to code or design from the ground up could be a big investment of effort with limited immediate payoff.  At the same time, we already have a number of folks with skill in coding or design who are are ready to contribute and aren't being utilized.  

I think DocSpencer's approach of teaching folks to meet in the middle and work as a team is a well-bounded task that seems both doable and likely to have quick benefits.  As an added bonus, working on the middle ground first should give us good insight as to how to efficiently teach the separate skill sets to support Freesewing's mission.

So yes, let's have a zoom discussion to flesh this out.  Standing by for date/time.

**Comment by DocSpencer77** [comment]
Thanks @dfbean for synthesizing the conversation and helping us find a direction.

I have most of the pieces necessary to put a little thing together that starts with a simple drawing and follows that with a simple pattern.  Then, we can find out where in the process people feel comfortable working, where we overlap and don't, where we're interested in learning and where we're not.

Date and time-wise, do we want to stick with a Saturday meeting as this next Saturday 9/26 is between regular Contributor calls?

**Comment by dfbean** [comment]
@DocSpencer77 The meeting time is fine for me, I'll go along with the crowd though.  If you want to see an example of the information that might be exchanged and how a techie/creative team communicates, go to the Titan development documentation  on GitHub.  I'm sorry, I don't remember what it was called or how to find it, so Joost should chime in now and direct you to it.  Warning, it's a long and winding road, but a very good example of what you'd be dealing with.

**Comment by enyachoke** [comment]
Saturday same time as the contributors call works for me.

**Comment by joostdecock** [comment]
> If you want to see an example of the information that might be exchanged and how a techie/creative team communicates, go to the Titan development documentation on GitHub.

@dfbean is referring to #398

> Saturday same time as the contributors call works for me.

Let's not forget @Sewanista here. That time slot means the call would start at midnight for her.
Perhaps she can let us know whether:

 - [ ] She plans to attend this *pattern-design* call
 - [ ] If so, could she attend
 - [ ] If not, what time slot would work better

**Comment by joostdecock** [comment]
Just adding the link here that @Sewanista posted on Discord to her skirt pattern: https://www.dropbox.com/sh/0ggk15j0c3h4yhd/AAAZDBI6fABpVOSsvtJsYOaBa?dl=0

Includes the pattern (for Valentina/Seamly), drafting instructions, and measurements chart.

**Comment by Sewanista** [comment]
I'm fine with the Saturday timeslot, if everyone can excuse occasional yawning and slight incoherence, lol.

**Comment by joostdecock** [comment]
That's awesome @Sewanista 

I've scheduled the call. Details here: #570 

For those of you whose email addresses are in my address book, I've sent you an invite.
There's a calendar link in #570 that does the same thing.

I'm closing this as we accomplished its goal :slightly_smiling_face:

**Comment by DocSpencer77** [comment]
Yay!! Super Duper on gathering resources to help us go forward in our collaboration @Sewanista  and @dfbean and @joostdecock and @rrolon47!  I'll post a link to a kind of "traditional method to code" bridge sample (not quite a tutorial, yet) some time today. In the next ~48hours I have to move heaven and earth and work a few data miracles,  %) but I'm very eager for us to gain traction and make Groovy Stuff! Looking forward to Saturday!

**Comment by DocSpencer77** [comment]
Catching up and tying together a few loose ends.

- Linking in Rachel's @rrolon47 shared link to her annotated coding experimentation/tutorial.
https://discord.com/channels/698854858052075530/698854858496802868/757822990963703939
The link is to her mention of it in discord, but there she links to her Github reponsitory.  I took that a step further by adding a few comments and generating a pull request which she then merged into her code, demonstrating how we can collaborate with each other.

- Linking here also to my previous idea about how someone might have a pattern idea:
https://github.com/freesewing/freesewing/issues/527#issuecomment-690797988
There I have a picture and a drawing of my simple little hat as an example:
![image](https://user-images.githubusercontent.com/43393580/94090998-bafd0d00-fddc-11ea-8705-84d135763ad8.png)

![image](https://user-images.githubusercontent.com/43393580/94091005-c0f2ee00-fddc-11ea-9c48-c9b91acf5361.png)

and now that hat is (partly) coded as a pattern which you can examine here (look in the src folder for the pattern pieces code)
https://github.com/DocSpencer77/LearnableHat

In the development environment it looks like this on the screen:
![image](https://user-images.githubusercontent.com/43393580/94091118-0ca59780-fddd-11ea-829f-d6ac2814ed93.png)

The shapes of that hat are there, but there's also a "gore" piece with which could be used to make a different kind of hat, andd the current "crown" circle could be turned into a little hat brim.  In other words, it's a simple start to a pattern but it invites further ideas and modifications.  The code is generously annotated/commented... but it's still rough, and @joostdecock  is likely to have some corrections for me if not some stern words about my coding practices.  %)

The point of it all is to illustrate some steps along the process where various folks might want to jump in.  Don't hesitate to ask questions.
