### ISSUE TITLE
Write Teagan documentation

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#564]
This is a todo from #553 where @tangerineshark volunteered to help with writing documentation.

Since we've got a milestone for the Teagan release, I've pegged this issue to it, and assigned @tangerineshark 
Obviously, this is the best-case scenario, don't feel pressured.

Good to know is also that translation can't happen until the original English text is written.

One thing that is less-obvious is any possible illustrations. We have a position open for that in #528 but in the meanwhile written instructions would already be great :slightly_smiling_face:

**Comment by tangerineshark** [comment]
I've been putting this together as a Google Doc, which is almost definitely the wrong approach, but can't hurt for a start. It's saved here: https://docs.google.com/document/d/1gX-sDKScMFk4oJ_hyf8c0a5R88h-ez63TlCMTKCU9ZU/edit?usp=sharing 

I tried to follow your standard formatting and language by stealing a lot from the Aaron and Sven patterns, then modifying to fit. Also, the Aaron already has amazing images, so I noted where you could just repurpose Aaron images if you wanted to maintain the same style with Teagan and save on some graphics creation.

If you want, I could try to format this in HTML. You'd have a better idea of whether that's worth it than I would probably, based on how fast you can typically throw a page together.

LMK what you think, and if there's a preferred place for me to save draft documentation. :-)

**Comment by joostdecock** [comment]
I guess this would be a good opportunity to update our documentation for editors: https://freesewing.dev/guides/editor/

It's a bit outdated, but the same principles still apply:

 - All our documentation is written in markdown
 - They are stored in the [freesewing/markdown](https://github.com/freesewing/markdown) repository
 - As an example, here are the Aaron docs: https://github.com/freesewing/markdown/tree/develop/org/docs/patterns/aaron
 - Obviously, writing them in the first place is the main job, formatting can be done later

What tools you use to write is a personal choice. So in a way, you are free to pick whatever tool you want.
But there's a catch: Content and style should be strictly separated. If you are going to use an editor that is going to mix both (like Microsoft Word, Apple Pages, Google Docs, and so on) you will need to export your document as **plain text**. Then somebody will have to take that text, and format it in Markdown.

So while all your contributions are welcome, and I'll gladly take your google docs or whatever, you could lift your contributions to a whole new level if you learned to write Markdown (it's real easy). Bonus points for learning to independently put your work in our repositories. This way, your work will also be correctly credited. Since if you send it to me and I put it in, it will be credited to me.

[VS Code](https://code.visualstudio.com/) is a very popular editor, that also has markdown support. Here's what it looks like when I open the Aaron docs:

![Screenshot from 2020-09-21 10-09-38](https://user-images.githubusercontent.com/1708494/93744860-d0164800-fbf2-11ea-8861-31623184543f.png)

As you can see, you can write on the left, preview on the right. The preview is not 100% what it will end up looking like on the website, but it's really just a difference of eye candy.
This editor has the benefit for supporting integration with Github, so you can work on it and save your work in the repository.

I don't get to tell you what to do. But learning to work with Markdown and git(hub) will change your life for the better.

**Comment by tangerineshark** [comment]
Thanks, Joost! This is awesome and super-helpful. I figured you had a whole process, but I also had time to write up the content side of things yesterday, which seemed like a good start. I'm still gaining familiarity with github, but I have a decent understanding of HTML, so I can definitely have a go at the formatting side of things! I'll keep you posted!

**Comment by joostdecock** [comment]
That's great to hear. A few things that are perhaps not obvious (and that we should document) are the custom components you can use:

#### Tip
```
<Tip>
Your tip here
</Tip>
```

![Screenshot_2020-09-21 Community(1)](https://user-images.githubusercontent.com/1708494/93787127-63ba3980-fc30-11ea-82fe-9b9f9b323463.png)

#### Note

```
<Note>
Your note here
</Note>
```
![Screenshot_2020-09-21 Community](https://user-images.githubusercontent.com/1708494/93787360-b0057980-fc30-11ea-87e7-9cc2773e926c.png)

#### Warning
```
<Warning>
Your warning here
</Warning>
```

![Screenshot_2020-09-21 Community(2)](https://user-images.githubusercontent.com/1708494/93787141-6a48b100-fc30-11ea-89c8-9e7b61a2b6ee.png)

#### Fixme
```
<Fixme>
under construction...
</Fixme>
```

![Screenshot_2020-09-21 Community(3)](https://user-images.githubusercontent.com/1708494/93787373-b267d380-fc30-11ea-9d6c-290da77a4f49.png)

**Comment by tangerineshark** [comment]
Just a status update: I've figured out Markdown but am still getting the hang of repositories and github overall. I will have everything written up in Markdown today, and either send it to you or merge it myself, so that there's at least a week for the folks on translation. Also, @TawniS is editing documentation, so I tagged her in here basically to acknowledge that she's awesome.

**Comment by tangerineshark** [comment]
I think I did it!! But also it's my first go, so apologies if I've instead created a disaster. I've tried to stick to the nomenclature I could see around the rest of the site, but LMK if there's anything I should change for the future.

**Comment by joostdecock** [comment]
Wow, fantastic work @tangerineshark I'm really impressed by how quick you're picking all of this up :+1: 

I made a few changes, but only because of the way the website is built. As a document as-such, your work was perfect :slightly_smiling_face: 

### About frontmatter

We (typically) use so-called *frontmatter* to provide metadata about the content. 
It is information that goes at the top of the page between two rows of `---` character as `key: "value"` pairs, like this:

```
---
key: value
title: "Quotes aren't strictly as long as you don't have : signs in your value"
---
```

When we turn markdown into a page (whether it's documentation of a blog post or showcase) we only get the main body as a blob of HTML. Any information that we want to display separately, we need to put in the frontmatter so we can specifically access it.

So for a blog post, we want to display the main image, the name of the author, the date and so on, above the actual body.
That's why you find all those things in the frontmatter of a blog post. Here's an example:

```md
---
date: 2020-08-30
title: Please help grow FreeSewing beyond what I can do on my own
linktitle: "Announcing the Carlita Coat"
img: book.jpg
caption: "Note: This post is a long read. Although nowhere near as long as this book"
author: joost
---
```
### Frontmatter in documentation

For documentation, the only thing we need to access separately is the page title. 
That's because the page title is re-used in the breadcrumbs, navigation menus and so on.

So a *typical* documentation page looks like this:

```
---
title: About FreeSewing
---

Markdown goes here
```

### Exceptions

To ensure consistency across the site, those pages that re-occur for every pattern (like the ones you created) are treated differently. We don't take the title from the markdown file, but set it manually.
Every pattern has a *fabric options*, *cutting*, *instructions* and so on pages. So we simply don't add a title to those pages.

So the only thing I did was remove the `#` level title from your work since it's not needed in these pages.


I hope to be able to improve the documentation about this in the near future. I might ask your for your review :wink:

**Comment by tangerineshark** [comment]
Yaaaayyyy!!! I can absolutely review documentation about, well, documentation I suppose. It's probably perfect timing, since I haven't internalized any of the undocumented bits yet.
