### ISSUE TITLE
Compile a list of sewing techniques/steps that we want to document with video

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#565]
This is a todo from #553 where we discussed a library of different sewing techniques or steps would facilitate making videos for new patterns.

The first step is to create a list of techniques that we would like to capture.
Please comment below with your suggestions, and I'll keep a list in the issue updated.

**Comment by TawniS** [comment]
I think a good place to start would be the list of techniques that you have on the site already. Adding a screenshot below. I can try to help filming some of these but the only equipment I have is a cell phone and I'm REALLY not good at speaking in front of people 🙊

 #
![Screenshot_20200920-113404](https://user-images.githubusercontent.com/70525956/93715161-94697880-fb35-11ea-898b-51d7edd5aa47.png)

**Comment by joostdecock** [comment]
Good suggestion. The list is here: https://freesewing.org/docs/sewing/

**Comment by joostdecock** [comment]
Over 4 months old with no initiative. Closing.
