### ISSUE TITLE
[bug]:Patterns don't show in Safari browser

### ISSUE THREAD

**Issue by SeaZeeZee** [freesewing/freesewing#5653]
### What seems to be the problem? 🤔

Patterns look like this on Safari: 

![IMG_0008](https://github.com/freesewing/freesewing/assets/86711383/2a1557b3-2615-4a5d-84e3-9cd473254909)

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
This is also seen on desktop Safari. 
- The draft view pattern area is blank when using the default render engine. Toggling the button to use the other render engine causes the contents to appear.
- Print view and inspect view pattern areas are similarly blank.

This was with desktop Safari 17.2.1 (the latest on macOS Sonoma).
