### ISSUE TITLE
cannot install dev environment

### ISSUE THREAD

**Issue by extracoffeebuzz** [freesewing/freesewing#5654]
### What seems to be the problem? 🤔

I have followed the tutorial for windows and linux
https://freesewing.dev/tutorials/getting-started-linux/dev-setup

I cannot get either setup to actually complete the final step and enter the local host.

On Ubuntu powershell I get stuck on monepro install here:

yarn kickstart
yarn run v1.22.21
$ npx yarn install && yarn prepare && yarn tips
npm ERR! must provide string spec

npm ERR! A complete log of this run can be found in: /home/adam/.npm/_logs/2023-12-16T23_46_09_041Z-debug-0.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I get stuck on Ubuntu standalone version and Windows powershell standalone version here:
yarn dev
yarn run v1.22.21
$ next dev -p 8000
/bin/sh: 1: next: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

windows:
npm run dev

> @freesewing/sde@3.0.0 dev
> next dev -p 8000

'next' is not recognized as an internal or external command,
operable program or batch file.

two side notes:
1. the linux tutorial on the node.js version has an instruction to set the version to v.10.22.1   future errors show that this needs to be version 18. There is no other instruction on the next page for setting the version to 18.19.0.  Suggest changing the copy box for nvm use v10.22.1 to the necessary version
2.  with the new monepro method, the instructions are intermixed for standalone and monepro. On a few tries, I've ended up in the other instruction set.

thanks

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Thank you for reporting this @extracoffeebuzz and sorry for the delay in response.
I am preparing a 3.1 release which will resolve this issue. I'll keep you posted.

**Comment by joostdecock** [comment]
@extracoffeebuzz I've release v3.1.0-rc-0, which is a pre-release. If you'd like to test it, you can do so with this command:

```
FS_BRANCH=develop npx @freesewing/new-design@next
```

Let me know how it goes. If I don't hear back, I'll probably release this in the next 24h or so as v3.1.0.

**Comment by joostdecock** [comment]
Should be resolved in 3.1. Closing
