### ISSUE TITLE
Edit new Teagan video using only a regular sewing machine

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#567]
This is a todo from #553 and can only be started after completion of #566 by @joostdecock

**Comment by joostdecock** [comment]
@creasyo I'm done recording. Files are being uploaded at Done. Files are being uploaded at: https://www.dropbox.com/sh/psvpcksxm3eu02y/AABhmRAO7FbVhzi6mWkmg5hKa?dl=0

There's 33 `.mp4` files and a `.wav` file for each. Will take a while, but they should be there tomorrow :slightly_smiling_face: 
I've added the `00.txt` file with some notes. Let me know if anything is not clear.

**Comment by creasyo** [comment]
Sorry for the radio silence. Its been a very busy couple of weeks! 

The tutorials are now edited together and I am just exporting them and uploading them to YouTube now. Should be done by this afternoon!

**Comment by joostdecock** [comment]
Great work @creasyo thanks a bunch :pray:
