### ISSUE TITLE
Try making an initial coding video to figure out what works and what doesn't

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#568]
This is a todo from #553 where Rachel suggested to (also) make video tutorials for the coding side of things.

That's a good idea, but we've never done anything like it. So perhaps we can start by just recording something and collecting feedback on what works and what not so we can gravitate to a formula we can then repeat.

**Comment by rrolon47** [comment]
I have some experience with OBS to record your screen. I haven't done it in a while but its probably what we would want to do.  
I am still learning the code and API but we could probably start with doing a walk through of the bib tutorial.  Maybe the first video could be setting up the dev environment and any trouble shooting that goes along with that.  I don't have class this week so I might be able to put something small together but I don't know how long it will take.

**Comment by joostdecock** [comment]
Closing in favor of #1054
