### ISSUE TITLE
[docs]: `paco` instructions

### ISSUE THREAD

**Issue by RockerKitten** [freesewing/freesewing#5682]
### Where can we see the problem? 🤔

https://freesewing.org/docs/designs/paco/instructions

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

conflicting information between the Paco generated pattern, and cutting instructions vs the sewing instructions. The generated pattern has the waistband with a fold line and says to cut 1, and cutting instructions also say to cut 1. The sewing instructions however says to "Place the two waistband pieces good sides together, and align the short edges. Sew the short edges together, then press open." a the image shows 2 waistband pieces sewn together as described. It appears that the pattern, and cutting instructions are correct based on the measurements used and the measurements of the pieces generated by the design.

### Additional context

generated waistband without seam allowances was 93cm, my seat measure used to generate it is 89cm, folded width with no seam allowance is 3cm which is wide enough to accommodate most elastic used for waistbands. this looks to be correct.
edited to change "hip" to "seat" because I momentarily forgot which is used for the fullest part of the hips/butt

**Comment by BenJamesBen** [comment]
Discussion about this issue:
https://discord.com/channels/698854858052075530/1186860686626783232/1187083116502843532
discord://discord.com/channels/698854858052075530/1186860686626783232/1187083116502843532
