### ISSUE TITLE
Compile a list of common coding challenges in sewing patterns

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#569]
This is a todo from #553 and the idea is to compile a list of common challenges when coding sewing patterns so we can provide instructions on how to solve them.

Challenges can either be things that are inherent to porting drafting instructions to parametric design (like, how to make easy not a fixed number), or more related to programming things (how to adapt your sleevecap length to fit your armhole).

#### List

 - Calculating curves that scale correctly
 - Truing seams
 - Using seam allowance and hem allowance
 - Notches, grain line, other markings
 - Fabric types

Please comment below with your suggestions of what should be added.

**Comment by Sewanista** [comment]
Calculating curves that scale correctly.

**Comment by joostdecock** [comment]
Thanks @Sewanista I created the list in the issue above, will update it with comments here :slightly_smiling_face:

**Comment by joostdecock** [comment]
See https://freesewing.dev/howtos/design/
