### ISSUE TITLE
Design team call: 26 September 2020

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#570]
You are all invited to the contributor call.
Please leave a comment to put things on the agenda.  
This issue will be updated after the call with notes and todos.

## About
 - [Add to your calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjhscmV2dmtiMWI1amY5MXRwNHAwaTQ3MjQgZGVjb2NrLm9yZ19pNjU2dTk2bGFvcnBhZWV1YmQzbjdhOGVxZ0Bn&tmsrc=decock.org_i656u96laorpaeeubd3n7a8eqg%40group.calendar.google.com)
 - Location: https://meet.freesewing.org (redirects to https://zoom.us/j/5168598687 )
 - Date: Sep 26, 2020 16:00 UTC, which is:
   - Los Angeles: 09:00
   - Chicago: 11:00
   - New York: 12:00
   - São Paulo: 13:00
   - London: 17:00
   - Paris: 18:00
   - Johannesburg: 18:00
   - Moscow: 19:00
   - Mumbai: 21:30
   - Hong Kong: 00:00 on Sunday
   - Tokyo: 01:00 on Sunday
   - Sydney: 02:00 on Sunday

## Agenda

 - Welcome
 - Design team goals
 - Free-form discussion

## Notes

 - This was the first call of the pattern design team, with 10 people attending
 - @joostdecock briefly explained that the goal was to build a consensus on what areas to focus our energy on
 - @DocSpencer77 asked what people were interested in:
    - @woutervdub explained that he's been writing code for a very long time and is happy doing that. He's also intrigued by the process of going from a 2D shape to a 3D garment and would like to work with a developer on that
    - @Sewanista explained that she has extensive experience in design, and that she's been experimenting with parametric design via valentina/seamly. She has a particular interest in drafting for plus-sized models and has collected a set of measurements from different people with a bust size of over 100.
    - @rrolon47 said that she is interested in parametric designs too, and has a preference to code
    - @enyachoke explained that he is a developer and so that's where his interests lie. He'd like to learn more about how one can take an existing pattern and make adjustments to it, like add a different collar and so on
    - Katie (who was a new face on the call) said that here interest and background was on the design side
    - Jim (another new face on the call) works in IT and feels he has a lot to contribute that way
    - @tangerineshark explained that her background is in sewinig
    - @dfbean joined the call a bit later (and after this question was posed) but to be complete, she has a background in pattern design
 - @DocSpencer77 picked up on @Sewanista 's comment that she has already made some parametric designs with Valentina. She said that she looked at the files and that they are XML. They are somewhat decipherable.
 - @rrolon47 Said that she had been making a video of how to setup the development environment using [OBS](https://obsproject.com/)
 - Rachel has also [created an annotated bib tutorial which she made available on her Github account](https://github.com/rrolon47/FS-tutorial/blob/master/src/bib.js).
 - @DocSpencer77 remarked that she has made a contributor to @rrolon47 's annotated tutorial and confirmed that you can contributor to each other's work that way
 - @Sewanista is looking for somebody who would be willing to take the designs she's been working on and turn them into code. These designs are already parametric in nature (within the bounds of what's possible in valentina/seamly) 
 - @enyachoke is interested to work with her on that
 - @dfbean suggests it would be useful to have a list of drafting terms and other jargon to avoid misunderstandings between designers and coders
 - @rrolon47 suggests that people who have limited pattern design experience would best team up with somebody like herself. Ie somebody who can code but also knows about pattern design. This could be a way to avoid misunderstandings.
 - @enyachoke explains that developers are always listening to people to figure out what it is they are expected to code. He suspects that after an initial bit of getting to know each other, there won't be too many misunderstandings. A sentiment echoed by @joostdecock 
 - @joostdecock floated the idea of video of showing how a pattern is coded, but that idea did not have legs
 - @dfbean suggested a library of techniques/approaches that are common in pattern design with examples of how to implement them in code. Essentially some sort of knowledge base to avoid people have to reinvent the wheel
 - This idea of re-usable examples was well received, and @joostdecock suggested we'd start by making a list of things people would like to see an example of
 - @enyachoke suggested a walk-through of a (complex) pattern and show how it is done
 - @joostdecock suggested that perhaps he could go through the patterns that are already there and see where there are things that feel like they are worth adding to the examples
 - @DocSpencer77 asked whether it was possible to share the pattern she was working on with candidate pattern testers. @joostdecock pointed out that she can ask for their measurements, put them in the development environment and generate a pattern for them, but there was currently no way to publish a work-in-progress pattern online
 - That being said, it might be able to add feature to the development environment, and @rrolon47 suggested we could use github pages for this
 -  Katie asked if there was a way to have designings *pitch* their ideas so that coders could pick up the ones they feel would be fun/interesting/worthwhile to work on. 
 - @woutervdub remarked that a good relationship between designer and developer is in the end what matters
 - @enyachoke suggested we should prioritize making quality basic blocks. That way, different developers could work on different styles all based on those blocks. That would make it easier for people, prevent them from having to start from zero. 
 - This *let's get blocks fixed* idea was well received
 - Meeting went 15 minutes over time

## Todo

 - @Sewanista and @enyachoke will work together to bring @Sewanista 's skirt dart to freesewing (starting with the skirt as a warm-up to @Sewanista 's bodice block) : #573
 - Create a list of techniques/challenges for which we want to create examples of how to implement them in code: #574
 - Look into whether we can have the dev environment publish itself online: #575
 - Create a list of pattern drafting terms + explanations: #576
 - Pull examples from the current patterns to show how to do certain things: #577

**Comment by amysews** [comment]
Sorry guys, I've got unexpected guests staying with me this weekend so won't be able to join the call again.

**Comment by joostdecock** [comment]
I've updated the notes and todos. Please feel free to comment to point out what I've forgotten or got wrong.

I'll also be closing this as the call if over, but don't let that stop you from commenting.
