### ISSUE TITLE
Re-Upload YouTube videos to our own channel

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#572]
- [x] Facemask video
- [x] Bruce boxers 1/2
- [x] Bruce boxers 2/2
- [x] Hugo 1/6
- [x] Hugo 2/6
- [x] Hugo 3/6
- [x] Hugo 4/6
- [x] Hugo 5/6
- [x] Hugo 6/6
- [x] Folding the cuff placket
- [x] Double welt pockets 1/2
- [x] Double welt pockets 2/2
- [x] Pattern assembly
- [x] Trousers 1/13
- [x] Trousers 2/13
- [x] Trousers 3a/13
- [x] Trousers 3b/13
- [x] Trousers 3c/13
- [x] Trousers 4a/13
- [x] Trousers 4b/13
- [x] Trousers 5/13
- [x] Trousers 6/13
- [x] Trousers 7a/13
- [x] Trousers 7b/13
- [x] Trousers 7c/13
- [x] Trousers 8/13
- [x] Trousers 9/13
- [x] Trousers 10/13
- [x] Trousers 11a/13
- [x] Trousers 11b/13
- [x] Trousers 12/13
- [x] Trousers 13/13

**Comment by TawniS** [comment]
Hey, let me know when these are up and I'll add descriptions etc

**Comment by joostdecock** [comment]
Will do :+1:

**Comment by joostdecock** [comment]
@TawniS All done :slightly_smiling_face: 
Would you like me to create issues for you to do the descriptions and so on?
Depends on whether you get a dopamine hit from closing a todo, or not :wink:

**Comment by TawniS** [comment]
Haha I think I can work with it this way! Thanks :) I'll make them public as I update them over the next couple of days
