### ISSUE TITLE
[bug]: Blog posts in the navigation context are alphabetic, rather than chronologic

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#5730]
### What seems to be the problem? 🤔

The blog posts are shown (in the sidebar, and in the 'previous - next' component in alphabetic, rather than chronological order.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

**Comment by BenJamesBen** [comment]
I am able to get blog posts ordered by date with the below code change. However, I'm not sure whether there might be any unwanted side effects, so I don't know whether this is an actual fix.

```diff
--- a/sites/shared/prebuild/markdown.mjs
+++ b/sites/shared/prebuild/markdown.mjs
@@ -167,7 +167,8 @@ const loadBlog = async () => {
   for (const lang of Object.keys(titles)) {
     posts[lang] = {}
     for (const post of ordered) {
-      posts[lang][post.s] = { t: post.t }
+      const sortkey = 9999999999 - post.o
+      posts[lang][post.s] = { t: post.t, o: sortkey }
       if (lang === 'en') meta[post.s] = { a: post.a, d: post.o }
     }
   }
```

![Screenshot 2024-01-24 at 10 28 07 PM](https://github.com/freesewing/freesewing/assets/109869956/512d3be9-9258-4143-81c7-23589847504a)
