### ISSUE TITLE
Create a list of pattern drafting terms + explanations

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#576]
This is a todo from #570 

Please comment below with your suggestions. See also: #574

**Comment by stoffsuchti** [comment]
Suggestions of pattern design elements that need to be documented/explained:

- Bust dart forms/variations
- Collar forms/variations 
- Waist line form / hights
- Trouser styles / forms / length
- Skirt styles / forms / length
- Necklines (forms / styles)
- Pocket forms / styles / designs
- Dress styles / forms / lengths / designs
- Seams / Hems (whitch technics exists and what are they used for)

**Comment by joostdecock** [comment]
For clarity: After discussion, we decided to close this issue as it's too vague and writing documentation that explains how pattern drafting works is outside the scope of this project.
