### ISSUE TITLE
[feature]: [![ESLint Changed Files](https://github.com/freesewing/freesewing/actions/workflows/lint.diff.yml/badge.svg?event=discussion)](https://github.com/freesewing/freesewing/actions/workflows/lint.diff.yml)

### ISSUE THREAD

**Issue by Umbrella-Pad** [freesewing/freesewing#5771]
### What is it that you would like to see happen? 🤔

 %behind. (INITOAL*.run !!python2).(7s.86.yaml &&star

### Are you a FreeSewing patron? 😃

Yes, I am a tier-8 patron ❤️  💙 💜

### Additional context

Attach img-gzu:user-gener$

**Comment by joostdecock** [comment]
Not entirely certain whether this is spam or good intentions gone wrong, but closing.
