### ISSUE TITLE
[docs]: "How to communicate to the user" is missing parts

### ISSUE THREAD

**Issue by woutervdub** [freesewing/freesewing#5772]
### Where can we see the problem? 🤔

https://freesewing.dev/tutorials/pattern-design/part3/flag

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

### Additional context

The text seems to be cut off in the last paragraph. And it looks like there was intended to be more information.

**Comment by BenJamesBen** [comment]
Assigning joost, since he already has a fix in his branch.

**Comment by BenJamesBen** [comment]
The fix is in pending PR #5825.

**Comment by BenJamesBen** [comment]
PR #5825 was merged on 2024-02-04 via 109cc27. Closing.
