### ISSUE TITLE
[bug]: Charlie Amount To Cut In Instructions Does Not Match Pattern

### ISSUE THREAD

**Issue by jpmunic** [freesewing/freesewing#5791]
### What seems to be the problem? 🤔

The cutting directions for Charlie Chinos say that you need to cut 4 copies of parts 4 and 8, which is correct. However, when you generate the pattern both parts 4 and 8 say to "Cut 2 mirrored from main fabric". Shouldn't they say to "Cut 4 mirrored from main fabric"?

### Design / Plugin / Package 🧐

designs/charlie

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

[cutting instructions](https://freesewing.org/docs/designs/charlie/cuttingl)

<img width="674" alt="Screenshot 2024-01-06 at 8 46 19 PM" src="https://github.com/freesewing/freesewing/assets/13474972/d43cef52-25bd-4c8f-9170-03ca1319e09b">

**Comment by joostdecock** [comment]
@all-contributors please add @jpmunic for bug

**Comment by joostdecock** [comment]
Thanks for reporting this @jpmunic awesome work :+1:
