### ISSUE TITLE
[bug]: Charlie backPocketWelt Seam Allowance Not Generated

### ISSUE THREAD

**Issue by jpmunic** [freesewing/freesewing#5792]
### What seems to be the problem? 🤔

When I generate Charlie Chinos with the "Include Seam Allowance" option set to yes, the backPocketWelt (part 4) does not receive a seam allowance. 

### Design / Plugin / Package 🧐

designs/charlie

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

The cutting instructions for Charlie Chinos say that [the fabric cutout should be this size](https://freesewing.org/docs/sewing/double-welt-pockets#pocket-welts)
>     Length: Pocket width + 4cm
>     Width: Welt height x2 + 5cm

However, when you generate the pattern with the seam allowance option set to yes, the backPocketWelt's seam allowance is not included. It's length is the pocket width and its width is the welt height x2.

<img width="307" alt="Screenshot 2024-01-06 at 9 24 21 PM" src="https://github.com/freesewing/freesewing/assets/13474972/feef74dd-2f03-42aa-9a67-433f25267559">
<img width="358" alt="Screenshot 2024-01-06 at 9 24 12 PM" src="https://github.com/freesewing/freesewing/assets/13474972/ba77db02-98c5-43fc-9a58-9a2403dcb715">

**Comment by woutervdub** [comment]
@jpmunic I don't think this is a bug. The welt is larger than the pocket opening, which is how welt pockets are constructed. I haven't made `charlie` myself, but with all the pants I have made that have welt pockets, including my `waralee` design, the welt piece does not have a seam allowance. Which is because the welt sides are not used in seams.

**Comment by jpmunic** [comment]
Sorry, seam allowance is the wrong word. The size of the backPocketWelt doesn't match the instructions. The instructions say the width should be (welt height x 2 + 5cm), and the welt height in the pattern is 2.92cm, which is less than 5cm.

**Comment by jpmunic** [comment]
Actually, I think it would take a lot of work to make the pocket welt instructions match the pattern exactly. Closing this issue.
