### ISSUE TITLE
[bug]: In older showcase posts, additional images in the post body don't show up

### ISSUE THREAD

**Issue by nataliasayang** [freesewing/freesewing#5799]
### What seems to be the problem? 🤔

Additional images in the body of older showcase posts don't show up. They display as a broken image icon.

Example where it's occurring: https://freesewing.org/showcase/floral-camoflaged-charlie-chinos

The first image in the showcase post body is this: https://posts.freesewing.org/uploads/PXL_20220418_142933261_90e5101fa5.jpg

When I try to view that image link, I get a 502 Bad Gateway error.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-4 patron ❤️  💙

### Additional context

Newer showcases where the additional images have an `imagedelivery.net` URL look fine.

**Comment by joostdecock** [comment]
These older in-body images are (still) hosted on Strapi. When the old v2-backend has issues, they stop showing up.
I've applied some TLC to the v2 backend, and images are back.

I've opened #5823 to track a permanent solution to this challenge. Closing this as it's a side-effect only.
