### ISSUE TITLE
[docs]: missing measurement in dev measurement docs

### ISSUE THREAD

**Issue by RockerKitten** [freesewing/freesewing#5805]
### Where can we see the problem? 🤔

https://freesewing.dev/reference/measurements

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Suggested content

missing waist to underarm in the dev docs ref for measurements.

**Comment by BenJamesBen** [comment]
Assigning joost, since he already has a fix in his branch.

**Comment by BenJamesBen** [comment]
The fix is in pending PR #5825.
