### ISSUE TITLE
Teagan Announcement blog post

### ISSUE THREAD

**Issue by tangerineshark** [freesewing/freesewing#584]
Okay, I don't think this issue is strictly necessary, but I'd never made one before and I **will** get better at using Github's features. Plus it allows me to:

Ask @joostdecock two questions before committing edits (although I can move them to discord if preferred):
1. Can I change the language around who the pattern is for? Specifically, I think your goal of sewing patterns for all is pretty genderless, so I want to take out the reference to "menswear," but leave the pattern's technical parameters (no breasts), so people can decide how that applies to them. (But also, the language and philosophy around gender is a complex topic, and I don't want to just change things on that front without a heads-up/explanation.)
2. Is there a link for the Zoom meeting schedule? (The Community page on next says it's here https://next.freesewing.org/community/where/#planning but that seems like not a thing yet.)

Keep track of a little list of todos for @tangerineshark :
- [x] source some images of other Teagan makes
- [x] add them to repository and post
- [x] get link to Teagan trailer
- [x] embed trailer in post (or link to, bc the internet says it might not be possible, but for the love of all that's holy, it's 2020, you **must** be able to embed youtube videos in markdown for github by now)

**Comment by tangerineshark** [comment]
ooh, perhaps I can't assign participants and am just talking to myself. ah well, to discord!

**Comment by joostdecock** [comment]
> Can I change the language

You can do whatever you want. The blog post is yours now. Have at it 😃

> Is there a link for the Zoom meeting schedule?

Not yet. I tried adding in the google calendar thing but it's rather clunky and I wasn't happy with it. I need to find a more elegant way 🤔
