### ISSUE TITLE
[bug]: (Safari) SecurityError: Attempt to use history.replaceState() more than 100 times per 10 seconds

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#5860]
### What seems to be the problem? 🤔

On the Safari desktop browser with the localhost lab, using design option sliders can frequently cause an Unhandled Runtime Error, "SecurityError: Attempt to use history.replaceState() more than 100 times per 10 seconds".
![Screenshot 2024-01-20 at 6 46 44 AM](https://github.com/freesewing/freesewing/assets/109869956/7bec474d-2367-4bcb-a333-9d5e6418c86e)

When this occurs, the error can be dismissed and the lab can continue to be used without any issue, although the error may continue to occur periodically.

Steps to Reproduce:
1. Start the localhost lab and start a new Sandy pattern.
2. In Design Options -> Style, use the Circle Ratio slider and slide it back and forth.
3. The error will occur.
4. Dismiss the error and continue using the lab.

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

### Additional context

An internet search suggests that this is likely an issue that affects only Safari and no other browsers. This was seen on Safari Version 17.2.1 (19617.1.17.11.12), on macOS Sonoma 14.2.1

The visible error dialog/page seems to occur only with the localhost lab. The error is not visible when using freesewing.org. However, the error still silently occurs and can be seen in the JavaScript Console.

Because this issue affects only Safari and does not block use of the lab, it may be that we choose to close this as Will Not Fix.

![Screenshot 2024-01-20 at 7 13 51 AM](https://github.com/freesewing/freesewing/assets/109869956/1e333eb8-b0dc-481a-a95e-252c097fe280)

**Comment by BenJamesBen** [comment]
Although no visible errors are seen on freesewing.org, it may be that this issue could result in Bugsnag-created Issues in GitHub. I suspect that #5696 might be an example. If this bug is closed as Will Not Fix, we might want to configure Bugsnag to ignore these errors.

**Comment by joostdecock** [comment]
This happens when users move a bunch of sliders which repeatedly updates the URL via the history API.
Too many updates to the URL in a short amount of time triggers this error in a browser because it's something that is (ab)used by sites to break the back button.

Silencing bugsnag as @BenJamesBen suggests is probably are best bet here, since if memory serves me right, we already debounce the inputs.

@BenJamesBen If you DM me an email address, I will give you access to bugsnag (not that you have to do it, I just think you should have access). If you want it of course :)

**Comment by HaasJona** [comment]
This error can also easily be reproduces with Firefox on https://freesewing.org. Just open a design pattern and start messing with the sliders. At some point the slider will stop responding and the developer console will print

`Too many calls to Location or History APIs within a short timeframe. 5378-43d35ec0aaaafd17.js:1:484`

```
Uncaught DOMException: The operation is insecure.
    c index.modern.js:1
    r index.modern.js:1
    writeAtomState vanilla.mjs:374
    writeAtom vanilla.mjs:379
    setAtom react.mjs:91
    settings new.mjs:136
    updateFunc index.mjs:85
    pctUpdateFunc inputs.mjs:435
    useSharedHandlers inputs.mjs:170
    Lodash 3
```

**Comment by joostdecock** [comment]
I plan to address this in #6552 - closing to make the list of open issue more manageable.
