### ISSUE TITLE
[bug]: Jargon plugin documentation is misleading

### ISSUE THREAD

**Issue by LunaticMuch** [freesewing/freesewing#5863]
### What seems to be the problem? 🤔

The documentation of the plugin is confusing and wrong:
- The plugin is a rehype plugin bug the example shows remark
- The example repo is empty
- The link to Gatsy example is broken (it does not exist anymore apparently)

### Design / Plugin / Package 🧐

packages/rehype-jargon

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by BenJamesBen** [comment]
This bug was fixed by PR #5864. Closing.
