### ISSUE TITLE
[feature]: Allow measurement sets with missing measurements to be selected for new patterns

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#5915]
### What is it that you would like to see happen? 🤔

A request to be able to select a measurement set for new patterns, even if it is missing measurements. So the user can see what measurements are missing and do something about it. So the measurement set can be edited by hand to add the missing measurements.

> Hmm, I'm trying to generate Wahid to see how much fabric I need, and I did this before with this measurement set (I think?), and now  I'm at this point and don't know what to do with this information:
![image](https://github.com/freesewing/freesewing/assets/109869956/f37cfab0-4cb8-4e09-850b-98d6ef0ca2b4)
> I can't pick my measurement  set to edit it below, it doesn't say what measurements are lacking either

>> I suspect you are missing the newly-added-in-v3 "Waist to Armpit" measurement in your old measurement sets.

> I guess so
> But I also expect to be able to click something and fix it
> Like pick this set and then have the measurements populated, with one missing, in this part
![image-1](https://github.com/freesewing/freesewing/assets/109869956/011014d8-be1a-4b36-be98-90d3fc2682b0)

https://discord.com/channels/698854858052075530/1101975649419268186/1201095246105292805
discord://discord.com/channels/698854858052075530/1101975649419268186/1201095246105292805

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

**Comment by BenJamesBen** [comment]
1. Create an alternate handler that stays on the measies view, instead of trying to go to draft view.
2. Give missing measurements sets a button that uses that alternate handler.

- Good measurement sets redirect to the draft view as usual.
- Missing measurement sets stay on the measies view, where a popup informs which measurements are missing. (This functionality was already present in the measies view.)
- The user can go to the "Edit measurements by hand" section at the bottom of the page.

```diff
--- a/sites/shared/components/account/sets.mjs
+++ b/sites/shared/components/account/sets.mjs
@@ -817,7 +817,7 @@ export const MsetButton = (props) => <MsetCard {...props} href={false} />
 export const MsetLink = (props) => <MsetCard {...props} onClick={false} useA={false} />
 export const MsetA = (props) => <MsetCard {...props} onClick={false} useA={true} />
 
-export const UserSetPicker = ({ design, t, href, clickHandler, size = 'lg' }) => {
+export const UserSetPicker = ({ design, t, href, clickHandler, altClickHandler, size = 'lg' }) => {
   // Hooks
   const backend = useBackend()
   const { control } = useAccount()
@@ -899,12 +899,13 @@ export const UserSetPicker = ({ design, t, href, clickHandler, size = 'lg' }) =>
           </Popout>
           <div className="grid grid-cols-1 md:grid-cols-2 2xl:grid-cols-3 gap-2">
             {lackingSets.map((set) => (
-              <MsetLink
-                {...{ set, control, design }}
-                onClick={clickHandler}
-                requiredMeasies={measurements[design]}
-                key={set.id}
-                size={size}
+            <MsetButton
+              {...{ set, control, design }}
+              onClick={altClickHandler}
+              href={href}
+              requiredMeasies={measurements[design]}
+              key={set.id}
+              size={size}
               />
             ))}
           </div>


--- a/sites/shared/components/workbench/views/measies/index.mjs
+++ b/sites/shared/components/workbench/views/measies/index.mjs
@@ -33,6 +33,14 @@ export const MeasiesView = ({ design, Design, settings, update, missingMeasureme
     setView('draft')
   }
 
+  const loadMissingMeasurements = (set) => {
+    update.settings([
+      [['measurements'], designMeasurements(Design, set.measies)],
+      [['units'], set.imperial ? 'imperial' : 'metric'],
+    ])
+    setView('measies')
+  }
+
   return (
     <div className="max-w-7xl mt-8 mx-auto px-4">
       <h2>{t('account:measurements')}</h2>
@@ -68,6 +76,7 @@ export const MeasiesView = ({ design, Design, settings, update, missingMeasureme
               key={2}
               design={design}
               clickHandler={loadMeasurements}
+              altClickHandler={loadMissingMeasurements}
               t={t}
               size="md"
             />,
```

![Screenshot 2024-01-28 at 4 29 51 AM](https://github.com/freesewing/freesewing/assets/109869956/323c4174-6107-47cd-812e-05166d576575)

**Comment by joostdecock** [comment]
While the `statusConfirmed` label was initially created to track bugs and let people know we know about it, I am using it here to indicate that we have accepted this feature request and intent to implement it :)
