### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [freesewing/freesewing#592]
Hi!

remark is switching to a new parser internally ([micromark](https://github.com/micromark/micromark), see [`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536) for more info).
From a quick glance at the code (remark-jargon), it seems this plugin should be fine. However, it would be good to check that in the future (there is `13.0.0-alpha.0` published now, and one or two more will come before the release)

**Comment by joostdecock** [comment]
Tested this with the new 13 release, and I can confirm that the plugin works fine.

Thanks for all your great work :heart:
