### ISSUE TITLE
[bug]: Lunina tests are broken

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#5956]
### What seems to be the problem? 🤔

The Lumina (sample) tests are broken. I had a look, but the design uses a ton of abstractions and is thus not trivial to follow, so I'll leave this to its designer :)

**Comment by joostdecock** [comment]
@woutervdub Could you have a look at this, I'd like to ship v3.2, but this would need to get resolved first :pray:

**Comment by woutervdub** [comment]
@joostdecock Fixed and issued a PR.
