### ISSUE TITLE
Handbag Hortensia

### ISSUE THREAD

**Issue by stoffsuchti** [freesewing/freesewing#596]
![image](https://user-images.githubusercontent.com/1039463/95012152-49238f80-0636-11eb-8032-cb2b084e1e83.jpeg)

Handbag Hortensia will be a pattern created by me, but I will need someone who makes the coding part of it. When i have drawn the the pattern and testsewing the hole bag, and written the documentation, i'll reach out for help for the coding part (I can not code) (I can sew, draw patterns (simpler ones), write the documentation).

I hope to have the testbag, the pattern and documentation until end of January 2021.

**Comment by enyachoke** [comment]
@stoffsuchti  as soon you get the paper pattern done ping the team on discord.

**Comment by stoffsuchti** [comment]
@enyachoke thank you. But I am not on discord and will not be there anytime. But I'll ping you and @joostdecock here if its okay?

**Comment by joostdecock** [comment]
Sure thing @stoffsuchti :+1:

**Comment by enyachoke** [comment]
@stoffsuchti  here works too.

**Comment by stoffsuchti** [comment]
Thank you all

**Comment by stoffsuchti** [comment]
![image](https://user-images.githubusercontent.com/1039463/95024135-7e090400-0681-11eb-951b-afa3bd24dcc9.jpeg)

Scribble of the outer pattern pieces, the lining will be layouted, when a have the pattern of the outer pieces

**Comment by woutervdub** [comment]
I can help with this. How would you like to communicate?

**Comment by stoffsuchti** [comment]
Thank you @woutervdub prefer Matrix/Elements, Threema, Signal for communication. But I'm not ready for implementation at the moment, first I need to draw the pattern and make one or mor sample bags :)

**Comment by woutervdub** [comment]
No problem. Just let me know when you're ready.

**Comment by stoffsuchti** [comment]
![image](https://user-images.githubusercontent.com/1039463/97106380-76a5ab00-16c1-11eb-9137-0582cebedd40.jpeg)

I made the paper pattern. I will digitize it to jpg or vector in the following 2-3 weeks

**Comment by joostdecock** [comment]
I think the main issue is to have an idea of the size. If you put a ruler on top of this, that's probably sufficient.

**Comment by stoffsuchti** [comment]
I will provide you with neat and exact sizing Information in the following days. Can you work with a scan of the piece that is roundly (curved) schaped? It would be a bitmap, not a vector, that would be much quicker for me to create.

**Comment by joostdecock** [comment]
Sure, no worries :)

**Comment by woutervdub** [comment]
Would you like this to become sizeable? 

And if so, would you like all the sizes move up and down using the same ratio for depth, width, and height?

**Comment by stoffsuchti** [comment]
Yeah at the end I would like to have it Sizeable, but not to the infinity. 

It will take me some more time to provide you the measurements, dimensions and the relations of measurements baked in to that Handback, there ist a lot golden Ration (phi) around here 🤣🌈. 

And I would like, when it gets sizable, that the proportions will be respected and not distorded.

**Comment by woutervdub** [comment]
We can just set up a standard size, and then make a slider that lets you generate a larger or smaller one, based on a percentage of the original, with minimum and maximum values.

So the normal width would be (just grabbing something out of thin air): 30cm.
The slider would allow you to change that to between 30% and 200%

@joostdecock Should we make this Ant Man compatible? That would turn into "normal width = 30cm _for neck circumference=36cm_", and we'd compensate for differences? Larger people get larger purses?

**Comment by stoffsuchti** [comment]
So ich schreibe die Masse zu dem Schnittmuster auf Deutsch auf, und füge Bilder an. Ich kann zu einem späteren Zeitpunkt gerne versuchen es zu übersetzten. 

Ganz wichtig ist, dass wenn die Tasche Skaliervar gemacht wird, oben der Platz für den Reissverschluss nicht skaliert wird, sondern vom Benutzer in absoluten Massen eingegeben werden kann. Bei Reissverschluss soll die am Ende sichtbare Breite als fester Wert eingegeben werden können. 

Mir ist sehr wichtig, dass beim Skalieren der Tasche, die Proportionen erhalten bleiben. Ich hab recht viele Verhältnisse im Goldenen Schnitt eingebaut. Alle Schnitteile, die ich zeige sind OHNE Nahtzugabe. Ich mache nachfolgende Kommentare mit Bildern und Scanns wo ich die Masse eintrage, so dass diese bei dem real vorliegenden Schnitt ersichtlich sind. Wo ich mir bereits konkrete Verhältnisse für die Berechnung zur Hilfe genommen habe, werde ich diese ebenfalls vermerken. 

Die Knipse (Nodges) am Seitenteil sind sehr wichtig. Diese müssen unbedingt im Schnittmuster auf Freesewing ebenfalls verfübar sein.

**Comment by stoffsuchti** [comment]
![Parts Overview Hortensia](https://user-images.githubusercontent.com/1039463/98438002-5aedcc00-20e7-11eb-8959-6dc83895ca85.png)

### Übersichtsplan der Teile.

**T1 Seitenteil**
- h1 Höhe Seitenteil
- b2 Breite Seitenteil

**T2 Bodenverstärkung Seitenteil**
- h2 Höhe Bodenverstärkung Seitenteil
- b2 Breite Bodenverstärkung Seitenteil

**T3 Bodenteil aussen**
- h3 Höhe Bodenteil aussen
- b3 Breite Bodenteil aussen

**T4 Vorderteil/Hinterteil**
- h4 Höhe Vorderteil/Hinterteil
- b4 Breite Vorderteil/Hinterteil

**T5 Reissverschlussblende**
- h5 Höhe Reissverschlussblende
- b2 Breite Reissverschlussblende

**T6 Haltelasche**
- h1 Höhe Haltelasche
- b2 Breite Haltelasche
_(auf dem Bild zu gross, da mit Nahtzugabe abgebildet)_

**T7 Reissverschlussentstück**
- h7 Höhe Reissverschlussentstück
- b7 Breite Reissverschlussentstück

**Comment by stoffsuchti** [comment]
![Side Pannel Hortensia](https://user-images.githubusercontent.com/1039463/98438575-6c38d780-20eb-11eb-8558-fca7cddb0692.jpg)
Scan of the Sidepannel

**Comment by stoffsuchti** [comment]
@joostdecock @woutervdub do you speek a bit of German or is the translation require in any scenario?

**Comment by stoffsuchti** [comment]
## Lining and Interlining

When I sew the first real Bag, i will create the pattern peaces for the lining and the interfacing. Most of those part will be rectangles and a slightly smaller and or altered side panel

**Comment by woutervdub** [comment]
@stoffsuchti I'll start working on this.

What is your neck-circumference?

**Comment by woutervdub** [comment]
@stoffsuchti I'll start working on this.

When you say that the zipper width/length should be open to the uer entering it, does that mean that all the other measurements should adapt, according to the ratios inherit in this version you detailed here?

Meaning, you now have a zipper width of 53.4 cm, with a side panel of 33 high. So if we make the zipper width 26.7, we should get a side panel height of 16.5 cm?

Or should the zipper width be independent of the width of the bag itself? So the bag (T5) can be 53.4 cm wide, but the zipper is only 45cm?

**Comment by joostdecock** [comment]
> Should we make this Ant Man compatible? That would turn into "normal width = 30cm for neck circumference=36cm", and we'd compensate for differences? Larger people get larger purses?

@woutervdub While made-to-measure is nifty and *our thing*, I don't think we should be slaves to it. Patterns don't _have to_ user measurements, and this seems like a good candidate for one that doesn't.

So Perhaps we just need some sort of *handbag-size* option that has a list of things to pick from that in reality is just a list of standard zipper sizes. That 1 option can then determine the size of the bag.

The zipper width is (in my understanding) a style choice (invisible zipper vs exposed zipper) and thus should not have an influence on the overall size of the bag.

So to summarize:

 - Let the user pick a zipper length from a list (with a sensible default)
 - Make all dimensions a factor of that length
 - Foresee both exposed and invisible zipper finish

Based on my understanding, that's how I would approach it.

**Comment by stoffsuchti** [comment]
In my opinion the bag should not be distorted by the endusers, but I'm fine if its made scalabe, when the proportion stay the same. But I'm also fine when you decide to provide this pattern in 5 or more sizes. 

The length of the zipper is a bit shorter then the length of the bag. Because there are the zipper end pieces, that cover the end of the zipper, id you like, i can make a drawing of my idea for this detail.

The visible with of the zipper (when the Zipper is visible) shot not go to smal, when the bag is infinitly scalable and the users wants it really smal. Most zipper teeth are 3mm , 5mm or 6 mm wide. And my plan was that you can also see a bit of the zipper band (don't know the exact word) left an right of the zipper teeth. Then you have the zipper panel (smal
long strip, and then the fron (back) panel and then the bottom as you go down the bag.

**Comment by woutervdub** [comment]
Do you have the exact measurements for the side panel? I'm specifically interested in:
- Radius of the rounded bottom corners
- Distance from the corner to where the angled side begins
- Radius of the top

I can use the drawing you uploaded and measure these myself, but I wondered if you already had those done (since you re so precise with the other ratios).

**Comment by stoffsuchti** [comment]
@woutervdub I will take a look at the original piece and h check out wich measurements I can give you from it. 
I must admit, the side panel was drawn by hand (one side and then mirrored and cut out). Then I measured the height an from that measurement i calculated and created all the other stuff. Because of that there are so few measurements for the side panel. I will provide what is avable :)

**Comment by stoffsuchti** [comment]
I have now checked if I can give you exact radii for the side panel and so on. Unfortunately not, because I drew the freehand and then mirrored it. 
Please just determine the radius from the scanned image as good as possible. :)
Sorry that I can't give you more exact information.

**Comment by woutervdub** [comment]
No a problem. I'll try and show you what I came up with.

**Comment by stoffsuchti** [comment]
> No a problem. I'll try and show you what I came up with. 

Thank You

**Comment by woutervdub** [comment]
Hi, this is what I came up with for the side panel. My FreeSewing version is superimposed in green onto your original sketch. Let me know what you think.
![hortensia v0 1](https://user-images.githubusercontent.com/24414629/100552846-8ffcc280-323e-11eb-8629-979edb15d5c0.png)

**Comment by stoffsuchti** [comment]
Yay thats awesome. I Like that :) very cool :).

**Comment by woutervdub** [comment]
@stoffsuchti 

> The nodges on the side are very important. They must be available in the pattern on Freesewing as well.

What do the notches represent? Are they where seams meet the side panel?

**Comment by woutervdub** [comment]
More questions:
- Does the bottom panel <-> front/back panel seam align with the top of the side panel reinforcement?
  (the seam between T3 and T4)

- Is the bag made up from 1x T3, 2x T4 and 1x T5 (going around)? 
  (so the length of T3 + T4 + T5 + T4 is the same as the circumference of the side panel?)

- Do we need to add straps/handles?

**Comment by stoffsuchti** [comment]
> @stoffsuchti 
>
> 
> What do the notches represent? Are they where seams meet the side panel?
> 
> 

![image](https://user-images.githubusercontent.com/1039463/101153922-50aae900-3625-11eb-8919-79e7e4d3f0fd.jpeg)![image](https://user-images.githubusercontent.com/1039463/101153931-543e7000-3625-11eb-8a66-63f087614f5f.jpeg)

**Comment by stoffsuchti** [comment]
@woutervdub yes we need Handle straps, but there will be different methods to make them. I will calculate the approx length that is suitable for the measurements I noted in this ticket, will take me some days :)

**Comment by stoffsuchti** [comment]
The rest I habe to translate to understand them, to be able to answer them

**Comment by woutervdub** [comment]
@stoffsuchti You answered the other parts too with your answer about the notches.

Thanks!

**Comment by woutervdub** [comment]
I have all the pieces in a pattern. Now I just have to figure out how to show it to you ;-)

**Comment by stoffsuchti** [comment]
@woutervdub wow that was really fast :). Can you export them as tiled PDF with A4 pages? So i can print them and compare the printed pattern to my handrawn one?

**Comment by woutervdub** [comment]
I realized that something isn't clear to me. It's about the zipper panel. I have not been reading your instructions well, I guess. 

Whenever I set in a zipper, I do it somewhat like a welt pocket. I undo the zipper, push it inside-out (teeth facing outwards), and then sew them to a single piece of fabric. Then cut the fabric in the middle, and work it like you normally do a welt pocket.

Your option here is to have two pieces of fabric on each side of the zipper. And have to end pieces on the ends of the zipper.

My concern with this is that there are different sizes zippers with different dimensions of the teeth. That would influence the width of the zipper. And that would influence the total width of the zipper + zipper bands. And since the total circumference of the bag includes that, the size of the front and back panel will need to be changed because of the width of the zipper. 

This means we will have to have the user enter the width of the zipper. 

It will also influence the look of the bag, and the ratios used. Because the width of the zipper teeth will influence where the notches 2 and 3 will end up. So with a wide zipper, the seam between T4 and T5 will move further down the bag, than with a narrow zipper.

**Comment by woutervdub** [comment]
[hortensia-A4.pdf](https://github.com/freesewing/freesewing/files/5649428/hortensia-A4.pdf)

**Comment by woutervdub** [comment]
Here is a large PDF with the pattern in 'paperless' mode, so it has all the dimensions on it.
[hortensia-paperless.pdf](https://github.com/freesewing/freesewing/files/5649435/hortensia-paperless.pdf)

**Comment by stoffsuchti** [comment]
> I realized that something isn't clear to me. It's about the zipper panel. I have not been reading your instructions well, I guess. 
> 
> 
> 
> Whenever I set in a zipper, I do it somewhat like a welt pocket. I undo the zipper, push it inside-out (teeth facing outwards), and then sew them to a single piece of fabric. Then cut the fabric in the middle, and work it like you normally do a welt pocket.
> 
> 
> 
> Your option here is to have two pieces of fabric on each side of the zipper. And have two end pieces on the ends of the zipper.
> 
> 
> 
> My concern with this is that there are different sizes zippers with different dimensions of the teeth. That would influence the width of the zipper. And that would influence the total width of the zipper + zipper bands. And since the total circumference of the bag includes that, the size of the front and back panel will need to be changed because of the width of the zipper. 
> 
> 
> 
> This means we will have to have the user enter the width of the zipper. 
> 
> 
> 
> It will also influence the look of the bag, and the ratios used. Because the width of the zipper teeth will influence where the notches 2 and 3 will end up. So with a wide zipper, the seam between T4 and T5 will move further down the bag, than with a narrow zipper.
> 
> 

Yes there are zipper with different with of teeths. But my plan is, that you not only show the teeth of the zipper but also some mm of the zipperband (left ab right of the teeth. So the visible with of the zipper can stay the same, independently from the size of the bag. I think 1,5 or 2 cm visible zipper width wouls be a good value.

If you can & are willed to let the user choose the visible zipper width, thats also fine for me.

And thank you for the pattern pdf :)

**Comment by woutervdub** [comment]
I added an option to set the zipper width. It knows normal zipper sizes (#3, #4, #4.5, #5, #6, #8, #10 & Invisible) and calculates the width of the pieces of fabric on both sides accordingly. So the total panel of the pieces of fabric and the zipper is always the same width (h2/phi).

I also made it scalable. So you can make a handbag that is anywhere between 4.6cm and 46cm wide (default is 23cm). All proportions scale along and remain in the same ratio (the pieces of fabric on both sides of the zipper are recalculated, so the h2/phi ratio is retained).

Should we do something with the handles/straps? How long do they need to be? How much distance between them on the bag? Up to what height does the handle need to be attached?

**Comment by stoffsuchti** [comment]
Thank you for the update and the modification you implemented. 

I will take a look on the handle question around xmas. Till then a have lot of workload at work.

**Comment by stoffsuchti** [comment]
Unfortunately I'm not feeling well at this time. It will take me more time to figure out the handle questions. Yes it needs handles, but in term of exact length and positioning I have no finished ideas. 

The handle should go around the hole bag and be long enough so one can put it unter the arm and on its shoulder. 

Sorry for the delay

**Comment by joostdecock** [comment]
Some great work going on here guys :+1: 

Since I'm preparing the v2.11 release, I've bumped this to the v2.12 milestone. No pressure :slightly_smiling_face:

**Comment by woutervdub** [comment]
I'm sorry to hear that you're not feeling well, @stoffsuchti 

I'll stop the work on this until you feel better. If, on the other hand, you'd like to continue working on this and implement the handles in a way i think would be best, please let me know.

Wouter

**Comment by stoffsuchti** [comment]
> 
> I'll stop the work on this until you feel better. If, on the other hand, you'd like to continue working on this and implement the handles in a way i think would be best, please let me know.
>


I'm fine with, when you implement the handles in the way you think its best. Thank you in advance :)

**Comment by woutervdub** [comment]
I figured I should make a mock-up to see how long the handles should be, and where to attach them. So I printed the pattern out. I made a mistake with the tiler, so it is only 80% of what it should be. But it is a huge bag! I thought we were making an ladies handbag. This is more of a gym bag. Is that intentional?

![IMG_6197](https://user-images.githubusercontent.com/24414629/104855373-4a18be00-58c1-11eb-842a-1fe52c6210af.jpg)

**Comment by joostdecock** [comment]
That's a big bag!

**Comment by stoffsuchti** [comment]
Some Ladys line big bags. As we male it scalable, each person can make it at the desired size.

**Comment by stoffsuchti** [comment]
![image](https://user-images.githubusercontent.com/1039463/105575875-20531180-5d6f-11eb-978e-2159b489217a.png)
This Hortensia is about 27cm in the length (most long side). I hope this helps a bit in the handle question. 

I habe to make a second one (full size), that one i will take a foto of each stepp for the documentation. 

I will also make a lining with several pockets, that could be nice for some inspiration for the lining pattern pieces. 


More Pictures
![image](https://user-images.githubusercontent.com/1039463/105575932-9ce5f000-5d6f-11eb-8bb9-2a1ac066a992.jpeg) ![image](https://user-images.githubusercontent.com/1039463/105575947-bb4beb80-5d6f-11eb-834d-2e3730d55d59.jpeg)![image](https://user-images.githubusercontent.com/1039463/105575953-c6068080-5d6f-11eb-883f-2998ec4e7834.jpeg)

**Comment by woutervdub** [comment]
I added the straps and made some other tweaks. I also made the default size somewhat smaller. Here is what I came up with. Looks pretty complete to me. 

![Uploading 63A50257-2B7A-4579-A7DB-B2107E14555B.jpeg…]()

**Comment by woutervdub** [comment]
![604DE604-6AF4-418D-BEE3-77B01F2EA71A](https://user-images.githubusercontent.com/24414629/106050963-a9828500-609c-11eb-95ff-5bb1c772f4cb.jpeg)
![07606AA5-D258-4D05-BB90-20A2C6AB7093](https://user-images.githubusercontent.com/24414629/106050970-ab4c4880-609c-11eb-85f7-f08a707d917c.jpeg)

**Comment by stoffsuchti** [comment]
Thank you very much.

**Comment by woutervdub** [comment]
![914EC7F4-1E90-44D4-B1EF-6289E05D7B2B](https://user-images.githubusercontent.com/24414629/106051399-3dece780-609d-11eb-9b43-562069de2430.jpeg)

**Comment by stoffsuchti** [comment]
I think this makes a nice standard size. When someone wants it bigger or smaller, they can adjust it.

**Comment by joostdecock** [comment]
This is awesome!

**Comment by joostdecock** [comment]
Code is in the [hortensia branch](https://github.com/freesewing/freesewing/tree/hortensia).

FYI @woutervdub I [rewrote the author on the git commit](https://github.com/freesewing/freesewing/commit/2e2a495bb5b77ce024fff6c23f0113841516ee1e) so that the code contribution is in your name :+1: 

That being said, it throws this error:
```
Error: Could not resolve './bottomsidepanel' from src/sidepanelreinforcement.js
```

Did you perhaps forget to include the `src/bottomsidepanel.js` file?

**Comment by woutervdub** [comment]
Well, that was embarrassing.  I added it to the repo.

**Comment by joostdecock** [comment]
Thanks Wouter :+1:

**Comment by joostdecock** [comment]
v2.13.0-rc.0 is published here: https://hortensia.freesewing.dev

Question: What's with those zipper size options? Will people understand what `#3`, `#4` and so on means?  
I mean, I don't, but I don't know much about zippers :slightly_smiling_face: 

I will need some time to integrate this in the frontend because this is the first pattern we have that does not use any measurements at all. So it doesn't make sense to have people go through the normal: pick a design => pick a size => draft pattern workflow. So I'll need to add some extra code to handle this.

Meanwhile, you can kick the tires, and translators can deal with the options.

**Comment by woutervdub** [comment]
Zipper sizes are basically standardized by YKK, one of the world's largest zipper manufacturers. There is a little variation between different types of zippers, as in a nylon coil #5 is slightly smaller than a metal teeth #5, but we're talking tenths of millimeters here. 

I hadn't thought of the interface adjustment for this. I guess it is the first non-measurement pattern. There will be more, I'm sure.

**Comment by stoffsuchti** [comment]
@macrba

**Comment by joostdecock** [comment]
Thanks for this, truly great work :+1: 

This is part of the v2.13 release, which is published on NPM. Website is building as we speak.
I'm closing this, but there's #860 still to be done.

**Comment by woutervdub** [comment]
Hi,There seems to be an issue with the design of Hortensia. Can you let me know if the zipper is supposed to be flanked by two pieces of fabric?Thanks! WouterOn Oct 29, 2020, at 08:46, Stoffsuchti ***@***.***> wrote:﻿
Yeah at the end I would like to have it Sizeable, but not to the infinity.
It will take me some more time to provide you the measurements, dimensions and the relations of measurements baked in to that Handback, there ist a lot golden Ration (phi) around here 🤣🌈.
And I would like, when it gets sizable, that the proportions will be respected and not distorded.

**Comment by stoffsuchti** [comment]
Hello Wouter 

Thank you for reaching out. 
Yes in my design it's supposed to have two strips along the length of the zipper. 
In the image of the Roségold Hortensia they are visible. Hope that helps ![image](https://github.com/freesewing/freesewing/assets/1039463/8533bc3e-6469-4cfc-b4fc-deeead66d9ab)

**Comment by stoffsuchti** [comment]
Her Exot can see it why more clearly. 
(This one was also made by me) 
![image](https://github.com/freesewing/freesewing/assets/1039463/8f8f486f-d8da-4557-a353-c6b8555d49ba)
