### ISSUE TITLE
[bug]: Path.join() converts move() operations to line() 

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#5976]
### What seems to be the problem? 🤔

When paths are joined using `Path.join()`, `move()` operations in the paths are converted to `line()`s. As a result, intended noncontiguous paths become contiguous after the `join()`.

(The exception is the first `move()` of the first path. That first `moveI()` is preserved, but all others are converted to `line()`)

It is unclear whether this behavior a bug or if it is intended.
- If intended, then the behavior should be added to the documentation.
- If not intended, it could be that some designs or related core functionality depends on the original behavior. Caution should be taken if a fix is attempted and the behavior is changed.

In this example, the two seam allowance paths were intended to be noncontiguous. However, they became contiguous after the second `join()` operation:
![Screenshot 2024-02-06 at 8 07 55 AM](https://github.com/freesewing/freesewing/assets/109869956/b9ed36ad-f01d-4257-9978-b2832e05b29f)

```js
     paths.seam1 = new Path()
       .move(points.leftCollarCorner)
       .line(points.leftCollarstandTip)
       .line(points.notchLeft)
       .line(points.notchTipRollLeft)
       .offset(sa)
       .hide()
     paths.seam2 = new Path()
       .move(points.notchTipRoll)
       .line(points.notch)
       .line(points.collarCorner)
       .offset(sa)
       .hide()
     paths.sa = new Path()
       .move(points.leftCollarCorner)
       .line(paths.seam1.start())
       .join(paths.seam1)
       .line(points.notchTipRollLeft)
       .move(points.notchTipRoll)
       .line(paths.seam2.start())
       .join(paths.seam2)
       .line(points.collarCorner)
       .attr('class', 'various sa')
```

### Design / Plugin / Package 🧐

packages/core

### Additional context

In `packages/core/src/path.mjs`, in `Paths.__joinPath()`, we see that both `line` and `move` operations are caught by the `if (op.type !== 'close')` condition and converted to `line()`:

```js
  for (let p of paths) {
     for (let op of p.ops) {
       if (op.type === 'curve') {
         joint.curve(op.cp1, op.cp2, op.to)
       } else if (op.type === 'noop') {
         joint.noop(op.id)
       } else if (op.type !== 'close') {
         // We're using sitsRoughlyOn here to avoid miniscule line segments
         if (current && !op.to.sitsRoughlyOn(current)) joint.line(op.to)
       } else {
         let err = 'Cannot join a closed path with another'
         joint.log.error(err)
         throw new Error(err)
       }
       if (op.to) current = op.to
     } 
   }
```

**Comment by woutervdub** [comment]
Such a fix, if desired, would need to be implemented very carefully. I know that there are `paths` in certain designs that use this as a feature.

**Comment by BenJamesBen** [comment]
We could add a new parameter `Path.join(path, closed=false, noncontiguous=false)`. For existing code missing the new parameter, the existing default behavior would still be used. For new code that adds `true` for the new parameter, new behavior could occur.

Or, we could instead just say that the method is intended to produce only contiguous paths and document it.

**Comment by joostdecock** [comment]
The behavior of `Path.join()` is as intended, but we can still improve things. So I did this: https://github.com/freesewing/freesewing/pull/6001

**Comment by joostdecock** [comment]
Summary: 
- `Path.join()` keeps working as before
- `Path.combine()` is there now if you want the other behavior
- Both are variadic, with `Path.join()` still accepting the old signature, but it will log a deprecation warning
- `Path.length()` can now be told to include gaps in the length calculation if you so desire.
