### ISSUE TITLE
[bug]: Jager sleeve width problems

### ISSUE THREAD

**Issue by RockerKitten** [freesewing/freesewing#5999]
### What seems to be the problem? 🤔

Jager seems to be having trouble with sleeve width. It appears to be reversed. using my measurements found here https://freesewing.org/set?id=40184 I generated a Jager pattern. With my bicep measure of 27cm, with the default bicep ease of 15% the width of part 4 at the widest is 15.67cm and part 5 is 11.61. Changing the bicep ease to 30% results in the width of the 2 parts changing to 14.61cm and 10.83cm respectively. setting it to 0% bicep ease and the widths are 16.8cm and 12.45cm.
Furthermore, manually editing the bicep circumference, leaving ease at 0% setting the bicep to 300 (30cm) the sleeve parts become 14.75 and 10.93. Setting the bicep to 200mm (20cm), again with 0% bicep ease, the sleeve parts are 19.11cm and 14.17cm. for reference here is the pattern with paperless view on, with my 27cm original measure at 0% ease.
![image](https://github.com/freesewing/freesewing/assets/84648053/890eed4f-0957-4bb1-9bdd-6e80ccf74a23)

### Design / Plugin / Package 🧐

designs/jaeger

### Additional context

![image](https://github.com/freesewing/freesewing/assets/84648053/8bda9a15-e584-47fb-ae72-90251b52c361)
![image](https://github.com/freesewing/freesewing/assets/84648053/5a39260c-bcfb-4eb8-a0bb-d70c61292f41)
![image](https://github.com/freesewing/freesewing/assets/84648053/66086bc7-2f3f-42ff-9948-46677541ed08)
here are screen shots of the ease only changes, all with the same bicep width.

**Comment by BenJamesBen** [comment]
Jaeger inherits its sleeves from Bent. I confirm that the problem is seen with Bent.

It is also related to the v2 vs. v3 Armhole Depth issue. The issue does not occur if Legacy Armhole Depth is enabled.

Bent bases its sleeves values calculated in Brian's front. So, ultimately this might be a Brian issue.

**Comment by joostdecock** [comment]
Thanks for digging in to this @BenJamesBen :+1:
