### ISSUE TITLE
[bug]: Jargon isn't displaying properly

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#6017]
### What seems to be the problem? 🤔

Jargon isn't displaying properly. Instead of hover definitions being seen, the jargon terms are just italicized as if they were plain markdown.

Examples of jargon not displaying properly:
- https://freesewing.dev/guides/markdown/jargon (_cjs_ and _esm_)
- https://freesewing.org/docs/designs/aaron/instructions (_good sides together_, _twin needle_, and _zig-zag switch_)

Also:
- I notice that the `sites/org/jargon.mjs` file no longer exists. Apparently, it was deleted, via 598463f/#4255.
- However, the `sites/dev/jargon.mjs` file does still exist. I'm not sure why one file exists but not the other.
- Some jargon definitions were moved from the old `i18n` package to the new `sites/shared/jargon/en.json` file, in the same commit/PR.
- The Using Jargon doc hasn't been updated with any information about the new files or processes. https://freesewing.dev/guides/markdown/jargon

I no longer know how Jargon is supposed to work.

**Comment by joostdecock** [comment]
Fixed in #6091 
If you want to know how jargon works: https://freesewing.dev/guides/markdown/jargon
(pending update of that page when the deploy finishes)
