### ISSUE TITLE
Create showcase from JV's Sandy

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#612]
- Content: https://twitter.com/RedBlaqueGolden/status/1317565349261434880
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: https://twitter.com/RedBlaqueGolden/status/1317752221933633537

**Comment by ElenaFdR** [comment]
I can take this! But not assign myself.

**Comment by joostdecock** [comment]
@ElenaFdR I've sent you an invite for the freesewing organisation.
Once you've accepted, you will have triage rights, and thus can assign issues to yourself or even to others.

Let me know if that doesn't work out somehow.

Also: Thank you for your contributions. It's really appreciated :heart:
