### ISSUE TITLE
[docs]: Brian's Draft For High Bust doc needs to be written

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#6124]
### Where can we see the problem? 🤔

https://freesewing.org/docs/designs/brian/options/draftforhighbust

### Suggested content

The entire contents of the `brian/options/draftforhighbust/en.md` file is:
```md
---
title: undefined
---

undefined
```

(Currently, the file doesn't appear in the org site navigation because of #6121.)

**Comment by VSinerva** [comment]
Closing as fixed by #6377
