### ISSUE TITLE
Create showcase from Karen's teagan

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#613]
- Content: https://www.instagram.com/p/CGcpH2UFlR2/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Can you comment to ok this @tangerineshark ?

**Comment by tangerineshark** [comment]
This is definitely okay! And I haven't uploaded anything to a showcase yet, but it looks like something I could figure out, so I can also take this issue. 😄
