### ISSUE TITLE
Create showcase for Julian's simon

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#615]
- Content: https://www.instagram.com/p/CER161PAv0P/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Please ask Julian

**Comment by nataliabarnhart** [comment]
I messaged Julian directly. Will report back!

**Comment by nataliabarnhart** [comment]
https://github.com/freesewing/markdown/pull/245
