### ISSUE TITLE
Create showcase for Simon by celtichomestead

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#616]
- Content: https://www.instagram.com/p/CCltTnDgKTr/
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: please ask celtichomestead on instagram

**Comment by nataliabarnhart** [comment]
I left a comment on celtichomestead's Instagram post as I wasn't able to send a direct message.

**Comment by nataliabarnhart** [comment]
https://github.com/freesewing/markdown/pull/245
