### ISSUE TITLE
Create Simon/Florence showcase from popshade post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#617]
- Content: https://www.instagram.com/p/B-2b01sALB_/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Please ask popshade on instagram

**Comment by tangerineshark** [comment]
Approval granted via FreeSewing Insta DM

**Comment by nataliabarnhart** [comment]
@tangerineshark handled this one! I checked with her before closing it.
