### ISSUE TITLE
Create showcase for Charlotte's Carlton

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#618]
- Content: https://www.instagram.com/p/B72tXp5gbir/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Please ask Charlotte (EngishGirlAtHome)

**Comment by nataliabarnhart** [comment]
I reached out to Charlotte, now charlotteemmapatterns on Instagram, to ask permission to showcase her work.

**Comment by nataliabarnhart** [comment]
https://github.com/freesewing/markdown/pull/245
