### ISSUE TITLE
Create Wahid showcase from instagram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#619]
- Content: https://www.instagram.com/p/B5Hi3ynA0r_/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Please ask kaena.mackinnon on Instagram

**Comment by tangerineshark** [comment]
Approval granted via FreeSewing Insta DM

**Comment by nataliabarnhart** [comment]
I'm closing several issues that @tangerineshark has already handled! I checked with her first ❤️
