### ISSUE TITLE
Create jaeger/wahid/simon/theodore showcase from Instagram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#620]
- Content: https://www.instagram.com/p/B2evN26oVdr/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Please ask the original author for permission

**Comment by nataliabarnhart** [comment]
I reached out to bensews on Instagram.

**Comment by nataliabarnhart** [comment]
I didn't receive a response, so I'm closing this. If the creator reaches out to me in the future, I'll reopen this issue.
