### ISSUE TITLE
Create florent showcase from Instragram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#621]
- Content: https://www.instagram.com/p/B16te2couT6/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Please ask the original author for permission

**Comment by nataliabarnhart** [comment]
We're trying to find Alexandre's contact info. If we can't figure it out, I'll close this issue.

**Comment by nataliabarnhart** [comment]
https://github.com/freesewing/markdown/pull/245
