### ISSUE TITLE
Create theodore showcase from instagram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#623]
- Content: https://www.instagram.com/p/ByA7YXUiXxM/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Please ask the original author

**Comment by tangerineshark** [comment]
So I guess these are a Vogue pattern, but completed with the help of (and much appreciation for) the "trousers from scratch" videos. So they'd probably be confusing as a showcase post, right?

**Comment by joostdecock** [comment]
I didn't realize this, but you're right @tangerineshark I just went through our Instagram feed and assumed they were all our patterns.

We'll close this, thanks for being on top of this 🙏👍
