### ISSUE TITLE
[docs]: Pattern design tutorial has wrong order of steps

### ISSUE THREAD

**Issue by HaasJona** [freesewing/freesewing#6232]
### Where can we see the problem? 🤔

https://freesewing.dev/tutorials/pattern-design/part2/drawing-the-straps

### Suggested content

At the moment of writing, the order of items on the left sidebar is

[Creating a new design](https://freesewing.dev/tutorials/pattern-design/part2/our-first-design)
[Creating a part](https://freesewing.dev/tutorials/pattern-design/part2/our-first-part)
[Drawing the straps](https://freesewing.dev/tutorials/pattern-design/part2/drawing-the-straps)
[Adding measurements](https://freesewing.dev/tutorials/pattern-design/part2/adding-measurements)
[Adding options](https://freesewing.dev/tutorials/pattern-design/part2/adding-options)
[A part's draft method](https://freesewing.dev/tutorials/pattern-design/part2/draft-method)
[Constructing the neck opening](https://freesewing.dev/tutorials/pattern-design/part2/constructing-the-neck-opening)
[Fitting the neck opening](https://freesewing.dev/tutorials/pattern-design/part2/fitting-the-neck-opening)
[Completing the neck opening](https://freesewing.dev/tutorials/pattern-design/part2/completing-the-neck-opening)
[Drawing the bib outline](https://freesewing.dev/tutorials/pattern-design/part2/drawing-the-bib-outline)
[Shaping the straps](https://freesewing.dev/tutorials/pattern-design/part2/shaping-the-straps)
[Creating the closure](https://freesewing.dev/tutorials/pattern-design/part2/creating-the-closure)
[Avoiding overlap](https://freesewing.dev/tutorials/pattern-design/part2/avoiding-overlap)
[Rounding the corners](https://freesewing.dev/tutorials/pattern-design/part2/rounding-the-corners)
[Conclusion (of part 2)](https://freesewing.dev/tutorials/pattern-design/part2/conclusion)

"Drawing the straps" references the `round` macro, so it should probably be sorted behind "Avoiding overlap", but it definitely doesn't belong so close to the beginning. I was super confused.

**Comment by BenJamesBen** [comment]
There was previous discussion on Discord about the tutorial pages not being in the correct order.
https://discord.com/channels/698854858052075530/944926520282054666/1205687058656665661
discord://discord.com/channels/698854858052075530/944926520282054666/1205687058656665661
