### ISSUE TITLE
[bug]: minor bug on Huey: infinite pocket height

### ISSUE THREAD

**Issue by AugustZellmer** [freesewing/freesewing#6238]
### What seems to be the problem? 🤔

When you change the Ribbing Height on the Huey the pocket gets infinitely tall, and then negative infinitely tall.

### Design / Plugin / Package 🧐

designs/huey

### Additional context

https://youtu.be/7brk9WDrtqQ

**Comment by AugustZellmer** [comment]
oh, does Huey extend Brian?
I didn't check whether the root cause of the bug is in Huey or a superclass. But somewhere in there. 🤷

**Comment by BenJamesBen** [comment]
In `back.mjs` and `front.mjs`, `points.hemCp2` seems to be based on the hips and waist measurements, ignoring `points.hem` and `points.CbHem` which were adjusted for the Ribbing Height option. This causes the seam to invert at certain Ribbing Height settings.

In `front.mjs`, `points.pocketTip` is based on waist measurements, ignoring `points.hem` and `points.CfHem` which were adjusted for the Ribbing Height option. `points.pocketTip` can get into an unexpected position, causing the `utils.beamsIntersect()` calculation to put `points.pocketTipCp2` into wildly unexpected positions at times. This causes the pocket curve to be incorrect.

I think that the remedy is to change the problem points to be based on `points.hem` instead. The logic for the calculation of various points might also have to be adjusted to make sure the pattern continues to follow designer intent.

**Comment by BenJamesBen** [comment]
Possible inverted side seam allowance fix:

```diff
--- a/designs/huey/src/back.mjs
+++ b/designs/huey/src/back.mjs
@@ -28,7 +28,7 @@ function draftHueyBack({
   // Shape side seam
   points.hips.x = (measurements.hips * (1 + options.hipsEase)) / 4
   points.hem.x = points.hips.x
-  points.hemCp2 = new Point(points.hips.x, points.cbWaist.y)
+  points.hemCp2 = new Point(points.hips.x, Math.min(points.cbWaist.y, points.hem.y))
 
   // Store length of the neck seam
   store.set(
```

```diff
--- a/designs/huey/src/front.mjs
+++ b/designs/huey/src/front.mjs
@@ -29,7 +29,7 @@ function draftHueyFront({
   // Shape side seam
   points.hips.x = (measurements.hips * (1 + options.hipsEase)) / 4
   points.hem.x = points.hips.x
-  points.hemCp2 = new Point(points.hips.x, points.cfWaist.y)
+  points.hemCp2 = new Point(points.hips.x, Math.min(points.cfWaist.y, points.hem.y))
 
   // Front pocket
   points.pocketCfTop = points.cfNeck.shiftFractionTowards(points.cfHem, 1 - options.pocketHeight)
```

Possible infinite pocket fix:

```diff
--- a/designs/huey/src/front.mjs
+++ b/designs/huey/src/front.mjs
@@ -36,7 +36,7 @@ function draftHueyFront({
   points.pocketTopRight = points.pocketCfTop.shift(0, points.hem.x * options.pocketWidth)
   points.pocketTip = new Point(
     points.pocketTopRight.x * 1.2,
-    points.cfWaist.y + points.cfWaist.dy(points.hem) * 0.7
+    points.pocketTopRight.y + (points.hem.y - points.pocketTopRight.y) * 0.9
   )
   points.pocketHem = new Point(
     points.pocketTopRight.x + points.pocketTopRight.dx(points.pocketTip) / 2,
```

**Comment by joostdecock** [comment]
@BenJamesBen I can't seem to reproduce this. Was there a fix that I've forgotten about, or an I just in need of sleep?

**Comment by BenJamesBen** [comment]
@joostdecock I am still able to reproduce this issue on freesewing.org by following the documented steps. _Make sure you use the "Ghislain" curated measurements set._

**Comment by joostdecock** [comment]
Ah yes, I did not test with that measurements set.

Ok, I've put up #6390 for this. But it's just your changes @BenJamesBen so you might as well put up a PR next time :)

**Comment by BenJamesBen** [comment]
Thanks for fixing the issue. 

(I will usually add a possible code fix in an issue if I do initial troubleshooting but am not ready to file a PR in the near future. Sometimes it's because at the moment I'm not prepared to commit to the time to do the work. Other times I want to think more about the fix and whether it is the best choice.)
