### ISSUE TITLE
[docs]: Uma required mesurements are none on the dedicate page

### ISSUE THREAD

**Issue by PtitLutinn** [freesewing/freesewing#6246]
### Where can we see the problem? 🤔

https://freesewing.org/fr/docs/designs/uma/measurements

### Suggested content

they are 4 required mesurements : 
    [Seat circumference](https://freesewing.org/fr/docs/measurements/seat)
    [Waist circumference](https://freesewing.org/fr/docs/measurements/waist)
    [Waist to seat](https://freesewing.org/fr/docs/measurements/waisttoseat)
    [Waist to upper leg](https://freesewing.org/fr/docs/measurements/waisttoupperleg)

Don't know the formal way, just copy from the design page

### Additional context

Just saw this when I'm working on translation

**Comment by BenJamesBen** [comment]
Uma's documentation is hardcoded to say that it has no required measurements.

In `markdown/org/docs/designs/uma/measurements/en.md`:
```md
---
title: "Uma undies: Required Measurements"
---

<Note>
Uma does not require any measurements
</Note>
```

Suggested fix:
```diff
--- a/markdown/org/docs/designs/uma/measurements/en.md
+++ b/markdown/org/docs/designs/uma/measurements/en.md
@@ -2,6 +2,4 @@
 title: "Uma undies: Required Measurements"
 ---
 
-<Note>
-Uma does not require any measurements
-</Note>
+<DesignMeasurements design='uma' />
```
