### ISSUE TITLE
Create simon showcase from instragram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#625]
- Content: https://www.instagram.com/p/Bu_aiD8H3Lg/?utm_source=ig_web_copy_link
 - Howto: https://freesewing.dev/editors/showcase/
 - Permission: Please ask the original author for permission

**Comment by nataliabarnhart** [comment]
I checked that Andrew granted us permission to share this.

![IMG_9693](https://user-images.githubusercontent.com/48160791/105554552-986cf900-5cd5-11eb-830a-ed70fe3af67e.PNG)

**Comment by nataliabarnhart** [comment]
https://github.com/freesewing/markdown/pull/151 :)

**Comment by joostdecock** [comment]
@nataliabarnhart I think you should have permissions that allow you to close this issue, no?

I mean, I can close it. But you did the work, I feel you get to close it for that sense of accomplishment :) :+1:
