### ISSUE TITLE
Create simon showcase from instagram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#626]
- Content: https://www.instagram.com/p/BuT-mIoHrWc/?utm_source=ig_web_copy_link
- Howto: https://freesewing.dev/editors/showcase/
- Permission: Please ask the original author for permission

**Comment by tangerineshark** [comment]
DM'd this person for permission from the FreeSewing Insta on 20 Nov 2020, haven't heard back

**Comment by nataliabarnhart** [comment]
I messaged @passfailsewing on Instagram asking for permission. If I don't hear back, I'll close this issue.

**Comment by nataliabarnhart** [comment]
I didn't receive a response, so I'm closing this. If the creator reaches out to me in the future, I'll reopen this issue.
