### ISSUE TITLE
Create jaeger showcase from instragram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#627]
- Content: https://www.instagram.com/p/Bo_r6iNnaRF/?utm_source=ig_web_copy_link (make sure to also post the YouTube video)
- Howto: https://freesewing.dev/editors/showcase/
- Permission: Please ask permission from the original author

**Comment by nataliabarnhart** [comment]
I reached out to @silent_art_photography on Instagram which is the contact info listed on their YouTube channel (https://youtu.be/kQRB2-Q9hgo).

**Comment by nataliabarnhart** [comment]
I didn't receive a response, so I'm closing this. If the creator reaches out to me in the future, I'll reopen this issue.
