### ISSUE TITLE
Create simon showcase from instagram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#628]
- Content: https://www.instagram.com/p/BnD6OL-BtMr/?utm_source=ig_web_copy_link
- Howto: https://freesewing.dev/editors/showcase/
- Permission: Please ask the original author for permission

**Comment by tangerineshark** [comment]
Permission granted via Insta DM

**Comment by nataliabarnhart** [comment]
@tangerineshark handled this one! I checked with her before closing it.
