### ISSUE TITLE
Create Jaeger showcase from instagram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#629]
- Content: https://www.instagram.com/p/BnBDQ4Xh9G0/?utm_source=ig_web_copy_link
- Howto: https://freesewing.dev/editors/showcase/
- Permission: Please ask the original author for permission

**Comment by nataliabarnhart** [comment]
Trying to identify the original author. If I can't find them, I'll close this out.

**Comment by nataliabarnhart** [comment]
https://github.com/freesewing/markdown/pull/245
