### ISSUE TITLE
Create sandy showcase from instagram post

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#631]
- Content: https://www.instagram.com/p/BmiiX7jARTd/?utm_source=ig_web_copy_link
- Howto: https://freesewing.dev/editors/showcase/
- Permission: Please ask the original author for permission aka @annekecaramin

**Comment by annekecaramin** [comment]
okido!

**Comment by ElenaFdR** [comment]
I can do this!

**Comment by ElenaFdR** [comment]
@annekecaramin, can I grab all the photos from your blogpost for this?

**Comment by annekecaramin** [comment]
Sure! No problem :)
