### ISSUE TITLE
[bug]: JSON and YAML buttons missing on public Measurement Sets when not logged in

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#6320]
### What seems to be the problem? 🤔

The JSON and YAML buttons are missing on public Measurement Sets for not-logged-in users. (The actual JSON and YAML web pages do work if the URLs are typed in manually.)

(Tested using https://freesewing.org/set?id=46035)

![Screenshot 2024-03-08 at 9 00 34 AM](https://github.com/freesewing/freesewing/assets/109869956/5f6cb6a9-b18a-492d-bad0-bd591dfa78b8)
![Screenshot 2024-03-08 at 9 00 46 AM](https://github.com/freesewing/freesewing/assets/109869956/a98831e6-fda7-456e-b24a-f849d5f415ad)

**Comment by BenJamesBen** [comment]
For non-logged-in users `account.control === 2`, and the `sites/shared/components/account/sets.mjs` says:
```js
          {account.control > 3 && mset.public ? (
            // the code that displays the JSON and YAML buttons
           ) : (
             <span></span>
           )}
```

There doesn't seem to be a way for non-logged-in users to change the User Experience.

**Comment by joostdecock** [comment]
I've bumped the control level to 3 for non-logged in users, and changed the check to `account.control > 2`.

See 6bd3009e9fb4292286a89f076b1810c4d0147cf5
