### ISSUE TITLE
[bug]: Old v2 websites like en.freesewing.org are still accessible

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#6323]
### What seems to be the problem? 🤔

Old v2 FreeSewing websites such as https://en.freesewing.org are still accessible. They allow users to create v2 accounts (which do not carry over to the new v3 site). This issue was reported on Discord by a user who inadvertently found that site and created a v2 account there before discovering that the newer, v3 freesewing.org site existed.

>Hey there! What is the difference between freesewing.org en.freesewing.org? I somehow found en.freesewing.org first, created an account there. It looks like the app on freesewing.org (without the subdomain) is more polished (?) and I can't log into freesewing.org with my en.freesewing.org account. Is that intended?

https://discord.com/channels/698854858052075530/1215700599161749535/1215700599161749535
discord://discord.com/channels/698854858052075530/1215700599161749535/1215700599161749535

The affected websites are:
- https://en.freesewing.org
- https://de.freesewing.org
- https://es.freesewing.org
- https://fr.freesewing.org
- https://nl.freesewing.org

(There is no uk.freesewing.org site.)

**Comment by BenJamesBen** [comment]
(If it is intentional that these v2 sites remain running, then perhaps we might want to put some sort of prominent banner on them to let users know that they are deprecated and point them to the current site.)

**Comment by HaasJona** [comment]
I remember from Discord discussion that the old pages have been taken offline and I'm getting certificate issues when trying to acces them. Can this issue be closed?

**Comment by joostdecock** [comment]
It can :)
