### ISSUE TITLE
Bad new user experience report

### ISSUE THREAD

**Issue by alex-fu27** [freesewing/freesewing#6324]
My girlfriend had a very bad experience creating an account today and I have learned a lot about UX from that that I would like to share with you.

## TLDR
* Passwordless login, if not explained, seems confusing if you have been taught that a strong password was required for any website to be safe.
* Some parts of the account creation workflow are unclear or even confusing, at least in the German translation.
* The account creation workflow should not drop the user into the documentation, but have a page that reads something like *"Done! If you want, you can set up a password in your account settings, but you can also keep logging in through sign-in links. We will now direct you to the documentation so you can learn how to create sewing patterns!"*

## Story
To begin with, we speak German natively and she has absolutely zero technical background.
I had found freesewing.org a week earlier, and created an account, but set the language to English, so I had ended up on en.freesewing.org which I found out now hosts an older version of the website.

My girlfriend started by entering `freesewing.org` into the address bar on her latpop PC, I had given her the domain name. The site was correctly served in German. It was looking a little bit different than on my PC, which started the confusion.

She then entered her e-mail address into the singup form and had a sign-up link sent to her e-mail address. She found it weird that she didn't have to enter a password and we will come back to that later.
Thinking that this was a confirmation e-mail, she clicked the link on her phone (she doesn't usually do this on her PC because then she has to enter her password because for reasons of perceived security she always logs out of any website before she closes the browser tab).
That made the onboarding flow continue on her phone.

She worked through the wizard and the first thing that comes up is the GPDR confirmation
<img width="512" alt="Screenshot 1" src="https://github.com/freesewing/freesewing/assets/49982580/3ad4813b-059b-4d5d-b347-37785328e81f">
Which she read and thought "of course they need to process my measurements" so she clicked "confirm" and then two checkmarks appeared
<img width="556" alt="Screenshot 2" src="https://github.com/freesewing/freesewing/assets/49982580/9bfecd63-1c48-49b0-affd-21d8ceb90d32">
while the text did not change, which confused me but didn't confuse her because she didn't read the labels because the text didn't change ¯\\\_(ツ)\_/¯

I then left her to join the Discord and ask about the difference between `en.freesewing.org` and `freesewing.org`. 

In the meanwhile, she got this screen
<img width="449" alt="Screenshot 3" src="https://github.com/freesewing/freesewing/assets/49982580/57e72e31-f68f-4937-a4e8-98505126e195">
which is a little bit lost in translation: "Power" has two different translations in German: one is "Leistung" which is measured in Watts (used in the middle option) and the other is "Macht" which is what a King has (in the fourth option). Then there is "safety" which is correctly translated as "Sicherheit", but in German this also means "security"... So she didn't understand that this was about the amount of options versus ease of use and thought it had something to do with account security.

The next thing that was confusing was the measurement comparison question:
<img width="444" alt="Screenshot 4" src="https://github.com/freesewing/freesewing/assets/49982580/91506efe-cc7c-4ed6-b1d0-beb3e3491b14">
She didn't understand that she would be compared to an average and asked herself if it was like "Person X has longer legs than you"? But she had already seen the comparison chart in my account.

She then clicked through the rest of the flow and then ended up here
![Bildschirmfoto am 2024-03-08 um 20 15 42](https://github.com/freesewing/freesewing/assets/49982580/8c4c9318-cb64-45a5-a3cd-304b44a9bb02)

which looks totally different than all the pages she had seen so far, which somehow frightened her. She thought that was part of the account creation process, didn't read it, and kept clicking the "next" buttons at the end of each documentation page.
Her feeling of uncanniness was growing. The website didn't look right, it had been looking differently on my computer, and after all she had not set a password. Having learned in school that passwords are veeery important, she started to get super frightened and deleted her account.

In the meantime, I was sitting at my desk, finding out that there is a version mismatch between en.freesewing.org and freesewing.org. She started saying things like "this seems not right" and "I don't feel comfortable with that" and I didn't understand what she meant and told her that it's fine and that the version she saw on my PC was probably older and she became more and more reluctant so finally I started to tell her to leave it be, then. She broke out in tears and left the room. I followed her to comfort her, and she was asking things like "I've deleted the account but I've given them my e-mail address, what can they do with that?" and "I've had my password manager open, could they have read my passwords?" and the situation was so weird that I couldn't help but start laughing, which really didn't help. I then left, pacing up and down in the living room thinking about what could have caused all of that.

She later told me about how she had learned in school that the internet was a very dangerous place, security practices that were outdated or wrong, and she didn't understand the way her e-mail and accounts were connected, and especially I told her about passwordless login. I then showed her Github and we are right now creating this issue togehter, creating a new account for her. See my conclusions in the TL;DR section. Maybe this weekend we will sign up to the translation tool and try to make some of the translations clearer.

**Comment by BenJamesBen** [comment]
This was first mentioned in a Discord discussion:
https://discord.com/channels/698854858052075530/1215700599161749535/1215704182317650011
discord://discord.com/channels/698854858052075530/1215700599161749535/1215704182317650011

**Comment by joostdecock** [comment]
Thank you @alex-fu27 for this detailed write-up, much appreciated.

Please extend my apologies to your girlfriend, it is clearly not our intention to cause people stress or make them worry.
The internet is indeed a dangerous place, and your girlfriend had the right instinct to back out when she felt unsure.
That being said, even on the internet there are _good guys_ and think we qualify for that, but still :)

There are two things here that I think we need to differentiate against (opinions my own)

- The UX is bad: It's perhaps because I'm too close to the subject matter, but I find it surprisingly difficult to explain what FreeSewing is/does in an intuitive way to people completely new to the site. So we drop them to the guide hoping they will read. Obviously not idea. I am super open to any input if you think you can crack this one.
- The translation is bad or confusing: We rely on volunteers to translate to other languages. The idea here being that having _a_ translation is better than having no translation. It's not perfect, but it's German speakers who can fix that ;)

As for en.freesewing.org, this is the _old_ v2 site. We migrated to v3 in ... checks notes ... November, and I've kept it around to allow people to visit their old account in case we needed to troubleshoot issues with the migration.

My plan is to remove it by the end of the month, so that issue should solve itself.

If you'd like to help us improve the UX, I'm happy to keep this open.
If not, I'm not sure having this constant reminder that no matter our best efforts, it's a confusing mess, will not do much good ;)

**Comment by alex-fu27** [comment]
We would be happy to contribute and I would start with trying to make the translation clearer, but that might currently take some time. So regarding this issue here, please go ahead and decide whether to keep it open or not :)

**Comment by joostdecock** [comment]
@alex-fu27 I'm going to close this because we have a lot of open issues and I'd like to get it down to a manageable amount.

This one is a bit too unspecific and risks staying open until the heath death of the universe.
The being said, I very much welcome the offer to help out :)
