### ISSUE TITLE
[bug]: Public measurement sets are always displayed as metric

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#6325]
### What seems to be the problem? 🤔

When a public measurement set is viewed, it is always in metric units. This is regardless of the measurement set setting. It is also regardless of the account setting for logged-in users.

### Additional context

It is unclear what should happen if User M (whose account is set to metric) creates a metric measurement set and User I (whose account is set to imperial) views that measurement set. Should the measurements be displayed in metric or imperial?

It is also unclear what should happen if User I (whose account is set to imperial) intentionally creates a metric measurement set, and then the same User I views that measurement set. Should the measurements be displayed in metric or imperial?

---

However, it appears that much of the problem is that:
1. When retrieved as a regular set, a given measurement set has an `imperial` property that is `true` or `false`. It does not have a `units` property.
2. When retrieved as a public set, the same measurement set has a `units` property that is `imperial` or `metric`. It does not have an `imperial` property.
3. The display code was always checking for `imperial` and not `units`.

A possible fix, assuming that the measurement set should dictate the units:
```diff
--- a/sites/shared/components/account/sets.mjs
+++ b/sites/shared/components/account/sets.mjs
@@ -263,7 +263,7 @@ export const Mset = ({ id, publicOnly = false }) => {
         setName(result.data.name)
         setImage(result.data.image)
         setIsPublic(result.data.public ? true : false)
-        setImperial(result.data.imperial ? true : false)
+        setImperial(result.data.units === 'imperial' ? true : false)
         setNotes(result.data.notes)
         setMeasies(result.data.measurements)
         setLoadingStatus([true, 'backendLoadingCompleted', true, true])
@@ -425,7 +425,7 @@ export const Mset = ({ id, publicOnly = false }) => {
             <h2>{t('measies')}</h2>
             {Object.entries(mset.measies).map(([m, val]) =>
               val > 0 ? (
-                <DisplayRow title={<MeasieVal {...{ m, val, imperial: mset.imperial }} />} key={m}>
+                <DisplayRow title={<MeasieVal {...{ m, val, imperial: (mset?.units === 'imperial' || mset?.imperial) ? true : false }} />} key={m}>
                   <span className="font-medium">{t(m)}</span>
                 </DisplayRow>
               ) : null
@@ -436,7 +436,7 @@ export const Mset = ({ id, publicOnly = false }) => {
         <h2>{t('data')}</h2>
         <DisplayRow title={t('name')}>{mset.name}</DisplayRow>
         <DisplayRow title={t('units')}>
-          {mset.imperial ? t('imperialUnits') : t('metricUnits')}
+          {(mset?.units === 'imperial' || mset?.imperial) ? t('imperialUnits') : t('metricUnits')}
         </DisplayRow>
         {control >= controlLevels.sets.notes && (
           <DisplayRow title={t('notes')}>
```

(Also, it might be nice to be able to toggle units back and forth when viewing a public measurement set, so metric users can more easily view an imperial-saved measurement set and vice versa.)

**Comment by joostdecock** [comment]
> *it might be nice to be able to toggle units back and forth when viewing a public measurement set*

This is what's implemented in #6376
