### ISSUE TITLE
[feature]: Duplicate measurement sets

### ISSUE THREAD

**Issue by HaasJona** [freesewing/freesewing#6339]
### What is it that you would like to see happen? 🤔

It would be good if you were able to create a duplicate of one of your measurement sets, for example to create a safety copy before making adjustments, or to have a duplicate with some intentional differences (e.g. one with padded breasts, one without)

### Additional context

There is an export option, but no import option, so another workaround would be to add an import option for json values.

**Comment by HaasJona** [comment]
Related is #5563

**Comment by joostdecock** [comment]
Implemented in #6371
