### ISSUE TITLE
[feature]: In exported SVG's, wrap symbols in <symbol> element instead of <g> and <use /> them from main content, for Inkscape integration

### ISSUE THREAD

**Issue by roel-v** [freesewing/freesewing#6359]
### What is it that you would like to see happen? 🤔

There may be a reason why this hasn't been implemented like this, but while I was working on an Inkscape-to-FS-Javascript converter, I stumbled upon all the FS symbols that are in every exported SVG in the defs sections. Things like 'logo', 'bnotch' and so on. There are also 'markers' in there already that can then be used inside Inkscape, but if all the other symbols (the ones that are now wrapped simply in <g> elements) would instead be <symbol>s, and then for each of them these was a 

```
  <use
     xlink:href="#symbol1"
     id="use1" />
```

element after the 'main content' so to say (outside of the defs), then those symbols would show up in the Inkscape Symbols manager and it would be possible to use them from there when using Inkscape for pattern drafting. I could then also easily convert that back into FS Javascript code from within my converter.

I don't know if there are other implications to this in other SVG software, or if any other part of FS already depends on the current behavior, but if there are no consequences, a little touch like this would make integration in the broader tool ecosystem nicer, IMO.

**Comment by joostdecock** [comment]
I'm generally in favor of facilitating integration with other tools.
We'd have to look into possible side-effects before implementing this, but on the principle, I'm on board.

**Comment by joostdecock** [comment]
No response. Closing. But feel free to revive.
