### ISSUE TITLE
[bug]: Lumira's shape part is not hidden

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#6387]
### What seems to be the problem? 🤔

Lumira has a shape part that is not visible in most Pattern Editor views because it has no visible paths. However, the part itself is not hidden, and it appears in the Print Layout view as a floating toolbar.
![Screenshot 2024-03-17 at 11 25 13 AM](https://github.com/freesewing/freesewing/assets/109869956/c82f7ef1-6e50-4376-84a6-30a9f5cdd7b8)

### Design / Plugin / Package 🧐

designs/lumira

### Additional context

This resulted in minor user confusion, as mentioned on Discord:
https://discord.com/channels/698854858052075530/1218975396050239588/1218975396050239588
discord://discord.com/channels/698854858052075530/1218975396050239588/1218975396050239588

**Comment by joostdecock** [comment]
Assigning to @woutervdub

**Comment by BenJamesBen** [comment]
FYI, I also see the same issue with the related Lumina design.
