### ISSUE TITLE
Pattern PDF cover page shows null for pattern name in tagline

### ISSUE THREAD

**Issue by DocSpencer77** [freesewing/freesewing#646]
![image](https://user-images.githubusercontent.com/43393580/87990182-20fda900-caa9-11ea-8f31-eb7891e29eb0.png)

Whether or not the pattern has been saved by the user, no pattern name shows.  This programming occurs in the tiler which is written in C, so it is more work than some things, but when cutting out and organizing patterns and pattern pieces, it would be very helpful to have the name the user has assigned to the particular pattern/draft (seeing as how they may make the same pattern for many different individual or sizes) on each piece, and certainly on the cover sheet.

**Comment by joostdecock** [comment]
Hell yeah I fixed it.

**Comment by DocSpencer77** [comment]
Thanks so much, @joostdecock !! Way to go!  I know it was not a trivial or "for fun" task.  I have a large file box of "orphaned" pattern pieces that have at some point in time become separated from the pattern they belong to!  At least they have pattern numbers on them! Admittedly, my organization scheme is weak, and I appreciate that you've made this work better.
