### ISSUE TITLE
Cant enter some Measurment. 

### ISSUE THREAD

**Issue by stoffsuchti** [freesewing/freesewing#647]
On the Person https://freesewing.org/people/veuft/  i cant enter some measurments. 
<img width="1425" alt="Bildschirmfoto 2020-10-24 um 20 19 42" src="https://user-images.githubusercontent.com/1039463/97089265-e6bb1f00-1636-11eb-90f3-c3ef5b90427e.png">
If i click on the pencil on the right

I end on the front page and can't go back to the measurement page. 

<img width="1678" alt="Bildschirmfoto 2020-10-24 um 20 20 22" src="https://user-images.githubusercontent.com/1039463/97090120-c93a8500-1637-11eb-8319-c0c9802c9c51.png">

Could you please look and if possible fix it?

**Comment by joostdecock** [comment]
Those are old measurements that have been deprecated, and don't exist any longer.
But they still show up in the person if they were added before we changed them (in 2.7 if memory serves me well).

I'll look into hiding them from the UI.

**Comment by joostdecock** [comment]
Reload your account, it should be ok now.

**Comment by stoffsuchti** [comment]
it seems to work
