### ISSUE TITLE
[bug]: After I allowed MFA authentication, login was unabled for good, just nothing was shown on web site page, it is empty. At Chrome, Firefox and at my cell phone too

### ISSUE THREAD

**Issue by GalitU** [freesewing/freesewing#6560]

**Comment by joostdecock** [comment]
Could you share your username on the site @GalitU that way I can see if there's something I can do about it.

**Comment by GalitU** [comment]
> Could you share your username on the site @GalitU that way I can see if there's something I can do about it.

Hello, it fix after a few minute, so please if you can, just close this issue.
