### ISSUE TITLE
Jargon terms white on white in dark mode

### ISSUE THREAD

**Issue by timorl** [freesewing/freesewing#661]
As seen here: ![screenshot](https://user-images.githubusercontent.com/4363804/97783956-79aa0b00-1b9b-11eb-985d-379237ee0d5f.jpg)

It seems the `background` property in the CSS is not overwritten for the `jargon-term` element in dark mode.

I wanted to make this a PR instead of an issue, but the way you generate CSS is over my head, sorry. :<

**Comment by joostdecock** [comment]
Thanks for reporting this. Fix is being build/deployed.

![Screenshot from 2020-11-02 16-13-32](https://user-images.githubusercontent.com/1708494/97884508-72fbcf00-1d26-11eb-821d-f8dc24fef24b.png)
