### ISSUE TITLE
Broken link in footer: FAQ should point to `/faq`

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#67]
The FAQ link in the footer points to /docs/faq but should point to /faq instead.

Just update this line: https://github.com/freesewing/freesewing/blob/develop/packages/components/src/Footer/index.js#L21

**Comment by joostdecock** [comment]
Ah, this is actually in the Footer component. Closing in favor of https://github.com/freesewing/freesewing/issues/67

**Comment by joostdecock** [comment]
Obviously I closed the wrong issue :)

**Comment by sorchanidhubhghaill** [comment]
Did I fix it?

**Comment by joostdecock** [comment]
You sure did :1st_place_medal:
