### ISSUE TITLE
[bug]: setError is not defined when trying to upload invalid measurement set yaml file

### ISSUE THREAD

**Issue by HaasJona** [freesewing/freesewing#6771]
### What seems to be the problem? 🤔

```
Uncaught (in promise) ReferenceError: setError is not defined
    uploadSet import.mjs:55
    onload inputs.mjs:606
    onDrop inputs.mjs:606
    setFiles index.js:708
    onDropCb index.js:732
    promise callback*useDropzone/onDropCb< index.js:727
    composeEventHandlers index.js:192
    composeEventHandlers index.js:190
    React 15
import.mjs:55:6
```

Tried to import this file here: https://gist.githubusercontent.com/BenJamesBen/3315434cdfb716f51325500ed73e1328/raw/8e6d9f9a051d6f7656250dfcdab241c03be43063/models.yaml

which apparently has duplicate keys or something.

### Design / Plugin / Package 🧐

packages/core

**Comment by HaasJona** [comment]
Note: I managed to import the file (just needed minor changes), but the error handling here needs to be improved. I couldn't find that `setError` method.

**Comment by joostdecock** [comment]
Knowing me, the idea here was probable to have a `[error, setError]` react state handler, which is why `setError` is called so we could display an error state.

However, since the error state is already shown in the loadingstatus, I've just dropped this call in #6836
