### ISSUE TITLE
[bug]: Problems With Tamiko Top

### ISSUE THREAD

**Issue by jaceruzek** [freesewing/freesewing#6822]
### What seems to be the problem? 🤔

When I generate the Tamiko Top, some necessary seam lines are pushed outside of the pattern itself. This continues when I go to create the PDF for the pattern as well as when I go to print it out. 

### Design / Plugin / Package 🧐

designs/tamiko

### Additional context

![Screenshot (4)](https://github.com/freesewing/freesewing/assets/171629048/b895ee89-0b2f-4bc7-9ac1-82b79e433a11)

**Comment by HaasJona** [comment]
Please double check your measurements. Shoulder-to-shoulder looks very large compared to the chest measurement.
