### ISSUE TITLE
The showcase post ursula-and-bee was claimed as their own by user 20650

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#6844]
This issue is about who should get credit for [this showcase post](https://freesewing.org/showcase/ursula-and-bee).

According to [user bobgeorgethe3rd](https://freesewing.org/users/user?id=20650) with ID 20650,
who claimed it as their own.

To reflect this on the site, update [this markdown file](https://github.com/freesewing/freesewing/blob/develop/markdown/org/showcase/ursula-and-bee/en.md) so that the frontmatter includes this:

```md
author: 20650
```

Anyone can do this, so if you're looking to contribute, this is a great way to get started.

[![User 20650](https://backend3.freesewing.org/users/20650/card)](https://next.freesewing.org/users/20650)

**Comment by bobgeorgethe3rd** [comment]
Testing Backend is back before informing people closing.
