### ISSUE TITLE
[feature]: Add option for collar width multiplier in Simon

### ISSUE THREAD

**Issue by karlnippoldt** [freesewing/freesewing#6907]
### What is it that you would like to see happen? 🤔

In Simon, currently a fixed 1.2 multiplier is used to calculate the collar width from the collar stand width. For smaller sizes, this results in a collar that barely covers the stand without a tie and does not cover the collar stand with a thicker tie. An option to adjust and increase this multiplier would allow users to resolve this issue in their patterns.

**Comment by joostdecock** [comment]
Sounds entirely reasonable.

If anyone wants to take a stab at this, feel free to submit a PR. Although perhaps leave a comment here to avoid double work.

**Comment by VSinerva** [comment]
I'll have crack, mostly to build my understanding of how to work with the actual designs :sweat_smile: :+1:
