### ISSUE TITLE
[docs]: `waralee` straps documentation inconsistent and unclear

### ISSUE THREAD

**Issue by woutervdub** [freesewing/freesewing#6931]
### Where can we see the problem? 🤔

https://freesewing.org/docs/designs/waralee/cutting
https://freesewing.org/docs/designs/waralee/instructions

### Additional context

@Wouter.vdub Waralee is a little bit confusing, because the cutting instructions don't mention the strips and the sewing instructions tell you to measure and construct them manually. (It explicitly says "These strings are not included in the pattern." at the top). But then the pattern actually contains the strips.

**Comment by VSinerva** [comment]
Closing as fixed by #6932
