### ISSUE TITLE
[bug]: Jaeger chest piece includes the lapel

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#6941]
### What seems to be the problem? 🤔

The chest piece should be cut off along the lapel roll line.

### Design / Plugin / Package 🧐

designs/jaeger

### Additional context

https://discord.com/channels/698854858052075530/757632180980547686/1259476297055473734

**Comment by BenJamesBen** [comment]
The Discord discussion:

Hopper — 07/07/2024 4:49 AM
> I'm working on the jaeger jacket right now, and i've gotten a bit stuck, the chest piece looks like it doesnt include the lapels in the instructions, but the pattern i printed had the chest piece including the lapels?
![image](https://github.com/user-attachments/assets/3ab48f61-4f9a-4baf-9f14-e4e1bb79752c)

joostdecock — 07/07/2024 8:58 AM
> Huh, you are right. It shouldn't You can cut that part off, so it's not too late. The instructions are correct.
Issue: https://github.com/freesewing/freesewing/issues/6941

Hopper — 07/07/2024 9:47 AM
> thank you so much!

**Comment by BenJamesBen** [comment]
In this screenshot, the dash-dotted line on the Front part shows the correct outline for the underlying Chest part, along with the actual, incorrect Chest part.
![Screenshot 2024-08-26 at 5 11 14 PM](https://github.com/user-attachments/assets/92ef9312-c931-4fdb-8b2f-8aae52517c09)

The triangular lapel section needs to be removed from the Chest part. The Grainline and Logos will also need to be moved over to the right in the corrected part.

**Comment by BenJamesBen** [comment]
A possible fix. In `designs/jaeger/src/chest-piece.mjs`:
```diff
@@ -44,9 +44,7 @@ function jaegerChestPiece({
     .curve(points.armholePitchCp2, points.shoulderCp1, points.shoulder)
     .line(points.neck)
     .line(points.collarCorner)
-    .line(points.notch)
-    .line(points.notchEdge)
-    ._curve(points.lapelStraightEndCp1, points.lapelStraightEnd)
+    .line(points.shoulderRoll)
     .line(points.lapelBreakPoint)
     .curve(points.cutawayPoint, points.waist, points.fsArmhole)
     .close()
@@ -61,12 +59,12 @@ function jaegerChestPiece({
   store.cutlist.setCut({ cut: 2, from: 'canvas' })
 
   // Logo
-  snippets.logo = new Snippet('logo', points.innerPocketBottomLeft)
+  snippets.logo = new Snippet('logo', points.innerPocketBottomRight)
 
   // Grainline
   macro('grainline', {
-    from: new Point(points.cfNeck.x, points.lapelBreakPoint.y),
-    to: points.cfNeck,
+    from: new Point(points.collarCorner.x, points.lapelBreakPoint.y),
+    to: points.collarCorner,
   })
 
   // Title
```
![Screenshot 2024-08-26 at 5 49 48 PM](https://github.com/user-attachments/assets/5274894d-f4a4-40b0-95a5-31e191e292b5)
