### ISSUE TITLE
The showcase post sandy-by-anneke was claimed as their own by user 71794

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#6973]
This issue is about who should get credit for [this showcase post](https://freesewing.org/showcase/sandy-by-anneke).

According to [user Karlo](https://freesewing.org/users/user?id=71794) with ID 71794,
who claimed it as their own.

To reflect this on the site, update [this markdown file](https://github.com/freesewing/freesewing/blob/develop/markdown/org/showcase/sandy-by-anneke/en.md) so that the frontmatter includes this:

```md
author: 71794
```

Anyone can do this, so if you're looking to contribute, this is a great way to get started.

[![User 71794](https://backend3.freesewing.org/users/71794/card)](https://next.freesewing.org/users/71794)

**Comment by VSinerva** [comment]
Username doesn't match the person who is known to have made this, and the account (based on user ID) is significantly newer than the showcase.

Closing.
