### ISSUE TITLE
Add a place for people to request new articles of clothing

### ISSUE THREAD

**Issue by gandrus** [freesewing/freesewing#702]
There are a few articles of clothing I'm interested in making - at the moment, it's:

- Athletic leggings 

- Leotards/full-torso swimwear

But there isn't a place on the site to submit requests of this nature.

**Comment by joostdecock** [comment]
Creating a place on the website to submit requests for patterns would set the wrong expectations.
So no, not going to happen.

As for your own requests, We are not shy of ideas for patterns. What we struggle with is a lack of time and resources.
