### ISSUE TITLE
The showcase post quentin-carlita was claimed as their own by user undefined

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#7042]
This issue is about who should get credit for [this showcase post](https://freesewing.org/showcase/quentin-carlita).

According to [user false](https://freesewing.org/users/user?id=undefined) with ID undefined,
who claimed it as their own.

To reflect this on the site, update [this markdown file](https://github.com/freesewing/freesewing/blob/develop/markdown/org/showcase/quentin-carlita/en.md) so that the frontmatter includes this:

```md
author: undefined
```

Anyone can do this, so if you're looking to contribute, this is a great way to get started.

[![User false](https://backend3.freesewing.org/users/false/card)](https://freesewing.org/users/user?id=false)

**Comment by HaasJona** [comment]
This looks like a bug

**Comment by bobgeorgethe3rd** [comment]
Undefined user
