### ISSUE TITLE
[bug]: "Bust aligned buttons: even spacing" crashes on measies with small bust

### ISSUE THREAD

**Issue by HaasJona** [freesewing/freesewing#7054]
### What seems to be the problem? 🤔

Might be a unusual edge case, but if you for some reason draft a Simone pattern on a measurement sets with small busts (presumably causing the FBA to be disabled), the drafting crashes if "even spacing" is selected for the bust button option.

Issue found while investigating another problem.

### Design / Plugin / Package 🧐

designs/simone

### Additional context

Test link to reproduce: https://freesewing.org/new/simone#view=%22logs%22&settings=%7B%22measurements%22%3A%7B%22biceps%22%3A310%2C%22chest%22%3A870%2C%22hpsToBust%22%3A280%2C%22hpsToWaistBack%22%3A430%2C%22neck%22%3A360%2C%22shoulderToShoulder%22%3A450%2C%22shoulderSlope%22%3A13%2C%22waistToArmpit%22%3A190%2C%22waistToHips%22%3A60%2C%22waist%22%3A880%2C%22hips%22%3A880%2C%22highBust%22%3A890%2C%22bustSpan%22%3A225%2C%22shoulderToWrist%22%3A630%2C%22wrist%22%3A165%7D%2C%22units%22%3A%22metric%22%2C%22metadata%22%3A%7B%22setName%22%3A%22Ghislain%22%7D%2C%22options%22%3A%7B%22bustAlignedButtons%22%3A%22even%22%7D%7D

**Comment by BenJamesBen** [comment]
When a FBA isn't performed, Simone returns without creating `points.cfBust` which Even and Split bust-aligned-buttons require.

A possible solution would be for Simone to create `points.cfBust` before the FBA check and return:

```diff
--- a/designs/simone/src/fba-front.mjs
+++ b/designs/simone/src/fba-front.mjs
@@ -24,6 +24,12 @@ function simoneFbaFront({
    * Once drafted, we add the FBA, which is what happens in this file
    */
 
+  /*
+   * Locate bust point
+   */
+  points.bust = new Point(measurements.bustSpan / 2, points.neck.y + measurements.hpsToBust)
+  points.cfBust = new Point(0, points.bust.y)
+
   /*
    * How much room to we need to create to fit the breasts?
    * Note that:
@@ -37,18 +43,13 @@ function simoneFbaFront({
    * If the FBA is negative, that means the high bust measurement is higher than the
    * front bust. That's not uncommon for people who don't have much breast tissue but
    * it generates a negative dart which is confusing and incorrect. So in that case, just
-   * return the original part from simon
+   * return the part from Simon without any adjustments.
    */
   if (FBA < 0) {
     log.info('No FBA required, using unaltered Simon front')
     return part
   }
 
-  /*
-   * Locate bust point
-   */
-  points.bust = new Point(measurements.bustSpan / 2, points.neck.y + measurements.hpsToBust)
-
   /*
    * Figure out how much do we need to open a dart to create the required FBA room
    */
```
