### ISSUE TITLE
The showcase post sebastiansew-paco was claimed as their own by user 92236

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#7061]
This issue is about who should get credit for [this showcase post](https://freesewing.org/showcase/sebastiansew-paco).

According to [user gak popo](https://freesewing.org/users/user?id=92236) with ID 92236,
who claimed it as their own.

To reflect this on the site, update [this markdown file](https://github.com/freesewing/freesewing/blob/develop/markdown/org/showcase/sebastiansew-paco/en.md) so that the frontmatter includes this:

```md
author: 92236
```

Anyone can do this, so if you're looking to contribute, this is a great way to get started.

[![User 92236](https://backend3.freesewing.org/users/92236/card)](https://freesewing.org/users/user?id=92236)

**Comment by bobgeorgethe3rd** [comment]
Showcase seems to be by SebastianSews not gak popo. The user number is high for a 3 year old post.
