### ISSUE TITLE
[charlie]: Pdf print out  2" x 4" box 10cm x 5cm box 

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#7084]
Hi. 
Iam new to the site.  Uploaded all measurements and printed the Charlies Chinos pattern.  Having difficulty figuring out how to put the pdf print together.
I cant figure out why the box that says " this box should be 4" x 2" to the outside of the black  box and 10cm d 5cm in the white.  
I have searched for documentation but cant find any.
If anyone could point me in the right direction that would be amazing.

Wanting to make sure the pdf print out is correct.  
Pleaee help
Matt

[![User false](https://backend3.freesewing.org/users/false/card)](https://freesewing.org/users/user?id=false)

**Comment by BenJamesBen** [comment]
The purpose of the scale box is so you can check that your pattern has printed at the correct scale. You should measure the box on your printed pattern, to make sure that the outside dimensions of the box are 4" x 2" and/or that the inner dimensions are 10 cm x 5 cm, if that is what the scale box says.

If you measure the scale box on your printed pattern and discover that it is not the expected dimensions, then the size of your pattern was incorrectly changed somewhere during the PDF export or printing process.

Troubleshooting steps. Please make sure that:
1. You are generating a PDF using the correct paper size. The default paper size is A4, and you should change it if you wish to use a different paper size. (For example, if you want to use Letter size paper.)
2. You are printing the PDF to the correct paper size. (If you have an A4 PDF, make sure the printing program thinks it is printing to A4 paper and make sure that the paper in the printer is A4 size.)
3. You are printing at "Actual size" or a 100% scale (as opposed to "Fit" or "Shrink oversize pages").

**Comment by Johnhenrybrown** [comment]
Thank you for the response.  I was printing to letter and not A4.  I didn't know the pdf creation was in A4.  Hopefully it can be converted from A4 to letter.
Thanks

**Comment by BenJamesBen** [comment]
I am glad that the source of the problem was identified. I am closing this Issue as resolved.

(I also filed PR #7104 to add the printing tips to the FAQ on the freesewing.org website.)

**Comment by Johnhenrybrown** [comment]
Yes. Thank you.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Johnhenrybrown** [comment]
Should have mentioned....just an idea, the first page could use the 4"x2" box, located under the main overall design on page 1 (if necessary or optional) to print as a test page to ensure scaling is correct. As well as the box on the parts page.

Thanks for your thorough reply.
Matt

Sent from Proton Mail Android

-------- Original Message --------
