### ISSUE TITLE
The showcase post ricos-huey was claimed as their own by user 94447

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#7116]
This issue is about who should get credit for [this showcase post](https://freesewing.org/showcase/ricos-huey).

According to [user NicoCot](https://freesewing.org/users/user?id=94447) with ID 94447,
who claimed it as their own.

To reflect this on the site, update [this markdown file](https://github.com/freesewing/freesewing/blob/develop/markdown/org/showcase/ricos-huey/en.md) so that the frontmatter includes this:

```md
author: 94447
```

Anyone can do this, so if you're looking to contribute, this is a great way to get started.

[![User 94447](https://backend3.freesewing.org/users/94447/card)](https://freesewing.org/users/user?id=94447)

**Comment by bobgeorgethe3rd** [comment]
Old showcase. High Number,
