### ISSUE TITLE
[bug]: Opal calculates intersection between two parallel vertical beams

### ISSUE THREAD

**Issue by HaasJona** [freesewing/freesewing#7123]
### What seems to be the problem? 🤔

When I generate an Opal and increase the **Back bib base angle** option to 90 degrees, the design tries to calculate a beam intersection between these 4 points in back.mjs line 124
```
  points.bibCurveMax = utils.beamsIntersect(
    points.waist,
    points.waist.shift(180 - options.backBibBaseAngle, 9001),
    points.bibHexagonLowerInside,
    points.bibHexagonUpperInside
  )
```

these are the values of the 4 points in my browser console:

```
Object { x: 0, y: -49.5, attributes: {…}, name: "waist", … }
 
Object { x: 1.6534568758687989e-12, y: -9050.5, attributes: {…}, … }
 
Object { x: -108.43749999999997, y: -220, attributes: {…}, name: "bibHexagonLowerInside", … }
 
Object { x: -108.43749999999997, y: -280, attributes: {…}, name: "bibHexagonUpperInside", … }
```

As you can see, these are both (almost) vertical lines, which causes stability problems in the calculation and crash the site (especially after applying https://github.com/freesewing/freesewing/pull/7122, which adds a missing check for intersecting two vertical beams).

**Comment by Thrunic** [comment]
I think the best fix is going to be to shrink the range of valid angles. This option is generally going to be somewhere between 0 and +45 degrees (mostly depending on style). I'm going to limit it to the 0 to +80 degrees range.

**Comment by Thrunic** [comment]
PR #7128 submitted, which should solve this bug.

**Comment by HaasJona** [comment]
I found another similar issue when `options.strapTaperPosition` is set to 100% with the following code:

```
  points.strapTaperCurveMax = utils.beamsIntersect(
    points.bibHexagonUpperInside,
    points.bibHexagonTop,
    points.strapTaperInside,
    points.strapEndInside
  )
```

**Comment by Thrunic** [comment]
PR #7138 submitted, which should solve this bug.
