### ISSUE TITLE
[chore]: Port designs documentation to Docusaurus

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#7168]
### What seems to be the problem? 🤔

This Issue is to help track work/progress on porting designs documentation to Docusaurus.

### Claimed

---

### Done
- aaron: by @joostdecock 
- brian: by @joostdecock 
- albert: By VSinerva
- bee:  By VSinerva
- bella: by Ben
- benjamin:  By VSinerva
- bent: By VSinerva
- bibi: by HaasJona
- bob By VSinerva
- carlita: by Ben
- carlton: by Ben
- jaeger: by Ben
- simon: by Ben
- simone: by Ben
- umbra: by HaasJona
- breanna by @joostdecock 
- bruce by @joostdecock 
- cathrin by @joostdecock 
- florence by @joostdecock 
- florent by @joostdecock 
- hugo: by @joostdecock 
- lunetius: by @joostdecock 
- onyx by @joostdecock 
- opal vy @joostdecock 
- paco: by @joostdecock 
- shin: by @joostdecock 
- sven: by @joostdecock 
- sandy by @joostdecock
- shelly by @joostdecock  
- tamiko: by @joostdecock 
- teagan: by @joostdecock 
- tiberius by @joostdecock 
- trayvon: by @joostdecock 
- uma by @joostdecock 
- wahid: by @joostdecock 
- walburga by @joostdecock 
- yuri by @joostdecock 
- lily by @joostdecock 
- cornelius: by woutervdub 
- gozer: by woutervdub
- hi: by woutervdub
- hortensia: by woutervdub
- lumina: by woutervdub
- lumira: by woutervdub
- noble: by woutervdub
- octoplushy: by woutervdub
- otis: by woutervdub
- penelope: by woutervdub
- skully: by woutervdub
- tristan: by @joostdecock 
- waralee: by @joostdecock 
- lucy: By @joostdecock 
- jane: By @joostdecock 
- holmes: By @joostdecock
- huey: by @joostdecock 
- titan: by @joostdecock 
- diana: by @joostdecock 
- charlie: by @joostdecock 
### Does not need to be done
- examples
- legend
- plugintest
- rendertest
- magde

**Comment by HaasJona** [comment]
I can definitely do Bibi and Umbra and I'm happy to help with leftovers, if needed.

**Comment by VSinerva** [comment]
I could use some mindless grunt work right now. I'll grab Albert, Bee and Benjamin to start with.

**Comment by bobgeorgethe3rd** [comment]
Holmes

**Comment by HaasJona** [comment]
Note: If your design has multiple designers or code authors, you need to apply #7170 or you get an error when viewing the design info page in the browser. 

Alternatively temporarily change `config/software/designs.json` so there's only a single string (and not an array) behind `"code"` or `"design"`.

**Comment by BenJamesBen** [comment]
I'm done with Bella, Simon, and Simone. I'll take Carlita, Carlton, and Jaeger next.

(For the design options page, I've been trying to order them in the same order as seen in the Pattern Editor UI.)

**Comment by woutervdub** [comment]
I'm good for my designs
- cornelius
- gozer
- hi
- hortensia
- lumina
- lumira
- noble
- octoplushy
- otis
- penelope
- skully
- tristan
- waralee

Hmmm, I should think about being less productive.

**Comment by joostdecock** [comment]
Note that I'm spending my Sunday on this: #7208 

I've automated the generation of the _options umbrella page_. Code in my PR.

**Comment by woutervdub** [comment]
My conversions are in the WvW branch. I’ll keep working on them when time permits.

**Comment by joostdecock** [comment]
> My conversions are in the WvW branch. I’ll keep working on them when time permits.

No worried. I'm doing my own designs, and those where I know the original designer is unlikely to get involved.

**Comment by VSinerva** [comment]
I'm cancelling my claim on Breanna, at least for now. Too much other stuff going on unfortunately :/ I'll gladly help out once I have time again, if there's still designs to port.

**Comment by joostdecock** [comment]
Thanks for letting us know @VSinerva I've added it back to the list of available designs.

**Comment by joostdecock** [comment]
> My conversions are in the WvW branch. I’ll keep working on them when time permits.

Given that the only designs remaining are claimed ones, and assuming that @woutervdub is asleep, I've imported the `WvW` branch and will complete the remaining designs Wouter claimed before he wakes up ;)

**Comment by joostdecock** [comment]
@woutervdub all yours are done. Thanks for your work, I was happy to see you had done pretty much all of them in your branch :)

I've merged them in #7222

**Comment by joostdecock** [comment]
@BenJamesBen have you worked on Charlie, Diana, Huey, or Titan?
@bobgeorgethe3rd have your worked on Holmes, Jane, or Lucy?

If so, let me know. If not, I might just get this to the finish line.

**Comment by joostdecock** [comment]
FYI: 
- @bobgeorgethe3rd I've ported all the designs you claimed. (see #7223)
- @BenJamesBen I'll be doing charlie, diana, huey, and titan next

**Comment by joostdecock** [comment]
All done. Thanks for the help everyone :pray:
