### ISSUE TITLE
[bug]: lab is gone, but parts of code and docs still require it

### ISSUE THREAD

**Issue by adler99** [freesewing/freesewing#7200]
### What seems to be the problem? 🤔

When I follow the documentation how to set up the environment I cant execute yarn new design successfully. 

It fails, complaining that there is no `freesewing/sites/lab/package.json` at `file:///.../freesewing/scripts/reconfigure.mjs:91:6` 
 

### Design / Plugin / Package 🧐

sites/lab

**Comment by adler99** [comment]
I was wondering if dev is the to be used instead of lab? Would it be a solution to rewire all the scripts to the dev site?

**Comment by HaasJona** [comment]
This should be fixed by #7140 , #7146 and possibly #7143 . If necessary, apply the patches locally yourself. 

For pattern development, you should `cd sites/org/` and then `yarn start`.

**Comment by adler99** [comment]
thx, will try. Leave this here open, so anyone having the same trouble finds hopefully your proposed solution.

**Comment by HaasJona** [comment]
This should be fixed now in the normal develop branch.

**Comment by HaasJona** [comment]
Closing this as it should be fixed. If you still have issues, please report back.
