### ISSUE TITLE
[bug]: Change `order:` frontmatter to `sidebar_position:` in documentation

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#7236]
### What seems to be the problem? 🤔

Previously our documenation used the `order:` frontmatter to order pages in the sidebar menu. Docusaurus instead uses `sidebar_position:` for this. We need to change `order:` to `sidebar_position:` in all our docs.

### Additional context

See Discord for discussion:
https://discord.com/channels/698854858052075530/1101975649419268186/1305197462658486393
discord://discord.com/channels/698854858052075530/1101975649419268186/1305197462658486393

**Comment by joostdecock** [comment]
This is fixed in the ongoing PR #7231 

For future reference, here's the one-liner I used:
```
find . -type f -name "readme.mdx" -execdir sed -i "s/^order:/sidebar_position:/g" {} \;
```
