### ISSUE TITLE
An author suggestion was submitted for the showcase post mermaid-scale-print-waralees-by-magicantace

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#7259]
This issue is about who should get credit for [this showcase post](https://freesewing.org/showcase/mermaid-scale-print-waralees-by-magicantace).

According to [user false](https://freesewing.org/users/user?id=undefined) with ID undefined,
who wrote:

---

Hi 
I'm making this articles

---

.

To reflect this on the site, update [this markdown file](https://github.com/freesewing/freesewing/blob/develop/markdown/org/showcase/mermaid-scale-print-waralees-by-magicantace/en.md) so that the frontmatter includes this:

```md
author: the FreeSewing user ID
```

Anyone can do this, so if you're looking to contribute, this is a great way to get started.

[![User false](https://backend3.freesewing.org/users/false/card)](https://freesewing.org/users/user?id=false)

**Comment by bobgeorgethe3rd** [comment]
No id
