### ISSUE TITLE
Paco pants

### ISSUE THREAD

**Issue by Ultrawoman98** [freesewing/freesewing#726]
will not create new Paco pants pattern
Error: Unable to draft part titanFront

TypeError: d.waistIn is undefined

Error: Unable to draft part front

TypeError: c.styleWaistIn is undefined

Error: Unable to draft part pocketBagFront

TypeError: r.topRight is undefined

Warning: Tried to access frontWaist in the store but it is not set

Warning: Tried to access frontAnkle in the store but it is not set

Warning: points.topRight was set with a x parameter that is not a number

Warning: points.topRight was set with a y parameter that is not a number

Warning: points.midRight was set with a x parameter that is not a number

Warning: points.midRight was set with a y parameter that is not a number

Warning: points.bottomRight was set with a x parameter that is not a number

Warning: points.bottomRight was set with a y parameter that is not a number

Warning: points.title was set with a x parameter that is not a number

Warning: points.title was set with a y parameter that is not a number

Warning: One or more errors occured. Not packing pattern parts

**Comment by joostdecock** [comment]
When this happens, there's a button on the website to report this issue and generate a crash report.
Could you please use that option, as it will provide us the info required to reproduce this.

tx

**Comment by Ultrawoman98** [comment]
That button didn't work.  It would just hang.
