### ISSUE TITLE
Open position: Code-of-conduct enforcement

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#739]
FreeSewing's [Code of Conduct](https://freesewing.dev/contributors/code-of-conduct/) sets out the rules to ensure our community is and remains an open and welcoming environment.  
While creating a clear code of conduct is an important step, it it also important to enforce these rules, and for people to have a safe place where they can report possible abuse.

Our current code of conduct states:

```
Instances of abusive, harassing, or otherwise unacceptable behavior 
may be reported to the community leaders responsible for enforcement:

  -  joost@joost.at
  -  ji.catherine@gmail.com
```

However, Catherine is no longer active in the community, so we would like to assign this responsibility to somebody else.

## What we expect from you
This is a safeguard against the *worst-case* scenario: When somebody inside the community behaves in a way that is toxic or perceived to be toxic by another member.  
In such a scenario, we want to offer an escape hatch. A safe place where you can report your concerns without judgement or blame, and where you will be greeted with kindness and empathy.

If that sounds like you, we expect you to be willing to be listed with name and email address in our code of conduct.
**And** should the day come that somebody escalates a complaint to you, we expect you to treat this with the gravitas and discretion it mandates.

## Why a woman?

While I as maintainer can step in and course-correct, I might not be the best person for (all) people to report to.

 - People might feel more comfortable sharing their experiences with somebody closer to them on the gender spectrum
 - Having only one person to report to leaves people with no place to report abuse by that one person. To put it bluntly: You would be who people can complain to about @joostdecock 

## What's the workload?

Given our friendly and inclusive community, it is perhaps unsurprising that nobody has ever reached for this last-line-of-defense against abusers. 

Still, much like insurance, we should have a system in place so that when people are victimized, they have recourse.

If you are willing to stand up to bullies, comment below.

**Comment by sorchanidhubhghaill** [comment]
Hey there, I would like to take this position. Please add me to the website and I will do my best to maintain the code of conduct.

**Comment by joostdecock** [comment]
Thank you @sorchanidhubhghaill   :heart: 
You've got the job: https://freesewing.dev/contributors/code-of-conduct/enforcement/
