### ISSUE TITLE
Create showcase from tweet about simon for Schorsch

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#746]
- Content:  https://twitter.com/ne_nuudle/status/1339006153406246916
 - Permission: Granted by original author: https://twitter.com/ne_nuudle/status/1341791252157788160 
 - Username: Dunno?

Looking to tackle this issue? We have [a how-to that shows how to add a showcase to the site]( https://freesewing.dev/editors/showcase/).

**Comment by tangerineshark** [comment]
Hey I can do this!

**Comment by joostdecock** [comment]
You can, and you did :pray:
