### ISSUE TITLE
Teagan 'Fabric options' page has an empty title

### ISSUE THREAD

**Issue by ephphatha** [freesewing/freesewing#759]
**What seems to be the problem?**

The [Teagan > Fabric options](https://en.freesewing.org/docs/patterns/teagan/fabrics/) page has an empty title in page-data.json. This is visible in result.pageContext.offspring of [teagan/page-data.json](https://en.freesewing.org/page-data/docs/patterns/teagan/page-data.json) and result.pageContext.siblings of any of the offspring pages (e.g. [teagan/fabrics/page-data.json](https://en.freesewing.org/page-data/docs/patterns/teagan/fabrics/page-data.json)).

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

I think this might be because Teagan somehow has a "fabric**s**" page id (plural), when other patterns use the singular "fabric"? Couldn't work out where this was defined to debug further though.

**Comment by joostdecock** [comment]
Thank you for reporting this. This has been fixed, the fixed will be deployed with the v2.11 release.
