### ISSUE TITLE
Fix pattern tags so they are consistent

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#764]
- Names are there in two varieties (specifically @AlfaLyr and @woutervdub )
 - Some pattern have a bunch of tags that seem more intended for general discoverability (like `diy`)

Which makes the pattern filter look like this chaos:

![Screenshot_2021-01-03 Designs](https://user-images.githubusercontent.com/1708494/103477651-2a61a000-4dc1-11eb-9f47-ed1fc6f7e946.png)

**Comment by woutervdub** [comment]
Do we have a preference? Just make them all the same as the github name? My freesewing/discord and github names are not identical (wouter.vdub vs woutervdub). And I can't change my github name to become identical because github doesn't allow periods in your username.

**Comment by AlfaLyr** [comment]
I'm fine with any or the names. Since everybody is using their real names I thing I'll use that one too, instead of AlfaLyr

**Comment by joostdecock** [comment]
Thanks you guys, I will update accordingly.

@woutervdub you cool with your real name too? Since it's your display name (at least here on Github) I guess you're not actually aiming for secret identity here 🤓

**Comment by woutervdub** [comment]
No problem. 🙂
