### ISSUE TITLE
Bug Report "Error: Node Sass version 5.0.0 is incompatible with ^4.0.0" when setting up development environment

### ISSUE THREAD

**Issue by marijnadesaus** [freesewing/freesewing#779]
**What seems to be the problem?**
I tried to follow the pattern drafting tutorial, everything went fine until I used "npm run start" in tutorial/example. At first it'd say "error Invalid Version: "14"" this was resolved by going into package.json of the example folder and changing the version to "14.0.0"
Then it complained about there not being a node_modules folder in there, so i copied the one in the tutorial folder to the example folder, due to not knowing what else to do
*Then* it proceeded to complain about node-sass not being installed. So I ran "npm install node-sass"
It now gets to the point where it will launch a new tab in my browser and then gives up and reports

>`Failed to compile.`
> ` `
>`./src/layout.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/layout.scss)
Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.`

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking: (though once i get the money i will!)

**Additional context**
I use ZorinOS 15.0 (ubuntu 18.04.5)
and am on `npm@6.14.10` using `node@v14.15.4`
If there's anything else I should add for context please tell me!

**Comment by joostdecock** [comment]
Hey thanks for this quality bug report :+1: 

I've pushed a fix for this, we'll cut a new release to make go away soon enough. Thanks for your patience :slightly_smiling_face:

**Comment by joostdecock** [comment]
Fixed in 2.11.1
