### ISSUE TITLE
NPM install fails on windows as the template files are not copied

### ISSUE THREAD

**Issue by ephphatha** [freesewing/freesewing#781]
**What seems to be the problem?**

create-freesewing-pattern/lib/create-library.js calls globby() to get a list of files to copy when creating the folder/file structure for a new pattern. This uses a path to the create-freesewing-pattern/template/ directory built with path.join(). On windows this returns a path like C:\<node_cache>\create-freesewing-pattern\template\ (using standard windows path separators of backslashes).

This is not handled by globby so the call results in an empty list and none of the template files are copied.
> Note that glob patterns can only contain forward-slashes, not backward-slashes, so if you want to construct a glob pattern from path components, you need to use path.posix.join() instead of path.join(). ([From the globby package documentation](https://www.npmjs.com/package/globby).)

This causes npm install and npm link to fail.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Comment by joostdecock** [comment]
Hey, thanks for this quality bug report. Windows support is a bit sketchy, because... well I don't have a Windows machine.

Still, this seems like low-hanging fruit and we should try to correct it.
