### ISSUE TITLE
"About" links broken

### ISSUE THREAD

**Issue by tangerineshark** [freesewing/freesewing#785]
**What seems to be the problem?**

From Discord: I believe that the About link on the freesewing.org/docs page is broken. It looks like anything that starts with freesewing.org/docs/about ... ends up at a 404. I think the list below is all of them?

- https://freesewing.org/docs/about/
- https://freesewing.org/docs/about/faq
- https://freesewing.org/docs/about/pledge
- https://freesewing.org/docs/about/privacy

![image](https://user-images.githubusercontent.com/70777269/104387967-e166c580-54fd-11eb-8672-af35cf1ce1d6.png)

**Comment by joostdecock** [comment]
I'll just leave this here as a hint for the eager contributor: https://github.com/freesewing/freesewing.org/blob/develop/src/components/app/footer.js#L21

**Comment by joostdecock** [comment]
Oh, and these have typically been moved to `/docs/various/` : https://freesewing.org/docs/various/

**Comment by joostdecock** [comment]
Fixed
