### ISSUE TITLE
Some errors in person edition pages onfreesewing.org (broken links, broken pages)

### ISSUE THREAD

**Issue by nadege** [freesewing/freesewing#789]
**What seems to be the problem?**

- The `cancel` button on various Person editions pages links to `/people/<peopleID>` instead of `/account/people/<peopleid>` resulting in a 404 if user click on it. (true for edit avatar, edit name, edit notes...)
- the Person "edit unit" and "edit chest" pages are broken (JS error about trying to modify a `readOnly` variable)

I have setup the dev env tonight, I'd like to work on fixing these. :) 

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking: 

**Additional context**
click the cancel button to see the 404 page 
![image](https://user-images.githubusercontent.com/3792171/104655078-6d731b80-56bd-11eb-9bf4-7b6475d0144c.png)

**Comment by joostdecock** [comment]
This got reported & fixed, all while I was asleep. Pretty great start of the day :heart:
