### ISSUE TITLE
Adapt Keystone measurements to contemporary standards

### ISSUE THREAD

**Issue by marijnadesaus** [freesewing/freesewing#794]
**Intro**
The Keystone Guide & The Keystone Systems are two out of copyright pattern drafting books. They would be ideal for adding to freesewing except for one issue: their measurement guides are wonky and the instructions are super vague.
I'm adding this issue here, so I can assign it to myself, or for anyone who feels like wrestling with this old-fashioned mess.

**Issues with the drafting system that need tackling:**
- [ ] Adapt measuring guides to modern standards (what was Mr Hecklinger even thinking when he wrote those guides?)
- [ ] Choose most interesting patterns to work on first (to be updated?)
- [ ] Adapt the weird pattern drafting maths to work with modern measuring standards
- [ ] Fix order of operations in the pattern drafting guides (no more "the armscye goes through point Z" when point Z is only explained 2 pages later)
- [ ] Rope some more people into this to help test patterns & adapt them some more
- [ ] Find some poor person with more knowledge of JavaScript than I have to help digitise the patterns

**Additional context**
Some of the more known Keystone books
https://archive.org/details/keystonesystemsc00heck/mode/2up The Keystone Systems for Coats, Vests, and Trousers
https://archive.org/details/keystonejacketdr00heck/mode/2up The Keystone Guide to Jacket and Dress Cutting
https://archive.org/details/keystonesystemte00heck/mode/2up The Keystone System: Text Book on Designing Ladies' Garments.

**Comment by joostdecock** [comment]
Cool initiative @marijnadesaus :+1: 

Since this is rather large in scope for a single issue, I suggest we treat this as the 'umbrella issue'. To facilitate that, I've created the **keystone** milestone, so all issues can be grouped together like that.

**Comment by marijnadesaus** [comment]
Thank you and noted! Will work with that going forward!

**Comment by woutervdub** [comment]
I'm currently working on Cycling Breeches.

(because I want to have some)

**Comment by joostdecock** [comment]
Stale => closing. 

Feel free to comment if you want to re-open this.
