### ISSUE TITLE
Make a new pattern that's a non-hoodie version of hugo

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#803]
This is a todo from #774 

The idea is to make a new pattern that is hugo without the hood and pocket

**Comment by bobgeorgethe3rd** [comment]
Would this make more sense to be a Raglan-Version of Sven? Rather than hoodless Hugo? I don't if the blocks are the same for Hugo and Sven, if they are my point is mute.

**Comment by nataliabarnhart** [comment]
@bobgeorgethe3rd Both Hugo and Sven are based on the Brian block.

**Comment by bobgeorgethe3rd** [comment]
I was thinking about taking a stab at this just wanted to run it by you guys.
Import Hugo
Hide Hood, Hood center, Pocket, Pocket Facing (Could make it an option to have them)
Add a Neck Binding piece that takes the neck distance of the Sleeves, Front and Back modified by the options.ribbingStretch (Not nessecarily full length to save paper) by the options.ribbingHeight
Modify Title Numbers if need be?

**Comment by joostdecock** [comment]
Stale. Closing
