### ISSUE TITLE
Discuss: A modular approach to patterns

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#805]
This is a todo from #774 

An idea was raised to make it possible to have a modular pattern system where you can combine sleeves, necklines, bodies and so on.

This issue is a place to discuss and perhaps more.

**Comment by joostdecock** [comment]
Stale. Closing

**Comment by jejacks0n** [comment]
I'm going to reopen this @joostdecock, for discussion, if that's alright?

I've had some thoughts about the overall approach we could take for this, and if you feel comfortable with me exploring some concepts here -- the thinking is that 2d boolean operations might give us a path forward for this.

**Comment by joostdecock** [comment]
Sure thing. We can also turn this into a discussion item if that's more appropriate. Whatever suits 👍

**Comment by jejacks0n** [comment]
It's surfaced that many pattern concepts might be handled by doing boolean operations (notable boolean subtraction).

Arm and neck holes are good examples of potentially benefitting from this concept. The shape of them must often be cohesive across multiple parts, and so this could be handled by simply subtracting an arm hole shape from the front bodice part and the back bodice part.

Changing the shape of the arm hole would then be the same operation on multiple parts, and the arm hole formula can be extracted into an "arm hole module" that can be more easily shared.

**Comment by jejacks0n** [comment]
> Sure thing. We can also turn this into a discussion item if that's more appropriate. Whatever suits 👍

Whichever you prefer!

**Comment by starfetch** [comment]
This sounds like a good starting point for using Discussions :)
