### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by valerydec17** [freesewing/freesewing#816]
**What if freesewing.org will be translated to Russian?**

I know Russian as a pro.

**Comment by joostdecock** [comment]
If you would like to start working on a Russian translation, we can add it as a language.
It's a bit of work to add a new language though, so I guess I'd like to know whether you're willing to spearhead the translation, as I don't know anyone who speaks Russian :)

**Comment by joostdecock** [comment]
Stale. Closing
