### ISSUE TITLE
Adapt the "Keystone" Regular Form Trousers pattern to contemporary standards

### ISSUE THREAD

**Issue by marijnadesaus** [freesewing/freesewing#831]
This is simply part of the bigger "keystone" milestone mentioned in #794  .
https://archive.org/details/keystonesystemsc00heck/page/156/mode/2up <- pattern drafting method is from here + the page after that.

- [ ] Adapt measures to metric system
- [ ] compare Keystone measurements to contemporary standards
- [ ] draft pattern using measures taken according to Keystone
- [ ] draft pattern using contemporary measures
- [ ] make mock-ups of both versions (?) and make adjustments
- [ ] (Check how this compares to the "corpulent form" version, because if the difference is simply the measurements there's no need to make a whole new drafting method for that.)
- [ ] adapt drafting method mathematics to work with contemporary measurements
- [ ] rewrite the instructions because the order of operations is nonsense
- [ ] More pattern testing and adjusting
- [ ] ask someone with more coding knowledge to add it to freesewing

**Comment by Joseph-McGroarty** [comment]
Hi Marinus, I was wondering if this project is still ongoing and if I could help out with it? I was thinking specifically I could help with reading through the instructions and translating them into more straight forward coding requirements cause I know those manuals can be challenging to read. (I've drafted a few paper patterns for myself from Progressive Tailor but haven't used Keystone yet)

If so just lmk specifically what needs to be done. I'm a little unclear whether this is a project for creating a new trouser pattern vs updating titain or another existing pattern

**Comment by joostdecock** [comment]
Don't want to discourage anyone, but seems stale so I'm closing it.
