### ISSUE TITLE
Missing on-the-fold indicator for Carlton/Carlita collar

### ISSUE THREAD

**Issue by ephphatha** [freesewing/freesewing#832]
Based on the seam allowances visible (when selected) it looks like the collar piece (8) for the Carlton/Carlita coat is meant to be cut on the fold. There is no on the fold indicator visible in the PDF or web view for this pattern. This appears to be the only part of the pattern that is cut on the fold, it seems easy to overlook and mistakenly draft this piece incorrectly (especially for the inexperienced).

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

PDF export:
![2021-02-01T142024_pattern-full pdf_-_Google_Chrome](https://user-images.githubusercontent.com/357684/106411192-c3570a00-6498-11eb-9d0b-a7a60fd2bcff.png)
Web view:
![2021-02-01T142159_New_Carlton_coat_for_Size_40,_Without_breasts_-_Go](https://user-images.githubusercontent.com/357684/106411251-e5e92300-6498-11eb-9973-9cfa01d304d2.png)
(Both from a Carlton pattern but the Carlita pattern looks the same)

**Comment by joostdecock** [comment]
Thanks for reporting this :+1:
