### ISSUE TITLE
Documentation/content update

### ISSUE THREAD

**Issue by KyleHaston** [freesewing/freesewing#839]
- Page links:
https://freesewing.dev/tutorials/pattern-design/testing-your-pattern/#testing-measurements
https://freesewing.dev/tutorials/pattern-design/testing-your-pattern/#testing-models
https://freesewing.dev/tutorials/pattern-design/testing-your-pattern/#the-antman-test
- Relevant section: (3 sections linked above)
- Suggested content: These sections seem to be missing images.

**Comment by joostdecock** [comment]
Thanks for reporting this @KyleHaston :+1: 

These are not images but embedded examples of our `example` pattern. 
We changed the name of the `headCircumference` measurement to `head` a while back, and the examples hadn't been updated.

I've done that now, and a new version of the site is being deployed.
