### ISSUE TITLE
Contibutor call: 20 February 2021

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#846]
You are all invited to the contributor call.
Please leave a comment to put things on the agenda. This issue will be updated after the call with notes and todos.

## About

 - Location: https://meet.freesewing.org (Zoom call)
 - Date: Saturday 20 February, 2021 17:00 UTC, which is:
   - Los Angeles: 09:00
   - Chicago: 11:00
   - New York: 12:00
   - São Paulo: 14:00
   - London: 17:00
   - Paris: 18:00
   - Johannesburg: 18:00
   - Moscow: 20:00
   - Mumbai: 22:30
   - Hong Kong: 01:00 on Sunday
   - Tokyo: 02:00 on Sunday
   - Sydney: 04:00 on Sunday

## Agenda

 - Todos from last call
   - Make an effort to bring the amount of open issues down
 - Assess design difficulty ratings
 - Discussion

## Notes
- The amount of open issues has been brought down significantly, going from 90-something at the time of the last call to less than 40 now.
-  We will keep on working on keeping the issue count down, but keep in mind that the ones that remain open or either non-trivial to tackle, or deliberately left open for new contributors
- About 300 people so far have subscribe to our newsletter. 40 or so are visitors, the rest users.
- @nataliabarnhart  brings up the fact that the difficulty ratings of the patterns are not always consistent, and first suggests, then volunteers for a review
- This also lead to a discussion on the matter, as Tim suggested we could ask the users for how hard/difficult it was to make the pattern
- Others point out that what is easy for one person is not easy for another, so this might not be that useful
- Given that it's typically beginner makers who are looking for an easy pattern, Joost suggested that perhaps we could add some guidance to the UI, some sort of *help me choose* feature
- Gradually a consensus arose that it would be good to have small labels to indicate different techniques used in a pattern (with perhaps an optional/mandatory specification) that would give extra indication on what's needed to make a pattern.
- @tangerineshark points out that she did some work on [a long open issue about artwork](https://github.com/freesewing/freesewing.org/issues/190#issuecomment-779592065) and she would love some feedback
- @woutervdub has been working on a new pattern for riding breeches which will be named `cornelius`

## Todo

 - Go through the difficulties and ensure consistency: #879 
 - Change the website to help people pick *easy* patterns: #881
 - Come up with a list of names/labels for different techniques used in patterns: #880
 - Add icons/labels for different techniques used: #882

**Comment by nataliabarnhart** [comment]
Agenda item suggestion: Assess design difficulty ratings

Someone asked in Discord, "what pattern would you recommend for a beginner to start with? i'm just learning how to sew and it's somewhat overwhelming seeing all the different patterns and not knowing if they are easy or not."

I think this is what the difficulty ratings are intended to help with. They may be fine as-is, but I'm a little skeptical about some such as Albert apron (3, should be lower?) and Titan trouser block (2, should be higher?).

**Comment by DocSpencer77** [comment]
For our ongoing conversation about our April Newsletter debut, I'm adding an example of a recent ASG (American Sewing Guild) newsletter.  No, it's not Freesewing's style or something to "emulate," but it might provide some ideas or a springboard for discussion.
[madison_stitchin_times_january21.pdf](https://github.com/freesewing/freesewing/files/6015408/madison_stitchin_times_january21.pdf)

**Comment by joostdecock** [comment]
Closing in favor of #878
