### ISSUE TITLE
Documentation/content update

### ISSUE THREAD

**Issue by KyleHaston** [freesewing/freesewing#848]
- Page link:  https://freesewing.dev/tutorials/pattern-design/conclusion/
- Relevant section: https://freesewing.dev/tutorials/pattern-design/conclusion/#more-reading-material
- Suggested content: Link to "high-level overview of FreeSewing" is broken. Page moved?

**Comment by joostdecock** [comment]
Thanks for reporting this @KyleHaston :+1: 

It's fixed, deploy of the updated site is ongoing.
