### ISSUE TITLE
seat circumference input area missing

### ISSUE THREAD

**Issue by artairdk** [freesewing/freesewing#86]
In Theo pattern, I noticed that it require seat circumference measurement however in both documentation tab and in the model page itself doesn't seem to list a way to input seat circumference.
Given that it's basically impossible to uses the pattern since it keeps saying necessary measurements is missing

**Comment by joostdecock** [comment]
Well spotted. This has been fixed in freesewing v2.0.1, which is now deployed in production.

Or in other words, it's fixed :)
