### ISSUE TITLE
Write Hortensia docs

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#860]
They need to go in this folder: https://github.com/freesewing/markdown/tree/develop/org/docs/patterns/hortensia

You can use one of the other patterns as example.  
Only create the `en.md` files, the rest will be created by the transation tools.

More useful info at: https://freesewing.dev/editors/

**Comment by stoffsuchti** [comment]
@joostdecock 

Hello

Finally I find the time to start the documentation for Hortensia

With with software or editor can one create .md files? 

Can i just write it as txt in my preferred text editor?

I will write the documentation first in German and then translate it to English.

Who can the German text be used/provided as a "translation" so the work doesn't be done twice?

**Comment by joostdecock** [comment]
Hi @stoffsuchti :wave: 

Yes, you can create any text editor. `.md` files are just text files.

As for the German, English is always the source language, and translation work is broken up into individual sentences.
You can join the translation platform here: https://translate.markdown.freesewing.org/project/fs-markdown/invite
Once your text is in the repository, it will become available for translation there.

**Comment by starfetch** [comment]
Hi @stoffsuchti, I've been doing some translation work to German on Crowdin, so if you want I could match the translations there for you. Just tell me once you're done :)

**Comment by joostdecock** [comment]
I don't think it's useful to keep this open. A [pattern ambassador](https://freesewing.dev/howtos/ways-to-contribute/pattern-ambassador) would be a far better way to handle this than keeping issues open for months/years on end.

So. Closing this.
