### ISSUE TITLE
Create Carlton showcase from Discord post

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#872]
- Content:  Discord
 - Permission: 
   - [ ] I am the original author, and hereby grant permission to repost this content
   - [x] I am not the original author. The author, Rudy on Discord, granted permission on Discord

Looking to tackle this issue? We have [a how-to that shows how to add a showcase to the site](https://freesewing.dev/editors/howtos/showcase/).

**Comment by nataliabarnhart** [comment]
I messaged Rudy to ask how he'd like to be credited.

**Comment by joostdecock** [comment]
I initially assigned this to you, but then I realized that perhaps you were merely preparing this as a low-effort issue for new contributors, so I left it open again :see_no_evil: 

Whichever it is, you're amazing :pray:

**Comment by nataliabarnhart** [comment]
I'm happy to take care of this! I was keeping my ears open on the contributor call for anyone expressing interest in helping with low-effort issues, but I didn't hear anything this time. Will complete this in the next couple days.

The author confirmed the preferred credit:

> My Instagram is @rudy_lee21 :)

**Comment by nataliabarnhart** [comment]
Added! https://github.com/freesewing/markdown/pull/157
