### ISSUE TITLE
Go through the difficulties and ensure consistency

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#879]
This is a todo from #846 

The idea is to go through the list of all freesewing patterns and rate each one for difficulty.  
Having this done by a single person would (hopefully) provide more consistency then the current situation where the difficulty is chosen by the person who created the pattern.

**Comment by nataliabarnhart** [comment]
Here's my start at descriptions for difficulties. I won't be insulted if this doesn't go anywhere.

1 | Beginner - This is a simple design and FreeSewing has thorough documentation on it. This is a good first sewing project.
-- | --
2 | Confident beginner - This design is fairly simple, but involves one or two sewing techniques, such as sewing knit binding. A confident beginner should be able to handle this, and more advanced sewers will have no problems.
3 | Advanced beginner / intermediate - This design involves more intermediate sewing techniques, such as inserting a zipper or sewing darts.
4 | Advanced intermediate
5 | Advanced

**Comment by nataliabarnhart** [comment]
Here are my suggestions for changes to difficulties for better consistency.


Design | Current Difficulty | Suggested Difficulty | Techniques
-- | -- | -- | --
Aaron athletic shirt | 3 | 2 | Knit binding
Albert apron | 3 | 2 | Simple pockets
Florent flat cap | 2 | 3 | Interfacing, Precision
Titan trouser block | 2 | 3 | Developing from a block
Teagan T-shirt | 3 | 2 | Sleeves, Knit binding
Waralee wrap pants | 3 | 2 | Welt pockets

See also: https://github.com/freesewing/freesewing/issues/880

**Comment by nataliabarnhart** [comment]
@joostdecock I can make these changes. Let me know if you're opposed, otherwise I'll go ahead.

**Comment by joostdecock** [comment]
Do it! 😀

**Comment by nataliabarnhart** [comment]
This is done! https://github.com/freesewing/freesewing/pull/1118
