### ISSUE TITLE
Come up with a list of names/labels for different techniques used in patterns

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#880]
This is a todo from #846 

The idea is to have some sort of list of techniques/challenges that are required to make a pattern, and then list them so people have an idea what it takes.

The first step: come up with such a list. Feel free to comment below to add items.

**Comment by nataliabarnhart** [comment]
My suggestions:

Technique/challenge | Notes
-- | --
Knit binding
Bias binding
Darts |  
Curved seams
Simple pockets | In my mind, for the current designs, this is "any pockets besides welt pockets," but this is just an idea. Might include pockets serged around the edges and inserted in side seams, like Paco, or folded and topstitched patch pockets, like Albert
Welt pockets | This design includes welt pockets, which are an intermediate sewing technique. It is easy to omit welt pockets if desired.
Zipper |  
Sleeves |  
Ribbing |  
Buttons |  
Grommets/eyelets
Interfacing
Basting | Maybe not needed? I think anything that would require basting would also require "Precision" though not the other way around
Lining |  
Elastic | Elastic is either sewn inside a fabric tube, like Paco, or attached directly, like Bruce
Precision | Precise sewing required, e.g., Benjamin, Carlita/Carlton, Cathrin, Florent, Jaeger, Simon/Simone, Trayvon, maybe others
Patternmaking from a block | This is a block, a basic shape on which other patterns are based. Blocks are typically not made as-is (except to verify the fit) but rather serve as a basis for other patterns. Making a pattern from a block may involve adding   wearing ease and design ease.

I've been jotting down techniques as I go through the difficulties ( #879 ), so can provide examples if helpful to anyone.

**Comment by darigovresearch** [comment]
Think this would be really helpful, is there any way we can publish a preliminary list with placeholders for the ones we don't have?

Example like the instructions for Albert - https://freesewing.org/docs/patterns/albert/instructions/

**Comment by nataliabarnhart** [comment]
@darigovresearch , do you mean a preliminary list of patterns and their associated techniques? If yes, see what you think of this...

Design | Techniques
-- | --
Aaron athletic shirt | Knit binding
Albert apron | Simple pockets
Bella body block | Darts, Developing from a block
Benjamin bow tie | Precision, Interfacing
Bent two-part sleeve block | Developing from a block, Sleeves
Breanna body block | Darts, Developing from a block
Brian body block | Sleeves, Developing from a block
Bruce boxer briefs | Curved seams, Elastic
Carlita coat | Simple pockets, Welt pockets, Interfacing, Basting, Precision, Darts,   Lining, Curved seams
Carlton coat | Simple pockets, Welt pockets, Interfacing, Basting, Precision, Darts,   Lining, Curved seams
Cathrin corset | Precision, Grommets/eyelets
Diana draped top | Sleeves, Bias binding
Florence face mask | Curved seams
Florent flat cap | Interfacing, Precision
Holmes hat | Precision, Lining
Hortensia handbag | Precision, Zipper
Huey hoodie | Zipper, Ribbing, Sleeves, Simple pockets
Hugo hooded jumper with raglan sleeves | Ribbing, Sleeves, Simple pockets
Jaeger sport coat | Darts, Buttons, Precision, Sleeves, Welt Pocket, Interfacing
Paco pants | Simple pockets, Elastic, Grommets/eyelets
Penelope pencil skirt | Darts, Zipper, Interfacing, Lining
Sandy circle skirt | Zipper, Buttons
Shin swim trunks | Grommets/eyelets
Simon shirt | Darts, Buttons, Precision, Sleeves
Simone shirt | Darts, Buttons, Precision, Sleeves
Sven sweater | Sleeves, Ribbing
Tamiko top | &nbsp;
Teagan T-shirt | Sleeves, Knit binding
Theo trouser | Welt pockets, Darts, Basting, Lining, Precision, Interfacing
Titan trouser block | Developing from a block
Trayvon tie | Precision, Interfacing
Wahid waistcoat | Darts, Buttons, Interfacing, Welt pockets
Waralee wrap pants | Welt pockets

**Comment by darigovresearch** [comment]
@nataliabarnhart that's amazing! Should we have a placeholder for any items which don't use any techniques as it may confuse users who think that a label is not present out of misdocumentation?

Having a dedicated section of the website explaining these techniques to use as a common/shared resource would be helpful but may be worth opening as a separate issue

**Comment by nataliabarnhart** [comment]
@darigovresearch I think a placeholder is a good idea! What do you think would be a sensible name?

Agreed, the sewing docs seem like a good spot for this. I'm happy to work on adding pages for new techniques if the current list is okay. Might be able to get help from sewing people on Discord too.

As far as adding techniques to patterns, what do you think, @joostdecock ? We had talked about icons/labels (https://github.com/freesewing/freesewing/issues/882) which I like, but I'm not sure where they would go. There are probably simpler options to do this without icons, like adding a note (https://freesewing.dev/editors/markdown/custom-components/note) to each pattern's instructions. Like what @darigovresearch listed for Albert :)

**Comment by darigovresearch** [comment]
@nataliabarnhart  "No complex techniques used in this pattern" should suffice as a placeholder.

May be good to add the list of techniques required in a new paragraph of the "What you need" section of each pattern as this is a common page & users are likely to go there to see what they will require. This requires no need for icons or specific notes as a first iteration. Request for icons can be set as an issue which someone from the community may want to make a pull request for.

**Comment by joostdecock** [comment]
A placeholder is a good idea, if for nothing else but to differentiate between patterns that have no tricky techniques, and patterns where we forgot to add the list of techniques (which I can see happening when we add a new pattern).

Perhaps we can take a queue from github where we label things with `good-first-issue`. Would something like `good-first-pattern` or `beginner-friendly` be useful? Or does that sort of invalidate the fact that it's supposed to be a list of techniques :thinking: 
If so, perhaps something like `basic sewing skills`.

In general, I prefer to avoid saying things are *easy* (or not complex) because that is easy enough for us to say as we are all *demi-gods of the sewing realm*. But it can be really discouraging for people who truly are absolute beginners.

**Comment by joostdecock** [comment]
As for where to keep this info, I think the logical choice would be in the `@freesewing/pattern-info` package.

That way, we can pull out that info and include it on a variety of pages. Whether that's in the docs, or on the pattern info pages.

**Comment by luizfzs** [comment]
For each of the challenges, as a user, I'd love if we had links to documentation on how to do them e.g. how to sew a dart, knit binding. 
With that, there would be no need to write instructions on know to do knit/band binding for Aaron and Teagan, for example, and it would link to the documentation instead. 

How does having an issue on our kanban board to write that documentation sound?

**Comment by BenJamesBen** [comment]
Some other techniques:

- Clipping corners/curves (Precision?)
- Pleating
- Gathering
- Hand sewing/finishing
- Topstitching
- Understitching
- Drawstring
- Boning
- Fabric pattern matching
- Serging

**Comment by joostdecock** [comment]
Has it been 2.5 years since this issue was created? Jeez.

Anyway, this is implemented:

- Techniques are listed in the `config/software/designs.json` file, which is the same place we list the tags.
- Translation is in `sites/shared/i18n/tags

The main place where this is currently on show is on the designs page, which now has nifty filtering:

![image](https://github.com/freesewing/freesewing/assets/1708494/8c2126ed-1fe9-4af5-aae7-9c41b9fa016a)

Note that not all designs have their techniques listed yet. That's because not all are ready for v3 beta. You can track the progress here: https://github.com/freesewing/freesewing/issues/4926

I'm closing this as while there's certainly room for improvement, I feel that as a feature request, this has been implemented. And keeping this open would not be very productive.

Thanks to all involved for your patience and input :pray:
