### ISSUE TITLE
Change the website to help people pick *easy* patterns

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#881]
This is a todo from #846 

We should provide some handrails for new makers who are intimidated by the wall of patterns.

**Comment by hellgy** [comment]
for inspiration : I really like the way the "easy peasy" is displayed : https://howmanyplants.com/plant-guides

**Comment by sarahloch** [comment]
Hi! I'm new to FreeSewing and fairly noob on JS and Git (fluent in HTML/can get by with CSS). I'd love to work on this, but not sure where/how to start (probably because this is my first time)

**Comment by joostdecock** [comment]
Since we're published our new NextJS-based freesewing.dev website, our plans for building a new website are getting pretty real now.
So I'm closing this because we'll be overhauling the entire site. 

Obviously, I appreciate the input and feedback, but I don't think it's that useful to keep this issue open.
