### ISSUE TITLE
Create Wahid showcase from Minty's post on Discord

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#907]
- Content:  Provide a link here to where we can find the content
 - Permission:
   - [ ] I am the original author, and hereby grant permission to repost this content
   - [x] I am not the original author. Minty on Discord granted permission
 - Credit: Minty

Looking to tackle this issue? We have [a how-to that shows how to add a showcase to the site](https://freesewing.dev/editors/howtos/showcase/).

**Comment by joostdecock** [comment]
All hail @nataliabarnhart the amazing!
