### ISSUE TITLE
Create Cornelius showcase from Wouter's Discord post

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#910]
- Content:  https://discord.com/channels/698854858052075530/787402509543145532/816013752632606800
 - Permission:
   - [ ] I am the original author, and hereby grant permission to repost this content
   - [x] I am not the original author, **I have requested permission from Wouter to share his Cornelius photos**
 - Credit: Pending Wouter's approval, @Wouter.vdub is his instagram account, https://shirtartistry.blog/ is his blog

Looking to tackle this issue? We have [a how-to that shows how to add a showcase to the site](https://freesewing.dev/editors/howtos/showcase/).

**Comment by nataliabarnhart** [comment]
Wouter graciously granted permission to share. Here's the PR: https://github.com/freesewing/markdown/pull/175

**Comment by joostdecock** [comment]
Awesome :+1:  and merged :)
