### ISSUE TITLE
Documentation/content correction

### ISSUE THREAD

**Issue by ttimearl** [freesewing/freesewing#919]
https://freesewing.dev/tutorials/getting-started-linux/installing-nvm/

Para 3 has typos, replace with the following:

Using nvm has a number of benefits in comparison with installing Node from the node.js website, or from a package provided by your linux distribution:

**Comment by joostdecock** [comment]
https://github.com/freesewing/markdown/blob/develop/dev/tutorials/getting-started-linux/installing-nvm/en.md
