### ISSUE TITLE
Account reload deletes heel measurement

### ISSUE THREAD

**Issue by tangerineshark** [freesewing/freesewing#940]
**What seems to be the problem?**
When I reload my account on FreeSewing, my "heel circumference" measurement disappears. I can go add it back in again, and it will hang out until I reload my account, at which point it disappears again.

**Are you a FreeSewing patron?**
 - [ ] Yes, I am :hugs:
 - [X] No, I am not :thinking:   oh dear I really should do something about this

**Comment by joostdecock** [comment]
Can you share your username on the site so I can try to reproduce this?

**Comment by tangerineshark** [comment]
My username's just "karen" 😊

**Comment by joostdecock** [comment]
I was so certain this was going to be a non-issue, but I was actually able to reproduce it. So well done!

**Comment by joostdecock** [comment]
Thanks for reporting this. It's fixed.

Please put in your correct heel measurement though, because I just put in 12 1/4" as a test and you can't actually remove a measurement once set :thinking:

**Comment by tangerineshark** [comment]
Thanks!! Will do!
