### ISSUE TITLE
Register one pattern as a Certified Open Source Hardware Project.

### ISSUE THREAD

**Issue by dglaude** [freesewing/freesewing#955]
**What is it that you would like to see happen?**

I would like FreeSewing to register one of it's pattern as an Certified Open Source Hardware Project.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [X] No, I am not :thinking:

**Additional context**

While OSHWA is more about electronic project, there is already one registered project that is a crochet thing:
https://certification.oshwa.org/se000008.html

So there should be no reason to refuse sewing pattern that is free, made by free software and at the cross section between software and hardware. Let's pick the best pattern, the first pattern, or an iconic pattern like a facemask, and try to register it manually: https://certification.oshwa.org/

Maybe they should even add a section for sewing pattern...

The benefit could be added visibility for that community and possibly wearable electronics geeks could be interested and contribute pattern.

As there is an API to register pattern, then all the pattern, or all new pattern could be automatically pushed for registration.

Then on 20 April 2022, @joostdecock could go to New York to speak at the OSWA conference...

**Comment by joostdecock** [comment]
Thanks for this suggestion :+1: I'll add it to the agenda of our next contributor call to see how to best deal with this.

**Comment by darigovresearch** [comment]
This sounds very interesting and worthwhile, would agree that the facemask would be a good starting point. Has there been any progress made on this since the contributor call?

**Comment by joostdecock** [comment]
No, it was mentioned in passing, but it's not actively being worked on.

**Comment by joostdecock** [comment]
I've submitted a certification request for Florence. We'll see how it goes.
Meanwhile, I'm closing this issue as whether or not the application is accepted is outside our control, and thus not something that should be an open issue for us.

**Comment by joostdecock** [comment]
It's up: https://certification.oshwa.org/be000004.html

**Comment by darigovresearch** [comment]
Sounds good, nice work!

**Comment by dglaude** [comment]
I am checking if this is the first community mask that is OSHWA certified.
And what other pattern would be already certified.
The idea would be to make a nice message celebrating this certification, hinting that there are potentially many more as there are X different pattern on the site.
