### ISSUE TITLE
Jaeger allows for 3 buttons in the config, but only implements 1 or 2

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#973]
Reported by  **starf** on Discord, setting the amount of buttons to `3` in Jaeger makes no difference.

Sure enough, it seems to be an oversight: https://github.com/freesewing/freesewing/blob/develop/packages/jaeger/src/front.js#L404

**Comment by starfetch** [comment]
Hm, this is still not working correctly. `1` and `2` work fine, but `3` draws only two buttons.

![image](https://user-images.githubusercontent.com/80041179/119242080-70928280-bb5b-11eb-8841-d3992280cd9a.png)

**Comment by joostdecock** [comment]
Sorry, I had added a strict type comparison, but the option is available as a string. This will be part of the upcoming 2.16 release
