### ISSUE TITLE
Bug report: Dead link to graphs page

### ISSUE THREAD

**Issue by darigovresearch** [freesewing/freesewing#983]
**What seems to be the problem?**

On the Measurements guide page it links to the graphs page but there is a typo in the URL so results in a 404

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Page in question -  https://freesewing.org/docs/guide/measurements/
Links to - https://freesewing.org/docs/guides/measurements/graph/
Assuming it should be - https://freesewing.org/docs/guide/measurements/graph/

**Comment by darigovresearch** [comment]
Pull request https://github.com/freesewing/markdown/pull/199 would resolve this issue if merged.

Also noticed that in one translation it links to estimates & Graphs pages so made the correction to the pages which links to Graphs on both of the links

**Comment by joostdecock** [comment]
PR merged, closing. Thanks again.
