### ISSUE TITLE
Create Charlie showcase from Joost's Discord post

### ISSUE THREAD

**Issue by nataliabarnhart** [freesewing/freesewing#984]
- Content:  https://discord.com/channels/698854858052075530/787402509543145532/831110448195174441
 - Permission:
   - [ ] I am the original author, and hereby grant permission to repost this content
   - [x] I am not the original author. The author, Joost, granted permission on Discord
 - Credit: Will check with Joost

Looking to tackle this issue? We have [a how-to that shows how to add a showcase to the site](https://freesewing.dev/editors/howtos/showcase/).

**Comment by joostdecock** [comment]
Permission granted :) Credit: https://twitter.com/j__st (the only social network I'm still on)

**Comment by nataliabarnhart** [comment]
@joostdecock Perfect, ty!

**Comment by nataliabarnhart** [comment]
https://github.com/freesewing/markdown/pull/220
